Fennix Project: kernel/proc/Task.cpp File Reference
Task.cpp File Reference
#include <internal_task.h>
#include <display.h>
#include <debug.h>
#include <asm.h>
#include <cputables.h>
#include <bootscreen.h>
#include "../drivers/serial.h"
Functions
void StartTasking (uint64_t Address, TaskingMode Mode)
Function Documentation
StartTasking()
void StartTasking (uint64_t Address, TaskingMode Mode)
Definition at line 11 of file Task.cpp.
 {
     CLI;
     trace("Initializing Syscalls...");
     init_syscalls();
     BS->IncreaseProgres();
     trace("Starting tasking mode %d", Mode);
     switch (Mode)
     {
     case TaskingMode::Mono:
     {
         monot = new MonoTasking(Address);
         BS->IncreaseProgres();
         break;
     }
     case TaskingMode::Multi:
     {
         mt = new Multitasking;
         mt->CreateThread(mt->CreateProcess(nullptr, (char *)"kernel", ELEVATION::Kernel), Address, 0, 0);
         MultitaskingSchedulerEnabled = true;
         BS->IncreaseProgres();
         break;
     }
     default:
     {
         STI;
         throw;
         break;
     }
     }
     STI;
 }
References Address, BS, CLI, BootScreen::Screen::IncreaseProgres(), init_syscalls(), Mode, Mono, Tasking::monot, Tasking::mt, Multi, Tasking::MultitaskingSchedulerEnabled, STI, and trace.
Referenced by do_tasking_test(), and KernelInit().