Fennix Project: libc/include/print.h File Reference
print.h File Reference
#include <file.h>
#include <stdarg.h>
Functions
E int fprintf (FILE *Stream, const char *Format,...)
E int sprintf (char *s, const char *format,...)
E int printf (const char *Format,...)
E int vfprintf (FILE *Stream, const char *Format, va_list Args)
E int vprintf (const char *Format, va_list Args)
E int snprintf (char *String, size_t Length, const char *Format,...)
E int vsnprintf (char *String, size_t Length, const char *Format, va_list Args)
E int sscanf (const char *String, const char *Format,...)
E int fputs (const char *String, FILE *Stream)
E int puts (const char *String)
E int fputc (int Char, FILE *Stream)
E int putchar (int Char)
E int fflush (FILE *Stream)
Variables
E FILE * fslin
E FILE * fslout
E FILE * fslerr
Function Documentation
fflush()
E int fflush (FILE * Stream)
Definition at line 172 of file print.c.
 {
     WriteSysDebugger("fflush( %p ) stub\n", stream);
     syscall_dbg(0x3F8, (char *)"\nfslout: ");
     syscall_dbg(0x3F8, (char *)fslout->PrintBuffer);
     syscall_dbg(0x3F8, (char *)"\nfslerr: ");
     syscall_dbg(0x3F8, (char *)fslerr->PrintBuffer);
     syscall_dbg(0x3F8, (char *)"\n");
     fslout->PrintBuffer[0] = '\0';
     fslerr->PrintBuffer[0] = '\0';
     return 0;
 }
References fslerr, fslout, _FILE::PrintBuffer, and WriteSysDebugger().
fprintf()
E int fprintf (FILE * Stream, const char * Format, ...)
Definition at line 29 of file print.c.
 {
     WriteSysDebugger("fprintf( %p %s ) stub\n", Stream, Format);
     return 0;
 }
References WriteSysDebugger().
Referenced by cag_option_print(), cag_option_print_letters(), cag_option_print_name(), and cag_option_print_value().
fputc()
E int fputc (int Char, FILE * Stream)
Definition at line 160 of file print.c.
 {
     append_printf(Stream->PrintBuffer, Char);
     return Char;
 }
References append_printf(), and _FILE::PrintBuffer.
fputs()
E int fputs (const char * String, FILE * Stream)
Definition at line 145 of file print.c.
 {
     size_t i = 0;
     for (i = 0; i < strlen((char *)String); i++)
         append_printf(Stream->PrintBuffer, String[i]);
     return i;
 }
References append_printf(), _FILE::PrintBuffer, and strlen().
Referenced by cag_option_print(), and puts().
printf()
E int printf (const char * Format, ...)
Definition at line 41 of file print.c.
 {
     va_list Args;
     va_start(Args, Format);
     int ret = vfctprintf(syswritedbgprint_wrapper, 0, Format, Args);
     va_end(Args);
     return ret;
 }
References syswritedbgprint_wrapper(), va_end, va_start, and vfctprintf().
putchar()
E int putchar (int Char)
Definition at line 166 of file print.c.
 {
     append_printf(fslout->PrintBuffer, Char);
     return 0;
 }
References append_printf(), fslout, and _FILE::PrintBuffer.
puts()
E int puts (const char * String)
Definition at line 153 of file print.c.
 {
     int ret = fputs(String, fslout);
     append_printf(fslout->PrintBuffer, '\n');
     return ret;
 }
References append_printf(), fputs(), fslout, and _FILE::PrintBuffer.
snprintf()
E int snprintf (char * String, size_t Length, const char * Format, ...)
Definition at line 60 of file print.c.
 {
     va_list Args;
     va_start(Args, Format);
     int ret = snprintf_(String, Length, Format, Args);
     va_end(Args);
     return ret;
 }
References Length, snprintf_(), va_end, and va_start.
sprintf()
E int sprintf (char * s, const char * format, ...)
Definition at line 35 of file print.c.
 {
     WriteSysDebugger("sprintf( %p %s ) stub\n", s, format);
     return 0;
 }
References WriteSysDebugger().
sscanf()
E int sscanf (const char * String, const char * Format, ...)
Definition at line 136 of file print.c.
 {
     va_list Args;
     va_start(Args, Format);
     int ret = vsscanf(String, Format, Args);
     va_end(Args);
     return ret;
 }
References va_end, va_start, and vsscanf().
vfprintf()
E int vfprintf (FILE * Stream, const char * Format, va_list Args)
Definition at line 50 of file print.c.
 {
     return vfctprintf(syswritedbgprint_wrapper, 0, Format, Args);
 }
References syswritedbgprint_wrapper(), and vfctprintf().
vprintf()
E int vprintf (const char * Format, va_list Args)
Definition at line 55 of file print.c.
 {
     return vfctprintf(syswritedbgprint_wrapper, 0, Format, Args);
 }
References syswritedbgprint_wrapper(), and vfctprintf().
vsnprintf()
E int vsnprintf (char * String, size_t Length, const char * Format, va_list Args)
Definition at line 69 of file print.c.
 {
     return vsnprintf_(String, Length, Format, Args);
 }
References Length, and vsnprintf_().
Variable Documentation
fslerr
E FILE* fslerr
Definition at line 9 of file print.h.
fslin
E FILE* fslin
Definition at line 7 of file print.h.
fslout
E FILE* fslout
Definition at line 8 of file print.h.