Fennix Project: Tasking Namespace Reference
Tasking Namespace Reference
Data Structures
class Monotasking
class Multitasking
struct TaskControlBlock
Enumerations
enum TaskState {
TaskStateNull, TaskStateReady, TaskStateRunning, TaskStateWaiting,
TaskStateTerminated, TaskPushed, TaskPoped
}
Functions
__attribute__ ((naked, used)) void MonoTaskingSchedulerHelper()
TaskControlBlock * FindLastTask ()
void AllocateTask (TaskControlBlock *task)
void FreeTask (TaskControlBlock *task)
InterruptHandler (mono_schedule_interrupt_handler)
__attribute__ ((__noreturn__)) void MonoTaskingTaskExit()
void drawrectangle (uint64_t X, uint64_t Y, uint64_t W, uint64_t H, uint32_t C)
void TraceSchedOnScreen ()
void TriggerOneShot (uint32_t Vector, uint64_t Miliseconds)
void ProcessDoExit (uint64_t Code)
void UpdateTimeUsed (GeneralProcessInfo *Info)
void UpdateCPUUsage (GeneralProcessInfo *Info)
void SetInfo (GeneralProcessInfo *Info)
bool InvalidPCB (PCB *pcb)
bool InvalidTCB (TCB *tcb)
void RemoveThread (TCB *tcb)
void RemoveProcess (PCB *pcb)
void UpdatePageTable (CR3 pt)
static void MakeOneShot ()
static void MultiTaskingSchedulerHandler (ThreadRegisters *regs)
Variables
bool MultitaskingSchedulerEnabled = false
Monotasking * monot = nullptr
Multitasking * mt = nullptr
TaskControlBlock * CurrentTask = nullptr
TaskControlBlock * TaskQueue [MAX_TASKS]
static uint64_t TaskIDs = 0
Critical::CriticalSectionData * CriticalSectionData = nullptr
Data Structure Documentation
Tasking::TaskControlBlock
struct Tasking::TaskControlBlock
Definition at line 30 of file internal_task.h.
Data Fields
unsigned int checksum
PCB * CompatibiltyProcess
TCB * CompatibiltyThread
uint64_t Day
uint64_t fs
uint64_t gs
uint64_t Hour
uint64_t id
uint64_t Minute
uint64_t Month
char name[256]
CR3 pml4
TrapFrame regs
uint64_t Second
uint64_t SpawnTick
void * stack
enum TaskState state
bool UserMode
uint64_t Year
Enumeration Type Documentation
TaskState
enum Tasking::TaskState
Enumerator
TaskStateNull
TaskStateReady
TaskStateRunning
TaskStateWaiting
TaskStateTerminated
TaskPushed
TaskPoped
Definition at line 18 of file internal_task.h.
     {
         TaskStateNull,
         TaskStateReady,
         TaskStateRunning,
         TaskStateWaiting,
         TaskStateTerminated,
         TaskPushed,
         TaskPoped,
     };
Function Documentation
__attribute__() [1/2]
Tasking::__attribute__ ((__noreturn__))
Definition at line 187 of file Monotasking.cpp.
     {
         CurrentTask->state = TaskState::TaskStateTerminated;
         trace("Task %s exited.", CurrentTask->name);
         SchedulerInterrupt;
         CPU_STOP;
     }
References CPU_STOP, CurrentTask, Tasking::TaskControlBlock::name, SchedulerInterrupt, Tasking::TaskControlBlock::state, TaskStateTerminated, and trace.
__attribute__() [2/2]
Tasking::__attribute__ ((naked, used))
Definition at line 24 of file Monotasking.cpp.
         {
             asm("cld\n"
                 "pushq %rax\n"
                 "pushq %rbx\n"
                 "pushq %rcx\n"
                 "pushq %rdx\n"
                 "pushq %rsi\n"
                 "pushq %rdi\n"
                 "pushq %rbp\n"
                 "pushq %r8\n"
                 "pushq %r9\n"
                 "pushq %r10\n"
                 "pushq %r11\n"
                 "pushq %r12\n"
                 "pushq %r13\n"
                 "pushq %r14\n"
                 "pushq %r15\n"
                 "movq %rsp, %rdi\n"
                 "call mono_schedule_interrupt_handler\n"
                 "popq %r15\n"
                 "popq %r14\n"
                 "popq %r13\n"
                 "popq %r12\n"
                 "popq %r11\n"
                 "popq %r10\n"
                 "popq %r9\n"
                 "popq %r8\n"
                 "popq %rbp\n"
                 "popq %rdi\n"
                 "popq %rsi\n"
                 "popq %rdx\n"
                 "popq %rcx\n"
                 "popq %rbx\n"
                 "popq %rax\n"
                 "addq $16, %rsp\n"
                 "iretq");
         }
AllocateTask()
void Tasking::AllocateTask (TaskControlBlock * task)
Definition at line 83 of file Monotasking.cpp.
     {
         for (size_t i = 0; i < MAX_TASKS; i++)
         {
             if (TaskQueue[i] != nullptr)
                 continue;
             if (TaskQueue[i]->checksum == TASK_CHECKSUM)
                 continue;
             TaskQueue[i] = task;
             debug("Task %s has been added to queue", task->name);
             break;
         }
     }
References debug, MAX_TASKS, Tasking::TaskControlBlock::name, TASK_CHECKSUM, and TaskQueue.
Referenced by Tasking::Monotasking::CreateTask().
drawrectangle()
void Tasking::drawrectangle (uint64_t X, uint64_t Y, uint64_t W, uint64_t H, uint32_t C)
Definition at line 39 of file Multitasking.cpp.
     {
         for (uint64_t y = Y; y < Y + H; y++)
             for (uint64_t x = X; x < X + W; x++)
                 CurrentDisplay->SetPixel(x, y, C);
     }
References CurrentDisplay.
Referenced by TraceSchedOnScreen().
FindLastTask()
TaskControlBlock* Tasking::FindLastTask ()
Definition at line 68 of file Monotasking.cpp.
     {
         for (int i = MAX_TASKS; i > -1; i--)
         {
             if (TaskQueue[i] == nullptr)
                 continue;
             if (TaskQueue[i]->checksum != TASK_CHECKSUM)
                 continue;
             debug("Last task in queue is %s.", TaskQueue[i]->name);
             return TaskQueue[i];
         }
         // debug("No more tasks in queue. Returning null...");
         return nullptr;
     }
References debug, MAX_TASKS, TASK_CHECKSUM, and TaskQueue.
Referenced by FreeTask(), InterruptHandler(), and Tasking::Monotasking::PushTask().
FreeTask()
void Tasking::FreeTask (TaskControlBlock * task)
Definition at line 97 of file Monotasking.cpp.
     {
         for (size_t i = 0; i < MAX_TASKS; i++)
         {
             if (TaskQueue[i] == nullptr)
                 continue;
             if (TaskQueue[i]->checksum != TASK_CHECKSUM)
                 continue;
             if (TaskQueue[i] == task)
             {
                 debug("Task %s will be removed from queue.", task->name);
                 KernelStackAllocator->FreeStack((void *)TaskQueue[i]->stack);
                 // KernelPageTableAllocator->RemovePageTable((VMM::PageTable *)TaskQueue[i]->pml4.raw);
                 delete TaskQueue[i];
                 memset(TaskQueue[i], 0, sizeof(TaskControlBlock));
                 TaskQueue[i] = FindLastTask();
                 debug("Task removed.");
                 break;
             }
         }
     }
References debug, FindLastTask(), KernelStackAllocator, MAX_TASKS, memset(), Tasking::TaskControlBlock::name, TASK_CHECKSUM, and TaskQueue.
Referenced by InterruptHandler(), and Tasking::Monotasking::~Monotasking().
InterruptHandler()
Tasking::InterruptHandler (mono_schedule_interrupt_handler)
Definition at line 121 of file Monotasking.cpp.
         {
             debug("Mono scheduler called.");
             foreach (auto t in TaskQueue)
             {
                 if (t->state == TaskState::TaskPushed)
                 {
                     t->state = TaskState::TaskStateWaiting;
                     // t->regs = *regs;
                 }
                 else if (t->state == TaskState::TaskPoped)
                 {
                     t->state = TaskState::TaskStateWaiting;
                     // *regs = t->regs;
                 }
             }
             bool task_changed = false;
             for (int i = MAX_TASKS; i > -1; i--)
             {
                 if (TaskQueue[i] == nullptr)
                     continue;
                 if (TaskQueue[i]->checksum != TASK_CHECKSUM)
                     continue;
                 switch (TaskQueue[i]->state)
                 {
                 case TaskState::TaskStateReady:
                 {
                     TaskQueue[i]->state = TaskState::TaskStateRunning;
                     *regs = TaskQueue[i]->regs;
                     writecr3(TaskQueue[i]->pml4);
                     CurrentTask = TaskQueue[i];
                     trace("Task %s is now running.", TaskQueue[i]->name);
                     task_changed = true;
                     goto scheduler_eoi;
                 }
                 case TaskState::TaskStateWaiting:
                 {
                     debug("Task %s is waiting for another task.", TaskQueue[i]->name);
                     continue;
                 }
                 case TaskState::TaskStateTerminated:
                 {
                     FreeTask(TaskQueue[i]);
                     if (FindLastTask() == nullptr)
                     {
                         err("No more tasks to run! System halted."); // we never want to get here.
                         CPU_HALT;
                     }
                     continue;
                 }
                 case TaskState::TaskPushed:
                 case TaskState::TaskPoped:
                 case TaskState::TaskStateRunning:
                 default:
                     continue;
                 }
             }
         scheduler_eoi:
             EndOfInterrupt(INT_NUM);
             if (!task_changed)
                 SchedulerInterrupt;
         }
References CPU_HALT, CurrentTask, debug, EndOfInterrupt(), err, FindLastTask(), FreeTask(), MAX_TASKS, Tasking::TaskControlBlock::regs, SchedulerInterrupt, Tasking::TaskControlBlock::state, TASK_CHECKSUM, TaskPoped, TaskPushed, TaskQueue, TaskStateReady, TaskStateRunning, TaskStateTerminated, TaskStateWaiting, trace, and writecr3().
InvalidPCB()
bool Tasking::InvalidPCB (PCB * pcb) inline
Definition at line 346 of file Multitasking.cpp.
     {
         if (pcb == nullptr)
             return true;
         if ((unsigned long)pcb >= (unsigned long)0x10000000) // FIXME: this is a workaround.
             return true;
         else if (pcb->Checksum != Checksum::PROCESS_CHECKSUM)
             return true;
         else if (pcb->Elevation == ELEVATION::Idle)
             return true;
         return false;
     }
Referenced by MultiTaskingSchedulerHandler(), and Tasking::Multitasking::~Multitasking().
InvalidTCB()
bool Tasking::InvalidTCB (TCB * tcb) inline
Definition at line 359 of file Multitasking.cpp.
     {
         if (tcb == nullptr)
             return true;
         if ((unsigned long)tcb >= (unsigned long)0x10000000) // FIXME: this is a workaround.
             return true;
         else if (tcb->Checksum != Checksum::THREAD_CHECKSUM)
             return true;
         else if (tcb->Parent->Elevation == ELEVATION::Idle)
             return true;
         return false;
     }
Referenced by MultiTaskingSchedulerHandler().
MakeOneShot()
static void Tasking::MakeOneShot () static
Definition at line 477 of file Multitasking.cpp.
 { TriggerOneShot(SchedulerInterrupt, 100); }
References SchedulerInterrupt, and TriggerOneShot().
MultiTaskingSchedulerHandler()
static void Tasking::MultiTaskingSchedulerHandler (ThreadRegisters * regs) static
Definition at line 487 of file Multitasking.cpp.
         {
             schedbg("MultiTaskingSchedulerHandler called.");
             if (!MultitaskingSchedulerEnabled)
             {
                 TriggerOneShot(SchedulerInterrupt, 100);
                 EndOfInterrupt(INT_NUM); // apic->IPI(CurrentCPU->ID, SchedulerInterrupt);
                 return;
             }
             CriticalSectionData->EnableInterrupts = InterruptsEnabled();
             CLI;
             LOCK(CriticalSectionData->CriticalLock);
 #ifdef DEBUG_TASK_MANAGER
             // static int slowschedule = 0;
             // if (slowschedule < 400)
             // {
             //     slowschedule++;
             //     UNLOCK(CriticalSectionData->CriticalLock);
             //     if (CriticalSectionData->EnableInterrupts)
             //         STI;
             //     TriggerOneShot(SchedulerInterrupt, 200);
             //     EndOfInterrupt(INT_NUM); // apic->IPI(CurrentCPU->ID, SchedulerInterrupt);
             //     return;
             // }
             // else
             //     slowschedule = 0;
             TraceSchedOnScreen();
 #endif
             schedbg("Status: 0-ukn | 1-rdy | 2-run | 3-wait | 4-term");
             schedbg("Technical Informations on regs %#lx", regs->int_num);
             schedbg("FS=%#lx  GS=%#lx  SS=%#lx  CS=%#lx", rdmsr(MSR_FS_BASE), rdmsr(MSR_GS_BASE), _SS, CS);
             schedbg("R8=%#lx  R9=%#lx  R10=%#lx  R11=%#lx", R8, R9, R10, R11);
             schedbg("R12=%#lx  R13=%#lx  R14=%#lx  R15=%#lx", R12, R13, R14, R15);
             schedbg("RAX=%#lx  RBX=%#lx  RCX=%#lx  RDX=%#lx", RAX, RBX, RCX, RDX);
             schedbg("RSI=%#lx  RDI=%#lx  RBP=%#lx  RSP=%#lx", RSI, RDI, RBP, RSP);
             schedbg("RIP=%#lx  RFL=%#lx  INT=%#lx  ERR=%#lx", RIP, FLAGS.raw, INT_NUM, ERROR_CODE);
             // Null or invalid process/thread? Let's find a new one to execute.
             if (InvalidPCB(CurrentCPU->CurrentProcess) || InvalidTCB(CurrentCPU->CurrentThread))
             {
                 schedbg("%d processes", mt->ListProcess.size());
 #ifdef DEBUG_SCHEDULER
                 foreach (auto var in mt->ListProcess)
                 {
                     schedbg("Process %d %s", var->ID, var->Name);
                 }
 #endif
                 // Find a new process to execute.
                 foreach (PCB *pcb in mt->ListProcess)
                 {
                     if (InvalidPCB(pcb))
                         continue;
                     // Check process status.
                     switch (pcb->Status)
                     {
                     case STATUS::Ready:
                         schedbg("Ready process (%s)%d", pcb->Name, pcb->ID);
                         break;
                     default:
                         schedbg("Process %s(%d) status %d", pcb->Name, pcb->ID, pcb->Status);
                         // RemoveProcess(pcb); // ignore for now
                         continue;
                     }
                     // Get first available thread from the list.
                     foreach (TCB *tcb in pcb->Threads)
                     {
                         if (InvalidTCB(tcb))
                             continue;
                         if (tcb->Status != STATUS::Ready)
                             continue;
                         // Set process and thread as the current one's.
                         CurrentCPU->CurrentProcess = pcb;
                         CurrentCPU->CurrentThread = tcb;
                         // Success!
                         goto Success;
                     }
                 }
                 schedbg("No process to run.");
                 // No process found. Idling...
                 goto Idle;
             }
             else
             {
                 // Save current process and thread registries, gs, fs, fpu, etc...
                 CurrentCPU->CurrentThread->Registers = *regs;
                 CurrentCPU->CurrentThread->gs = rdmsr(MSR_SHADOW_GS_BASE);
                 CurrentCPU->CurrentThread->fs = rdmsr(MSR_FS_BASE);
                 CurrentCPU->fxsave(CurrentCPU->CurrentThread->FXRegion);
                 // Set the process & thread as ready if it's running.
                 if (CurrentCPU->CurrentProcess->Status == STATUS::Running)
                     CurrentCPU->CurrentProcess->Status = STATUS::Ready;
                 if (CurrentCPU->CurrentThread->Status == STATUS::Running)
                     CurrentCPU->CurrentThread->Status = STATUS::Ready;
                 // Get next available thread from the list.
                 for (uint64_t i = 0; i < CurrentCPU->CurrentProcess->Threads.size(); i++)
                 {
                     // Loop until we find the current thread from the process thread list.
                     if (CurrentCPU->CurrentProcess->Threads[i] == CurrentCPU->CurrentThread)
                     {
                         // Check if the next thread is valid. If not, we search until we find, but if we reach the end of the list, we go to the next process.
                         uint64_t tmpidx = i;
                     RetryAnotherThread:
                         TCB *thread = CurrentCPU->CurrentProcess->Threads[tmpidx + 1];
                         if (InvalidTCB(thread))
{
                             if (tmpidx > CurrentCPU->CurrentProcess->Threads.size())
                                 break;
                             tmpidx++;
                             goto RetryAnotherThread;
                         }
                         schedbg("%s(%d) and next thread is %s(%d)", CurrentCPU->CurrentProcess->Threads[i]->Name, CurrentCPU->CurrentProcess->Threads[i]->ID, thread->Name, thread->ID);
                         // Check if the thread is ready to be executed.
                         if (thread->Status != STATUS::Ready)
{
                             schedbg("Thread %d is not ready", thread->ID);
                             goto RetryAnotherThread;
                         }
                         // Everything is fine, we can set the new thread as the current one.
                         CurrentCPU->CurrentThread = thread;
                         schedbg("[thd 0 -> end] Scheduling thread %d parent of %s->%d Procs %d", thread->ID, thread->Parent->Name, CurrentCPU->CurrentProcess->Threads.size(), mt->ListProcess.size());
                         // Yay! We found a new thread to execute.
                         goto Success;
                     }
                 }
                 // If the last process didn't find a thread to execute, we search for a new process.
                 for (uint64_t i = 0; i < mt->ListProcess.size(); i++)
                 {
                     // Loop until we find the current process from the process list.
                     if (mt->ListProcess[i] == CurrentCPU->CurrentProcess)
                     {
                         // Check if the next process is valid. If not, we search until we find.
                         uint64_t tmpidx = i;
                     RetryAnotherProcess:
                         PCB *pcb = mt->ListProcess[tmpidx + 1];
                         if (InvalidPCB(pcb))
{
                             if (tmpidx > mt->ListProcess.size())
                                 break;
                             tmpidx++;
                             goto RetryAnotherProcess;
                         }
                         if (pcb->Status != STATUS::Ready)
                             goto RetryAnotherProcess;
                         // Everything good, now search for a thread.
                         for (uint64_t j = 0; j < pcb->Threads.size(); j++)
{
                             TCB *tcb = pcb->Threads[j];
                             if (InvalidTCB(tcb))
                                 continue;
                             if (tcb->Status != STATUS::Ready)
                                 continue;
                             // Success! We set as the current one and restore the stuff.
                             CurrentCPU->CurrentProcess = pcb;
                             CurrentCPU->CurrentThread = tcb;
                             schedbg("[cur proc+1 -> first thd] Scheduling thread %d %s->%d (Total Procs %d)", tcb->ID, tcb->Name, pcb->Threads.size(), mt->ListProcess.size());
                             goto Success;
                         }
                     }
                 }
                 // Before checking from the beginning, we remove everything that is terminated.
                 foreach (PCB *pcb in mt->ListProcess)
                 {
                     if (InvalidPCB(pcb))
                         continue;
                     // RemoveProcess(pcb); // comment this until i will find a way to handle properly vectors, the memory need to be 0ed after removing.
                 }
                 // If we didn't find anything, we check from the start of the list. This is the last chance to find something or we go to idle.
                 foreach (PCB *pcb in mt->ListProcess)
                 {
                     if (InvalidPCB(pcb))
                         continue;
                     if (pcb->Status != STATUS::Ready)
                         continue;
                     // Now do the thread search!
                     foreach (TCB *tcb in pcb->Threads)
                     {
                         if (InvalidTCB(tcb))
                             continue;
                         if (tcb->Status != STATUS::Ready)
                             continue;
                         // \o/ We found a new thread to execute.
                         CurrentCPU->CurrentProcess = pcb;
                         CurrentCPU->CurrentThread = tcb;
                         schedbg("[proc 0 -> end -> first thd] Scheduling thread %d parent of %s->%d (Procs %d)", tcb->ID, tcb->Parent->Name, pcb->Threads.size(), mt->ListProcess.size());
                         goto Success;
                     }
                 }
             }
         Idle:
         {
             // I should remove processes that are no longer having any threads? remove only from userspace?
             if (mt->IdleProcess == nullptr)
             {
                 schedbg("Idle process created");
                 mt->IdleProcess = mt->CreateProcess(nullptr, (char *)"idle", ELEVATION::Idle);
                 mt->IdleThread = mt->CreateThread(mt->IdleProcess, reinterpret_cast<uint64_t>(IdleProcessLoop), 0, 0);
             }
             CurrentCPU->CurrentProcess = mt->IdleProcess;
             CurrentCPU->CurrentThread = mt->IdleThread;
             *regs = CurrentCPU->CurrentThread->Registers;
             CR3 cr3;
             cr3.raw = (uint64_t)KernelPageTableManager.PML4;
             UpdatePageTable(cr3);
             wrmsr(MSR_FS_BASE, CurrentCPU->CurrentThread->fs);
             wrmsr(MSR_GS_BASE, (uint64_t)CurrentCPU->CurrentThread);
             wrmsr(MSR_SHADOW_GS_BASE, (uint64_t)CurrentCPU->CurrentThread);
             CurrentCPU->fxrstor(CurrentCPU->CurrentThread->FXRegion);
             goto End;
         }
         Success:
         {
             schedbg("Success Prc:%s(%d) Thd:%s(%d)->RIP:%#lx-RSP:%#lx(STACK: %#lx)",
                     CurrentCPU->CurrentProcess->Name, CurrentCPU->CurrentProcess->ID,
                     CurrentCPU->CurrentThread->Name, CurrentCPU->CurrentThread->ID,
                     CurrentCPU->CurrentThread->Registers.rip, CurrentCPU->CurrentThread->Registers.rsp, CurrentCPU->CurrentThread->Stack);
             CurrentCPU->CurrentProcess->Status = STATUS::Running;
             CurrentCPU->CurrentThread->Status = STATUS::Running;
             *regs = CurrentCPU->CurrentThread->Registers;
             UpdatePageTable(CurrentCPU->CurrentProcess->PageTable);
             wrmsr(MSR_FS_BASE, CurrentCPU->CurrentThread->fs);
             wrmsr(MSR_GS_BASE, (uint64_t)CurrentCPU->CurrentThread);
             switch (CurrentCPU->CurrentProcess->Elevation)
             {
             case ELEVATION::System:
             case ELEVATION::Idle:
             case ELEVATION::Kernel:
                 wrmsr(MSR_SHADOW_GS_BASE, (uint64_t)CurrentCPU->CurrentThread);
                 break;
             case ELEVATION::User:
                 wrmsr(MSR_SHADOW_GS_BASE, CurrentCPU->CurrentThread->gs);
                 break;
             default:
                 err("Unknown elevation %d.", CurrentCPU->CurrentProcess->Elevation);
                 break;
             }
             CurrentCPU->fxrstor(CurrentCPU->CurrentThread->FXRegion);
         }
         End:
         {
             UpdateTimeUsed(&CurrentCPU->CurrentProcess->Info);
             UpdateTimeUsed(&CurrentCPU->CurrentThread->Info);
             UpdateCPUUsage(&CurrentCPU->CurrentProcess->Info);
             UpdateCPUUsage(&CurrentCPU->CurrentThread->Info);
             UNLOCK(CriticalSectionData->CriticalLock);
             if (CriticalSectionData->EnableInterrupts)
                 STI;
             TriggerOneShot(SchedulerInterrupt, CurrentCPU->CurrentThread->Info.Priority);
             schedbg("Scheduler end");
             EndOfInterrupt(INT_NUM); // apic->IPI(CurrentCPU->ID, SchedulerInterrupt);
         }
             schedbg("Technical Informations on Thread %s[%ld]:", CurrentCPU->CurrentThread->Name, CurrentCPU->CurrentThread->ID);
             schedbg("FS=%#lx  GS=%#lx  SS=%#lx  CS=%#lx", rdmsr(MSR_FS_BASE), rdmsr(MSR_GS_BASE), _SS, CS);
             schedbg("R8=%#lx  R9=%#lx  R10=%#lx  R11=%#lx", R8, R9, R10, R11);
             schedbg("R12=%#lx  R13=%#lx  R14=%#lx  R15=%#lx", R12, R13, R14, R15);
             schedbg("RAX=%#lx  RBX=%#lx  RCX=%#lx  RDX=%#lx", RAX, RBX, RCX, RDX);
             schedbg("RSI=%#lx  RDI=%#lx  RBP=%#lx  RSP=%#lx", RSI, RDI, RBP, RSP);
             schedbg("RIP=%#lx  RFL=%#lx  INT=%#lx  ERR=%#lx", RIP, FLAGS.raw, INT_NUM, ERROR_CODE);
             schedbg("SCHEDULER FUNCTION END");
         }
References CLI, Tasking::Multitasking::CreateProcess(), Tasking::Multitasking::CreateThread(), Critical::CriticalSectionData::CriticalLock, CriticalSectionData, CurrentCPU, Critical::CriticalSectionData::EnableInterrupts, EndOfInterrupt(), err, Tasking::Multitasking::IdleProcess, Tasking::Multitasking::IdleThread, InterruptsEnabled(), InvalidPCB(), InvalidTCB(), KernelPageTableManager, Tasking::Multitasking::ListProcess, LOCK, MSR_FS_BASE, MSR_GS_BASE, MSR_SHADOW_GS_BASE, mt, MultitaskingSchedulerEnabled, rdmsr(), schedbg, SchedulerInterrupt, STI, TraceSchedOnScreen(), TriggerOneShot(), UNLOCK, UpdateCPUUsage(), UpdatePageTable(), UpdateTimeUsed(), and wrmsr().
ProcessDoExit()
void Tasking::ProcessDoExit (uint64_t Code)
Definition at line 164 of file Multitasking.cpp.
     {
         EnterCriticalSection;
         CurrentCPU->CurrentThread->Status = STATUS::Terminated;
         CurrentCPU->CurrentThread->ExitCode = Code;
         schedbg("parent:%s tid:%d, code:%016p", CurrentCPU->CurrentProcess->Name, CurrentCPU->CurrentThread->ID, Code);
         trace("Exiting thread %d(%s)...", CurrentCPU->CurrentThread->ID, CurrentCPU->CurrentThread->Name);
         LeaveCriticalSection;
         TriggerOneShot(SchedulerInterrupt, 100);
         CPU_STOP;
     }
References CPU_STOP, CurrentCPU, EnterCriticalSection, LeaveCriticalSection, schedbg, SchedulerInterrupt, trace, and TriggerOneShot().
Referenced by Tasking::Multitasking::CreateThread().
RemoveProcess()
void Tasking::RemoveProcess (PCB * pcb)
Definition at line 386 of file Multitasking.cpp.
     {
         if (pcb == nullptr)
             return;
         if (pcb->Status == Terminated)
         {
             foreach (TCB *thread in pcb->Threads)
             {
                 RemoveThread(thread);
             }
             foreach (PCB *process in pcb->Children)
             {
                 RemoveProcess(process);
             }
             for (size_t i = 0; i < mt->ListProcess.size(); i++)
             {
                 if (mt->ListProcess[i] == pcb)
                 {
                     trace("pcb %d terminated", mt->ListProcess[i]->ID);
                     KernelPageTableAllocator->RemovePageTable(reinterpret_cast<VMM::PageTable *>(mt->ListProcess[i]->PageTable.raw));
                     mt->ListProcess[i]->Checksum = badfennec;
                     kfree(mt->ListProcess[i]);
                     mt->ListProcess.remove(i);
                     break;
                 }
             }
         }
         else
         {
             foreach (TCB *thread in pcb->Threads)
             {
                 if (thread->Status == Terminated)
                     RemoveThread(thread);
             }
         }
     }
References badfennec, KernelPageTableAllocator, kfree, Tasking::Multitasking::ListProcess, mt, PageTable, RemoveThread(), and trace.
Referenced by Tasking::Multitasking::~Multitasking().
RemoveThread()
void Tasking::RemoveThread (TCB * tcb)
Definition at line 372 of file Multitasking.cpp.
     {
         for (uint64_t i = 0; i < tcb->Parent->Threads.size(); i++)
             if (tcb->Parent->Threads[i] == tcb)
             {
                 trace("Thread %d terminated", tcb->ID);
                 KernelStackAllocator->FreeStack(tcb->Parent->Threads[i]->Stack);
                 tcb->Parent->Threads[i]->Checksum = badfennec;
                 kfree(tcb->Parent->Threads[i]);
                 tcb->Parent->Threads.remove(i);
                 break;
             }
     }
References badfennec, KernelStackAllocator, kfree, and trace.
Referenced by RemoveProcess().
SetInfo()
void Tasking::SetInfo (GeneralProcessInfo * Info)
Definition at line 204 of file Multitasking.cpp.
     {
         Info->SpawnTick = counter();
         uint32_t t = 0;
         outb(0x70, 0x00);
         t = inb(0x71);
         Info->Second = ((t & 0x0F) + ((t >> 4) * 10));
         outb(0x70, 0x02);
         t = inb(0x71);
         Info->Minute = ((t & 0x0F) + ((t >> 4) * 10));
         outb(0x70, 0x04);
         t = inb(0x71);
         Info->Hour = ((t & 0x0F) + ((t >> 4) * 10));
         outb(0x70, 0x07);
         t = inb(0x71);
         Info->Day = ((t & 0x0F) + ((t >> 4) * 10));
         outb(0x70, 0x08);
         t = inb(0x71);
         Info->Month = ((t & 0x0F) + ((t >> 4) * 10));
         outb(0x70, 0x09);
         t = inb(0x71);
         Info->Year = ((t & 0x0F) + ((t >> 4) * 10));
     }
References counter(), inb, and outb.
Referenced by Tasking::Multitasking::CreateProcess(), and Tasking::Multitasking::CreateThread().
TraceSchedOnScreen()
void Tasking::TraceSchedOnScreen ()
Definition at line 46 of file Multitasking.cpp.
     {
         CurrentDisplay->ResetPrintPosition();
         drawrectangle(0, 0, 222, CurrentDisplay->GetFramebuffer()->Height / 2, 0x282828);
         bool showarrow = false;
         CurrentDisplay->SetPrintColor(0xF222F2);
         if (CurrentCPU->CurrentProcess == mt->IdleProcess)
             printf("Idle Process Running\n");
         if (CurrentCPU->CurrentThread == mt->IdleThread)
             printf("Idle Thread Running\n");
         foreach (auto Proc1 in mt->ListProcess)
         {
             showarrow = false;
             CurrentDisplay->SetPrintColor(0xFF2200);
             if (Proc1 == CurrentCPU->CurrentProcess)
                 showarrow = true;
             printf("%s(%ld) %s [%ld%%/%ld]\n", Proc1->Name, Proc1->ID, showarrow ? "<-" : "  ", Proc1->Info.Usage[0], Proc1->Info.UsedTicks);
             foreach (auto thd in Proc1->Threads)
             {
                 showarrow = false;
                 CurrentDisplay->SetPrintColor(0x00FF22);
                 if (thd == CurrentCPU->CurrentThread)
                     showarrow = true;
                 printf(" \\%s(%ld) %s [%ld%%/%ld]\n", Proc1->Name, thd->ID, showarrow ? "<-" : "  ", thd->Info.Usage[0], thd->Info.UsedTicks);
             }
             foreach (auto Proc1Children in Proc1->Children)
             {
                 showarrow = false;
                 CurrentDisplay->SetPrintColor(0xFF2200);
                 if (Proc1Children == CurrentCPU->CurrentProcess)
                     showarrow = true;
                 printf(" \\%s(%ld) %s [%ld%%/%ld]\n", Proc1Children->Name, Proc1Children->ID, showarrow ? "<-" : "  ", Proc1Children->Info.Usage[0], Proc1Children->Info.UsedTicks);
                 foreach (auto thd in Proc1Children->Threads)
                 {
                     showarrow = false;
                     CurrentDisplay->SetPrintColor(0x00FF22);
                     if (thd == CurrentCPU->CurrentThread)
                         showarrow = true;
                     printf("  \\%s(%ld) %s [%ld%%/%ld]\n", Proc1Children->Name, thd->ID, showarrow ? "<-" : "  ", thd->Info.Usage[0], thd->Info.UsedTicks);
                 }
                 foreach (auto Proc2Children in Proc1Children->Children)
                 {
                     showarrow = false;
                     CurrentDisplay->SetPrintColor(0xFF2200);
                     if (Proc2Children == CurrentCPU->CurrentProcess)
                         showarrow = true;
                     printf("  \\%s(%ld) %s [%ld%%/%ld]\n", Proc2Children->Name, Proc2Children->ID, showarrow ? "<-" : "  ", Proc2Children->Info.Usage[0], Proc2Children->Info.UsedTicks);
                     foreach (auto thd in Proc2Children->Threads)
                     {
                         showarrow = false;
                         CurrentDisplay->SetPrintColor(0x00FF22);
                         if (thd == CurrentCPU->CurrentThread)
                             showarrow = true;
                         printf("   \\%s(%ld) %s [%ld%%/%ld]\n", Proc2Children->Name, thd->ID, showarrow ? "<-" : "  ", thd->Info.Usage[0], thd->Info.UsedTicks);
                     }
                     foreach (auto Proc3Children in Proc2Children->Children)
                     {
                         showarrow = false;
                         CurrentDisplay->SetPrintColor(0xFF2200);
                         if (Proc3Children == CurrentCPU->CurrentProcess)
                             showarrow = true;
                         printf("   \\%s(%ld) %s [%ld%%/%ld]\n", Proc3Children->Name, Proc3Children->ID, showarrow ? "<-" : "  ", Proc3Children->Info.Usage[0], Proc3Children->Info.UsedTicks);
                         foreach (auto thd in Proc3Children->Threads)
{
                             showarrow = false;
                             CurrentDisplay->SetPrintColor(0x00FF22);
                             if (thd == CurrentCPU->CurrentThread)
                                 showarrow = true;
                             printf("     \\%s(%ld) %s [%ld%%/%ld]\n", Proc3Children->Name, thd->ID, showarrow ? "<-" : "  ", thd->Info.Usage[0], thd->Info.UsedTicks);
                         }
                         foreach (auto Proc4Children in Proc3Children->Children)
{
                             showarrow = false;
                             CurrentDisplay->SetPrintColor(0xFF2200);
                             if (Proc4Children == CurrentCPU->CurrentProcess)
                                 showarrow = true;
                             printf("     \\%s(%ld) %s [%ld%%/%ld]\n", Proc4Children->Name, Proc4Children->ID, showarrow ? "<-" : "  ", Proc4Children->Info.Usage[0], Proc4Children->Info.UsedTicks);
                             foreach (auto thd in Proc4Children->Threads)
{
                                 showarrow = false;
                                 CurrentDisplay->SetPrintColor(0x00FF22);
                                 if (thd == CurrentCPU->CurrentThread)
                                     showarrow = true;
                                 printf("      \\%s(%ld) %s [%ld%%/%ld]\n", Proc4Children->Name, thd->ID, showarrow ? "<-" : "  ", thd->Info.Usage[0], thd->Info.UsedTicks);
                             }
                             foreach (auto Proc5Children in Proc4Children->Children)
{
                                 showarrow = false;
                                 CurrentDisplay->SetPrintColor(0xFF2200);
                                 if (Proc5Children == CurrentCPU->CurrentProcess)
                                     showarrow = true;
                                 printf("      \\%s(%ld) %s [%ld%%/%ld]\n", Proc5Children->Name, Proc5Children->ID, showarrow ? "<-" : "  ", Proc5Children->Info.Usage[0], Proc5Children->Info.UsedTicks);
                                 foreach (auto thd in Proc5Children->Threads)
{
                                     showarrow = false;
                                     CurrentDisplay->SetPrintColor(0x00FF22);
                                     if (thd == CurrentCPU->CurrentThread)
                                         showarrow = true;
                                     printf("       \\%s(%ld) %s [%ld%%/%ld]\n", Proc5Children->Name, thd->ID, showarrow ? "<-" : "  ", thd->Info.Usage[0], thd->Info.UsedTicks);
                                 }
                             }
                         }
                     }
                 }
             }
             break;
         }
     }
References CurrentCPU, CurrentDisplay, drawrectangle(), Tasking::Multitasking::IdleProcess, Tasking::Multitasking::IdleThread, Tasking::Multitasking::ListProcess, mt, and printf.
Referenced by MultiTaskingSchedulerHandler().
TriggerOneShot()
void Tasking::TriggerOneShot (uint32_t Vector, uint64_t Miliseconds)
Definition at line 158 of file Multitasking.cpp.
     {
         schedbg("TriggerOneShot(IRQ%d, %d)", Vector - 32, Miliseconds);
         TimerOneShot(Vector, Miliseconds);
     }
References schedbg, and TimerOneShot().
Referenced by MakeOneShot(), Tasking::Multitasking::Multitasking(), MultiTaskingSchedulerHandler(), and ProcessDoExit().
UpdateCPUUsage()
void Tasking::UpdateCPUUsage (GeneralProcessInfo * Info)
Definition at line 191 of file Multitasking.cpp.
     {
         // uint64_t CurrentCount = counter();
         // TODO: for Info->Usage[cpu_count] = ...
         // for (size_t i = 0; i < 2; i++)
         // {
         // Info->Usage[i] = (uint32_t)((CurrentCount - Info->LastUsedTicks) * 100 / (CurrentCount - Info->SpawnTick));
         // if (Info->Usage[i] > 100)
         // Info->Usage[i] = 100;
         // }
     }
Referenced by MultiTaskingSchedulerHandler().
UpdatePageTable()
void Tasking::UpdatePageTable (CR3 pt)
Definition at line 426 of file Multitasking.cpp.
     {
         if (pt.raw == 0)
             return;
         if (pt.raw != readcr3().raw)
             writecr3(pt);
     }
References readcr3(), and writecr3().
Referenced by MultiTaskingSchedulerHandler().
UpdateTimeUsed()
void Tasking::UpdateTimeUsed (GeneralProcessInfo * Info)
Definition at line 176 of file Multitasking.cpp.
     {
         uint64_t CurrentCount = counter();
         if (Info->LastUsedTicks == 0)
         {
             Info->UsedTicks += CurrentCount + Info->SpawnTick;
             Info->LastUsedTicks = CurrentCount;
         }
         else
         {
             Info->UsedTicks += CurrentCount + Info->LastUsedTicks;
             Info->LastUsedTicks = CurrentCount;
         }
     }
References counter().
Referenced by MultiTaskingSchedulerHandler().
Variable Documentation
CriticalSectionData
Critical::CriticalSectionData* Tasking::CriticalSectionData = nullptr
Definition at line 434 of file Multitasking.cpp.
Referenced by Critical::Enter(), Tasking::Multitasking::Multitasking(), MultiTaskingSchedulerHandler(), and Tasking::Multitasking::~Multitasking().
CurrentTask
TaskControlBlock* Tasking::CurrentTask = nullptr
Definition at line 19 of file Monotasking.cpp.
Referenced by __attribute__(), InterruptHandler(), Tasking::Monotasking::KillMe(), Tasking::Monotasking::PopTask(), Tasking::Monotasking::PushTask(), and Tasking::Monotasking::~Monotasking().
monot
Monotasking * Tasking::monot = nullptr
Definition at line 16 of file Monotasking.cpp.
Referenced by internal_createtask(), internal_exit(), internal_poptask(), internal_pushtask(), StartTasking(), and SysCreateProcessFromFile().
mt
Multitasking * Tasking::mt = nullptr
Definition at line 36 of file Multitasking.cpp.
Referenced by MultiTaskingSchedulerHandler(), RemoveProcess(), StartTasking(), SysCreateProcess(), SysCreateThread(), SysGetProcessByPID(), SysGetThreadByTID(), TraceSchedOnScreen(), and Tasking::Multitasking::~Multitasking().
MultitaskingSchedulerEnabled
bool Tasking::MultitaskingSchedulerEnabled = false
Definition at line 35 of file Multitasking.cpp.
Referenced by MultiTaskingSchedulerHandler(), StartTasking(), and Tasking::Multitasking::~Multitasking().
TaskIDs
uint64_t Tasking::TaskIDs = 0 static
Definition at line 66 of file Monotasking.cpp.
Referenced by Tasking::Monotasking::CreateTask().
TaskQueue
TaskControlBlock* Tasking::TaskQueue[MAX_TASKS]
Definition at line 20 of file Monotasking.cpp.
Referenced by AllocateTask(), FindLastTask(), FreeTask(), InterruptHandler(), Tasking::Monotasking::KillMe(), Tasking::Monotasking::Monotasking(), Tasking::Monotasking::PopTask(), Tasking::Monotasking::PushTask(), and Tasking::Monotasking::~Monotasking().