Fennix Project: kernel/Lock.cpp File Reference
Lock.cpp File Reference
#include <lock.h>
#include <display.h>
#include <debug.h>
#include "drivers/serial.h"
Functions
void deadlock_handler (LOCK *lock)
unsigned long api_redirect_debug_write (int type, char *message, const char *file, int line, const char *function,...)
Variables
static int timeout = 0
Function Documentation
api_redirect_debug_write()
unsigned long api_redirect_debug_write (int type, char * message, const char * file, int line, const char * function, ...)
Definition at line 37 of file Lock.cpp.
 {
     return debug(message);
 }
References debug.
deadlock_handler()
void deadlock_handler (LOCK * lock)
Definition at line 9 of file Lock.cpp.
 {
     uint32_t x, y;
     x = CurrentDisplay->CurrentFont->GetFontSize().Width;
     y = CurrentDisplay->CurrentFont->GetFontSize().Height;
     CurrentDisplay->ResetPrintPosition();
     CurrentDisplay->SetPrintColor(0x450402);
     printf("Potential deadlock in lock '%s' held by '%s'", lock->lock_name, lock->current_holder);
     CurrentDisplay->ResetPrintColor();
     CurrentDisplay->SetPrintLocation(x, y);
     serial_write_text(COM1, (char *)"Potential deadlock in lock '");
     serial_write_text(COM1, (char *)lock->lock_name);
     serial_write_text(COM1, (char *)"' held by '");
     serial_write_text(COM1, (char *)lock->current_holder);
     serial_write_text(COM1, (char *)"'\nAttempting to get lock from ");
     serial_write_text(COM1, (char *)lock->attempting_to_get);
     write_serial(COM1, '\n');
     timeout++;
     if (timeout == 20)
     {
         timeout = 0;
         // Unlock it. Maybe this is a bad idea so that's why
         // TODO: Unlock only if it's from the kernel. If a driver or something else is holding it, we should not unlock after timeout. Also this never should be enabled when the smp is enabled. Or at least a timeout should be per core.
         spinlock_unlock(&lock->lock_dat);
         lock->count--;
     }
 }
References LOCK::attempting_to_get, COM1, LOCK::count, LOCK::current_holder, CurrentDisplay, LOCK::lock_dat, LOCK::lock_name, printf, serial_write_text(), spinlock_unlock(), timeout, and write_serial().
Variable Documentation
timeout
int timeout = 0 static
Definition at line 6 of file Lock.cpp.
Referenced by deadlock_handler().