Fennix Project: Xalloc::AllocatorV1 Class Reference
Xalloc::AllocatorV1 Class Reference
#include <Xalloc.hpp>
Data Structures
struct HeapSegment
Public Member Functions
void Xstac ()
void Xclac ()
AllocatorV1 (void *Address, bool UserMode, bool SMAPEnabled)
Construct a new Allocator V1 object.
~AllocatorV1 ()
Destroy the Allocator V 1 object.
void * Malloc (Xuint64_t Size)
Allocate a new memory block.
void Free (void *Address)
Free a previously allocated block.
void * Calloc (Xuint64_t NumberOfBlocks, Xuint64_t Size)
Allocate a new memory block.
void * Realloc (void *Address, Xuint64_t Size)
Reallocate a previously allocated block.
Private Member Functions
struct Xalloc::AllocatorV1::HeapSegment __attribute__ ((aligned(16)))
void ExpandHeap (Xuint64_t Length)
Static Private Member Functions
static void * Xmemcpy (void *__restrict__ Destination, const void *__restrict__ Source, Xuint64_t Length)
static void * Xmemset (void *__restrict__ Destination, int Data, Xuint64_t Length)
Private Attributes
void * HeapStart = nullptr
void * HeapEnd = nullptr
HeapSegment * LastSegment = nullptr
bool UserMapping = false
bool SMAPUsed = false
Detailed Description
Definition at line 27 of file Xalloc.hpp.
Constructor & Destructor Documentation
AllocatorV1()
Xalloc::AllocatorV1::AllocatorV1 (void * Address, bool UserMode, bool SMAPEnabled)
Construct a new Allocator V1 object.
Parameters
Address Virtual address to allocate.
UserMode Map the new pages with USER flag?
SMAPEnabled Does the kernel has Supervisor Mode Access Prevention enabled?
Definition at line 7 of file Xalloc.cpp.
     {
         void *Position = Address;
         UserMapping = UserMode;
         SMAPUsed = SMAPEnabled;
         Xstac();
         for (Xuint64_t i = 0; i < 0x20; i++)
         {
             void *Page = Xalloc_REQUEST_PAGE();
             if (UserMapping)
                 Xalloc_MAP_MEMORY(Position, Page, Xalloc_MAP_MEMORY_READ_WRITE | Xalloc_MAP_MEMORY_USER);
             else
                 Xalloc_MAP_MEMORY(Position, Page, Xalloc_MAP_MEMORY_READ_WRITE);
             Xalloc_trace("Preallocate Heap Memory (%#llx-%#llx [%#llx])...", Position, (Xuint64_t)Position + Xalloc_PAGE_SIZE, Page);
             Position = (void *)((Xuint64_t)Position + Xalloc_PAGE_SIZE);
         }
         Xuint64_t HeapLength = 16 * Xalloc_PAGE_SIZE;
         this->HeapStart = Address;
         this->HeapEnd = (void *)((Xuint64_t)this->HeapStart + HeapLength);
         HeapSegment *StartSegment = (HeapSegment *)Address;
         StartSegment->Length = HeapLength - sizeof(HeapSegment);
         StartSegment->Next = nullptr;
         StartSegment->Last = nullptr;
         StartSegment->IsFree = true;
         this->LastSegment = StartSegment;
         Xclac();
     }
References Address, HeapEnd, HeapStart, Xalloc::AllocatorV1::HeapSegment::IsFree, Xalloc::AllocatorV1::HeapSegment::Last, LastSegment, Xalloc::AllocatorV1::HeapSegment::Length, Xalloc::AllocatorV1::HeapSegment::Next, SMAPUsed, UserMapping, Xalloc_MAP_MEMORY, Xalloc_MAP_MEMORY_READ_WRITE, Xalloc_MAP_MEMORY_USER, Xalloc_PAGE_SIZE, Xalloc_REQUEST_PAGE, Xalloc_trace, Xclac(), and Xstac().
~AllocatorV1()
Xalloc::AllocatorV1::~AllocatorV1 ()
Destroy the Allocator V 1 object.
Definition at line 35 of file Xalloc.cpp.
     {
         Xstac();
         Xalloc_trace("Destructor not implemented yet.");
         Xclac();
     }
References Xalloc_trace, Xclac(), and Xstac().
Member Function Documentation
__attribute__()
struct Xalloc::AllocatorV1::HeapSegment Xalloc::AllocatorV1::__attribute__ ((aligned(16))) private
Calloc()
void * Xalloc::AllocatorV1::Calloc (Xuint64_t NumberOfBlocks, Xuint64_t Size)
Allocate a new memory block.
Parameters
NumberOfBlocks Number of blocks to allocate.
Size Size of the block to allocate.
Returns
void* Pointer to the allocated block.
Definition at line 151 of file Xalloc.cpp.
     {
         Xstac();
         if (this->HeapStart == nullptr)
         {
             Xalloc_err("Memory allocation not initialized yet!");
             Xclac();
             return 0;
         }
         if (Size < 0x10)
         {
             // Xalloc_warn("Allocation size is too small, using 0x10 instead!");
             Size = 0x10;
         }
         void *Block = this->Malloc(NumberOfBlocks * Size);
         Xstac();
         if (Block)
             Xmemset(Block, 0, NumberOfBlocks * Size);
         Xclac();
         return Block;
     }
References HeapStart, Malloc(), Xalloc_err, Xclac(), Xmemset(), and Xstac().
Referenced by HeapCalloc(), and Realloc().
ExpandHeap()
void Xalloc::AllocatorV1::ExpandHeap (Xuint64_t Length) private
Definition at line 42 of file Xalloc.cpp.
     {
         if (Length % Xalloc_PAGE_SIZE)
         {
             Length -= Length % Xalloc_PAGE_SIZE;
             Length += Xalloc_PAGE_SIZE;
         }
         Xuint64_t PageCount = Length / Xalloc_PAGE_SIZE;
         HeapSegment *NewSegment = (HeapSegment *)this->HeapEnd;
         for (Xuint64_t i = 0; i < PageCount; i++)
         {
             void *Page = Xalloc_REQUEST_PAGE();
             if (UserMapping)
                 Xalloc_MAP_MEMORY(this->HeapEnd, Page, Xalloc_MAP_MEMORY_READ_WRITE | Xalloc_MAP_MEMORY_USER);
             else
                 Xalloc_MAP_MEMORY(this->HeapEnd, Page, Xalloc_MAP_MEMORY_READ_WRITE);
             // Xalloc_trace("Expanding Heap Memory (%#llx-%#llx [%#llx])...", this->HeapEnd, (Xuint64_t)this->HeapEnd + Xalloc_PAGE_SIZE, Page);
             this->HeapEnd = (void *)((Xuint64_t)this->HeapEnd + Xalloc_PAGE_SIZE);
         }
         NewSegment->IsFree = true;
         NewSegment->Last = this->LastSegment;
         this->LastSegment->Next = NewSegment;
         this->LastSegment = NewSegment;
         NewSegment->Next = nullptr;
         NewSegment->Length = Length - sizeof(HeapSegment);
         NewSegment->CombineBackward(this->LastSegment);
     }
References Xalloc::AllocatorV1::HeapSegment::CombineBackward(), HeapEnd, Xalloc::AllocatorV1::HeapSegment::IsFree, Xalloc::AllocatorV1::HeapSegment::Last, LastSegment, Xalloc::AllocatorV1::HeapSegment::Length, Length, Xalloc::AllocatorV1::HeapSegment::Next, UserMapping, Xalloc_MAP_MEMORY, Xalloc_MAP_MEMORY_READ_WRITE, Xalloc_MAP_MEMORY_USER, Xalloc_PAGE_SIZE, and Xalloc_REQUEST_PAGE.
Referenced by Malloc().
Free()
void Xalloc::AllocatorV1::Free (void * Address)
Free a previously allocated block.
Parameters
Address Address of the block to free.
Definition at line 135 of file Xalloc.cpp.
     {
         Xstac();
         if (this->HeapStart == nullptr)
         {
             Xalloc_err("Memory allocation not initialized yet!");
             Xclac();
             return;
         }
         HeapSegment *Segment = (HeapSegment *)Address - 1;
         Segment->IsFree = true;
         Segment->CombineForward(this->LastSegment);
         Segment->CombineBackward(this->LastSegment);
         Xclac();
     }
References Address, Xalloc::AllocatorV1::HeapSegment::CombineBackward(), Xalloc::AllocatorV1::HeapSegment::CombineForward(), HeapStart, Xalloc::AllocatorV1::HeapSegment::IsFree, LastSegment, Xalloc_err, Xclac(), and Xstac().
Referenced by HeapFree(), and Realloc().
Malloc()
void * Xalloc::AllocatorV1::Malloc (Xuint64_t Size)
Allocate a new memory block.
Parameters
Size Size of the block to allocate.
Returns
void* Pointer to the allocated block.
Definition at line 70 of file Xalloc.cpp.
     {
         Xstac();
         if (this->HeapStart == nullptr)
         {
             Xalloc_err("Memory allocation not initialized yet!");
             Xclac();
             return 0;
         }
         if (Size < 0x10)
         {
             // Xalloc_warn("Allocation size is too small, using 0x10 instead!");
             Size = 0x10;
         }
         // #ifdef DEBUG
         //     if (Size < 1024)
         //         debug("Allocating %dB", Size);
         //     else if (TO_KB(Size) < 1024)
         //         debug("Allocating %dKB", TO_KB(Size));
         //     else if (TO_MB(Size) < 1024)
         //         debug("Allocating %dMB", TO_MB(Size));
         //     else if (TO_GB(Size) < 1024)
         //         debug("Allocating %dGB", TO_GB(Size));
         // #endif
         if (Size % 0x10 > 0)
         { // it is not a multiple of 0x10
             Size -= (Size % 0x10);
             Size += 0x10;
         }
         if (Size == 0)
         {
             Xclac();
             return nullptr;
         }
         HeapSegment *CurrentSegment = (HeapSegment *)this->HeapStart;
         while (true)
         {
             if (CurrentSegment->IsFree)
             {
                 if (CurrentSegment->Length > Size)
                 {
                     CurrentSegment->Split(Size, this->LastSegment);
                     CurrentSegment->IsFree = false;
                     Xclac();
                     return (void *)((Xuint64_t)CurrentSegment + sizeof(HeapSegment));
                 }
                 if (CurrentSegment->Length == Size)
                 {
                     CurrentSegment->IsFree = false;
                     Xclac();
                     return (void *)((Xuint64_t)CurrentSegment + sizeof(HeapSegment));
                 }
             }
             if (CurrentSegment->Next == nullptr)
                 break;
             CurrentSegment = CurrentSegment->Next;
         }
         ExpandHeap(Size);
         return this->Malloc(Size);
     }
References ExpandHeap(), HeapStart, Xalloc::AllocatorV1::HeapSegment::IsFree, LastSegment, Xalloc::AllocatorV1::HeapSegment::Length, Xalloc::AllocatorV1::HeapSegment::Next, Xalloc::AllocatorV1::HeapSegment::Split(), Xalloc_err, Xclac(), and Xstac().
Referenced by Calloc(), HeapMalloc(), internal_filefullpath(), internal_filegetchildren(), internal_fileOpen(), and internal_fileOpenWithParent().
Realloc()
void * Xalloc::AllocatorV1::Realloc (void * Address, Xuint64_t Size)
Reallocate a previously allocated block.
Parameters
Address Address of the block to reallocate.
Size New size of the block.
Returns
void* Pointer to the reallocated block.
Definition at line 175 of file Xalloc.cpp.
     {
         Xstac();
         if (this->HeapStart == nullptr)
         {
             Xalloc_err("Memory allocation not initialized yet!");
             Xclac();
             return 0;
         }
         if (!Address && Size == 0)
         {
             this->Free(Address);
             return nullptr;
         }
         else if (!Address)
         {
             return this->Calloc(Size, sizeof(char));
         }
         if (Size < 0x10)
         {
             // Xalloc_warn("Allocation size is too small, using 0x10 instead!");
             Size = 0x10;
         }
         void *newAddress = this->Calloc(Size, sizeof(char));
         Xstac();
         Xmemcpy(newAddress, Address, Size);
         Xclac();
         return newAddress;
     }
References Address, Calloc(), Free(), HeapStart, Xalloc_err, Xclac(), Xmemcpy(), and Xstac().
Referenced by HeapRealloc().
Xclac()
void Xalloc::AllocatorV1::Xclac () inline
Definition at line 113 of file Xalloc.hpp.
         {
             if (this->SMAPUsed)
                 asm volatile("clac" ::
                                  : "cc");
         }
Referenced by AllocatorV1(), Calloc(), Free(), internal_filechildrensize(), internal_fileClose(), internal_filefullpath(), internal_filegetchildren(), internal_fileOpen(), internal_fileOpenWithParent(), internal_fileRead(), internal_filesize(), internal_fileWrite(), Malloc(), Realloc(), and ~AllocatorV1().
Xmemcpy()
static void* Xalloc::AllocatorV1::Xmemcpy (void *__restrict__ Destination, const void *__restrict__ Source, Xuint64_t Length) inline static private
Definition at line 88 of file Xalloc.hpp.
         {
             unsigned char *dst = (unsigned char *)Destination;
             const unsigned char *src = (const unsigned char *)Source;
             for (Xuint64_t i = 0; i < Length; i++)
                 dst[i] = src[i];
             return Destination;
         }
References Length.
Referenced by Realloc().
Xmemset()
static void* Xalloc::AllocatorV1::Xmemset (void *__restrict__ Destination, int Data, Xuint64_t Length) inline static private
Definition at line 97 of file Xalloc.hpp.
         {
             unsigned char *Buffer = (unsigned char *)Destination;
             for (Xuint64_t i = 0; i < Length; i++)
                 Buffer[i] = (unsigned char)Data;
             return Destination;
         }
References Length.
Referenced by Calloc().
Xstac()
void Xalloc::AllocatorV1::Xstac () inline
Definition at line 106 of file Xalloc.hpp.
         {
             if (this->SMAPUsed)
                 asm volatile("stac" ::
                                  : "cc");
         }
Referenced by AllocatorV1(), Calloc(), Free(), internal_filechildrensize(), internal_fileClose(), internal_filefullpath(), internal_filegetchildren(), internal_fileOpen(), internal_fileOpenWithParent(), internal_fileRead(), internal_filesize(), internal_fileWrite(), Malloc(), Realloc(), and ~AllocatorV1().
Field Documentation
HeapEnd
void* Xalloc::AllocatorV1::HeapEnd = nullptr private
Definition at line 81 of file Xalloc.hpp.
Referenced by AllocatorV1(), and ExpandHeap().
HeapStart
void* Xalloc::AllocatorV1::HeapStart = nullptr private
Definition at line 80 of file Xalloc.hpp.
Referenced by AllocatorV1(), Calloc(), Free(), Malloc(), and Realloc().
LastSegment
HeapSegment* Xalloc::AllocatorV1::LastSegment = nullptr private
Definition at line 82 of file Xalloc.hpp.
Referenced by AllocatorV1(), Xalloc::AllocatorV1::HeapSegment::CombineBackward(), Xalloc::AllocatorV1::HeapSegment::CombineForward(), ExpandHeap(), Free(), and Malloc().
SMAPUsed
bool Xalloc::AllocatorV1::SMAPUsed = false private
Definition at line 84 of file Xalloc.hpp.
Referenced by AllocatorV1().
UserMapping
bool Xalloc::AllocatorV1::UserMapping = false private
Definition at line 83 of file Xalloc.hpp.
Referenced by AllocatorV1(), and ExpandHeap().
The documentation for this class was generated from the following files:
kernel/mem/xalloc/Xalloc.hpp
kernel/mem/xalloc/Xalloc.cpp