Fennix Project: kernel/test.cpp File Reference
test.cpp File Reference
#include <test.h>
#include "network/NetworkController.hpp"
#include "cpu/apic.hpp"
#include "cpu/smp.hpp"
#include "../timer.h"
#include "cpu/gdt.h"
#include "kernel.h"
#include <internal_task.h>
#include <string.h>
#include <heap.h>
Functions
void do_libs_test ()
void do_mem_bitmap_print ()
void do_mem_test ()
void do_interrupts_mem_test ()
void do_tasking_test ()
void do_stacktrace_test ()
void do_network_test ()
Function Documentation
do_interrupts_mem_test()
void do_interrupts_mem_test ()
Definition at line 226 of file test.cpp.
 {
 #ifdef UNIT_TESTS
     kmalloc(176);
     kmalloc(511);
     kmalloc(1027);
     kmalloc(1569);
     if (InterruptsEnabled())
         CLI;
     TEST_DBG("Testing memory without interrupts...\n");
     do_mem_test();
     RegisterInterrupt(stub_int_hnd, IRQ10, true);
     for (uint64_t i = 0; i < 256; i++)
         asm("int $0x2a");
     TEST_DBG("\nTesting interrupt handler again but with sti...\n");
     if (!InterruptsEnabled())
         STI;
     for (uint64_t i = 0; i < 256; i++)
         asm("int $0x2a");
     UnregisterInterrupt(IRQ10);
     TEST_DBG("Now testing memory without interrupts...\n");
     do_mem_test();
     do_mem_test();
     do_mem_test();
     do_mem_test();
     do_mem_test();
     do_mem_test();
     TEST_DBG("\n\n\n\n\n========================================================================================\nTEST COMPLETE! HALTING...\n========================================================================================\n");
     CPU_HALT;
 #endif
 }
References CLI, CPU_HALT, do_mem_test(), InterruptsEnabled(), kmalloc, RegisterInterrupt(), STI, TEST_DBG, and UnregisterInterrupt().
do_libs_test()
void do_libs_test ()
Definition at line 14 of file test.cpp.
 {
 #ifdef UNIT_TESTS
     TEST_ASSERT(strcmp("String Compare.", "String Compare.") == 0);
     TEST_ASSERT(strncmp("1 Test?", "1 Test?", 0) == 0);
     TEST_ASSERT(memcmp("No, 2 Tests.", "No, 2 Tests.", 0) == 0);
     char buf[12] = {'H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd', '!'};
     char emptybuf[12];
     memcpy(emptybuf, buf, 12);
     TEST_EQUAL_STRN(emptybuf, buf, 12);
     memset(buf, '\0', 12);
     TEST_EQUAL_STRN("\0\0\0\0\0\0\0\0\0\0\0\0\0", buf, 12);
     memmove(buf, "Hello World!", 12);
     TEST_EQUAL_STRN("Hello World!", buf, 12);
 #endif
 }
References memcmp(), memcpy(), memmove(), memset(), strcmp(), strncmp(), TEST_ASSERT, and TEST_EQUAL_STRN.
Referenced by KernelInit().
do_mem_bitmap_print()
void do_mem_bitmap_print ()
Definition at line 31 of file test.cpp.
 {
 #ifdef UNIT_TESTS
     TEST_DBG("\nPrinting Bitmap:\n");
     uint64_t nl = 1;
     for (uint64_t i = 0; i < KernelAllocator.PageBitmap.Size; i++)
     {
         nl--;
         if (nl <= 0)
         {
             nl = 148;
             TEST_DBG("\n%08d: ", i);
         }
         TEST_DBG("%d", KernelAllocator.PageBitmap[i] ? 1 : 0);
     }
     TEST_DBG("\n");
 #endif
 }
References KernelAllocator, and TEST_DBG.
Referenced by do_mem_test().
do_mem_test()
void do_mem_test ()
Definition at line 74 of file test.cpp.
 {
 #ifdef UNIT_TESTS
     // return;
     void *tmpAlloc1 = kmalloc(176);
     void *tmpAlloc2 = kmalloc(511);
     void *tmpAlloc3 = kmalloc(1027);
     void *tmpAlloc4 = kmalloc(1569);
     TEST_DBG("Kernel Address: Start:%p ---- End:%p [%ldKB/%ldKB]\n", bootparams->kernel.file, bootparams->kernel.file + bootparams->kernel.size, TO_KB(KernelAllocator.GetUsedRAM()), TO_KB(KernelAllocator.GetFreeRAM()));
     for (int repeat = 0; repeat < 16; repeat++)
     {
         TEST_DBG("---------------[TEST %d]---------------\n", repeat);
         TEST_DBG("Single Page Request Test");
         uint64_t ReqAddress1 = (uint64_t)KernelAllocator.RequestPage();
         KernelAllocator.FreePage((void *)ReqAddress1);
         for (uint64_t i = 0; i < MEMTEST_ITERATIONS; i++)
             KernelAllocator.FreePage(KernelAllocator.RequestPage());
         uint64_t ReqAddress2 = (uint64_t)KernelAllocator.RequestPage();
         KernelAllocator.FreePage((void *)ReqAddress2);
         TEST_DBG(" Result:\t\t1-[%#lx]; 2-[%#lx]\n", (void *)ReqAddress1, (void *)ReqAddress2);
         TEST_EQUAL(ReqAddress1, ReqAddress2);
         // Next Test
         TEST_DBG("Multiple Page Request Test");
         uint64_t ReqAddresses1 = (uint64_t)KernelAllocator.RequestPages(10);
         KernelAllocator.FreePages((void *)ReqAddresses1, 10);
         for (uint64_t i = 0; i < MEMTEST_ITERATIONS; i++)
             KernelAllocator.FreePages(KernelAllocator.RequestPages(20), 20);
         uint64_t ReqAddresses2 = (uint64_t)KernelAllocator.RequestPages(10);
         KernelAllocator.FreePages((void *)ReqAddresses2, 10);
         TEST_DBG(" Result:\t\t1-[%#lx]; 2-[%#lx]\n", (void *)ReqAddresses1, (void *)ReqAddresses2);
         TEST_EQUAL(ReqAddresses1, ReqAddresses2);
         // Next Test
         TEST_DBG("Multiple Fixed Malloc Test");
         uint64_t MallocAddress1 = (uint64_t)kmalloc(0x1000);
         kfree((void *)MallocAddress1);
         for (uint64_t i = 0; i < MEMTEST_ITERATIONS; i++)
             kfree(kmalloc(0x10000));
         uint64_t MallocAddress2 = (uint64_t)kmalloc(0x1000);
         kfree((void *)MallocAddress2);
         TEST_DBG(" Result:\t\t1-[%#lx]; 2-[%#lx]\n", (void *)MallocAddress1, (void *)MallocAddress2);
         TEST_EQUAL(MallocAddress1, MallocAddress2);
         // Next Test
         TEST_DBG("Multiple Dynamic Malloc Test");
         uint64_t MallocAddress_1 = (uint64_t)kmalloc(0x1000);
         kfree((void *)MallocAddress_1);
         for (uint64_t i = 0; i < MEMTEST_ITERATIONS; i++)
             kfree(kmalloc(i));
         uint64_t MallocAddress_2 = (uint64_t)kmalloc(0x1000);
         kfree((void *)MallocAddress_2);
         TEST_DBG(" Result:\t1-[%#lx]; 2-[%#lx]\n", (void *)MallocAddress_1, (void *)MallocAddress_2);
         TEST_EQUAL(MallocAddress_1, MallocAddress_2);
         // Next Test
         TEST_DBG("New/Delete Test");
         uint64_t MallocAddress__1 = (uint64_t)kmalloc(0x1000);
         kfree((void *)MallocAddress__1);
         for (uint64_t i = 0; i < MEMTEST_ITERATIONS; i++)
         {
             test_mem_new_delete *t = new test_mem_new_delete();
             delete t;
         }
         uint64_t MallocAddress__2 = (uint64_t)kmalloc(0x1000);
         kfree((void *)MallocAddress__2);
         TEST_DBG(" Result:               \t1-[%#lx]; 2-[%#lx]\n", (void *)MallocAddress__1, (void *)MallocAddress__2);
         TEST_EQUAL(MallocAddress__1, MallocAddress__2);
         // Next Test
         TEST_DBG("New/Delete Fixed Array Test");
         uint64_t MallocAddress___1 = (uint64_t)kmalloc(0x1000);
         kfree((void *)MallocAddress___1);
         for (uint64_t i = 0; i < MEMTEST_ITERATIONS; i++)
         {
             char *t = new char[128];
             delete[] t;
         }
         uint64_t MallocAddress___2 = (uint64_t)kmalloc(0x1000);
         kfree((void *)MallocAddress___2);
         TEST_DBG(" Result:    \t1-[%#lx]; 2-[%#lx]\n", (void *)MallocAddress___1, (void *)MallocAddress___2);
         TEST_EQUAL(MallocAddress___1, MallocAddress___2);
         // Next Test
         TEST_DBG("New/Delete Dynamic Array Test");
         uint64_t MallocAddress____1 = (uint64_t)kmalloc(0x1000);
         kfree((void *)MallocAddress____1);
         for (uint64_t i = 0; i < MEMTEST_ITERATIONS; i++)
         {
             if (i == 0)
                 continue;
             char *t = new char[i];
             delete[] t;
         }
         uint64_t MallocAddress____2 = (uint64_t)kmalloc(0x1000);
         kfree((void *)MallocAddress____2);
         TEST_DBG(" Result:\t1-[%#lx]; 2-[%#lx]\n", (void *)MallocAddress____1, (void *)MallocAddress____2);
         TEST_EQUAL(MallocAddress____1, MallocAddress____2);
     }
     kfree(tmpAlloc1);
     kfree(tmpAlloc2);
     kfree(tmpAlloc3);
     kfree(tmpAlloc4);
     do_mem_bitmap_print();
 #endif
 }
References bootparams, do_mem_bitmap_print(), kernel_file::file, _GlobalBootParams::kernel, KernelAllocator, kfree, kmalloc, kernel_file::size, TEST_DBG, TEST_EQUAL, and TO_KB.
Referenced by do_interrupts_mem_test().
do_network_test()
void do_network_test ()
Definition at line 500 of file test.cpp.
 {
     TEST_DBG("Network test started.\n");
     InternetProtocol4 IP1 = {.Address = {0xFF, 0xFF, 0xFF, 0xFF}};
     InternetProtocol4 IP2 = {.Address = {0xFF, 0xFF, 0xFF, 0xFF}};
     InternetProtocol4 IPN1 = {.Address = {127, 0, 0, 1}};
     InternetProtocol4 IPN2 = {.Address = {192, 168, 0, 1}};
     MediaAccessControl MAC1 = {.Address = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}};
     MediaAccessControl MAC2 = {.Address = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}};
     MediaAccessControl MACN1 = {.Address = {0xF0, 0x2F, 0x6F, 0xF7, 0x1F, 0xFF}};
     MediaAccessControl MACN2 = {.Address = {0xF2, 0xAF, 0x02, 0xF1, 0x1C, 0xFA}};
     MediaAccessControl MACV1 = {.Address = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}};
     MediaAccessControl MACV2 = {.Address = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0}};
     TEST_ASSERT(IP1 == IP2);
     TEST_ASSERT(IPN1 != IPN2);
     TEST_ASSERT(IP1.ToHex() == 0xFFFFFFFF)
     TEST_ASSERT(IP1.FromHex(0xFFFFFFFF) == IP2);
     TEST_ASSERT(MAC1 == MAC2);
     TEST_ASSERT(MACN1 != MACN2);
     TEST_ASSERT(MAC1.ToHex() == 0xFFFFFFFFFFFF);
     TEST_ASSERT(MAC1.FromHex(0xFFFFFFFFFFFF) == MAC2);
     TEST_ASSERT(MACV1.Valid() == false);
     TEST_ASSERT(MACV2.Valid() == false);
     TEST_ASSERT(MACN1.Valid() == true);
     TEST_ASSERT(MACN2.Valid() == true);
     TEST_DBG("Network test finished.\n");
 }
References MediaAccessControl::Address, InternetProtocol4::Address, MediaAccessControl::FromHex(), InternetProtocol4::FromHex(), TEST_ASSERT, TEST_DBG, MediaAccessControl::ToHex(), InternetProtocol4::ToHex(), and MediaAccessControl::Valid().
Referenced by KernelInit().
do_stacktrace_test()
void do_stacktrace_test ()
Definition at line 493 of file test.cpp.
 {
 #ifdef UNIT_TESTS
     backtrace0();
 #endif
 }
Referenced by KernelInit().
do_tasking_test()
void do_tasking_test ()
Definition at line 465 of file test.cpp.
 {
 #ifdef UNIT_TESTS
     // test_safescheduler();
     StartTasking((uint64_t)test_kernelmultitasking, TaskingMode::Multi);
     CPU_STOP;
 #endif
 }
References CPU_STOP, Multi, and StartTasking().