Fennix Project: InterProcessCommunication::IPC Class Reference
InterProcessCommunication::IPC Class Reference
#include <ipc.hpp>
Public Member Functions
IPC ()
~IPC ()
IPCHandle * RegisterHandle (IPCPort Port)
IPCHandle * Wait (IPCPort port)
IPCError Read (int pid, IPCPort port, void *buf, int size)
IPCError Write (int pid, IPCPort port, void *buf, int size)
Private Attributes
PCB * IPCProc
Detailed Description
Definition at line 6 of file ipc.hpp.
Constructor & Destructor Documentation
IPC()
InterProcessCommunication::IPC::IPC ()
Definition at line 53 of file InterProcessCommunication.cpp.
     {
         IPCProc = SysCreateProcess("IPC Service", CBElevation::System);
         SysCreateThread(IPCProc, (uint64_t)IPCServiceStub, 0, 0);
     }
References IPCProc, InterProcessCommunication::IPCServiceStub(), SysCreateProcess(), SysCreateThread(), and System.
~IPC()
InterProcessCommunication::IPC::~IPC ()
Definition at line 59 of file InterProcessCommunication.cpp.
     {
     }
Member Function Documentation
Read()
IPCError InterProcessCommunication::IPC::Read (int pid, IPCPort port, void * buf, int size)
Definition at line 34 of file InterProcessCommunication.cpp.
     {
         return IPCError{IPCUnknown};
     }
References InterProcessCommunication::IPCUnknown.
RegisterHandle()
IPCHandle * InterProcessCommunication::IPC::RegisterHandle (IPCPort Port)
Definition at line 8 of file InterProcessCommunication.cpp.
     {
         if (Port == 0)
             return nullptr;
         PCB *pcb = SysGetCurrentProcess();
         if (pcb->IPCHandles->Get((int)Port) != 0)
             return nullptr;
         IPCHandle *handle = new IPCHandle;
         handle->ID = -1;
         handle->Buffer = nullptr;
         handle->Length = 0;
         handle->Type = IPCOperationNone;
         handle->Listening = 0;
         handle->Error = IPCUnknown;
         pcb->IPCHandles->AddNode(Port, (uint64_t)handle);
         return handle;
     }
References HashMap< K, V >::AddNode(), InterProcessCommunication::IPCHandle::Buffer, InterProcessCommunication::IPCHandle::Error, HashMap< K, V >::Get(), InterProcessCommunication::IPCHandle::ID, PCB::IPCHandles, InterProcessCommunication::IPCOperationNone, InterProcessCommunication::IPCUnknown, InterProcessCommunication::IPCHandle::Length, InterProcessCommunication::IPCHandle::Listening, SysGetCurrentProcess(), and InterProcessCommunication::IPCHandle::Type.
Wait()
IPCHandle * InterProcessCommunication::IPC::Wait (IPCPort port)
Definition at line 29 of file InterProcessCommunication.cpp.
     {
         return nullptr;
     }
Write()
IPCError InterProcessCommunication::IPC::Write (int pid, IPCPort port, void * buf, int size)
Definition at line 39 of file InterProcessCommunication.cpp.
     {
         return IPCError{IPCUnknown};
     }
References InterProcessCommunication::IPCUnknown.
Field Documentation
IPCProc
PCB* InterProcessCommunication::IPC::IPCProc private
Definition at line 9 of file ipc.hpp.
Referenced by IPC().
The documentation for this class was generated from the following files:
kernel/proc/ipc.hpp
kernel/proc/InterProcessCommunication.cpp