Fennix Project: NetworkInterfaceManager::DeviceInterface Struct Reference
NetworkInterfaceManager::DeviceInterface Struct Reference
#include <NetworkController.hpp>
Public Member Functions
virtual void Send (void *Data, uint64_t Length)
virtual void Receive (void *Data)
Data Fields
char Name [128]
uint64_t ID
MediaAccessControl MAC
InternetProtocol IP
Detailed Description
Definition at line 67 of file NetworkController.hpp.
Member Function Documentation
Receive()
virtual void NetworkInterfaceManager::DeviceInterface::Receive (void * Data) inline virtual
Definition at line 79 of file NetworkController.hpp.
         {
             warn("Not implemented.");
         }
References warn.
Referenced by NetworkInterfaceManager::NetworkInterface::Receive().
Send()
virtual void NetworkInterfaceManager::DeviceInterface::Send (void * Data, uint64_t Length) inline virtual
Reimplemented in E1000::NetworkInterfaceController, RTL8139::NetworkInterfaceController, and RTL8169::NetworkInterfaceController.
Definition at line 74 of file NetworkController.hpp.
         {
             warn("Not implemented.");
         }
References warn.
Referenced by NetworkInterfaceManager::NetworkInterface::Send(), and NetworkEthernet::Ethernet::Send().
Field Documentation
ID
uint64_t NetworkInterfaceManager::DeviceInterface::ID
Definition at line 70 of file NetworkController.hpp.
IP
InternetProtocol NetworkInterfaceManager::DeviceInterface::IP
Definition at line 72 of file NetworkController.hpp.
Referenced by NetworkARP::ARP::Receive(), and NetworkARP::ARP::Send().
MAC
MediaAccessControl NetworkInterfaceManager::DeviceInterface::MAC
Definition at line 71 of file NetworkController.hpp.
Referenced by NetworkEthernet::Ethernet::Receive(), NetworkARP::ARP::Receive(), NetworkEthernet::Ethernet::Send(), and NetworkARP::ARP::Send().
Name
char NetworkInterfaceManager::DeviceInterface::Name[128]
Definition at line 69 of file NetworkController.hpp.
The documentation for this struct was generated from the following file:
kernel/network/NetworkController.hpp