Fennix Project: FileSystem::Mount Class Reference
FileSystem::Mount Class Reference
#include <filesystem.h>
Public Member Functions
FileSystemNode * MountFileSystem (FileSystemOpeations *Operator, uint64_t Mode, string Name)
void DetectAndMountFS (void *drive)
Mount ()
~Mount ()
Detailed Description
Definition at line 173 of file filesystem.h.
Constructor & Destructor Documentation
Mount()
FileSystem::Mount::Mount ()
Definition at line 44 of file mountfs.cpp.
     {
         trace("Mounting file systems...");
         MountRootNode = vfs->Create(nullptr, "/system/mnt");
         MountRootNode->Flags = NodeFlags::FS_DIRECTORY;
         MountRootNode->Mode = 0755;
         BS->IncreaseProgres();
     }
References BS, FileSystem::Virtual::Create(), FileSystem::FileSystemNode::Flags, FS_DIRECTORY, BootScreen::Screen::IncreaseProgres(), FileSystem::FileSystemNode::Mode, FileSystem::MountRootNode, trace, and vfs.
~Mount()
FileSystem::Mount::~Mount ()
Definition at line 53 of file mountfs.cpp.
     {
     }
Member Function Documentation
DetectAndMountFS()
void FileSystem::Mount::DetectAndMountFS (void * drive)
Definition at line 33 of file mountfs.cpp.
     {
         foreach (auto partition in((DiskManager::Partition::Drive *)drive)->Partitions)
         {
             debug("Mounting File Systems for Partition %d...", partition->Index);
             new EXT2(partition);
             new FAT(partition);
             /* ... */
         }
     }
References debug, and Partitions.
Referenced by DiskManager::Partition::AddPartition().
MountFileSystem()
FileSystemNode * FileSystem::Mount::MountFileSystem (FileSystemOpeations * Operator, uint64_t Mode, string Name)
Definition at line 13 of file mountfs.cpp.
     {
         if (isempty((char *)Name))
         {
             warn("Tried to mount file system with empty name!");
             sprintf_((char *)Name, "mount%lu", MountNodeIndexNodeCount);
         }
         trace("Adding %s to mounted file systems", Name);
         // FileSystemNode *newNode = vfs->Create(MountRootNode, Name);
         FileSystemNode *newNode = new FileSystemNode;
         strcpy(newNode->Name, Name);
         newNode->IndexNode = MountNodeIndexNodeCount++;
         newNode->Mode = Mode;
         newNode->Operator = Operator;
         newNode->Flags = NodeFlags::FS_MOUNTPOINT;
         MountRootNode->Children.push_back(newNode);
         return newNode;
     }
References FileSystem::FileSystemNode::Children, FileSystem::FileSystemNode::Flags, FS_MOUNTPOINT, FileSystem::FileSystemNode::IndexNode, isempty(), FileSystem::FileSystemNode::Mode, Mode, FileSystem::MountNodeIndexNodeCount, FileSystem::MountRootNode, FileSystem::FileSystemNode::Name, FileSystem::FileSystemNode::Operator, sprintf_(), strcpy(), trace, and warn.
Referenced by FileSystem::EXT2::EXT2(), and FileSystem::FAT::FAT().
The documentation for this class was generated from the following files:
kernel/include/filesystem.h
kernel/filesystem/mountpoints/mountfs.cpp