Fennix Project: InternetProtocol4 Struct Reference
InternetProtocol4 Struct Reference
#include <NetworkController.hpp>
Public Member Functions
bool operator== (const InternetProtocol4 &lhs) const
bool operator== (const uint32_t &lhs) const
bool operator!= (const InternetProtocol4 &lhs) const
bool operator!= (const uint32_t &lhs) const
uint32_t ToHex ()
InternetProtocol4 FromHex (uint32_t Hex)
Data Fields
uint8_t Address [4]
Detailed Description
Definition at line 124 of file NetworkController.hpp.
Member Function Documentation
FromHex()
InternetProtocol4 InternetProtocol4::FromHex (uint32_t Hex) inline
Definition at line 161 of file NetworkController.hpp.
     {
         this->Address[0] = (uint8_t)((Hex >> 24) & 0xFF);
         this->Address[1] = (uint8_t)((Hex >> 16) & 0xFF);
         this->Address[2] = (uint8_t)((Hex >> 8) & 0xFF);
         this->Address[3] = (uint8_t)(Hex & 0xFF);
         return *this;
     }
Referenced by do_network_test(), NetworkARP::ARP::OnEthernetPacketReceived(), NetworkDHCP::DHCP::OnUDPPacketReceived(), and NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
operator!=() [1/2]
bool InternetProtocol4::operator!= (const InternetProtocol4 & lhs) const inline
Definition at line 150 of file NetworkController.hpp.
 { return !(*this == lhs); }
operator!=() [2/2]
bool InternetProtocol4::operator!= (const uint32_t & lhs) const inline
Definition at line 151 of file NetworkController.hpp.
 { return !(*this == lhs); }
operator==() [1/2]
bool InternetProtocol4::operator== (const InternetProtocol4 & lhs) const inline
Definition at line 128 of file NetworkController.hpp.
     {
         return lhs.Address[0] == this->Address[0] &&
                lhs.Address[1] == this->Address[1] &&
                lhs.Address[2] == this->Address[2] &&
                lhs.Address[3] == this->Address[3];
     }
References Address.
operator==() [2/2]
bool InternetProtocol4::operator== (const uint32_t & lhs) const inline
Definition at line 136 of file NetworkController.hpp.
     {
         InternetProtocol4 IP;
         IP.Address[0] = (uint8_t)((lhs >> 24) & 0xFF);
         IP.Address[1] = (uint8_t)((lhs >> 16) & 0xFF);
         IP.Address[2] = (uint8_t)((lhs >> 8) & 0xFF);
         IP.Address[3] = (uint8_t)(lhs & 0xFF);
         return IP.Address[0] == this->Address[0] &&
                IP.Address[1] == this->Address[1] &&
                IP.Address[2] == this->Address[2] &&
                IP.Address[3] == this->Address[3];
     }
References Address.
ToHex()
uint32_t InternetProtocol4::ToHex () inline
Definition at line 153 of file NetworkController.hpp.
     {
         return ((uint64_t)this->Address[0] << 24) |
                ((uint64_t)this->Address[1] << 16) |
                ((uint64_t)this->Address[2] << 8) |
                ((uint64_t)this->Address[3]);
     }
Referenced by NetworkARP::ARP::Broadcast(), do_network_test(), NetworkARP::ARP::OnEthernetPacketReceived(), NetworkIPv4::IPv4::OnEthernetPacketReceived(), NetworkDHCP::DHCP::Request(), NetworkARP::ARP::Resolve(), NetworkIPv4::IPv4::Send(), and NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
Field Documentation
Address
uint8_t InternetProtocol4::Address[4]
Definition at line 126 of file NetworkController.hpp.
Referenced by NetworkUDP::UDP::Connect(), do_network_test(), NetworkARP::ARP::OnEthernetPacketReceived(), NetworkUDP::UDP::OnIPv4PacketReceived(), operator==(), NetworkDHCP::DHCP::Request(), NetworkARP::ARP::Resolve(), NetworkIPv4::IPv4::Send(), NetworkUDP::UDP::Send(), RTL8139::NetworkInterfaceController::SetIP(), and NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
The documentation for this struct was generated from the following file:
kernel/network/NetworkController.hpp