Fennix Project: kernel/syscalls/Linux.cpp File Reference
Linux.cpp File Reference
#include "syscalls.hpp"
#include <internal_task.h>
#include "../../libc/include/syscalls.h"
Functions
static uint64_t internal_unimpl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_read (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_write (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_open (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_close (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_stat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fstat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_lstat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_poll (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_lseek (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mmap (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mprotect (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_munmap (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_brk (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_rt_sigaction (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_rt_sigprocmask (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_rt_sigreturn (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_ioctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_pread64 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_pwrite64 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_readv (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_writev (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_access (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_pipe (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_select (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sched_yield (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mremap (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_msync (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mincore (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_madvise (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_shmget (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_shmat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_shmctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_dup (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_dup2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_pause (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_nanosleep (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getitimer (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_alarm (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setitimer (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getpid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sendfile (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_socket (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_connect (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_accept (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sendto (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_recvfrom (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sendmsg (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_recvmsg (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_shutdown (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_bind (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_listen (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getsockname (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getpeername (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_socketpair (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setsockopt (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getsockopt (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_clone (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fork (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_vfork (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_execve (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_exit (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_wait4 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_kill (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_uname (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_semget (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_semop (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_semctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_shmdt (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_msgget (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_msgsnd (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_msgrcv (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_msgctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fcntl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_flock (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fsync (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fdatasync (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_truncate (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_ftruncate (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getdents (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getcwd (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_chdir (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fchdir (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_rename (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mkdir (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_rmdir (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_creat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_link (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_unlink (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_symlink (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_readlink (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_chmod (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fchmod (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_chown (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fchown (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_lchown (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_umask (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_gettimeofday (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getrlimit (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getrusage (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sysinfo (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_times (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_ptrace (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getuid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_syslog (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getgid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setuid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setgid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_geteuid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getegid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setpgid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getppid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getpgrp (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setsid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setreuid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setregid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getgroups (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setgroups (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setresuid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getresuid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setresgid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getresgid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getpgid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setfsuid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setfsgid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getsid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_capget (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_capset (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_rt_sigpending (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_rt_sigtimedwait (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_rt_sigqueueinfo (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_rt_sigsuspend (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sigaltstack (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_utime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mknod (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_uselib (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_personality (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_ustat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_statfs (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fstatfs (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sysfs (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getpriority (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setpriority (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sched_setparam (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sched_getparam (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sched_setscheduler (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sched_getscheduler (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sched_get_priority_max (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sched_get_priority_min (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sched_rr_get_interval (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mlock (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_munlock (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mlockall (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_munlockall (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_vhangup (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_modify_ldt (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_pivot_root (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys__sysctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_prctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_arch_prctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_adjtimex (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setrlimit (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_chroot (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sync (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_acct (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_settimeofday (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mount (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_umount2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_swapon (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_swapoff (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_reboot (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sethostname (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setdomainname (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_iopl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_ioperm (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_create_module (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_init_module (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_delete_module (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_get_kernel_syms (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_query_module (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_quotactl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_nfsservctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getpmsg (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_putpmsg (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_afs_syscall (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_tuxcall (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_security (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_gettid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_readahead (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_lsetxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fsetxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_lgetxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fgetxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_listxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_llistxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_flistxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_removexattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_lremovexattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fremovexattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_tkill (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_time (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_futex (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sched_setaffinity (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sched_getaffinity (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_set_thread_area (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_io_setup (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_io_destroy (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_io_getevents (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_io_submit (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_io_cancel (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_get_thread_area (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_lookup_dcookie (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_epoll_create (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_epoll_ctl_old (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_epoll_wait_old (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_remap_file_pages (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getdents64 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_set_tid_address (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_restart_syscall (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_semtimedop (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fadvise64 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_timer_create (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_timer_settime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_timer_gettime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_timer_getoverrun (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_timer_delete (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_clock_settime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_clock_gettime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_clock_getres (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_clock_nanosleep (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_exit_group (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_epoll_wait (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_epoll_ctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_tgkill (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_utimes (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_vserver (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mbind (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_set_mempolicy (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_get_mempolicy (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mq_open (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mq_unlink (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mq_timedsend (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mq_timedreceive (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mq_notify (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mq_getsetattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_kexec_load (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_waitid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_add_key (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_request_key (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_keyctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_ioprio_set (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_ioprio_get (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_inotify_init (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_inotify_add_watch (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_inotify_rm_watch (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_migrate_pages (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_openat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mkdirat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_mknodat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fchownat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_futimesat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_newfstatat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_unlinkat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_renameat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_linkat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_symlinkat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_readlinkat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fchmodat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_faccessat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_pselect6 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_ppoll (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_unshare (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_set_robust_list (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_get_robust_list (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_splice (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_tee (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sync_file_range (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_vmsplice (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_move_pages (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_utimensat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_epoll_pwait (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_signalfd (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_timerfd_create (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_eventfd (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fallocate (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_timerfd_settime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_timerfd_gettime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_accept4 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_signalfd4 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_eventfd2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_epoll_create1 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_dup3 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_pipe2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_inotify_init1 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_preadv (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_pwritev (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_rt_tgsigqueueinfo (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_perf_event_open (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_recvmmsg (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fanotify_init (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_fanotify_mark (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_prlimit64 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_name_to_handle_at (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_open_by_handle_at (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_clock_adjtime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_syncfs (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sendmmsg (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_setns (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getcpu (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_process_vm_readv (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_process_vm_writev (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_kcmp (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_finit_module (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sched_setattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_sched_getattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_renameat2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_seccomp (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_getrandom (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_memfd_create (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_kexec_file_load (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t sys_bpf (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t stub_execveat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t userfaultfd (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t membarrier (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t mlock2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t copy_file_range (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t preadv2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t pwritev2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t pkey_mprotect (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t pkey_alloc (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t pkey_free (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t statx (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t io_pgetevents (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t rseq (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t pkey_mprotect_ (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
uint64_t HandleLinuxSyscalls (SyscallsRegs *regs)
Variables
static void * LinuxSyscallsTable []
Function Documentation
copy_file_range()
static uint64_t copy_file_range (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 339 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
HandleLinuxSyscalls()
uint64_t HandleLinuxSyscalls (SyscallsRegs * regs)
Definition at line 691 of file Linux.cpp.
 {
     if (RAX > sizeof(LinuxSyscallsTable))
     {
         return internal_unimpl(regs->rax, regs->rbx, regs->rcx, regs->rdx, regs->rsi, regs->rdi, regs->rbp);
     }
     uint64_t (*call)(uint64_t, ...) = reinterpret_cast<uint64_t (*)(uint64_t, ...)>(LinuxSyscallsTable[RAX]);
     if (!call)
     {
         err("Syscall %#llx failed.", RAX);
         return -1;
     }
     uint64_t ret = call(regs->int_num, 0, 0, 0, 0);
     RAX = ret;
     return ret;
 }
References err, _SyscallsRegs::int_num, internal_unimpl(), LinuxSyscallsTable, _SyscallsRegs::rax, _SyscallsRegs::rbp, _SyscallsRegs::rbx, _SyscallsRegs::rcx, _SyscallsRegs::rdi, _SyscallsRegs::rdx, and _SyscallsRegs::rsi.
Referenced by syscall_handler().
internal_unimpl()
static uint64_t internal_unimpl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 7 of file Linux.cpp.
 {
     fixme("Unimplemented Syscall: %d %d %d %d %d %d %d", a, b, c, d, e, f, g);
     return -1;
 }
References fixme().
Referenced by copy_file_range(), HandleLinuxSyscalls(), io_pgetevents(), membarrier(), mlock2(), pkey_alloc(), pkey_free(), pkey_mprotect(), pkey_mprotect_(), preadv2(), pwritev2(), rseq(), statx(), stub_execveat(), sys__sysctl(), sys_accept(), sys_accept4(), sys_access(), sys_acct(), sys_add_key(), sys_adjtimex(), sys_afs_syscall(), sys_alarm(), sys_arch_prctl(), sys_bind(), sys_bpf(), sys_brk(), sys_capget(), sys_capset(), sys_chdir(), sys_chmod(), sys_chown(), sys_chroot(), sys_clock_adjtime(), sys_clock_getres(), sys_clock_gettime(), sys_clock_nanosleep(), sys_clock_settime(), sys_clone(), sys_close(), sys_connect(), sys_creat(), sys_create_module(), sys_delete_module(), sys_dup(), sys_dup2(), sys_dup3(), sys_epoll_create(), sys_epoll_create1(), sys_epoll_ctl(), sys_epoll_ctl_old(), sys_epoll_pwait(), sys_epoll_wait(), sys_epoll_wait_old(), sys_eventfd(), sys_eventfd2(), sys_execve(), sys_exit(), sys_exit_group(), sys_faccessat(), sys_fadvise64(), sys_fallocate(), sys_fanotify_init(), sys_fanotify_mark(), sys_fchdir(), sys_fchmod(), sys_fchmodat(), sys_fchown(), sys_fchownat(), sys_fcntl(), sys_fdatasync(), sys_fgetxattr(), sys_finit_module(), sys_flistxattr(), sys_flock(), sys_fork(), sys_fremovexattr(), sys_fsetxattr(), sys_fstat(), sys_fstatfs(), sys_fsync(), sys_ftruncate(), sys_futex(), sys_futimesat(), sys_get_kernel_syms(), sys_get_mempolicy(), sys_get_robust_list(), sys_get_thread_area(), sys_getcpu(), sys_getcwd(), sys_getdents(), sys_getdents64(), sys_getegid(), sys_geteuid(), sys_getgid(), sys_getgroups(), sys_getitimer(), sys_getpeername(), sys_getpgid(), sys_getpgrp(), sys_getpid(), sys_getpmsg(), sys_getppid(), sys_getpriority(), sys_getrandom(), sys_getresgid(), sys_getresuid(), sys_getrlimit(), sys_getrusage(), sys_getsid(), sys_getsockname(), sys_getsockopt(), sys_gettid(), sys_gettimeofday(), sys_getuid(), sys_getxattr(), sys_init_module(), sys_inotify_add_watch(), sys_inotify_init(), sys_inotify_init1(), sys_inotify_rm_watch(), sys_io_cancel(), sys_io_destroy(), sys_io_getevents(), sys_io_setup(), sys_io_submit(), sys_ioctl(), sys_ioperm(), sys_iopl(), sys_ioprio_get(), sys_ioprio_set(), sys_kcmp(), sys_kexec_file_load(), sys_kexec_load(), sys_keyctl(), sys_kill(), sys_lchown(), sys_lgetxattr(), sys_link(), sys_linkat(), sys_listen(), sys_listxattr(), sys_llistxattr(), sys_lookup_dcookie(), sys_lremovexattr(), sys_lseek(), sys_lsetxattr(), sys_lstat(), sys_madvise(), sys_mbind(), sys_memfd_create(), sys_migrate_pages(), sys_mincore(), sys_mkdir(), sys_mkdirat(), sys_mknod(), sys_mknodat(), sys_mlock(), sys_mlockall(), sys_mmap(), sys_modify_ldt(), sys_mount(), sys_move_pages(), sys_mprotect(), sys_mq_getsetattr(), sys_mq_notify(), sys_mq_open(), sys_mq_timedreceive(), sys_mq_timedsend(), sys_mq_unlink(), sys_mremap(), sys_msgctl(), sys_msgget(), sys_msgrcv(), sys_msgsnd(), sys_msync(), sys_munlock(), sys_munlockall(), sys_munmap(), sys_name_to_handle_at(), sys_nanosleep(), sys_newfstatat(), sys_nfsservctl(), sys_open(), sys_open_by_handle_at(), sys_openat(), sys_pause(), sys_perf_event_open(), sys_personality(), sys_pipe(), sys_pipe2(), sys_pivot_root(), sys_poll(), sys_ppoll(), sys_prctl(), sys_pread64(), sys_preadv(), sys_prlimit64(), sys_process_vm_readv(), sys_process_vm_writev(), sys_pselect6(), sys_ptrace(), sys_putpmsg(), sys_pwrite64(), sys_pwritev(), sys_query_module(), sys_quotactl(), sys_read(), sys_readahead(), sys_readlink(), sys_readlinkat(), sys_readv(), sys_reboot(), sys_recvfrom(), sys_recvmmsg(), sys_recvmsg(), sys_remap_file_pages(), sys_removexattr(), sys_rename(), sys_renameat(), sys_renameat2(), sys_request_key(), sys_restart_syscall(), sys_rmdir(), sys_rt_sigaction(), sys_rt_sigpending(), sys_rt_sigprocmask(), sys_rt_sigqueueinfo(), sys_rt_sigreturn(), sys_rt_sigsuspend(), sys_rt_sigtimedwait(), sys_rt_tgsigqueueinfo(), sys_sched_get_priority_max(), sys_sched_get_priority_min(), sys_sched_getaffinity(), sys_sched_getattr(), sys_sched_getparam(), sys_sched_getscheduler(), sys_sched_rr_get_interval(), sys_sched_setaffinity(), sys_sched_setattr(), sys_sched_setparam(), sys_sched_setscheduler(), sys_sched_yield(), sys_seccomp(), sys_security(), sys_select(), sys_semctl(), sys_semget(), sys_semop(), sys_semtimedop(), sys_sendfile(), sys_sendmmsg(), sys_sendmsg(), sys_sendto(), sys_set_mempolicy(), sys_set_robust_list(), sys_set_thread_area(), sys_set_tid_address(), sys_setdomainname(), sys_setfsgid(), sys_setfsuid(), sys_setgid(), sys_setgroups(), sys_sethostname(), sys_setitimer(), sys_setns(), sys_setpgid(), sys_setpriority(), sys_setregid(), sys_setresgid(), sys_setresuid(), sys_setreuid(), sys_setrlimit(), sys_setsid(), sys_setsockopt(), sys_settimeofday(), sys_setuid(), sys_setxattr(), sys_shmat(), sys_shmctl(), sys_shmdt(), sys_shmget(), sys_shutdown(), sys_sigaltstack(), sys_signalfd(), sys_signalfd4(), sys_socket(), sys_socketpair(), sys_splice(), sys_stat(), sys_statfs(), sys_swapoff(), sys_swapon(), sys_symlink(), sys_symlinkat(), sys_sync(), sys_sync_file_range(), sys_syncfs(), sys_sysfs(), sys_sysinfo(), sys_syslog(), sys_tee(), sys_tgkill(), sys_time(), sys_timer_create(), sys_timer_delete(), sys_timer_getoverrun(), sys_timer_gettime(), sys_timer_settime(), sys_timerfd_create(), sys_timerfd_gettime(), sys_timerfd_settime(), sys_times(), sys_tkill(), sys_truncate(), sys_tuxcall(), sys_umask(), sys_umount2(), sys_uname(), sys_unlink(), sys_unlinkat(), sys_unshare(), sys_uselib(), sys_ustat(), sys_utime(), sys_utimensat(), sys_utimes(), sys_vfork(), sys_vhangup(), sys_vmsplice(), sys_vserver(), sys_wait4(), sys_waitid(), sys_write(), sys_writev(), and userfaultfd().
io_pgetevents()
static uint64_t io_pgetevents (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 346 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
membarrier()
static uint64_t membarrier (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 337 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
mlock2()
static uint64_t mlock2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 338 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
pkey_alloc()
static uint64_t pkey_alloc (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 343 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
pkey_free()
static uint64_t pkey_free (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 344 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
pkey_mprotect()
static uint64_t pkey_mprotect (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 342 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
pkey_mprotect_()
static uint64_t pkey_mprotect_ (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 348 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
preadv2()
static uint64_t preadv2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 340 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
pwritev2()
static uint64_t pwritev2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 341 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
rseq()
static uint64_t rseq (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 347 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
statx()
static uint64_t statx (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 345 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
stub_execveat()
static uint64_t stub_execveat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 335 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys__sysctl()
static uint64_t sys__sysctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 169 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_accept()
static uint64_t sys_accept (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 56 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_accept4()
static uint64_t sys_accept4 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 301 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_access()
static uint64_t sys_access (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 34 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_acct()
static uint64_t sys_acct (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 176 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_add_key()
static uint64_t sys_add_key (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 261 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_adjtimex()
static uint64_t sys_adjtimex (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 172 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_afs_syscall()
static uint64_t sys_afs_syscall (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 196 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_alarm()
static uint64_t sys_alarm (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 50 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_arch_prctl()
static uint64_t sys_arch_prctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 171 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_bind()
static uint64_t sys_bind (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 62 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_bpf()
static uint64_t sys_bpf (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 334 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_brk()
static uint64_t sys_brk (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 25 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_capget()
static uint64_t sys_capget (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 138 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_capset()
static uint64_t sys_capset (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 139 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_chdir()
static uint64_t sys_chdir (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 93 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_chmod()
static uint64_t sys_chmod (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 103 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_chown()
static uint64_t sys_chown (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 105 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_chroot()
static uint64_t sys_chroot (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 174 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_clock_adjtime()
static uint64_t sys_clock_adjtime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 318 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_clock_getres()
static uint64_t sys_clock_getres (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 242 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_clock_gettime()
static uint64_t sys_clock_gettime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 241 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_clock_nanosleep()
static uint64_t sys_clock_nanosleep (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 243 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_clock_settime()
static uint64_t sys_clock_settime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 240 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_clone()
static uint64_t sys_clone (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 69 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_close()
static uint64_t sys_close (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 16 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_connect()
static uint64_t sys_connect (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 55 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_creat()
static uint64_t sys_creat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 98 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_create_module()
static uint64_t sys_create_module (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 187 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_delete_module()
static uint64_t sys_delete_module (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 189 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_dup()
static uint64_t sys_dup (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 45 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_dup2()
static uint64_t sys_dup2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 46 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_dup3()
static uint64_t sys_dup3 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 305 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_epoll_create()
static uint64_t sys_epoll_create (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 226 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_epoll_create1()
static uint64_t sys_epoll_create1 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 304 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_epoll_ctl()
static uint64_t sys_epoll_ctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 246 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_epoll_ctl_old()
static uint64_t sys_epoll_ctl_old (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 227 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_epoll_pwait()
static uint64_t sys_epoll_pwait (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 294 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_epoll_wait()
static uint64_t sys_epoll_wait (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 245 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_epoll_wait_old()
static uint64_t sys_epoll_wait_old (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 228 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_eventfd()
static uint64_t sys_eventfd (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 297 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_eventfd2()
static uint64_t sys_eventfd2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 303 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_execve()
static uint64_t sys_execve (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 72 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_exit()
static uint64_t sys_exit (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 73 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_exit_group()
static uint64_t sys_exit_group (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 244 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_faccessat()
static uint64_t sys_faccessat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 282 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fadvise64()
static uint64_t sys_fadvise64 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 234 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fallocate()
static uint64_t sys_fallocate (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 298 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fanotify_init()
static uint64_t sys_fanotify_init (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 313 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fanotify_mark()
static uint64_t sys_fanotify_mark (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 314 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fchdir()
static uint64_t sys_fchdir (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 94 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fchmod()
static uint64_t sys_fchmod (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 104 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fchmodat()
static uint64_t sys_fchmodat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 281 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fchown()
static uint64_t sys_fchown (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 106 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fchownat()
static uint64_t sys_fchownat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 273 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fcntl()
static uint64_t sys_fcntl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 85 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fdatasync()
static uint64_t sys_fdatasync (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 88 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fgetxattr()
static uint64_t sys_fgetxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 206 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_finit_module()
static uint64_t sys_finit_module (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 326 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_flistxattr()
static uint64_t sys_flistxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 209 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_flock()
static uint64_t sys_flock (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 86 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fork()
static uint64_t sys_fork (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 70 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fremovexattr()
static uint64_t sys_fremovexattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 212 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fsetxattr()
static uint64_t sys_fsetxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 203 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fstat()
static uint64_t sys_fstat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 18 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fstatfs()
static uint64_t sys_fstatfs (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 151 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_fsync()
static uint64_t sys_fsync (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 87 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_ftruncate()
static uint64_t sys_ftruncate (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 90 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_futex()
static uint64_t sys_futex (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 215 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_futimesat()
static uint64_t sys_futimesat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 274 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_get_kernel_syms()
static uint64_t sys_get_kernel_syms (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 190 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_get_mempolicy()
static uint64_t sys_get_mempolicy (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 252 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_get_robust_list()
static uint64_t sys_get_robust_list (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 287 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_get_thread_area()
static uint64_t sys_get_thread_area (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 224 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getcpu()
static uint64_t sys_getcpu (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 322 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getcwd()
static uint64_t sys_getcwd (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 92 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getdents()
static uint64_t sys_getdents (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 91 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getdents64()
static uint64_t sys_getdents64 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 230 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getegid()
static uint64_t sys_getegid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 121 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_geteuid()
static uint64_t sys_geteuid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 120 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getgid()
static uint64_t sys_getgid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 117 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getgroups()
static uint64_t sys_getgroups (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 128 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getitimer()
static uint64_t sys_getitimer (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 49 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getpeername()
static uint64_t sys_getpeername (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 65 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getpgid()
static uint64_t sys_getpgid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 134 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getpgrp()
static uint64_t sys_getpgrp (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 124 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getpid()
static uint64_t sys_getpid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 52 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getpmsg()
static uint64_t sys_getpmsg (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 194 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getppid()
static uint64_t sys_getppid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 123 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getpriority()
static uint64_t sys_getpriority (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 153 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getrandom()
static uint64_t sys_getrandom (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 331 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getresgid()
static uint64_t sys_getresgid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 133 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getresuid()
static uint64_t sys_getresuid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 131 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getrlimit()
static uint64_t sys_getrlimit (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 110 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getrusage()
static uint64_t sys_getrusage (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 111 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getsid()
static uint64_t sys_getsid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 137 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getsockname()
static uint64_t sys_getsockname (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 64 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getsockopt()
static uint64_t sys_getsockopt (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 68 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_gettid()
static uint64_t sys_gettid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 199 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_gettimeofday()
static uint64_t sys_gettimeofday (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 109 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getuid()
static uint64_t sys_getuid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 115 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_getxattr()
static uint64_t sys_getxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 204 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_init_module()
static uint64_t sys_init_module (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 188 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_inotify_add_watch()
static uint64_t sys_inotify_add_watch (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 267 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_inotify_init()
static uint64_t sys_inotify_init (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 266 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_inotify_init1()
static uint64_t sys_inotify_init1 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 307 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_inotify_rm_watch()
static uint64_t sys_inotify_rm_watch (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 268 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_io_cancel()
static uint64_t sys_io_cancel (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 223 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_io_destroy()
static uint64_t sys_io_destroy (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 220 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_io_getevents()
static uint64_t sys_io_getevents (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 221 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_io_setup()
static uint64_t sys_io_setup (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 219 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_io_submit()
static uint64_t sys_io_submit (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 222 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_ioctl()
static uint64_t sys_ioctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 29 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_ioperm()
static uint64_t sys_ioperm (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 186 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_iopl()
static uint64_t sys_iopl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 185 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_ioprio_get()
static uint64_t sys_ioprio_get (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 265 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_ioprio_set()
static uint64_t sys_ioprio_set (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 264 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_kcmp()
static uint64_t sys_kcmp (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 325 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_kexec_file_load()
static uint64_t sys_kexec_file_load (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 333 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_kexec_load()
static uint64_t sys_kexec_load (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 259 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_keyctl()
static uint64_t sys_keyctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 263 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_kill()
static uint64_t sys_kill (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 75 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_lchown()
static uint64_t sys_lchown (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 107 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_lgetxattr()
static uint64_t sys_lgetxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 205 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_link()
static uint64_t sys_link (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 99 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_linkat()
static uint64_t sys_linkat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 278 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_listen()
static uint64_t sys_listen (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 63 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_listxattr()
static uint64_t sys_listxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 207 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_llistxattr()
static uint64_t sys_llistxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 208 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_lookup_dcookie()
static uint64_t sys_lookup_dcookie (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 225 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_lremovexattr()
static uint64_t sys_lremovexattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 211 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_lseek()
static uint64_t sys_lseek (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 21 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_lsetxattr()
static uint64_t sys_lsetxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 202 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_lstat()
static uint64_t sys_lstat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 19 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_madvise()
static uint64_t sys_madvise (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 41 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mbind()
static uint64_t sys_mbind (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 250 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_memfd_create()
static uint64_t sys_memfd_create (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 332 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_migrate_pages()
static uint64_t sys_migrate_pages (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 269 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mincore()
static uint64_t sys_mincore (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 40 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mkdir()
static uint64_t sys_mkdir (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 96 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mkdirat()
static uint64_t sys_mkdirat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 271 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mknod()
static uint64_t sys_mknod (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 146 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mknodat()
static uint64_t sys_mknodat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 272 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mlock()
static uint64_t sys_mlock (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 162 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mlockall()
static uint64_t sys_mlockall (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 164 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mmap()
static uint64_t sys_mmap (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 22 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_modify_ldt()
static uint64_t sys_modify_ldt (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 167 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mount()
static uint64_t sys_mount (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 178 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_move_pages()
static uint64_t sys_move_pages (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 292 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mprotect()
static uint64_t sys_mprotect (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 23 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mq_getsetattr()
static uint64_t sys_mq_getsetattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 258 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mq_notify()
static uint64_t sys_mq_notify (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 257 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mq_open()
static uint64_t sys_mq_open (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 253 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mq_timedreceive()
static uint64_t sys_mq_timedreceive (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 256 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mq_timedsend()
static uint64_t sys_mq_timedsend (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 255 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mq_unlink()
static uint64_t sys_mq_unlink (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 254 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_mremap()
static uint64_t sys_mremap (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 38 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_msgctl()
static uint64_t sys_msgctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 84 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_msgget()
static uint64_t sys_msgget (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 81 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_msgrcv()
static uint64_t sys_msgrcv (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 83 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_msgsnd()
static uint64_t sys_msgsnd (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 82 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_msync()
static uint64_t sys_msync (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 39 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_munlock()
static uint64_t sys_munlock (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 163 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_munlockall()
static uint64_t sys_munlockall (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 165 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_munmap()
static uint64_t sys_munmap (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 24 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_name_to_handle_at()
static uint64_t sys_name_to_handle_at (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 316 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_nanosleep()
static uint64_t sys_nanosleep (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 48 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_newfstatat()
static uint64_t sys_newfstatat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 275 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_nfsservctl()
static uint64_t sys_nfsservctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 193 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_open()
static uint64_t sys_open (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 15 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_open_by_handle_at()
static uint64_t sys_open_by_handle_at (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 317 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_openat()
static uint64_t sys_openat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 270 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_pause()
static uint64_t sys_pause (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 47 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_perf_event_open()
static uint64_t sys_perf_event_open (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 311 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_personality()
static uint64_t sys_personality (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 148 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_pipe()
static uint64_t sys_pipe (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 35 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_pipe2()
static uint64_t sys_pipe2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 306 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_pivot_root()
static uint64_t sys_pivot_root (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 168 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_poll()
static uint64_t sys_poll (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 20 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_ppoll()
static uint64_t sys_ppoll (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 284 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_prctl()
static uint64_t sys_prctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 170 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_pread64()
static uint64_t sys_pread64 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 30 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_preadv()
static uint64_t sys_preadv (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 308 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_prlimit64()
static uint64_t sys_prlimit64 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 315 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_process_vm_readv()
static uint64_t sys_process_vm_readv (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 323 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_process_vm_writev()
static uint64_t sys_process_vm_writev (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 324 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_pselect6()
static uint64_t sys_pselect6 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 283 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_ptrace()
static uint64_t sys_ptrace (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 114 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_putpmsg()
static uint64_t sys_putpmsg (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 195 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_pwrite64()
static uint64_t sys_pwrite64 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 31 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_pwritev()
static uint64_t sys_pwritev (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 309 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_query_module()
static uint64_t sys_query_module (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 191 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_quotactl()
static uint64_t sys_quotactl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 192 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_read()
static uint64_t sys_read (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 13 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_readahead()
static uint64_t sys_readahead (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 200 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_readlink()
static uint64_t sys_readlink (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 102 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_readlinkat()
static uint64_t sys_readlinkat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 280 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_readv()
static uint64_t sys_readv (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 32 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_reboot()
static uint64_t sys_reboot (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 182 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_recvfrom()
static uint64_t sys_recvfrom (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 58 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_recvmmsg()
static uint64_t sys_recvmmsg (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 312 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_recvmsg()
static uint64_t sys_recvmsg (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 60 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_remap_file_pages()
static uint64_t sys_remap_file_pages (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 229 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_removexattr()
static uint64_t sys_removexattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 210 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_rename()
static uint64_t sys_rename (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 95 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_renameat()
static uint64_t sys_renameat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 277 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_renameat2()
static uint64_t sys_renameat2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 329 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_request_key()
static uint64_t sys_request_key (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 262 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_restart_syscall()
static uint64_t sys_restart_syscall (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 232 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_rmdir()
static uint64_t sys_rmdir (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 97 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_rt_sigaction()
static uint64_t sys_rt_sigaction (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 26 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_rt_sigpending()
static uint64_t sys_rt_sigpending (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 140 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_rt_sigprocmask()
static uint64_t sys_rt_sigprocmask (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 27 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_rt_sigqueueinfo()
static uint64_t sys_rt_sigqueueinfo (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 142 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_rt_sigreturn()
static uint64_t sys_rt_sigreturn (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 28 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_rt_sigsuspend()
static uint64_t sys_rt_sigsuspend (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 143 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_rt_sigtimedwait()
static uint64_t sys_rt_sigtimedwait (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 141 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_rt_tgsigqueueinfo()
static uint64_t sys_rt_tgsigqueueinfo (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 310 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sched_get_priority_max()
static uint64_t sys_sched_get_priority_max (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 159 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sched_get_priority_min()
static uint64_t sys_sched_get_priority_min (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 160 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sched_getaffinity()
static uint64_t sys_sched_getaffinity (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 217 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sched_getattr()
static uint64_t sys_sched_getattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 328 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sched_getparam()
static uint64_t sys_sched_getparam (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 156 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sched_getscheduler()
static uint64_t sys_sched_getscheduler (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 158 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sched_rr_get_interval()
static uint64_t sys_sched_rr_get_interval (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 161 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sched_setaffinity()
static uint64_t sys_sched_setaffinity (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 216 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sched_setattr()
static uint64_t sys_sched_setattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 327 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sched_setparam()
static uint64_t sys_sched_setparam (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 155 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sched_setscheduler()
static uint64_t sys_sched_setscheduler (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 157 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sched_yield()
static uint64_t sys_sched_yield (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 37 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_seccomp()
static uint64_t sys_seccomp (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 330 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_security()
static uint64_t sys_security (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 198 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_select()
static uint64_t sys_select (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 36 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_semctl()
static uint64_t sys_semctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 79 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_semget()
static uint64_t sys_semget (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 77 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_semop()
static uint64_t sys_semop (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 78 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_semtimedop()
static uint64_t sys_semtimedop (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 233 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sendfile()
static uint64_t sys_sendfile (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 53 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sendmmsg()
static uint64_t sys_sendmmsg (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 320 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sendmsg()
static uint64_t sys_sendmsg (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 59 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sendto()
static uint64_t sys_sendto (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 57 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_set_mempolicy()
static uint64_t sys_set_mempolicy (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 251 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_set_robust_list()
static uint64_t sys_set_robust_list (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 286 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_set_thread_area()
static uint64_t sys_set_thread_area (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 218 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_set_tid_address()
static uint64_t sys_set_tid_address (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 231 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setdomainname()
static uint64_t sys_setdomainname (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 184 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setfsgid()
static uint64_t sys_setfsgid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 136 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setfsuid()
static uint64_t sys_setfsuid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 135 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setgid()
static uint64_t sys_setgid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 119 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setgroups()
static uint64_t sys_setgroups (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 129 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sethostname()
static uint64_t sys_sethostname (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 183 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setitimer()
static uint64_t sys_setitimer (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 51 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setns()
static uint64_t sys_setns (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 321 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setpgid()
static uint64_t sys_setpgid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 122 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setpriority()
static uint64_t sys_setpriority (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 154 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setregid()
static uint64_t sys_setregid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 127 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setresgid()
static uint64_t sys_setresgid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 132 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setresuid()
static uint64_t sys_setresuid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 130 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setreuid()
static uint64_t sys_setreuid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 126 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setrlimit()
static uint64_t sys_setrlimit (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 173 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setsid()
static uint64_t sys_setsid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 125 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setsockopt()
static uint64_t sys_setsockopt (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 67 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_settimeofday()
static uint64_t sys_settimeofday (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 177 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setuid()
static uint64_t sys_setuid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 118 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_setxattr()
static uint64_t sys_setxattr (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 201 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_shmat()
static uint64_t sys_shmat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 43 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_shmctl()
static uint64_t sys_shmctl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 44 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_shmdt()
static uint64_t sys_shmdt (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 80 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_shmget()
static uint64_t sys_shmget (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 42 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_shutdown()
static uint64_t sys_shutdown (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 61 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sigaltstack()
static uint64_t sys_sigaltstack (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 144 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_signalfd()
static uint64_t sys_signalfd (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 295 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_signalfd4()
static uint64_t sys_signalfd4 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 302 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_socket()
static uint64_t sys_socket (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 54 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_socketpair()
static uint64_t sys_socketpair (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 66 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_splice()
static uint64_t sys_splice (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 288 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_stat()
static uint64_t sys_stat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 17 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_statfs()
static uint64_t sys_statfs (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 150 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_swapoff()
static uint64_t sys_swapoff (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 181 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_swapon()
static uint64_t sys_swapon (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 180 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_symlink()
static uint64_t sys_symlink (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 101 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_symlinkat()
static uint64_t sys_symlinkat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 279 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sync()
static uint64_t sys_sync (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 175 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sync_file_range()
static uint64_t sys_sync_file_range (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 290 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_syncfs()
static uint64_t sys_syncfs (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 319 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sysfs()
static uint64_t sys_sysfs (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 152 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_sysinfo()
static uint64_t sys_sysinfo (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 112 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_syslog()
static uint64_t sys_syslog (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 116 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_tee()
static uint64_t sys_tee (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 289 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_tgkill()
static uint64_t sys_tgkill (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 247 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_time()
static uint64_t sys_time (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 214 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_timer_create()
static uint64_t sys_timer_create (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 235 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_timer_delete()
static uint64_t sys_timer_delete (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 239 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_timer_getoverrun()
static uint64_t sys_timer_getoverrun (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 238 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_timer_gettime()
static uint64_t sys_timer_gettime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 237 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_timer_settime()
static uint64_t sys_timer_settime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 236 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_timerfd_create()
static uint64_t sys_timerfd_create (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 296 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_timerfd_gettime()
static uint64_t sys_timerfd_gettime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 300 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_timerfd_settime()
static uint64_t sys_timerfd_settime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 299 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_times()
static uint64_t sys_times (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 113 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_tkill()
static uint64_t sys_tkill (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 213 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_truncate()
static uint64_t sys_truncate (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 89 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_tuxcall()
static uint64_t sys_tuxcall (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 197 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_umask()
static uint64_t sys_umask (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 108 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_umount2()
static uint64_t sys_umount2 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 179 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_uname()
static uint64_t sys_uname (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 76 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_unlink()
static uint64_t sys_unlink (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 100 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_unlinkat()
static uint64_t sys_unlinkat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 276 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_unshare()
static uint64_t sys_unshare (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 285 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_uselib()
static uint64_t sys_uselib (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 147 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_ustat()
static uint64_t sys_ustat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 149 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_utime()
static uint64_t sys_utime (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 145 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_utimensat()
static uint64_t sys_utimensat (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 293 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_utimes()
static uint64_t sys_utimes (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 248 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_vfork()
static uint64_t sys_vfork (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 71 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_vhangup()
static uint64_t sys_vhangup (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 166 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_vmsplice()
static uint64_t sys_vmsplice (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 291 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_vserver()
static uint64_t sys_vserver (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 249 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_wait4()
static uint64_t sys_wait4 (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 74 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_waitid()
static uint64_t sys_waitid (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 260 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_write()
static uint64_t sys_write (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 14 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
sys_writev()
static uint64_t sys_writev (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 33 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
userfaultfd()
static uint64_t userfaultfd (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 336 of file Linux.cpp.
 { return internal_unimpl(a, b, c, d, e, f, g); }
References internal_unimpl().
Variable Documentation
LinuxSyscallsTable
void* LinuxSyscallsTable[] static
Definition at line 352 of file Linux.cpp.
Referenced by HandleLinuxSyscalls().