Fennix Project: libc/libgcc/allocator.cpp File Reference
allocator.cpp File Reference
Functions
void * malloc (unsigned long s)
void free (void *p)
The standard function.
void * memset (void *dest, int data, unsigned long nbytes)
void * operator new (unsigned long Size)
void * operator new[] (unsigned long Size)
void operator delete (void *Pointer)
void operator delete[] (void *Pointer)
void operator delete (void *Pointer, long unsigned int n)
void operator delete[] (void *Pointer, long unsigned int n)
Function Documentation
free()
void free (void * p)
The standard function.
Definition at line 99 of file defaultalloc.cpp.
 {
     if (HeapStart == nullptr)
     {
         err("Memory allocation not initialized yet!");
         return;
     }
     HeapSegHdr *Segment = (HeapSegHdr *)Address - 1;
     Segment->IsFree = true;
     Segment->CombineForward();
     Segment->CombineBackward();
 }
Referenced by operator delete(), and operator delete[]().
malloc()
void* malloc (unsigned long s)
Referenced by operator new(), and operator new[]().
memset()
void* memset (void * dest, int data, unsigned long nbytes)
Definition at line 10 of file mem.c.
 {
     unsigned char *buf = (unsigned char *)dest;
     for (unsigned long i = 0; i < nbytes; i++)
         buf[i] = (unsigned char)data;
     return dest;
 }
Referenced by operator new(), and operator new[]().
operator delete() [1/2]
void operator delete (void * Pointer)
Definition at line 31 of file allocator.cpp.
 {
     free(Pointer);
 }
References free().
operator delete() [2/2]
void operator delete (void * Pointer, long unsigned int n)
Definition at line 41 of file allocator.cpp.
 {
     free(Pointer);
 }
References free().
operator delete[]() [1/2]
void operator delete[] (void * Pointer)
Definition at line 36 of file allocator.cpp.
 {
     free(Pointer);
 }
References free().
operator delete[]() [2/2]
void operator delete[] (void * Pointer, long unsigned int n)
Definition at line 46 of file allocator.cpp.
 {
     free(Pointer);
 }
References free().
operator new()
void* operator new (unsigned long Size)
Definition at line 5 of file allocator.cpp.
 {
     if (Size == 0)
         Size = 1;
     if (void *Pointer = malloc(Size))
     {
         memset(Pointer, 0, Size);
         return Pointer;
     }
     // warn("new( %llx ) failed!", Size);
     throw;
 }
References malloc(), and memset().
operator new[]()
void* operator new[] (unsigned long Size)
Definition at line 18 of file allocator.cpp.
 {
     if (Size == 0)
         Size = 1;
     if (void *Pointer = malloc(Size))
     {
         memset(Pointer, 0, Size);
         return Pointer;
     }
     // warn("new[]( %llx ) failed!", Size);
     throw;
 }
References malloc(), and memset().