Fennix Project: DiskManager::Partition Class Reference
DiskManager::Partition Class Reference
#include <disk.h>
Data Structures
class Drive
struct GUIDPartitionTable
struct GUIDPartitionTablePartition
struct MasterBootRecord
struct MasterBootRecordPartition
struct Part
struct PartitionTable
Public Member Functions
void AddPartition (AHCI::Port *Port)
Partition ()
~Partition ()
Private Types
enum PartitionStyle { Unknown, MBR, GPT }
enum PartitionFlags { Present, Bootable, EFISystemPartition }
Private Member Functions
struct DiskManager::Partition::MasterBootRecordPartition __attribute__ ((packed))
struct DiskManager::Partition::MasterBootRecord __attribute__ ((packed))
struct DiskManager::Partition::GUIDPartitionTablePartition __attribute__ ((packed))
struct DiskManager::Partition::GUIDPartitionTable __attribute__ ((packed))
Private Attributes
struct DiskManager::Partition::PartitionTable __attribute__
Detailed Description
Definition at line 19 of file disk.h.
Data Structure Documentation
DiskManager::Partition::Drive
class DiskManager::Partition::Drive
Definition at line 100 of file disk.h.
Data Fields
uint8_t * Buffer
bool MechanicalDisk
char Name[64]
Vector< Part * > Partitions
PartitionStyle Style
PartitionTable Table
uint64_t UniqueIdentifier
DiskManager::Partition::GUIDPartitionTable
struct DiskManager::Partition::GUIDPartitionTable
Definition at line 72 of file disk.h.
Data Fields
uint64_t ALTLBA
uint32_t EntrySize
uint64_t FirstBlock
uint64_t GUIDHigh
uint64_t GUIDLow
uint32_t HdrCRC32
uint32_t HdrSize
uint64_t LastBlock
uint64_t LBA
uint32_t PartCount
uint32_t PartCRC32
uint64_t PartLBA
uint32_t Reserved
uint32_t Revision
uint64_t Signature
DiskManager::Partition::GUIDPartitionTablePartition
struct DiskManager::Partition::GUIDPartitionTablePartition
Definition at line 60 of file disk.h.
Data Fields
uint64_t Attributes
uint64_t EndLBA
uint64_t GUIDHigh
uint64_t GUIDLow
char Label[72]
uint64_t StartLBA
uint64_t TypeHigh
uint64_t TypeLow
DiskManager::Partition::MasterBootRecord
struct DiskManager::Partition::MasterBootRecord
Definition at line 51 of file disk.h.
Data Fields
uint8_t Bootstrap[440]
MasterBootRecordPartition Partitions[4]
uint16_t Reserved
uint8_t Signature[2]
uint32_t UniqueID
DiskManager::Partition::MasterBootRecordPartition
struct DiskManager::Partition::MasterBootRecordPartition
Definition at line 41 of file disk.h.
Data Fields
uint8_t CHSFirst[3]
uint8_t CHSLast[3]
uint8_t Flags
uint32_t LBAFirst
uint32_t Sectors
uint8_t Type
DiskManager::Partition::PartitionTable
struct DiskManager::Partition::PartitionTable
Definition at line 91 of file disk.h.
Data Fields
GUIDPartitionTable GPT
MasterBootRecord MBR
Member Enumeration Documentation
PartitionFlags
enum DiskManager::Partition::PartitionFlags private
Enumerator
Present
Bootable
EFISystemPartition
Definition at line 34 of file disk.h.
         {
             Present,
             Bootable,
             EFISystemPartition
         };
PartitionStyle
enum DiskManager::Partition::PartitionStyle private
Enumerator
Unknown
MBR
GPT
Definition at line 27 of file disk.h.
         {
             Unknown,
             MBR,
             GPT
         };
Constructor & Destructor Documentation
Partition()
DiskManager::Partition::Partition ()
Definition at line 184 of file disk.cpp.
     {
         trace("Mounting partitions...");
         for (auto var : ahci)
         {
             for (size_t i = 0; i < var->PortCount; i++)
                 AddPartition(var->Ports[i]);
         }
         BS->IncreaseProgres();
     }
References AddPartition(), ahci, BS, BootScreen::Screen::IncreaseProgres(), and trace.
~Partition()
DiskManager::Partition::~Partition ()
Definition at line 195 of file disk.cpp.
     {
         warn("Tried to uninitialize Partition driver!");
     }
References warn.
Member Function Documentation
__attribute__() [1/4]
struct DiskManager::Partition::MasterBootRecordPartition DiskManager::Partition::__attribute__ ((packed)) private
__attribute__() [2/4]
struct DiskManager::Partition::MasterBootRecord DiskManager::Partition::__attribute__ ((packed)) private
__attribute__() [3/4]
struct DiskManager::Partition::GUIDPartitionTable DiskManager::Partition::__attribute__ ((packed)) private
__attribute__() [4/4]
struct DiskManager::Partition::GUIDPartitionTablePartition DiskManager::Partition::__attribute__ ((packed)) private
AddPartition()
void DiskManager::Partition::AddPartition (AHCI::Port * Port)
Definition at line 56 of file disk.cpp.
     {
         if (Port == nullptr)
         {
             err("Port is null!");
             return;
         }
         Drive *drive = new Drive;
         drives.push_back(drive);
         sprintf_(drive->Name, "sd%ld", sizeof(drive->Name));
         // TODO: Implement disk type detection. Very useful in the future.
         drive->MechanicalDisk = true;
         Port->ReadWrite(0, 2, drive->Buffer, false);
         memcpy(&drive->Table, drive->Buffer, sizeof(PartitionTable));
         devfs->AddFileSystem(&sata_disk, 0666, drive->Name, FileSystem::NodeFlags::FS_BLOCKDEVICE);
         if (drive->Table.GPT.Signature == GPT_MAGIC)
         {
             drive->Style = GPT;
             uint32_t Entries = 512 / drive->Table.GPT.EntrySize;
             uint32_t Sectors = drive->Table.GPT.PartCount / Entries;
             for (uint32_t Block = 0; Block < Sectors; Block++)
             {
                 Port->ReadWrite(2 + Block, 1, drive->Buffer, false);
                 for (uint32_t e = 0; e < Entries; e++)
                 {
                     GUIDPartitionTablePartition GPTPartition = reinterpret_cast<GUIDPartitionTablePartition *>(drive->Buffer)[e];
                     if (GPTPartition.TypeLow || GPTPartition.TypeHigh)
                     {
                         Part *partition = new Part;
                         memcpy(partition->Label, GPTPartition.Label, sizeof(partition->Label));
                         partition->StartLBA = GPTPartition.StartLBA;
                         partition->EndLBA = GPTPartition.EndLBA;
                         partition->Sectors = partition->EndLBA - partition->StartLBA;
                         partition->Parent = drive;
                         partition->Port = Port;
                         partition->Flags = Present;
                         partition->Style = GPT;
                         if (GPTPartition.Attributes & 1)
                             partition->Flags |= EFISystemPartition;
                         partition->Index = drive->Partitions.size();
                         // why there is \0 between every char?????
                         char PartName[72];
                         memcpy(PartName, GPTPartition.Label, 72);
                         for (uint32_t i = 0; i < 72; i++)
                             if (PartName[i] == '\0')
                                 PartName[i] = ' ';
                         PartName[71] = '\0';
                         trace("GPT partition \"%s\" found with %lld sectors", PartName, partition->Sectors);
                         drive->Partitions.push_back(partition);
                         char *PartitionName = new char[64];
                         sprintf_(PartitionName, "sd%ldp%ld", drives.size() - 1, partition->Index);
                         devfs->AddFileSystem(&sata_disk, 0666, PartitionName, FileSystem::NodeFlags::FS_BLOCKDEVICE);
                         delete[] PartitionName;
                     }
                 }
             }
             trace("%d GPT partitions found.", drive->Partitions.size());
         }
         else if (drive->Table.MBR.Signature[0] == MBR_MAGIC0 && drive->Table.MBR.Signature[1] == MBR_MAGIC1)
         {
             drive->Style = MBR;
             for (size_t p = 0; p < 4; p++)
                 if (drive->Table.MBR.Partitions[p].LBAFirst != 0)
                 {
                     Part *partition = new Part;
                     partition->StartLBA = drive->Table.MBR.Partitions[p].LBAFirst;
                     partition->EndLBA = drive->Table.MBR.Partitions[p].LBAFirst + drive->Table.MBR.Partitions[p].Sectors;
                     partition->Sectors = drive->Table.MBR.Partitions[p].Sectors;
                     partition->Port = Port;
                     partition->Flags = Present;
                     partition->Style = MBR;
                     partition->Parent = drive;
                     partition->Index = drive->Partitions.size();
                     trace("Partition \"%#llx\" found with %lld sectors.", drive->Table.MBR.UniqueID, partition->Sectors);
                     drive->Partitions.push_back(partition);
                     char *PartitionName = new char[64];
                     sprintf_(PartitionName, "sd%ldp%ld", drives.size() - 1, partition->Index);
                     devfs->AddFileSystem(&sata_disk, 0666, PartitionName, FileSystem::NodeFlags::FS_BLOCKDEVICE);
                     delete[] PartitionName;
                 }
             trace("%d MBR partitions found.", drive->Partitions.size());
         }
         else
             warn("No partition table found on port %d!", Port->PortNumber);
         mountfs->DetectAndMountFS(drive);
     }
References FileSystem::Device::AddFileSystem(), DiskManager::Partition::GUIDPartitionTablePartition::Attributes, DiskManager::Partition::Drive::Buffer, FileSystem::Mount::DetectAndMountFS(), devfs, DiskManager::drives, EFISystemPartition, DiskManager::Partition::GUIDPartitionTablePartition::EndLBA, DiskManager::Partition::Part::EndLBA, Entries, DiskManager::Partition::GUIDPartitionTable::EntrySize, err, DiskManager::Partition::Part::Flags, FS_BLOCKDEVICE, GPT, DiskManager::Partition::PartitionTable::GPT, GPT_MAGIC, DiskManager::Partition::Part::Index, DiskManager::Partition::GUIDPartitionTablePartition::Label, DiskManager::Partition::Part::Label, DiskManager::Partition::MasterBootRecordPartition::LBAFirst, MBR, DiskManager::Partition::PartitionTable::MBR, MBR_MAGIC0, MBR_MAGIC1, DiskManager::Partition::Drive::MechanicalDisk, memcpy(), mountfs, DiskManager::Partition::Drive::Name, DiskManager::Partition::Part::Parent, DiskManager::Partition::GUIDPartitionTable::PartCount, DiskManager::Partition::MasterBootRecord::Partitions, DiskManager::Partition::Drive::Partitions, DiskManager::Partition::Part::Port, Present, DiskManager::sata_disk, Sectors, DiskManager::Partition::MasterBootRecordPartition::Sectors, DiskManager::Partition::Part::Sectors, DiskManager::Partition::MasterBootRecord::Signature, DiskManager::Partition::GUIDPartitionTable::Signature, sprintf_(), DiskManager::Partition::GUIDPartitionTablePartition::StartLBA, DiskManager::Partition::Part::StartLBA, DiskManager::Partition::Drive::Style, DiskManager::Partition::Part::Style, DiskManager::Partition::Drive::Table, trace, DiskManager::Partition::GUIDPartitionTablePartition::TypeHigh, DiskManager::Partition::GUIDPartitionTablePartition::TypeLow, DiskManager::Partition::MasterBootRecord::UniqueID, and warn.
Referenced by Partition().
Field Documentation
__attribute__
struct DiskManager::Partition::PartitionTable DiskManager::Partition::__attribute__ private
The documentation for this class was generated from the following files:
kernel/drivers/disk.h
kernel/drivers/disk.cpp