Fennix Project: kernel/include/debug.h File Reference
debug.h File Reference
Macros
#define fixme(m, ...) (void)(m)
#define stub ;
#define trace(m, ...) (void)(m)
#define warn(m, ...) debug_printf(warn,__FILE__, __LINE__, __FUNCTION__, m, ##__VA_ARGS__)
#define err(m, ...) debug_printf(err,__FILE__, __LINE__, __FUNCTION__, m, ##__VA_ARGS__)
#define debug(m, ...) (void)(m)
#define ubsan(m, ...) (void)(m)
#define TRACEREGS(r) (void)(r)
Enumerations
enum debug_type {
_default_val, _fixme, _stub, _trace,
_warn, _err, _debug, _checkpoint,
_ubsan
}
Functions
void dbg_showregs (void *regs, const char *file, int line, const char *function)
int debug_printf (enum debug_type type, const char *file, int line, const char *function, const char *message,...)
Macro Definition Documentation
debug
#define debug (m, ...) (void)(m)
Definition at line 69 of file debug.h.
err
#define err (m, ...) debug_printf(err,__FILE__, __LINE__, __FUNCTION__, m, ##__VA_ARGS__)
Definition at line 68 of file debug.h.
fixme
#define fixme (m, ...) (void)(m)
Definition at line 64 of file debug.h.
stub
#define stub ;
Definition at line 65 of file debug.h.
trace
#define trace (m, ...) (void)(m)
Definition at line 66 of file debug.h.
TRACEREGS
#define TRACEREGS (r) (void)(r)
Definition at line 71 of file debug.h.
ubsan
#define ubsan (m, ...) (void)(m)
Definition at line 70 of file debug.h.
warn
#define warn (m, ...) debug_printf(warn,__FILE__, __LINE__, __FUNCTION__, m, ##__VA_ARGS__)
Definition at line 67 of file debug.h.
Enumeration Type Documentation
debug_type
enum debug_type
Enumerator
_default_val
_fixme
_stub
_trace
_warn
_err
_debug
_checkpoint
_ubsan
Definition at line 8 of file debug.h.
     {
         _default_val,
         _fixme,
         _stub,
         _trace,
         _warn,
         _err,
         _debug,
         _checkpoint,
         _ubsan
     };
Function Documentation
dbg_showregs()
void dbg_showregs (void * regs, const char * file, int line, const char * function)
Definition at line 12 of file Debug.c.
 {
     TrapFrame *regs = r;
     CR0 cr0 = readcr0();
     CR2 cr2 = readcr2();
     CR3 cr3 = readcr3();
     CR4 cr4 = readcr4();
     CR8 cr8 = readcr8();
     RFLAGS rflags = FLAGS;
     err("\tFS=%#lx  GS=%#lx  SS=%#lx  CS=%#lx", rdmsr(MSR_FS_BASE), rdmsr(MSR_GS_BASE), _SS, CS);
     err("\tR8=%#lx  R9=%#lx  R10=%#lx  R11=%#lx", R8, R9, R10, R11);
     err("\tR12=%#lx  R13=%#lx  R14=%#lx  R15=%#lx", R12, R13, R14, R15);
     err("\tRAX=%#lx  RBX=%#lx  RCX=%#lx  RDX=%#lx", RAX, RBX, RCX, RDX);
     err("\tRSI=%#lx  RDI=%#lx  RBP=%#lx  RSP=%#lx", RSI, RDI, RBP, RSP);
     err("\tRIP=%#lx  RFL=%#lx  INT=%#lx  ERR=%#lx", RIP, FLAGS.raw, INT_NUM, ERROR_CODE);
     err("\tCR0=%#lx  CR2=%#lx  CR3=%#lx  CR4=%#lx  CR8=%#lx", cr0.raw, cr2.raw, cr3.raw, cr4.raw, cr8.raw);
     err("\nCR0: PE:%s     MP:%s     EM:%s     TS:%s\n     ET:%s     NE:%s     WP:%s     AM:%s\n     NW:%s     CD:%s     PG:%s\n     R0:%#x R1:%#x R2:%#x",
         cr0.PE ? "True " : "False", cr0.MP ? "True " : "False", cr0.EM ? "True " : "False", cr0.TS ? "True " : "False",
         cr0.ET ? "True " : "False", cr0.NE ? "True " : "False", cr0.WP ? "True " : "False", cr0.AM ? "True " : "False",
         cr0.NW ? "True " : "False", cr0.CD ? "True " : "False", cr0.PG ? "True " : "False",
         cr0._reserved0, cr0._reserved1, cr0._reserved2);
     err("\nCR2: PFLA: %#lx", cr2.PFLA);
     err("\nCR3: PWT:%s     PCD:%s    PDBR:%#lx", cr3.PWT ? "True " : "False", cr3.PCD ? "True " : "False", cr3.PDBR);
     err("\nCR4: VME:%s     PVI:%s     TSD:%s      DE:%s\n     PSE:%s     PAE:%s     MCE:%s     PGE:%s\n     PCE:%s    UMIP:%s  OSFXSR:%s OSXMMEXCPT:%s\n    LA57:%s    VMXE:%s    SMXE:%s   PCIDE:%s\n OSXSAVE:%s    SMEP:%s    SMAP:%s     PKE:%s\n     R0:%d R1:%d R2:%d",
         cr4.VME ? "True " : "False", cr4.PVI ? "True " : "False", cr4.TSD ? "True " : "False", cr4.DE ? "True " : "False",
         cr4.PSE ? "True " : "False", cr4.PAE ? "True " : "False", cr4.MCE ? "True " : "False", cr4.PGE ? "True " : "False",
         cr4.PCE ? "True " : "False", cr4.UMIP ? "True " : "False", cr4.OSFXSR ? "True " : "False", cr4.OSXMMEXCPT ? "True " : "False",
         cr4.LA57 ? "True " : "False", cr4.VMXE ? "True " : "False", cr4.SMXE ? "True " : "False", cr4.PCIDE ? "True " : "False",
         cr4.OSXSAVE ? "True " : "False", cr4.SMEP ? "True " : "False", cr4.SMAP ? "True " : "False", cr4.PKE ? "True " : "False",
         cr4._reserved0, cr4._reserved1, cr4._reserved2);
     err("\nCR8: TPL:%d", cr8.TPL);
     err("\nRFL: CF:%s     PF:%s     AF:%s     ZF:%s\n     SF:%s     TF:%s     IF:%s     DF:%s\n     OF:%s   IOPL:%s     NT:%s     RF:%s\n     VM:%s     AC:%s    VIF:%s    VIP:%s\n     ID:%s     AlwaysOne:%d\n     R0:%#x R1:%#x R2:%#x R3:%#x",
         FLAGS.CF ? "True " : "False", FLAGS.PF ? "True " : "False", FLAGS.AF ? "True " : "False", FLAGS.ZF ? "True " : "False",
         FLAGS.SF ? "True " : "False", FLAGS.TF ? "True " : "False", FLAGS.IF ? "True " : "False", FLAGS.DF ? "True " : "False",
         FLAGS.OF ? "True " : "False", FLAGS.IOPL ? "True " : "False", FLAGS.NT ? "True " : "False", FLAGS.RF ? "True " : "False",
         FLAGS.VM ? "True " : "False", FLAGS.AC ? "True " : "False", FLAGS.VIF ? "True " : "False", FLAGS.VIP ? "True " : "False",
         FLAGS.ID ? "True " : "False", FLAGS.always_one,
         FLAGS._reserved0, FLAGS._reserved1, FLAGS._reserved2, FLAGS._reserved3);
 }
References _SS, CS, err, ERROR_CODE, FLAGS, INT_NUM, MSR_FS_BASE, MSR_GS_BASE, R10, R11, R12, R13, R14, R15, R8, R9, CR0::raw, CR2::raw, CR3::raw, CR4::raw, CR8::raw, RAX, RBP, RBX, RCX, RDI, rdmsr(), RDX, readcr0(), readcr2(), readcr3(), readcr4(), readcr8(), RIP, RSI, and RSP.
debug_printf()
int debug_printf (enum debug_type type, const char * file, int line, const char * function, const char * message, ...)
Definition at line 77 of file Debug.c.
 {
     switch (type)
     {
     case _fixme:
         serial_write_text(COM1, "FIXME");
         break;
     case _stub:
         serial_write_text(COM1, "STUB");
         break;
     case _trace:
         serial_write_text(COM1, "TRACE");
         break;
     case _warn:
         serial_write_text(COM1, "WARN");
         break;
     case _err:
         serial_write_text(COM1, "ERROR");
         break;
     case _debug:
         serial_write_text(COM1, "DEBUG");
         break;
     case _ubsan:
         serial_write_text(COM1, "UBSAN");
         break;
     case _checkpoint:
         serial_write_text(COM1, "Checkpoint hit in ");
         serial_write_text(COM1, (char *)file);
         serial_write_text(COM1, " at ");
         shortdbgprint("%d", line);
         serial_write_text(COM1, " in function \"");
         serial_write_text(COM1, (char *)function);
         serial_write_text(COM1, "\"\n");
         goto cleanup;
     default:
         serial_write_text(COM1, "MESSAGE");
         break;
     }
     serial_write_text(COM1, ":");
     serial_write_text(COM1, (char *)file);
     serial_write_text(COM1, ":");
     shortdbgprint("%d", line);
     serial_write_text(COM1, ":");
     serial_write_text(COM1, (char *)function);
     if (type != _stub)
     {
         serial_write_text(COM1, ": ");
         va_list args;
         va_start(args, message);
         dbg_vprintf(message, args);
         serial_write_text(COM1, "\n");
         va_end(args);
     }
     else
     {
         serial_write_text(COM1, ": stub!\n");
     }
 cleanup:
     if (type == _stub)
     {
         return -1;
     }
     return 0;
 }
References _checkpoint, _debug, _err, _fixme, _stub, _trace, _ubsan, _warn, COM1, dbg_vprintf(), serial_write_text(), shortdbgprint(), va_end, and va_start.