Fennix Project: libc/include/io.h File Reference
io.h File Reference
#include <stdint.h>
Macros
#define inb(Port) inportb(Port)
#define inw(Port) inportw(Port)
#define inl(Port) inportl(Port)
#define outb(Port, Data) outportb(Port, Data)
#define outw(Port, Data) outportw(Port, Data)
#define outl(Port, Data) outportl(Port, Data)
Functions
static uint8_t inportb (uint16_t Port)
static uint16_t inportw (uint16_t Port)
static uint32_t inportl (uint16_t Port)
static void outportb (uint16_t Port, uint8_t Data)
static void outportw (uint16_t Port, uint16_t Data)
static void outportl (uint16_t Port, uint32_t Data)
static uint8_t mmioin8 (uint64_t Address)
static uint16_t mmioin16 (uint64_t Address)
static uint32_t mmioin32 (uint64_t Address)
static uint64_t mmioin64 (uint64_t Address)
static void mmioout8 (uint64_t Address, uint8_t Data)
static void mmioout16 (uint64_t Address, uint16_t Data)
static void mmioout32 (uint64_t Address, uint32_t Data)
static void mmioout64 (uint64_t Address, uint64_t Data)
static void mmoutb (void *Address, uint8_t value)
static void mmoutw (void *Address, uint16_t value)
static void mmoutl (void *Address, uint32_t value)
static void mmoutq (void *Address, uint64_t value)
static uint8_t mminb (void *Address)
static uint16_t mminw (void *Address)
static uint32_t mminl (void *Address)
static uint64_t mminq (void *Address)
Macro Definition Documentation
inb
#define inb (Port) inportb(Port)
Definition at line 209 of file io.h.
inl
#define inl (Port) inportl(Port)
Definition at line 211 of file io.h.
inw
#define inw (Port) inportw(Port)
Definition at line 210 of file io.h.
outb
#define outb (Port, Data) outportb(Port, Data)
Definition at line 212 of file io.h.
outl
#define outl (Port, Data) outportl(Port, Data)
Definition at line 214 of file io.h.
outw
#define outw (Port, Data) outportw(Port, Data)
Definition at line 213 of file io.h.
Function Documentation
inportb()
static uint8_t inportb (uint16_t Port) inline static
Definition at line 9 of file io.h.
     {
         uint8_t result;
         asm("in %%dx, %%al"
             : "=a"(result)
             : "d"(Port));
         return result;
     }
Referenced by ScreenRefreshProc().
inportl()
static uint32_t inportl (uint16_t Port) inline static
Definition at line 27 of file io.h.
     {
         uint32_t result;
         asm volatile("inl %1, %0"
                      : "=a"(result)
                      : "dN"(Port));
         return result;
     }
inportw()
static uint16_t inportw (uint16_t Port) inline static
Definition at line 18 of file io.h.
     {
         uint16_t result;
         asm("in %%dx, %%ax"
             : "=a"(result)
             : "d"(Port));
         return result;
     }
mminb()
static uint8_t mminb (void * Address) inline static
Definition at line 165 of file io.h.
     {
         uint8_t ret;
         asm volatile("mov %1, %0"
                      : "=r"(ret)
                      : "m"((*(uint8_t *)(Address)))
                      : "memory");
         return ret;
     }
References Address.
mminl()
static uint32_t mminl (void * Address) inline static
Definition at line 185 of file io.h.
     {
         uint32_t ret;
         asm volatile("mov %1, %0"
                      : "=r"(ret)
                      : "m"((*(uint32_t *)(Address)))
                      : "memory");
         return ret;
     }
References Address.
mminq()
static uint64_t mminq (void * Address) inline static
Definition at line 195 of file io.h.
     {
         uint64_t ret;
         asm volatile("mov %1, %0"
                      : "=r"(ret)
                      : "m"((*(uint64_t *)(Address)))
                      : "memory");
         return ret;
     }
References Address.
Referenced by hpet_read_counter().
mminw()
static uint16_t mminw (void * Address) inline static
Definition at line 175 of file io.h.
     {
         uint16_t ret;
         asm volatile("mov %1, %0"
                      : "=r"(ret)
                      : "m"((*(uint16_t *)(Address)))
                      : "memory");
         return ret;
     }
References Address.
mmioin16()
static uint16_t mmioin16 (uint64_t Address) inline static
Definition at line 67 of file io.h.
     {
         asm volatile("" ::
                          : "memory");
         uint16_t value = *(volatile uint16_t *)Address;
         asm volatile("" ::
                          : "memory");
         return value;
     }
References Address.
mmioin32()
static uint32_t mmioin32 (uint64_t Address) inline static
Definition at line 77 of file io.h.
     {
         asm volatile("" ::
                          : "memory");
         uint32_t value = *(volatile uint32_t *)Address;
         asm volatile("" ::
                          : "memory");
         return value;
     }
References Address.
mmioin64()
static uint64_t mmioin64 (uint64_t Address) inline static
Definition at line 87 of file io.h.
     {
         asm volatile("" ::
                          : "memory");
         uint64_t value = *(volatile uint64_t *)Address;
         asm volatile("" ::
                          : "memory");
         return value;
     }
References Address.
mmioin8()
static uint8_t mmioin8 (uint64_t Address) inline static
Definition at line 57 of file io.h.
     {
         asm volatile("" ::
                          : "memory");
         uint8_t value = *(volatile uint8_t *)Address;
         asm volatile("" ::
                          : "memory");
         return value;
     }
References Address.
mmioout16()
static void mmioout16 (uint64_t Address, uint16_t Data) inline static
Definition at line 106 of file io.h.
     {
         asm volatile("" ::
                          : "memory");
         *(volatile uint16_t *)Address = Data;
         asm volatile("" ::
                          : "memory");
     }
References Address.
mmioout32()
static void mmioout32 (uint64_t Address, uint32_t Data) inline static
Definition at line 115 of file io.h.
     {
         asm volatile("" ::
                          : "memory");
         *(volatile uint32_t *)Address = Data;
         asm volatile("" ::
                          : "memory");
     }
References Address.
mmioout64()
static void mmioout64 (uint64_t Address, uint64_t Data) inline static
Definition at line 124 of file io.h.
     {
         asm volatile("" ::
                          : "memory");
         *(volatile uint64_t *)Address = Data;
         asm volatile("" ::
                          : "memory");
     }
References Address.
mmioout8()
static void mmioout8 (uint64_t Address, uint8_t Data) inline static
Definition at line 97 of file io.h.
     {
         asm volatile("" ::
                          : "memory");
         *(volatile uint8_t *)Address = Data;
         asm volatile("" ::
                          : "memory");
     }
References Address.
mmoutb()
static void mmoutb (void * Address, uint8_t value) inline static
Definition at line 133 of file io.h.
     {
         asm volatile("mov %1, %0"
                      : "=m"((*(uint8_t *)(Address)))
                      : "r"(value)
                      : "memory");
     }
References Address.
mmoutl()
static void mmoutl (void * Address, uint32_t value) inline static
Definition at line 149 of file io.h.
     {
         asm volatile("mov %1, %0"
                      : "=m"((*(uint32_t *)(Address)))
                      : "r"(value)
                      : "memory");
     }
References Address.
mmoutq()
static void mmoutq (void * Address, uint64_t value) inline static
Definition at line 157 of file io.h.
     {
         asm volatile("mov %1, %0"
                      : "=m"((*(uint64_t *)(Address)))
                      : "r"(value)
                      : "memory");
     }
References Address.
Referenced by init_HPET().
mmoutw()
static void mmoutw (void * Address, uint16_t value) inline static
Definition at line 141 of file io.h.
     {
         asm volatile("mov %1, %0"
                      : "=m"((*(uint16_t *)(Address)))
                      : "r"(value)
                      : "memory");
     }
References Address.
outportb()
static void outportb (uint16_t Port, uint8_t Data) inline static
Definition at line 36 of file io.h.
     {
         asm volatile("out %%al, %%dx"
                      :
                      : "a"(Data), "d"(Port));
     }
outportl()
static void outportl (uint16_t Port, uint32_t Data) inline static
Definition at line 50 of file io.h.
     {
         asm volatile("outl %1, %0"
                      :
                      : "dN"(Port), "a"(Data));
     }
outportw()
static void outportw (uint16_t Port, uint16_t Data) inline static
Definition at line 43 of file io.h.
     {
         asm volatile("out %%ax, %%dx"
                      :
                      : "a"(Data), "d"(Port));
     }