Fennix Project: kernel/include/heap.h File Reference
heap.h File Reference
#include <types.h>
#include <cputables.h>
Macros
#define STACK_SIZE 0x1000
#define PAGE_SIZE 0x1000
#define NORMAL_VMA_OFFSET 0xFFFF800000000000
#define KERNEL_VMA_OFFSET 0xFFFFFFFF80000000
#define KERNEL_STACK_HEAP_BASE 0xFFFFA00000000000
#define KERNEL_STACK_HEAP_END 0xFFFFAFFFFFFF0000
#define USER_STACK_HEAP_BASE 0xFFFFB00000000000
#define USER_STACK_HEAP_END 0xFFFFBFFFFFFF0000
#define KERNEL_HEAP_BASE 0xFFFFC00000000000
#define KERNEL_HEAP_END 0xFFFFC00080000000
#define USER_HEAP_BASE 0xFFFFD00000000000
#define USER_HEAP_END 0xFFFFD00080000000
#define kmalloc(Size) HeapMalloc(Size)
#define kcalloc(n, Size) HeapCalloc(n, Size)
#define krealloc(Address, Size) HeapRealloc(Address, Size)
#define kfree(Address) HeapFree(Address)
Enumerations
enum PTFlag {
P = 1 << 0, RW = 1 << 1, US = 1 << 2, PWT = 1 << 3,
PCD = 1 << 4, A = 1 << 5, D = 1 << 6, PS = 1 << 7,
G = 1 << 8, AVL0 = 1 << 9, AVL1 = 1 << 10, AVL2 = 1 << 11,
PAT = 1 << 12, AVL3 = (uint64_t)1 << 52, AVL4 = (uint64_t)1 << 53, AVL5 = (uint64_t)1 << 54,
AVL6 = (uint64_t)1 << 55, AVL7 = (uint64_t)1 << 56, AVL8 = (uint64_t)1 << 57, AVL9 = (uint64_t)1 << 58,
PK0 = (uint64_t)1 << 59, PK1 = (uint64_t)1 << 60, PK2 = (uint64_t)1 << 61, PK3 = (uint64_t)1 << 62,
XD = (uint64_t)1 << 63
}
https://wiki.osdev.org/images/4/41/64-bit_page_tables1.png
enum AllocationAlgorithm {
NoAllocationAlgorithm, Default, LibAlloc, LibAlloc11,
BuddyAlloc, XallocV1
}
Functions
START_EXTERNC void * HeapMalloc (size_t Size)
void * HeapCalloc (size_t n, size_t Size)
void * HeapRealloc (void *Address, size_t Size)
void HeapFree (void *Address)
void * RequestPage ()
void * RequestPages (uint64_t pages)
void * CreateNewPML4 ()
void FreePage (void *address)
void FreePages (void *address, uint64_t pages)
uint64_t GetTotalMemory ()
uint64_t GetFreeMemory ()
uint64_t GetUsedMemory ()
uint64_t GetReservedMemory ()
void MapMemory (void *PML4, void *VirtualMemory, void *PhysicalMemory, uint64_t Flags)
void init_pmm ()
void init_vmm ()
void init_kernelpml ()
void init_heap (enum AllocationAlgorithm Type)
Variables
uint64_t _kernel_start
uint64_t _kernel_end
uint64_t _kernel_text_end
uint64_t _kernel_rodata_end
enum PTFlag __attribute__
Macro Definition Documentation
kcalloc
#define kcalloc (n, Size) HeapCalloc(n, Size)
Definition at line 277 of file heap.h.
KERNEL_HEAP_BASE
#define KERNEL_HEAP_BASE 0xFFFFC00000000000
Definition at line 170 of file heap.h.
KERNEL_HEAP_END
#define KERNEL_HEAP_END 0xFFFFC00080000000
Definition at line 171 of file heap.h.
KERNEL_STACK_HEAP_BASE
#define KERNEL_STACK_HEAP_BASE 0xFFFFA00000000000
Definition at line 164 of file heap.h.
KERNEL_STACK_HEAP_END
#define KERNEL_STACK_HEAP_END 0xFFFFAFFFFFFF0000
Definition at line 165 of file heap.h.
KERNEL_VMA_OFFSET
#define KERNEL_VMA_OFFSET 0xFFFFFFFF80000000
Definition at line 162 of file heap.h.
kfree
#define kfree (Address) HeapFree(Address)
Definition at line 279 of file heap.h.
kmalloc
#define kmalloc (Size) HeapMalloc(Size)
Definition at line 276 of file heap.h.
krealloc
#define krealloc (Address, Size) HeapRealloc(Address, Size)
Definition at line 278 of file heap.h.
NORMAL_VMA_OFFSET
#define NORMAL_VMA_OFFSET 0xFFFF800000000000
Definition at line 161 of file heap.h.
PAGE_SIZE
#define PAGE_SIZE 0x1000
Definition at line 159 of file heap.h.
STACK_SIZE
#define STACK_SIZE 0x1000
Definition at line 158 of file heap.h.
USER_HEAP_BASE
#define USER_HEAP_BASE 0xFFFFD00000000000
Definition at line 173 of file heap.h.
USER_HEAP_END
#define USER_HEAP_END 0xFFFFD00080000000
Definition at line 174 of file heap.h.
USER_STACK_HEAP_BASE
#define USER_STACK_HEAP_BASE 0xFFFFB00000000000
Definition at line 167 of file heap.h.
USER_STACK_HEAP_END
#define USER_STACK_HEAP_END 0xFFFFBFFFFFFF0000
Definition at line 168 of file heap.h.
Enumeration Type Documentation
AllocationAlgorithm
enum AllocationAlgorithm
Enumerator
NoAllocationAlgorithm
Default
LibAlloc
LibAlloc11
BuddyAlloc
XallocV1
Definition at line 258 of file heap.h.
 {
     NoAllocationAlgorithm,
     Default,
     LibAlloc,
     LibAlloc11,
     BuddyAlloc,
     XallocV1
 };
PTFlag
enum PTFlag
https://wiki.osdev.org/images/4/41/64-bit_page_tables1.png
https://wiki.osdev.org/images/6/6b/64-bit_page_tables2.png
Enumerator
P
Present.
RW
Read/Write.
US
User/Supervisor.
PWT
Write-Through.
PCD
Cache Disable.
A
Accessed.
D
Dirty.
PS
Page Size.
G
Global.
AVL0
Available 0.
AVL1
Available 1.
AVL2
Available 2.
PAT
Page Attribute Table.
AVL3
Available 3.
AVL4
Available 4.
AVL5
Available 5.
AVL6
Available 6.
AVL7
Available 7.
AVL8
Available 8.
AVL9
Available 9.
PK0
Protection Key 0.
PK1
Protection Key 1.
PK2
Protection Key 2.
PK3
Protection Key 3.
XD
Execute Disable.
Definition at line 180 of file heap.h.
 {
     P = 1 << 0,
     RW = 1 << 1,
     US = 1 << 2,
     PWT = 1 << 3,
     PCD = 1 << 4,
     A = 1 << 5,
     D = 1 << 6,
     PS = 1 << 7,
     G = 1 << 8,
     AVL0 = 1 << 9,
     AVL1 = 1 << 10,
     AVL2 = 1 << 11,
     PAT = 1 << 12,
     AVL3 = (uint64_t)1 << 52,
     AVL4 = (uint64_t)1 << 53,
     AVL5 = (uint64_t)1 << 54,
     AVL6 = (uint64_t)1 << 55,
     AVL7 = (uint64_t)1 << 56,
     AVL8 = (uint64_t)1 << 57,
     AVL9 = (uint64_t)1 << 58,
     PK0 = (uint64_t)1 << 59,
     PK1 = (uint64_t)1 << 60,
     PK2 = (uint64_t)1 << 61,
     PK3 = (uint64_t)1 << 62,
     XD = (uint64_t)1 << 63
 };
Function Documentation
CreateNewPML4()
void* CreateNewPML4 ()
FreePage()
void PageFrameAllocator::FreePage (void * address)
Definition at line 109 of file PageFrameAllocator.cpp.
 {
 #ifdef DEBUG_MEM_ALLOCATION
     if (Address == nullptr)
     {
         warn("Null address specified");
         // return;
     }
 #endif
     LOCK(pfa_lock);
 #ifdef DEBUG_MEM_ALLOCATION
     // debug("Freeing page %016p", Address); // spam
 #endif
     uint64_t Index = (uint64_t)Address / 4096;
     if (PageBitmap[Index] == false)
     {
 #ifdef DEBUG_MEM_ALLOCATION
         warn("Trying to free already free page %016p", Address);
 #endif
         UNLOCK(pfa_lock);
         return;
     }
     if (PageBitmap.Set(Index, false))
     {
         FreeMemory += 4096;
         UsedMemory -= 4096;
         if (PageBitmapIndex > Index)
             PageBitmapIndex = Index;
     }
     UNLOCK(pfa_lock);
 }
References Address, address, FreeMemory, KernelAllocator, LOCK, PageBitmapIndex, UNLOCK, UsedMemory, and warn.
Referenced by FileSystem::EXT2::EXT2(), FileSystem::FAT::FAT(), and FreePages().
FreePages()
void PageFrameAllocator::FreePages (void * address, uint64_t pages)
Definition at line 182 of file PageFrameAllocator.cpp.
 {
 #ifdef DEBUG_MEM_ALLOCATION
     if (Address == nullptr || PageCount == 0)
     {
         warn("Trying to free %s", Address ? "address" : "", PageCount ? "0 pages" : "");
         // return;
     }
 #endif
     for (uint64_t t = 0; t < PageCount; t++)
         FreePage((void *)((uint64_t)Address + (t * 4096)));
 }
References Address, address, FreePage(), KernelAllocator, and warn.
Referenced by free(), and liballoc_free().
GetFreeMemory()
uint64_t GetFreeMemory ()
Definition at line 227 of file HeapManager.cpp.
 { return KernelAllocator.GetFreeRAM(); }
References KernelAllocator.
Referenced by init_pmm().
GetReservedMemory()
uint64_t GetReservedMemory ()
Definition at line 231 of file HeapManager.cpp.
 { return KernelAllocator.GetReservedRAM(); }
References KernelAllocator.
Referenced by init_pmm().
GetTotalMemory()
uint64_t GetTotalMemory ()
Definition at line 225 of file HeapManager.cpp.
 { return KernelAllocator.GetTotalRAM(); }
References KernelAllocator.
GetUsedMemory()
uint64_t GetUsedMemory ()
Definition at line 229 of file HeapManager.cpp.
 { return KernelAllocator.GetUsedRAM(); }
References KernelAllocator.
Referenced by init_pmm().
HeapCalloc()
void* HeapCalloc (size_t n, size_t Size)
Definition at line 137 of file HeapManager.cpp.
 {
     LOCK(heap_lock);
     bool inten = InterruptsEnabled();
     CLI;
     void *ret = nullptr;
     switch (AlgorithmToUse)
     {
     case AllocationAlgorithm::Default:
         ret = defPREFIX(calloc)(n, Size);
         break;
     case AllocationAlgorithm::LibAlloc:
         ret = liballoc_calloc(n, Size);
         break;
     case AllocationAlgorithm::LibAlloc11:
         ret = libPREFIX(calloc)(n, Size);
         break;
     case AllocationAlgorithm::BuddyAlloc:
         ret = buddy_calloc(buddy, n, Size);
         break;
     case AllocationAlgorithm::XallocV1:
         ret = xalloc->Calloc(n, Size);
         break;
     case AllocationAlgorithm::NoAllocationAlgorithm:
         panic("HeapFree called before heap initialized!", true);
         break;
     default:
         panic("Unknown allocation algorithm!", true);
         break;
     }
     memset(ret, 0, n * Size);
     UNLOCK(heap_lock);
     if (inten)
         STI;
     return ret;
 }
References AlgorithmToUse, buddy, buddy_calloc(), BuddyAlloc, Xalloc::AllocatorV1::Calloc(), calloc(), CLI, Default, defPREFIX, InterruptsEnabled(), LibAlloc, LibAlloc11, liballoc_calloc(), libPREFIX, LOCK, memset(), NoAllocationAlgorithm, panic, STI, UNLOCK, xalloc, and XallocV1.
HeapFree()
void HeapFree (void * Address)
Definition at line 63 of file HeapManager.cpp.
 {
     LOCK(heap_lock);
     bool inten = InterruptsEnabled();
     CLI;
     switch (AlgorithmToUse)
     {
     case AllocationAlgorithm::Default:
         defPREFIX(free)(Address);
         break;
     case AllocationAlgorithm::LibAlloc:
         liballoc_free(Address);
         break;
     case AllocationAlgorithm::LibAlloc11:
         libPREFIX(free)(Address);
         break;
     case AllocationAlgorithm::BuddyAlloc:
         buddy_free(buddy, Address);
         break;
     case AllocationAlgorithm::XallocV1:
         xalloc->Free(Address);
         break;
     case AllocationAlgorithm::NoAllocationAlgorithm:
         panic("HeapFree called before heap initialized!", true);
         break;
     default:
         panic("Unknown allocation algorithm!", true);
         break;
     }
     UNLOCK(heap_lock);
     if (inten)
         STI;
 }
References Address, AlgorithmToUse, buddy, buddy_free(), BuddyAlloc, CLI, Default, defPREFIX, free(), Xalloc::AllocatorV1::Free(), InterruptsEnabled(), LibAlloc, LibAlloc11, liballoc_free(), libPREFIX, LOCK, NoAllocationAlgorithm, panic, STI, UNLOCK, xalloc, and XallocV1.
Referenced by operator delete(), and operator delete[]().
HeapMalloc()
START_EXTERNC void* HeapMalloc (size_t Size)
Definition at line 97 of file HeapManager.cpp.
 {
     LOCK(heap_lock);
     bool inten = InterruptsEnabled();
     CLI;
     void *ret = nullptr;
     switch (AlgorithmToUse)
     {
     case AllocationAlgorithm::Default:
         ret = defPREFIX(malloc)(Size);
         break;
     case AllocationAlgorithm::LibAlloc:
         ret = liballoc_malloc(Size);
         break;
     case AllocationAlgorithm::LibAlloc11: // TODO: Make that the Liballoc 1.1 start at KERNEL_HEAP_BASE
         ret = libPREFIX(malloc)(Size);
         break;
     case AllocationAlgorithm::BuddyAlloc:
         ret = buddy_malloc(buddy, Size);
         break;
     case AllocationAlgorithm::XallocV1:
         ret = xalloc->Malloc(Size);
         break;
     case AllocationAlgorithm::NoAllocationAlgorithm:
         panic("HeapFree called before heap initialized!", true);
         break;
     default:
         panic("Unknown allocation algorithm!", true);
         break;
     }
     memset(ret, 0, Size);
     UNLOCK(heap_lock);
     if (inten)
         STI;
     return ret;
 }
References AlgorithmToUse, buddy, buddy_malloc(), BuddyAlloc, CLI, Default, defPREFIX, InterruptsEnabled(), LibAlloc, LibAlloc11, liballoc_malloc(), libPREFIX, LOCK, malloc(), Xalloc::AllocatorV1::Malloc(), memset(), NoAllocationAlgorithm, panic, STI, UNLOCK, xalloc, and XallocV1.
Referenced by for().
HeapRealloc()
void* HeapRealloc (void * Address, size_t Size)
Definition at line 177 of file HeapManager.cpp.
 {
     LOCK(heap_lock);
     bool inten = InterruptsEnabled();
     CLI;
     void *ret = nullptr;
     switch (AlgorithmToUse)
     {
     case AllocationAlgorithm::Default:
         ret = defPREFIX(realloc)(Address, Size);
         break;
     case AllocationAlgorithm::LibAlloc:
         ret = liballoc_realloc(Address, Size);
         break;
     case AllocationAlgorithm::LibAlloc11:
         ret = libPREFIX(realloc)(Address, Size);
         break;
     case AllocationAlgorithm::BuddyAlloc:
         ret = buddy_realloc(buddy, Address, Size);
         break;
     case AllocationAlgorithm::XallocV1:
         ret = xalloc->Realloc(Address, Size);
         break;
     case AllocationAlgorithm::NoAllocationAlgorithm:
         panic("HeapFree called before heap initialized!", true);
         break;
     default:
         panic("Unknown allocation algorithm!", true);
         break;
     }
     memset(ret, 0, Size);
     UNLOCK(heap_lock);
     if (inten)
         STI;
     return ret;
 }
References Address, AlgorithmToUse, buddy, buddy_realloc(), BuddyAlloc, CLI, Default, defPREFIX, InterruptsEnabled(), LibAlloc, LibAlloc11, liballoc_realloc(), libPREFIX, LOCK, memset(), NoAllocationAlgorithm, panic, Xalloc::AllocatorV1::Realloc(), realloc(), STI, UNLOCK, xalloc, and XallocV1.
init_heap()
void init_heap (enum AllocationAlgorithm Type)
Definition at line 29 of file HeapManager.cpp.
 {
     LOCK(heap_lock);
     switch (Type)
     {
     case AllocationAlgorithm::Default:
         InitHeap((void *)KERNEL_HEAP_BASE, 0x20);
         break;
     case AllocationAlgorithm::LibAlloc:
         break;
     case AllocationAlgorithm::LibAlloc11:
         break;
     case AllocationAlgorithm::BuddyAlloc:
     {
         alignas(max_align_t) unsigned char buddy_buf[buddy_sizeof(4096)];
         alignas(max_align_t) unsigned char data_buf[4096];
         {
             buddy = buddy_init(buddy_buf, data_buf, 4096);
             assert(buddy != NULL);
         }
         break;
     }
     case AllocationAlgorithm::XallocV1:
     {
         xalloc = new Xalloc::AllocatorV1((void *)KERNEL_HEAP_BASE, false, false);
         break;
     }
     default:
         panic("Unknown allocation algorithm!", true);
     }
     AlgorithmToUse = Type;
     UNLOCK(heap_lock);
 }
References AlgorithmToUse, assert, buddy, buddy_init(), buddy_sizeof(), BuddyAlloc, Default, InitHeap(), KERNEL_HEAP_BASE, LibAlloc, LibAlloc11, LOCK, NULL, panic, Type, UNLOCK, xalloc, and XallocV1.
Referenced by limine_initializator().
init_kernelpml()
void init_kernelpml ()
Definition at line 60 of file PageTableHeapManager.cpp.
 {
     if (KernelPML4 == NULL)
     {
         debug("Kernel VM Start-End: %016p-%016p", &_kernel_start, &_kernel_end);
         KernelPML4 = (PageTable *)KernelAllocator.RequestPage();
         memset(KernelPML4, 0, PAGE_SIZE);
         KernelPageTableManager = PageTableManager(KernelPML4);
         uint64_t VirtualOffsetNormalVMA = NORMAL_VMA_OFFSET;
         uint64_t BaseKernelMapAddress = earlyparams.mem.KernelBasePhysical;
         uint64_t KernelStart = (uint64_t)&_kernel_start;
         uint64_t KernelTextEnd = (uint64_t)&_kernel_text_end;
         uint64_t KernelRoDataEnd = (uint64_t)&_kernel_rodata_end;
         uint64_t KernelEnd = (uint64_t)&_kernel_end;
         for (uint64_t t = 0; t < earlyparams.mem.Size; t += PAGE_SIZE)
         {
             // TODO: remove US flag
             KernelPageTableManager.MapMemory((void *)t, (void *)t, PTFlag::RW | US);
             KernelPageTableManager.MapMemory((void *)VirtualOffsetNormalVMA, (void *)t, PTFlag::RW | US);
             VirtualOffsetNormalVMA += PAGE_SIZE;
         }
         /* Mapping Framebuffer address */
         for (uint64_t fb_base = earlyparams.Framebuffer.BaseAddress;
              fb_base < (earlyparams.Framebuffer.BaseAddress + (earlyparams.Framebuffer.BufferSize + PAGE_SIZE));
              fb_base += PAGE_SIZE)
             KernelPageTableManager.MapMemory((void *)fb_base, (void *)(fb_base - NORMAL_VMA_OFFSET), PTFlag::RW | PTFlag::US);
         /* Kernel mapping */
         for (uint64_t k = KernelStart; k < KernelTextEnd; k += PAGE_SIZE)
         {
             KernelPageTableManager.MapMemory((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW);
             KernelAllocator.LockPage((void *)BaseKernelMapAddress);
             BaseKernelMapAddress += PAGE_SIZE;
         }
         for (uint64_t k = KernelTextEnd; k < KernelRoDataEnd; k += PAGE_SIZE)
         {
             KernelPageTableManager.MapMemory((void *)k, (void *)BaseKernelMapAddress, PTFlag::P);
             KernelAllocator.LockPage((void *)BaseKernelMapAddress);
             BaseKernelMapAddress += PAGE_SIZE;
         }
         for (uint64_t k = KernelRoDataEnd; k < KernelEnd; k += PAGE_SIZE)
         {
             KernelPageTableManager.MapMemory((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW);
             KernelAllocator.LockPage((void *)BaseKernelMapAddress);
             BaseKernelMapAddress += PAGE_SIZE;
         }
         debug("\nStart: %#llx - Text End: %#llx - RoEnd: %#llx - End: %#llx\nStart Physical: %#llx - End Physical: %#llx",
               KernelStart, KernelTextEnd, KernelRoDataEnd, KernelEnd, earlyparams.mem.KernelBasePhysical, BaseKernelMapAddress);
         /*    KernelStart             KernelTextEnd       KernelRoDataEnd                  KernelEnd
         Kernel Start & Text Start ------ Text End ------ Kernel Rodata End ------ Kernel Data End & Kernel End
         */
         trace("Applying new page table from address %#llx", KernelPML4);
         CR3 CR3PageTable;
         CR3PageTable.raw = (uint64_t)KernelPML4;
         writecr3(CR3PageTable);
         CurrentCPU->PageTable.raw = CR3PageTable.raw;
         SetKernelPageTableAddress((void *)KernelPML4);
     }
 }
References _kernel_end, _kernel_rodata_end, _kernel_start, _kernel_text_end, GBPFramebuffer::BaseAddress, GBPFramebuffer::BufferSize, CurrentCPU, debug, earlyparams, _GlobalBootParams::Framebuffer, KernelAllocator, GBPMemory::KernelBasePhysical, KernelPageTableManager, KernelPML4, _GlobalBootParams::mem, memset(), NORMAL_VMA_OFFSET, NULL, P, PAGE_SIZE, PageTable, CR3::raw, RW, SetKernelPageTableAddress(), GBPMemory::Size, trace, US, and writecr3().
Referenced by limine_initializator().
init_pmm()
void init_pmm ()
Definition at line 7 of file PhysicalMemoryManager.cpp.
 {
     trace("initializing pmm");
     uint64_t kernelSize = (uint64_t)&_kernel_end - (uint64_t)&_kernel_start;
     // uint64_t kernelPages = (uint64_t)kernelSize / 4096 + 1;
     uint64_t fbBase = earlyparams.Framebuffer.BaseAddress;
     uint64_t fbSize = earlyparams.Framebuffer.BufferSize + 0x1000;
     KernelAllocator = PageFrameAllocator();
     KernelAllocator.ReadMemoryMap();
     // KernelAllocator.LockPages(&_kernel_start, kernelPages);
     debug("RAM SIZE: %dGB", TO_GB(earlyparams.mem.Size));
     debug("Kernel Start: %016p - End: %016p - Size: %d (%dKB)", &_kernel_start, &_kernel_end, kernelSize, TO_KB(kernelSize));
     debug("Framebuffer Base: %016p - Framebuffer Size: %d (%dKB)", fbBase, fbSize, TO_KB(fbSize));
     debug("RAM-> Free: %dGB (%dMB) - Used: %dGB (%dMB) - Reserved: %dGB (%dMB)",
           TO_GB(GetFreeMemory()), TO_MB(GetFreeMemory()),
           TO_GB(GetUsedMemory()), TO_MB(GetUsedMemory()),
           TO_GB(GetReservedMemory()), TO_MB(GetReservedMemory()));
 }
References _kernel_end, _kernel_start, GBPFramebuffer::BaseAddress, GBPFramebuffer::BufferSize, debug, earlyparams, FileSystem::fbSize, _GlobalBootParams::Framebuffer, GetFreeMemory(), GetReservedMemory(), GetUsedMemory(), KernelAllocator, _GlobalBootParams::mem, GBPMemory::Size, TO_GB, TO_KB, TO_MB, and trace.
Referenced by limine_initializator().
init_vmm()
void init_vmm ()
Definition at line 130 of file VirtualMemoryManager.cpp.
 {
     trace("initializing virtual memory manager");
     KernelPageTableManager.Initalized = true;
 }
References KernelPageTableManager, and trace.
Referenced by limine_initializator().
MapMemory()
void MapMemory (void * PML4, void * VirtualMemory, void * PhysicalMemory, uint64_t Flags)
Definition at line 109 of file VirtualMemoryManager.cpp.
 {
     if (PML4 != NULL)
     {
         PageTable *KernelNewPML = KernelPageTableManager.PML4;
         KernelPageTableManager.PML4 = (PageTable *)PML4;
         if (Flags == 0)
             KernelPageTableManager.MapMemory(VirtualMemory, PhysicalMemory, PTFlag::RW);
         else
             KernelPageTableManager.MapMemory(VirtualMemory, PhysicalMemory, Flags);
         KernelPageTableManager.PML4 = KernelNewPML;
     }
     else
     {
         if (Flags == 0)
             KernelPageTableManager.MapMemory(VirtualMemory, PhysicalMemory, PTFlag::RW);
         else
             KernelPageTableManager.MapMemory(VirtualMemory, PhysicalMemory, Flags);
     }
 }
References Flags, KernelPageTableManager, NULL, PageTable, and RW.
Referenced by init_HPET().
RequestPage()
void * PageFrameAllocator::RequestPage ()
Definition at line 85 of file PageFrameAllocator.cpp.
 {
     LOCK(pfa_lock);
     for (; PageBitmapIndex < PageBitmap.Size * 8; PageBitmapIndex++)
     {
         if (PageBitmap[PageBitmapIndex] == true)
             continue;
         LockPage((void *)(PageBitmapIndex * 4096));
 #ifdef DEBUG_MEM_ALLOCATION
         if (KernelPageTableManager.Initalized)
             debug("Requested page %#llx", (void *)(PageBitmapIndex * 4096));
 #endif
         UNLOCK(pfa_lock);
         return (void *)(PageBitmapIndex * 4096);
     }
     // TODO: Page Frame Swap to file
     char buf[256] = {'\0'};
     sprintf_(buf, "Out of memory! (Free: %ldMB; Used: %ldMB; Reserved: %ldMB)", TO_MB(FreeMemory), TO_MB(UsedMemory), TO_MB(ReservedMemory));
     panic(buf, true);
     UNLOCK(pfa_lock);
     return NULL;
 }
References debug, FreeMemory, KernelAllocator, KernelPageTableManager, LOCK, NULL, PageBitmapIndex, panic, ReservedMemory, sprintf_(), TO_MB, UNLOCK, and UsedMemory.
Referenced by allocate_new_tag(), FileSystem::EXT2::EXT2(), and FileSystem::FAT::FAT().
RequestPages()
void * PageFrameAllocator::RequestPages (uint64_t pages)
Definition at line 141 of file PageFrameAllocator.cpp.
 {
 #ifdef DEBUG_MEM_ALLOCATION
     if (PageCount == 0)
     {
         warn("Trying to request 0 pages");
         // PageCount = 1;
     }
 #endif
     LOCK(pfa_lock);
     for (; PageBitmapIndex < PageBitmap.Size * 8; PageBitmapIndex++)
     {
         if (PageBitmap[PageBitmapIndex] == true)
             continue;
         for (uint64_t Index = PageBitmapIndex; Index < PageBitmap.Size * 8; Index++)
         {
             if (PageBitmap[Index] == true)
                 continue;
             for (uint64_t i = 0; i < PageCount; i++)
                 if (PageBitmap[Index + i] == true)
                     goto NextPage;
             LockPages((void *)(Index * 4096), PageCount);
 #ifdef DEBUG_MEM_ALLOCATION
             debug("Requested pages %016p returning %#lx", PageCount, (void *)(Index * 4096));
 #endif
             UNLOCK(pfa_lock);
             return (void *)(Index * 4096);
         NextPage:
             Index += PageCount;
             continue;
         }
     }
     err("out of memory (free: %dMB, used: %dMB, reserved: %dMB)", TO_MB(FreeMemory), TO_MB(UsedMemory), TO_MB(ReservedMemory));
     UNLOCK(pfa_lock);
     return NULL;
 }
References debug, err, FreeMemory, KernelAllocator, LOCK, NULL, PageBitmapIndex, ReservedMemory, TO_MB, UNLOCK, UsedMemory, and warn.
Referenced by allocate_new_page().
Variable Documentation
__attribute__
enum PTFlag __attribute__
_kernel_end
uint64_t _kernel_end
Definition at line 9 of file heap.h.
Referenced by init_kernelpml(), and init_pmm().
_kernel_rodata_end
uint64_t _kernel_rodata_end
Definition at line 10 of file heap.h.
Referenced by init_kernelpml().
_kernel_start
uint64_t _kernel_start
Referenced by init_kernelpml(), and init_pmm().
_kernel_text_end
uint64_t _kernel_text_end
Referenced by init_kernelpml().