Fennix Project: PS2Keyboard::PS2KeyboardDriver Class Reference
PS2Keyboard::PS2KeyboardDriver Class Reference
#include <keyboard.hpp>
Public Member Functions
unsigned char GetLastScanCode ()
PS2KeyboardDriver ()
~PS2KeyboardDriver ()
Detailed Description
Definition at line 5 of file keyboard.hpp.
Constructor & Destructor Documentation
PS2KeyboardDriver()
PS2Keyboard::PS2KeyboardDriver::PS2KeyboardDriver ()
Definition at line 34 of file keyboard.cpp.
     {
         RegisterInterrupt(PS2KeyboardInterruptHandler, IRQ1, true);
         while (inb(0x64) & 0x1)
             inb(0x60);
         outb(0x64, 0xAE);
         outb(0x64, 0x20);
         uint8_t ret = (inb(0x60) | 1) & ~0x10;
         outb(0x64, 0x60);
         outb(0x60, ret);
         outb(0x60, 0xF4);
     }
References inb, outb, and RegisterInterrupt().
~PS2KeyboardDriver()
PS2Keyboard::PS2KeyboardDriver::~PS2KeyboardDriver ()
Definition at line 49 of file keyboard.cpp.
     {
         warn("Unloading default keyboard driver is not supported.");
     }
References warn.
Member Function Documentation
GetLastScanCode()
uint8_t PS2Keyboard::PS2KeyboardDriver::GetLastScanCode ()
Definition at line 26 of file keyboard.cpp.
     {
         LastSC = 0x0;
         while (!LastSC)
             asm volatile("hlt");
         return LastSC;
     }
References PS2Keyboard::LastSC.
Referenced by internal_getlastkeyboardscancode(), KernelInit(), and SystemRecovery::Recovery::Recovery().
The documentation for this class was generated from the following files:
kernel/drivers/keyboard.hpp
kernel/drivers/keyboard.cpp