Fennix Project: kernel/mem/PageTableHeapManager.cpp File Reference
PageTableHeapManager.cpp File Reference
#include <heap.h>
#include <asm.h>
#include <lock.h>
#include "../kernel.h"
#include "../cpu/idt.h"
#include "../cpu/smp.hpp"
Namespaces
PageTableHeap
Functions
NEWLOCK (pagetable_lock)
void init_kernelpml ()
Variables
PageTable * KernelPML4
PageTableHeap::PageTableHeap * KernelPageTableAllocator = nullptr
static uint64_t PageTableHeap::MemoryEntries = bootparams->mem.Size
Function Documentation
init_kernelpml()
void init_kernelpml ()
Definition at line 60 of file PageTableHeapManager.cpp.
 {
     if (KernelPML4 == NULL)
     {
         debug("Kernel VM Start-End: %016p-%016p", &_kernel_start, &_kernel_end);
         KernelPML4 = (PageTable *)KernelAllocator.RequestPage();
         memset(KernelPML4, 0, PAGE_SIZE);
         KernelPageTableManager = PageTableManager(KernelPML4);
         uint64_t VirtualOffsetNormalVMA = NORMAL_VMA_OFFSET;
         uint64_t BaseKernelMapAddress = earlyparams.mem.KernelBasePhysical;
         uint64_t KernelStart = (uint64_t)&_kernel_start;
         uint64_t KernelTextEnd = (uint64_t)&_kernel_text_end;
         uint64_t KernelRoDataEnd = (uint64_t)&_kernel_rodata_end;
         uint64_t KernelEnd = (uint64_t)&_kernel_end;
         for (uint64_t t = 0; t < earlyparams.mem.Size; t += PAGE_SIZE)
         {
             // TODO: remove US flag
             KernelPageTableManager.MapMemory((void *)t, (void *)t, PTFlag::RW | US);
             KernelPageTableManager.MapMemory((void *)VirtualOffsetNormalVMA, (void *)t, PTFlag::RW | US);
             VirtualOffsetNormalVMA += PAGE_SIZE;
         }
         /* Mapping Framebuffer address */
         for (uint64_t fb_base = earlyparams.Framebuffer.BaseAddress;
              fb_base < (earlyparams.Framebuffer.BaseAddress + (earlyparams.Framebuffer.BufferSize + PAGE_SIZE));
              fb_base += PAGE_SIZE)
             KernelPageTableManager.MapMemory((void *)fb_base, (void *)(fb_base - NORMAL_VMA_OFFSET), PTFlag::RW | PTFlag::US);
         /* Kernel mapping */
         for (uint64_t k = KernelStart; k < KernelTextEnd; k += PAGE_SIZE)
         {
             KernelPageTableManager.MapMemory((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW);
             KernelAllocator.LockPage((void *)BaseKernelMapAddress);
             BaseKernelMapAddress += PAGE_SIZE;
         }
         for (uint64_t k = KernelTextEnd; k < KernelRoDataEnd; k += PAGE_SIZE)
         {
             KernelPageTableManager.MapMemory((void *)k, (void *)BaseKernelMapAddress, PTFlag::P);
             KernelAllocator.LockPage((void *)BaseKernelMapAddress);
             BaseKernelMapAddress += PAGE_SIZE;
         }
         for (uint64_t k = KernelRoDataEnd; k < KernelEnd; k += PAGE_SIZE)
         {
             KernelPageTableManager.MapMemory((void *)k, (void *)BaseKernelMapAddress, PTFlag::RW);
             KernelAllocator.LockPage((void *)BaseKernelMapAddress);
             BaseKernelMapAddress += PAGE_SIZE;
         }
         debug("\nStart: %#llx - Text End: %#llx - RoEnd: %#llx - End: %#llx\nStart Physical: %#llx - End Physical: %#llx",
               KernelStart, KernelTextEnd, KernelRoDataEnd, KernelEnd, earlyparams.mem.KernelBasePhysical, BaseKernelMapAddress);
         /*    KernelStart             KernelTextEnd       KernelRoDataEnd                  KernelEnd
         Kernel Start & Text Start ------ Text End ------ Kernel Rodata End ------ Kernel Data End & Kernel End
         */
         trace("Applying new page table from address %#llx", KernelPML4);
         CR3 CR3PageTable;
         CR3PageTable.raw = (uint64_t)KernelPML4;
         writecr3(CR3PageTable);
         CurrentCPU->PageTable.raw = CR3PageTable.raw;
         SetKernelPageTableAddress((void *)KernelPML4);
     }
 }
References _kernel_end, _kernel_rodata_end, _kernel_start, _kernel_text_end, GBPFramebuffer::BaseAddress, GBPFramebuffer::BufferSize, CurrentCPU, debug, earlyparams, _GlobalBootParams::Framebuffer, KernelAllocator, GBPMemory::KernelBasePhysical, KernelPageTableManager, KernelPML4, _GlobalBootParams::mem, memset(), NORMAL_VMA_OFFSET, P, PAGE_SIZE, PageTable, RW, SetKernelPageTableAddress(), GBPMemory::Size, trace, US, and writecr3().
Referenced by stivale2_initializator().
NEWLOCK()
NEWLOCK (pagetable_lock)
Variable Documentation
KernelPageTableAllocator
PageTableHeap::PageTableHeap* KernelPageTableAllocator = nullptr
Definition at line 14 of file PageTableHeapManager.cpp.
Referenced by Tasking::Multitasking::CreateProcess(), Tasking::Monotasking::CreateTask(), KernelInit(), and Tasking::RemoveProcess().
KernelPML4
PageTable* KernelPML4
Definition at line 13 of file PageTableHeapManager.cpp.
Referenced by init_kernelpml().