Fennix Project: kernel/include/sys.h File Reference
sys.h File Reference
#include <interrupts.h>
#include <int.h>
Macros
#define panic(m, clear) crash(m, clear)
Functions
EXTERNC void crash (string message, bool clear)
void TriggerUserModeCrash (TrapFrame *regs)
EXTERNC void isrcrash (TrapFrame *regs)
Macro Definition Documentation
panic
#define panic (m, clear) crash(m, clear)
Definition at line 9 of file sys.h.
Function Documentation
crash()
EXTERNC void crash (string message, bool clear)
Definition at line 36 of file CrashHandler.cpp.
 {
     // TODO: Add more useful information.
     CLI;
     debug("System crashed with message: %s", message);
     if (CurrentDisplay == nullptr)
     {
         debug("No display found. Cannot display crash message.");
         CPU_HALT;
     }
     if (clear)
         CurrentDisplay->Clear(0x121160);
     CurrentDisplay->SetPrintColor(0xDD2920);
     SET_PRINT_MID((char *)"System crashed!", FHeight(1));
     CurrentDisplay->ResetPrintColor();
     SET_PRINT_MID((char *)message, (CurrentDisplay->GetFramebuffer()->Height / 2));
     if (CurrentCPU->CurrentThread != nullptr)
     {
         err("\"%s\" happened while running thread %s(%d)", message, CurrentCPU->CurrentThread->Name, CurrentCPU->CurrentThread->ID);
     }
     CPU_HALT;
 }
References CLI, CPU_HALT, CurrentCPU, CurrentDisplay, debug, err, FHeight, and SET_PRINT_MID.
isrcrash()
EXTERNC void isrcrash (TrapFrame * regs)
TriggerUserModeCrash()
void TriggerUserModeCrash (TrapFrame * regs)
Definition at line 58 of file UserCrashHandler.cpp.
 {
     switch (INT_NUM)
     {
     case ISR_DivideByZero:
     {
         err("Division by zero in an user-mode thread %s(%d) on CPU %ld.", SysGetCurrentThread()->Name, SysGetCurrentThread()->ID, rdmsr(MSR_FS_BASE));
         // TODO: signal the application to stop.
         SysGetCurrentThread()->Status = Terminated;
         break;
     }
     case ISR_Debug:
     {
         break;
     }
     case ISR_NonMaskableInterrupt:
     {
         break;
     }
     case ISR_Breakpoint:
     {
         break;
     }
     case ISR_Overflow:
     {
         break;
     }
     case ISR_BoundRange:
     {
         break;
     }
     case ISR_InvalidOpcode:
     {
         err("Invalid opcode in an user-mode thread %s(%d) on CPU %ld.", SysGetCurrentThread()->Name, SysGetCurrentThread()->ID, rdmsr(MSR_FS_BASE));
         // TODO: signal the application to stop.
         SysGetCurrentThread()->Status = Terminated;
         break;
     }
     case ISR_DeviceNotAvailable:
     {
         break;
     }
     case ISR_DoubleFault:
     {
         break;
     }
     case ISR_CoprocessorSegmentOverrun:
     {
         break;
     }
     case ISR_InvalidTSS:
     {
         SelectorErrorCode SelCode = {.raw = ERROR_CODE};
         break;
     }
     case ISR_SegmentNotPresent:
     {
         SelectorErrorCode SelCode = {.raw = ERROR_CODE};
         break;
     }
     case ISR_StackSegmentFault:
     {
         err("Stack Segment Fault caused by an user-mode thread %s(%d) at %#lx on CPU %ld.", SysGetCurrentThread()->Name, SysGetCurrentThread()->ID, RIP, rdmsr(MSR_FS_BASE));
         // TODO: signal the application to stop.
         SysGetCurrentThread()->Status = Terminated;
         break;
     }
     case ISR_GeneralProtectionFault:
     {
         err("General Protection Fault caused by an user-mode thread %s(%d) at %#lx on CPU %ld.", SysGetCurrentThread()->Name, SysGetCurrentThread()->ID, RIP, rdmsr(MSR_FS_BASE));
         // TODO: signal the application to stop.
         SysGetCurrentThread()->Status = Terminated;
         break;
     }
     case ISR_PageFault:
     {
         err("Page fault caused by an user-mode thread %s(%d) on CPU %ld.", SysGetCurrentThread()->Name, SysGetCurrentThread()->ID, rdmsr(MSR_FS_BASE));
         uint64_t addr = readcr2().raw;
         debug("Page fault at address %#llx", addr);
         PageFaultErrorCode params = {.raw = (uint32_t)ERROR_CODE};
         err("\nPage: %s\nWrite Operation: %s\nProcessor Mode: %s\nCPU Reserved Bits: %s\nCaused By An Instruction Fetch: %s\nDescription: %s",
             params.P ? "Present" : "Not Present",
             params.W ? "Read-Only" : "Read-Write",
             params.U ? "User-Mode" : "Kernel-Mode",
             params.R ? "Reserved" : "Unreserved",
             params.I ? "Yes" : "No",
             ERROR_CODE & 0x00000008 ? "One or more page directory entries contain reserved bits which are set to 1." : pagefault_message[ERROR_CODE & 0b111]);
         // TODO: signal the application to stop.
         SysGetCurrentThread()->Status = Terminated;
         break;
     }
     case ISR_x87FloatingPoint:
     {
         break;
     }
     case ISR_AlignmentCheck:
     {
         break;
     }
     case ISR_MachineCheck:
     {
         break;
     }
     case ISR_SIMDFloatingPoint:
     {
         break;
     }
     case ISR_Virtualization:
     {
         break;
     }
     case ISR_Security:
     {
         break;
     }
     default:
     {
         break;
     }
     }
 #ifdef DEBUG
     CurrentDisplay->SetPrintColor(0xFF0000);
     if (CurrentTaskingMode == TaskingMode::Mono)
         printf_("Usermode task ");
     else
         printf_("Usermode thread ");
     printf_("%s(%ld) crashed on CPU %ld! Check the serial port (COM1) for more info.\n", SysGetCurrentThread()->Name, SysGetCurrentThread()->ID, rdmsr(MSR_FS_BASE));
 #endif
     STI;
     err("Launching usermode crash handler...");
     if (CurrentTaskingMode == TaskingMode::Mono)
     {
         TrapFrame *tf = (TrapFrame *)UserAllocator->Malloc(sizeof(TrapFrame));
         memcpy(tf, regs, sizeof(TrapFrame));
         Tasking::monot->PopTask(true);
         SysCreateProcessFromFile("/system/umc", (uint64_t)tf, 0, ELEVATION::User);
         Tasking::monot->PushTask(0);
     }
     else
     {
         TrapFrame *tf = (TrapFrame *)UserAllocator->Malloc(sizeof(TrapFrame));
         memcpy(tf, regs, sizeof(TrapFrame));
         SysCreateProcessFromFile("/system/umc", (uint64_t)tf, 0, ELEVATION::User);
     }
 }
References addr, CurrentDisplay, CurrentTaskingMode, debug, err, ERROR_CODE, ID, INT_NUM, ISR_AlignmentCheck, ISR_BoundRange, ISR_Breakpoint, ISR_CoprocessorSegmentOverrun, ISR_Debug, ISR_DeviceNotAvailable, ISR_DivideByZero, ISR_DoubleFault, ISR_GeneralProtectionFault, ISR_InvalidOpcode, ISR_InvalidTSS, ISR_MachineCheck, ISR_NonMaskableInterrupt, ISR_Overflow, ISR_PageFault, ISR_Security, ISR_SegmentNotPresent, ISR_SIMDFloatingPoint, ISR_StackSegmentFault, ISR_Virtualization, ISR_x87FloatingPoint, Xalloc::AllocatorV1::Malloc(), memcpy(), Mono, Tasking::monot, MSR_FS_BASE, pagefault_message, printf_(), CR2::raw, PageFaultErrorCode::raw, SelectorErrorCode::raw, rdmsr(), readcr2(), RIP, TCB::Status, STI, SysCreateProcessFromFile(), SysGetCurrentThread(), Terminated, User, and UserAllocator.
Referenced by __attribute__().