Fennix Project: kernel/timer/PIT.c File Reference
PIT.c File Reference
#include "pit.h"
#include <debug.h>
#include <io.h>
#include "../timer.h"
Functions
uint32_t get_freq ()
void init_pit ()
void pit_wait (uint32_t miliseconds)
uint64_t pit_get_uptime ()
void pit_oneshot (uint32_t Vector, uint64_t Miliseconds)
Variables
bool PIC_initialized = false
uint64_t TimeSinceBoot = 0
const uint32_t freq = 1193182
uint16_t hertz = 1000
Function Documentation
get_freq()
uint32_t get_freq ()
Definition at line 11 of file PIT.c.
 {
     return freq;
 }
References freq.
Referenced by get_timer_clock().
init_pit()
void init_pit ()
Definition at line 22 of file PIT.c.
 {
     trace("Initializing PIT timer");
     uint32_t divisor = freq / hertz;
     outb(PIT_CMD, CMD_BINARY | CMD_MODE3 | CMD_RW_BOTH | CMD_COUNTER0);
     outb(PIT_COUNTER0, divisor);
     outb(PIT_COUNTER0, divisor >> 8);
     PIC_initialized = true;
 }
References CMD_BINARY, CMD_COUNTER0, CMD_MODE3, CMD_RW_BOTH, freq, hertz, outb, PIC_initialized, PIT_CMD, PIT_COUNTER0, and trace.
Referenced by init_timer().
pit_get_uptime()
uint64_t pit_get_uptime ()
Definition at line 45 of file PIT.c.
 {
     return TimeSinceBoot;
 }
References TimeSinceBoot.
pit_oneshot()
void pit_oneshot (uint32_t Vector, uint64_t Miliseconds)
Definition at line 50 of file PIT.c.
 {
     err("PIT One-Shot mode is not implemented!");
 }
References err.
Referenced by TimerOneShot().
pit_wait()
void pit_wait (uint32_t miliseconds)
Definition at line 32 of file PIT.c.
 {
     uint32_t now = ticks;
     ++miliseconds;
     if (ticks <= 0)
     {
         err("PIT timer is not enabled!!");
     }
     else
         while (ticks - now < miliseconds)
             ;
 }
References err, and ticks.
Referenced by msleep(), nsleep(), sleep(), and usleep().
Variable Documentation
freq
const uint32_t freq = 1193182
Definition at line 8 of file PIT.c.
Referenced by get_freq(), and init_pit().
hertz
uint16_t hertz = 1000
Definition at line 9 of file PIT.c.
Referenced by init_pit().
PIC_initialized
bool PIC_initialized = false
Definition at line 6 of file PIT.c.
Referenced by init_pit(), init_timer(), msleep(), nsleep(), sleep(), TimerOneShot(), and usleep().
TimeSinceBoot
uint64_t TimeSinceBoot = 0
Definition at line 7 of file PIT.c.
Referenced by pit_get_uptime().