Fennix Project: kernel/cpu/gdt.h File Reference
gdt.h File Reference
#include <types.h>
#include <cputables.h>
Macros
#define GDT_KERNEL_CODE offsetof(GlobalDescriptorTableEntries, Code)
#define GDT_KERNEL_DATA offsetof(GlobalDescriptorTableEntries, Data)
#define GDT_USER_DATA (offsetof(GlobalDescriptorTableEntries, UserData) | 3)
#define GDT_USER_CODE (offsetof(GlobalDescriptorTableEntries, UserCode) | 3)
#define GDT_TSS (offsetof(GlobalDescriptorTableEntries, TaskStateSegment) | 3)
Functions
EXTERNC void init_gdt ()
EXTERNC void init_tss ()
EXTERNC void CreateNewTSS (int CPUCore)
Variables
GlobalDescriptorTableDescriptor gdt
TaskStateSegment * tss
Macro Definition Documentation
GDT_KERNEL_CODE
#define GDT_KERNEL_CODE offsetof(GlobalDescriptorTableEntries, Code)
Definition at line 7 of file gdt.h.
GDT_KERNEL_DATA
#define GDT_KERNEL_DATA offsetof(GlobalDescriptorTableEntries, Data)
Definition at line 8 of file gdt.h.
GDT_TSS
#define GDT_TSS (offsetof(GlobalDescriptorTableEntries, TaskStateSegment) | 3)
Definition at line 11 of file gdt.h.
GDT_USER_CODE
#define GDT_USER_CODE (offsetof(GlobalDescriptorTableEntries, UserCode) | 3)
Definition at line 10 of file gdt.h.
GDT_USER_DATA
#define GDT_USER_DATA (offsetof(GlobalDescriptorTableEntries, UserData) | 3)
Definition at line 9 of file gdt.h.
Function Documentation
CreateNewTSS()
EXTERNC void CreateNewTSS (int CPUCore)
Definition at line 68 of file GDT.c.
 {
     LOCK(tss_lock);
     trace("initializing task state segment for CPU %d", CPUCore);
     tss = (TaskStateSegment *)kmalloc(sizeof(TaskStateSegment));
     uint64_t tss_base = (uint64_t)&tss[CPUCore];
     gdt.Entries->TaskStateSegment.Length = tss_base + sizeof(tss[CPUCore]);
     gdt.Entries->TaskStateSegment.Low = (uint16_t)(tss_base & 0xFFFF);
     gdt.Entries->TaskStateSegment.Middle = (uint8_t)((tss_base >> 16) & 0xFF);
     gdt.Entries->TaskStateSegment.High = (uint8_t)((tss_base >> 24) & 0xFF);
     gdt.Entries->TaskStateSegment.Upper32 = (uint32_t)((tss_base >> 32) & 0xFFFFFFFF);
     gdt.Entries->TaskStateSegment.Flags1 = 0b10001001;
     gdt.Entries->TaskStateSegment.Flags2 = 0b00000000;
     (&tss[CPUCore])->IOMapBaseAddressOffset = sizeof(TaskStateSegment);
     ltr(GDT_TSS);
     (&tss[CPUCore])->StackPointer[0] = (uint64_t)kernel_stack;
     (&tss[CPUCore])->InterruptStackTable[0] = (uint64_t)RequestPage(); // exceptions
     (&tss[CPUCore])->InterruptStackTable[1] = (uint64_t)RequestPage(); // nmi
     (&tss[CPUCore])->InterruptStackTable[2] = (uint64_t)RequestPage(); // page fault, double fault, general protection fault, etc...
     UNLOCK(tss_lock);
 }
References gdt, GDT_TSS, kernel_stack, kmalloc, LOCK, ltr(), RequestPage(), trace, tss, and UNLOCK.
init_gdt()
EXTERNC void init_gdt ()
Definition at line 17 of file GDT.c.
 {
     trace("Setting up GDT...");
     lgdt(gdt);
     asm volatile("movq %%rsp, %%rax\n"
                  "pushq $16\n"
                  "pushq %%rax\n"
                  "pushfq\n"
                  "pushq $8\n"
                  "pushq $1f\n"
                  "iretq\n"
                  "1:\n"
                  "movw $16, %%ax\n"
                  "movw %%ax, %%ds\n"
                  "movw %%ax, %%es\n"
                  "movw $0x1b, %%ax\n"
                  "movw %%ax, %%fs\n"
                  "movw %%ax, %%gs\n" ::
                      : "memory", "rax");
     debug("KC:%#llx|KD:%#llx|UD:%#llx|UC:%#llx|TSS:%#llx", GDT_KERNEL_CODE, GDT_KERNEL_DATA, GDT_USER_DATA, GDT_USER_CODE, GDT_TSS);
     debug("KC:%d|KD:%d|UD:%d|UC:%d|TSS:%d", GDT_KERNEL_CODE, GDT_KERNEL_DATA, GDT_USER_DATA, GDT_USER_CODE, GDT_TSS);
 }
References debug, gdt, GDT_KERNEL_CODE, GDT_KERNEL_DATA, GDT_TSS, GDT_USER_CODE, GDT_USER_DATA, lgdt(), and trace.
Referenced by KernelInit().
init_tss()
EXTERNC void init_tss ()
Definition at line 43 of file GDT.c.
 {
     trace("initializing tss");
     tss = (TaskStateSegment *)kcalloc(bootparams->smp.CPUCount, sizeof(TaskStateSegment));
     uint64_t tss_base = (uint64_t)&tss[0];
     gdt.Entries->TaskStateSegment.Length = tss_base + sizeof(tss[0]);
     gdt.Entries->TaskStateSegment.Low = (uint16_t)(tss_base & 0xFFFF);
     gdt.Entries->TaskStateSegment.Middle = (uint8_t)((tss_base >> 16) & 0xFF);
     gdt.Entries->TaskStateSegment.High = (uint8_t)((tss_base >> 24) & 0xFF);
     gdt.Entries->TaskStateSegment.Upper32 = (uint32_t)((tss_base >> 32) & 0xFFFFFFFF);
     gdt.Entries->TaskStateSegment.Flags1 = 0b10001001;
     gdt.Entries->TaskStateSegment.Flags2 = 0b00000000;
     (&tss[0])->IOMapBaseAddressOffset = sizeof(TaskStateSegment);
     (&tss[0])->StackPointer[0] = (uint64_t)RequestPage();
     (&tss[0])->InterruptStackTable[0] = (uint64_t)RequestPage(); // exceptions
     (&tss[0])->InterruptStackTable[1] = (uint64_t)RequestPage(); // nmi
     (&tss[0])->InterruptStackTable[2] = (uint64_t)RequestPage(); // page fault, double fault, general protection fault, etc...
     ltr(GDT_TSS);
     asm volatile("mov %%rsp, %0"
                  : "=r"((&tss[0])->StackPointer[0]));
 }
References bootparams, GBPSMP::CPUCount, gdt, GDT_TSS, kcalloc, ltr(), RequestPage(), _GlobalBootParams::smp, trace, and tss.
Referenced by KernelInit().
Variable Documentation
gdt
GlobalDescriptorTableDescriptor gdt
Definition at line 15 of file GDT.c.
Referenced by CreateNewTSS(), init_gdt(), init_tss(), and lgdt().
tss
TaskStateSegment* tss
Definition at line 41 of file GDT.c.
Referenced by CreateNewTSS(), and init_tss().