Fennix Project: NetworkUDP::UDP Class Reference
NetworkUDP::UDP Class Reference
#include <NetworkController.hpp>
Public Member Functions
NetworkInterfaceManager::DeviceInterface * GetInterface ()
UDP (NetworkIPv4::IPv4 *ipv4, NetworkInterfaceManager::DeviceInterface *Interface)
~UDP ()
virtual Socket * Connect (InternetProtocol4 IP, uint16_t Port)
virtual Socket * Listen (uint16_t Port)
virtual void Disconnect (Socket *Socket)
virtual void Send (Socket *Socket, uint8_t *Data, uint64_t Length)
virtual void Bind (Socket *Socket, UDPEvents *EventHandler)
virtual bool OnIPv4PacketReceived (InternetProtocol4 SourceIP, InternetProtocol4 DestinationIP, uint8_t *Data, uint64_t Length)
Public Member Functions inherited from NetworkIPv4::IPv4Events
uint8_t GetProtocol ()
Private Attributes
NetworkIPv4::IPv4 * ipv4
NetworkInterfaceManager::DeviceInterface * Interface
Additional Inherited Members
Protected Member Functions inherited from NetworkIPv4::IPv4Events
IPv4Events (IPv4Protocols Protocol)
~IPv4Events ()
Detailed Description
Definition at line 636 of file NetworkController.hpp.
Constructor & Destructor Documentation
UDP()
NetworkUDP::UDP::UDP (NetworkIPv4::IPv4 * ipv4, NetworkInterfaceManager::DeviceInterface * Interface)
Definition at line 20 of file UserDatagramProtocol.cpp.
                                                                                      : NetworkIPv4::IPv4Events(NetworkIPv4::PROTOCOL_UDP)
     {
         netdbg("UDP: Initializing.");
         this->ipv4 = ipv4;
         this->Interface = Interface;
     }
References Interface, ipv4, and netdbg.
~UDP()
NetworkUDP::UDP::~UDP ()
Definition at line 27 of file UserDatagramProtocol.cpp.
 {}
Member Function Documentation
Bind()
void NetworkUDP::UDP::Bind (Socket * Socket, UDPEvents * EventHandler) virtual
Definition at line 71 of file UserDatagramProtocol.cpp.
 { Socket->EventHandler = EventHandler; }
References NetworkUDP::Socket::EventHandler.
Referenced by NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
Connect()
Socket * NetworkUDP::UDP::Connect (InternetProtocol4 IP, uint16_t Port) virtual
Definition at line 31 of file UserDatagramProtocol.cpp.
     {
         netdbg("UDP: Connecting to %d.%d.%d.%d:%d", IP.Address[0], IP.Address[1], IP.Address[2], IP.Address[3], Port);
         Socket *socket = new Socket(this);
         socket->RemoteIP = IP;
         socket->RemotePort = Port;
         socket->LocalPort = UsuablePort++; // TODO: track ports
         socket->LocalIP = Interface->IP;
         socket->LocalPort = __builtin_bswap16(socket->LocalPort);
         socket->RemotePort = __builtin_bswap16(socket->RemotePort);
         RegisteredEvents.push_back({.UDPSocket = socket, .Port = socket->LocalPort});
         return socket;
     }
References InternetProtocol4::Address, Interface, NetworkInterfaceManager::DeviceInterface::IP, NetworkUDP::Socket::LocalIP, NetworkUDP::Socket::LocalPort, netdbg, NetworkUDP::RegisteredEvents, NetworkUDP::Socket::RemoteIP, NetworkUDP::Socket::RemotePort, and NetworkUDP::UsuablePort.
Referenced by NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
Disconnect()
void NetworkUDP::UDP::Disconnect (Socket * Socket) virtual
Definition at line 51 of file UserDatagramProtocol.cpp.
     {
         warn("Not implemented.");
     }
References warn.
GetInterface()
NetworkInterfaceManager::DeviceInterface* NetworkUDP::UDP::GetInterface () inline
Definition at line 643 of file NetworkController.hpp.
 { return this->Interface; }
References Interface.
Listen()
Socket * NetworkUDP::UDP::Listen (uint16_t Port) virtual
Definition at line 45 of file UserDatagramProtocol.cpp.
     {
         warn("Not implemented.");
         return nullptr;
     }
References warn.
OnIPv4PacketReceived()
bool NetworkUDP::UDP::OnIPv4PacketReceived (InternetProtocol4 SourceIP, InternetProtocol4 DestinationIP, uint8_t * Data, uint64_t Length) virtual
Reimplemented from NetworkIPv4::IPv4Events.
Definition at line 73 of file UserDatagramProtocol.cpp.
     {
         netdbg("UDP: Received %d bytes from %d.%d.%d.%d", Length, SourceIP.Address[0], SourceIP.Address[1], SourceIP.Address[2], SourceIP.Address[3]);
         if (Length < sizeof(UDPHeader))
             return false;
         UDPHeader *udp = (UDPHeader *)Data;
         netdbg("UDP: SP:%d | DP:%d | L:%d | CHK:%#x", b16(udp->SourcePort), b16(udp->DestinationPort), b16(udp->Length), b16(udp->Checksum));
         Socket *GoodSocket = nullptr;
         foreach (auto var in RegisteredEvents)
         {
             netdbg("UDP->SKT[]: LP:%d | LIP:%d.%d.%d.%d | RP:%d | RIP:%d.%d.%d.%d | LST:%d",
                    b16(var.UDPSocket->LocalPort),
                    var.UDPSocket->LocalIP.Address[0], var.UDPSocket->LocalIP.Address[1], var.UDPSocket->LocalIP.Address[2], var.UDPSocket->LocalIP.Address[3],
                    b16(var.UDPSocket->RemotePort),
                    var.UDPSocket->RemoteIP.Address[0], var.UDPSocket->RemoteIP.Address[1], var.UDPSocket->RemoteIP.Address[2], var.UDPSocket->RemoteIP.Address[3],
                    b16(var.UDPSocket->Listening));
             if (var.UDPSocket->LocalPort == udp->DestinationPort &&
                 var.UDPSocket->LocalIP == DestinationIP &&
                 var.UDPSocket->Listening == true)
             {
                 var.UDPSocket->Listening = false;
                 var.UDPSocket->RemotePort = b16(udp->SourcePort);
                 var.UDPSocket->RemoteIP = SourceIP;
                 netdbg("UDP: E1");
                 return true;
             }
             GoodSocket = var.UDPSocket;
         }
         if (GoodSocket)
             GoodSocket->EventHandler->OnUDPPacketReceived(GoodSocket, ((UDPPacket *)Data)->Data, Length);
         netdbg("UDP: E0 (Success)");
         return false;
     }
References InternetProtocol4::Address, b16, NetworkUDP::UDPHeader::Checksum, Data, NetworkUDP::UDPHeader::DestinationPort, Length, NetworkUDP::UDPHeader::Length, netdbg, NetworkUDP::RegisteredEvents, and NetworkUDP::UDPHeader::SourcePort.
Send()
void NetworkUDP::UDP::Send (Socket * Socket, uint8_t * Data, uint64_t Length) virtual
Definition at line 56 of file UserDatagramProtocol.cpp.
     {
         netdbg("UDP: Sending %d bytes to %d.%d.%d.%d:%d", Length, Socket->RemoteIP.Address[0], Socket->RemoteIP.Address[1], Socket->RemoteIP.Address[2], Socket->RemoteIP.Address[3], Socket->RemotePort);
         uint16_t TotalLength = Length + sizeof(UDPHeader);
         UDPPacket *packet = (UDPPacket *)kmalloc(TotalLength);
         packet->Header.SourcePort = Socket->LocalPort;
         packet->Header.DestinationPort = Socket->RemotePort;
         packet->Header.Length = b16(TotalLength);
         memcpy(packet->Data, Data, Length);
         packet->Header.Checksum = 0; // I totaly should do this. Some devices may require it.
         // packet->Header.Checksum = CalculateChecksum((uint16_t *)packet, TotalLength);
         this->ipv4->Send((uint8_t *)packet, TotalLength, 0x11, Socket->RemoteIP);
         kfree(packet);
     }
References InternetProtocol4::Address, b16, Data, ipv4, kfree, kmalloc, Length, NetworkUDP::Socket::LocalPort, memcpy(), netdbg, NetworkUDP::Socket::RemoteIP, NetworkUDP::Socket::RemotePort, and NetworkIPv4::IPv4::Send().
Referenced by NetworkDHCP::DHCP::Request().
Field Documentation
Interface
NetworkInterfaceManager::DeviceInterface* NetworkUDP::UDP::Interface private
Definition at line 640 of file NetworkController.hpp.
Referenced by Connect(), GetInterface(), and UDP().
ipv4
NetworkIPv4::IPv4* NetworkUDP::UDP::ipv4 private
Definition at line 639 of file NetworkController.hpp.
Referenced by Send(), and UDP().
The documentation for this class was generated from the following files:
kernel/network/NetworkController.hpp
kernel/network/UserDatagramProtocol.cpp