Fennix Project: NetworkICMPv4::ICMPv4 Class Reference
NetworkICMPv4::ICMPv4 Class Reference
#include <NetworkController.hpp>
Public Member Functions
NetworkInterfaceManager::DeviceInterface * GetInterface ()
ICMPv4 (NetworkInterfaceManager::DeviceInterface *Interface)
~ICMPv4 ()
void Send ()
void Receive (ICMPPacket *Packet)
Private Attributes
NetworkInterfaceManager::DeviceInterface * Interface
Detailed Description
Definition at line 554 of file NetworkController.hpp.
Constructor & Destructor Documentation
ICMPv4()
NetworkICMPv4::ICMPv4::ICMPv4 (NetworkInterfaceManager::DeviceInterface * Interface)
Definition at line 5 of file InternetControlMessageProtocol.cpp.
 { this->Interface = Interface; }
References Interface.
~ICMPv4()
NetworkICMPv4::ICMPv4::~ICMPv4 ()
Definition at line 6 of file InternetControlMessageProtocol.cpp.
 {}
Member Function Documentation
GetInterface()
NetworkInterfaceManager::DeviceInterface* NetworkICMPv4::ICMPv4::GetInterface () inline
Definition at line 560 of file NetworkController.hpp.
 { return this->Interface; }
References Interface.
Receive()
void NetworkICMPv4::ICMPv4::Receive (ICMPPacket * Packet)
Definition at line 13 of file InternetControlMessageProtocol.cpp.
     {
         if (Packet->Header.Type == ICMPv4Type::TYPE_ECHO)
         {
             // TODO: This probably doesn't work
             netdbg("ICMPv4: Echo Request");
             Packet->Header.Type = ICMPv4Type::TYPE_ECHO_REPLY;
             Packet->Header.Code = 0x0;
             Packet->Header.Checksum = CalculateChecksum((uint16_t *)Packet, sizeof(ICMPHeader));
             this->Interface->Send((uint8_t *)Packet, sizeof(ICMPHeader) + 0);
         }
         else
         {
             netdbg("ICMPv4: Unknown type %d", Packet->Header.Type);
         }
     }
References CalculateChecksum(), Interface, netdbg, PS2Mouse::Packet, NetworkInterfaceManager::DeviceInterface::Send(), NetworkICMPv4::TYPE_ECHO, and NetworkICMPv4::TYPE_ECHO_REPLY.
Send()
void NetworkICMPv4::ICMPv4::Send ()
Definition at line 8 of file InternetControlMessageProtocol.cpp.
     {
         fixme("Unimplemented");
     }
References fixme().
Field Documentation
Interface
NetworkInterfaceManager::DeviceInterface* NetworkICMPv4::ICMPv4::Interface private
Definition at line 557 of file NetworkController.hpp.
Referenced by GetInterface(), ICMPv4(), and Receive().
The documentation for this class was generated from the following files:
kernel/network/NetworkController.hpp
kernel/network/InternetControlMessageProtocol.cpp