Fennix Project: kernel/include/string.h File Reference
string.h File Reference
#include <stdint.h>
#include <stddef.h>
Functions
int isdigit (int c)
int isspace (int c)
int isempty (char *str)
unsigned int isdelim (char c, char *delim)
void * memcpy (void *__restrict__ dest, const void *__restrict__ src, size_t n)
void * memset (void *dest, int data, size_t nbytes)
void * memmove (void *dest, const void *src, size_t n)
int memcmp (const void *vl, const void *vr, size_t n)
long unsigned strlen (const char s[])
int strncmp (const char *s1, const char *s2, unsigned long n)
char * strcat (char *destination, const char *source)
char * strcpy (char *destination, const char *source)
char * strncpy (char *destination, const char *source, unsigned long num)
int strcmp (const char *l, const char *r)
char * strstr (const char *haystack, const char *needle)
char * strdup (const char *String)
char * strchr (const char *String, int Char)
char * strrchr (const char *String, int Char)
int strncasecmp (const char *lhs, const char *rhs, long unsigned int Count)
int strcasecmp (const char *lhs, const char *rhs)
char * strtok (char *__restrict__ src, const char *__restrict__ delim)
Function Documentation
isdelim()
unsigned int isdelim (char c, char * delim)
Definition at line 34 of file string.c.
 {
     while (*delim != '\0')
     {
         if (c == *delim)
             return 1;
         delim++;
     }
     return 0;
 }
Referenced by strtok().
isdigit()
int isdigit (int c)
Definition at line 139 of file String.c.
 {
     return c >= '0' && c <= '9';
 }
Referenced by atof(), and vsscanf().
isempty()
int isempty (char * str)
Definition at line 149 of file String.c.
 {
     if (strlen(str) == 0)
         return 1;
     while (*str != '\0')
     {
         if (!isspace(*str))
             return 0;
         str++;
     }
     return 1;
 }
References isspace(), and strlen().
Referenced by FileSystem::Virtual::Create(), FileSystem::FileExists(), FileSystem::Virtual::Mount(), and FileSystem::Mount::MountFileSystem().
isspace()
int isspace (int c)
Definition at line 144 of file String.c.
 {
     return c == ' ' || c == '\t' || c == '\r' || c == '\n' || c == '\f' || c == '\v';
 }
Referenced by isempty_1(), and vsscanf().
memcmp()
int memcmp (const void * vl, const void * vr, size_t n)
Definition at line 39 of file String.c.
 {
     const unsigned char *l = vl, *r = vr;
     for (; n && *l == *r; n--, l++, r++)
         ;
     return n ? *l - *r : 0;
 }
Referenced by do_libs_test(), ACPI::DSDT::DSDT(), and FileSystem::USTAR::USTAR().
memcpy()
void* memcpy (void *__restrict__ dest, const void *__restrict__ src, size_t n)
Definition at line 5 of file String.c.
 {
     unsigned char *d = (unsigned char *)dest;
     const unsigned char *c = (const unsigned char *)src;
     for (size_t i = 0; i < n; i++)
         d[i] = c[i];
     return dest;
 }
Referenced by DiskManager::Partition::AddPartition(), CheckRunningUnderVM(), FileSystem::Virtual::Create(), Tasking::Multitasking::CreateProcess(), Tasking::Monotasking::CreateTask(), Tasking::Multitasking::CreateThread(), do_libs_test(), EnableCPUFeatures(), FileSystem::EXT2::EXT2(), fillemptycbs(), FileSystem::Virtual::GetNodeFromPath(), InitializeCPU(), internal_filegetchildren(), internal_fileOpen(), internal_fileOpenWithParent(), isrcrash(), Driver::KernelDriver::LoadKernelDriverFromFile(), FileSystem::ReadFSFunction(), PS2Mouse::ReadFSFunction(), realloc(), NetworkEthernet::Ethernet::Send(), SymmetricMultiprocessing::SMP::SMP(), and SysCreateProcessFromFile().
memmove()
void* memmove (void * dest, const void * src, size_t n)
Definition at line 22 of file String.c.
 {
     unsigned char *dst = (unsigned char *)dest;
     const unsigned char *srcc = (const unsigned char *)src;
     if (dst < srcc)
     {
         for (size_t i = 0; i < n; i++)
             dst[i] = srcc[i];
     }
     else
     {
         for (size_t i = n; i != 0; i--)
             dst[i - 1] = srcc[i - 1];
     }
     return dest;
 }
Referenced by cwk_path_output_sized(), do_libs_test(), MonotonLib::mtl::Scroll(), and FileSystem::USTAR::USTAR().
memset()
void* memset (void * dest, int data, size_t nbytes)
Definition at line 14 of file String.c.
 {
     unsigned char *buf = (unsigned char *)dest;
     for (size_t i = 0; i < nbytes; i++)
         buf[i] = (unsigned char)data;
     return dest;
 }
Referenced by calloc(), clearbuffer(), Tasking::Monotasking::CreateTask(), Tasking::Multitasking::CreateThread(), do_libs_test(), Tasking::FreeTask(), HeapCalloc(), HeapMalloc(), HeapRealloc(), init_kernelpml(), InitializeCPU(), Driver::KernelDriver::LoadKernelDriverFromFile(), RTL8139::NetworkInterfaceController::NetworkInterfaceController(), FileSystem::ReadFSFunction(), and SysCreateProcessFromFile().
strcasecmp()
int strcasecmp (const char * lhs, const char * rhs)
Definition at line 184 of file string.c.
 {
     while (*lhs && (tolower(*lhs) == tolower(*rhs)))
     {
         lhs++;
         rhs++;
     }
     int lc = tolower(*lhs);
     int rc = tolower(*rhs);
     return lc - rc;
 }
strcat()
char* strcat (char * destination, const char * source)
Definition at line 68 of file String.c.
 {
     if ((destination == NULL) && (source == NULL))
         return NULL;
     char *start = destination;
     while (*start != '\0')
     {
         start++;
     }
     while (*source != '\0')
     {
         *start++ = *source++;
     }
     *start = '\0';
     return destination;
 }
Referenced by cpu_get_info(), FileSystem::Virtual::GetPathFromNode(), and ParseBuffer().
strchr()
char* strchr (const char * String, int Char)
Definition at line 144 of file string.c.
 {
     while (*String != (char)Char)
     {
         if (!*String++)
             return 0;
     }
     return (char *)String;
 }
Referenced by cag_option_find_by_letter(), and cwk_path_is_string_equal().
strcmp()
int strcmp (const char * l, const char * r)
Definition at line 115 of file String.c.
 {
     for (; *l == *r && *l; l++, r++)
         ;
     return *(unsigned char *)l - *(unsigned char *)r;
 }
Referenced by CheckRunningUnderVM(), FileSystem::Virtual::Create(), do_libs_test(), EnableCPUFeatures(), FileSystem::GetChild(), FileSystem::Virtual::GetNodeFromPath(), init_stivale2(), KernelInit(), KernelTask(), Driver::KernelDriver::LoadKernelDriverFromFile(), FileSystem::Virtual::Open(), ParseBuffer(), FileSystem::RemoveChild(), and SymmetricMultiprocessing::SMP::SMP().
strcpy()
char* strcpy (char * destination, const char * source)
Definition at line 85 of file String.c.
 {
     if (destination == NULL)
         return NULL;
     char *ptr = destination;
     while (*source != '\0')
     {
         *destination = *source;
         destination++;
         source++;
     }
     *destination = '\0';
     return ptr;
 }
Referenced by FileSystem::AddNewChild(), FileSystem::Virtual::CreateRoot(), internal_filefullpath(), loop(), FileSystem::Virtual::NormalizePath(), ParseBuffer(), and FileSystem::Virtual::Virtual().
strdup()
char* strdup (const char * String)
Definition at line 137 of file string.c.
 {
     char *OutBuffer = malloc(strlen((char *)String) + 1);
     strcpy(OutBuffer, String);
     return OutBuffer;
 }
strlen()
long unsigned strlen (const char s[])
Definition at line 60 of file String.c.
 {
     long unsigned i = 0;
     while (s[i] != '\0')
         ++i;
     return i;
 }
Referenced by append(), atoi(), backspace(), cag_option_get_print_indention(), cwk_path_change_extension(), cwk_path_change_root(), cwk_path_change_segment(), cwk_path_output(), FileSystem::EXT2::EXT2(), fputs(), FileSystem::Virtual::GetPathFromNode(), internal_filefullpath(), KernelInit(), loop(), FileSystem::Virtual::NormalizePath(), ParseBuffer(), serial_write_text(), trimwhitespace(), and FileSystem::USTAR::USTAR().
strncasecmp()
int strncasecmp (const char * lhs, const char * rhs, long unsigned int Count)
Definition at line 165 of file string.c.
 {
     while (Count--)
     {
         if (*lhs == 0 || *rhs == 0)
         {
             return *(unsigned char *)(lhs) - *(unsigned char *)(rhs);
         }
         if (tolower(*lhs) != tolower(*rhs))
         {
             return *(unsigned char *)(lhs) - *(unsigned char *)(rhs);
         }
         lhs++;
         rhs++;
     }
     return 0;
 }
strncmp()
int strncmp (const char * s1, const char * s2, unsigned long n)
Definition at line 53 of file string.c.
 {
     for (unsigned long i = 0; i < n; i++)
     {
         char c1 = s1[i], c2 = s2[i];
         if (c1 != c2)
             return c1 - c2;
         if (!c1)
             return 0;
     }
     return 0;
 }
Referenced by cag_option_find_by_name(), cwk_path_get_segment_type(), cwk_path_is_string_equal(), do_libs_test(), and ParseBuffer().
strncpy()
char* strncpy (char * destination, const char * source, unsigned long num)
Definition at line 100 of file String.c.
 {
     if (destination == NULL)
         return NULL;
     char *ptr = destination;
     while (*source && num--)
     {
         *destination = *source;
         destination++;
         source++;
     }
     *destination = '\0';
     return ptr;
 }
strrchr()
char* strrchr (const char * String, int Char)
Definition at line 154 of file string.c.
 {
     char *ret = 0;
     do
     {
         if (*String == (char)Char)
             ret = (char *)String;
     } while (*String++);
     return ret;
 }
strstr()
char* strstr (const char * haystack, const char * needle)
Definition at line 122 of file String.c.
 {
     const char *a = haystack, *b = needle;
     while (1)
     {
         if (!*b)
             return (char *)haystack;
         if (!*a)
             return NULL;
         if (*a++ != *b++)
         {
             a = ++haystack;
             b = needle;
         }
     }
 }
Referenced by init_stivale2(), initializeKernelFlags(), and KernelInit().
strtok()
char* strtok (char *__restrict__ src, const char *__restrict__ delim)