Fennix Project: FileSystem::FAT Class Reference
FileSystem::FAT Class Reference
#include <filesystem.h>
Data Structures
struct BIOSParameterBlock
Public Types
enum FatType { Unknown, FAT12, FAT16, FAT32 }
Public Member Functions
struct FileSystem::FAT::BIOSParameterBlock __attribute__ ((__packed__))
FatType GetFATType (BIOSParameterBlock *bpb)
FAT (void *partition)
~FAT ()
Detailed Description
Definition at line 347 of file filesystem.h.
Data Structure Documentation
FileSystem::FAT::BIOSParameterBlock
struct FileSystem::FAT::BIOSParameterBlock
Definition at line 359 of file filesystem.h.
Data Fields
uint16_t BytesPerSector The number of Bytes per sector (remember, all numbers are in the little-endian format).
uint32_t HiddenSectors Number of hidden sectors. (i.e. the LBA of the beginning of the partition).
uint8_t JumpBoot[3] The first three bytes EB 3C 90 disassemble to JMP SHORT 3C NOP. (The 3C value may be different.) The reason for this is to jump over the disk format information (the BPB and EBPB). Since the first sector of the disk is loaded into ram at location 0x0000:0x7c00 and executed, without this jump, the processor would attempt to execute data that isn't code. Even for non-bootable volumes, code matching this pattern (or using the E9 jump opcode) is required to be present by both Windows and OS X. To fulfil this requirement, an infinite loop can be placed here with the bytes EB FE 90.
uint8_t Media This Byte indicates the media descriptor type.
uint8_t NumberOfFATs Number of File Allocation Tables (FAT's) on the storage media. Often this value is 2.
uint16_t NumberOfHeads Number of heads or sides on the storage media.
uint8_t OEM[8] OEM identifier. The first 8 Bytes (3 - 10) is the version of DOS being used. The next eight Bytes 29 3A 63 7E 2D 49 48 and 43 read out the name of the version. The official FAT Specification from Microsoft says that this field is really meaningless and is ignored by MS FAT Drivers, however it does recommend the value "MSWIN4.1" as some 3rd party drivers supposedly check it and expect it to have that value. Older versions of dos also report MSDOS5.1, linux-formatted floppy will likely to carry "mkdosfs" here, and FreeDOS formatted disks have been observed to have "FRDOS5.1" here. If the string is less than 8 bytes, it is padded with spaces.
uint16_t ReservedSectors Number of reserved sectors. The boot record sectors are included in this value.
uint16_t RootDirectoryEntries Number of root directory entries (must be set so that the root directory occupies entire sectors).
uint16_t Sectors16 The total sectors in the logical volume. If this value is 0, it means there are more than 65535 sectors in the volume, and the actual count is stored in the Large Sector Count entry at 0x20.
uint32_t Sectors32 Large sector count. This field is set if there are more than 65535 sectors in the volume, resulting in a value which does not fit in the Number of Sectors entry at 0x13.
uint8_t SectorsPerCluster Number of sectors per cluster.
uint16_t SectorsPerFAT Number of sectors per FAT. FAT12/FAT16 only.
uint16_t SectorsPerTrack Number of sectors per track.
Member Enumeration Documentation
FatType
enum FileSystem::FAT::FatType
Enumerator
Unknown
FAT12
FAT16
FAT32
Definition at line 350 of file filesystem.h.
         {
             Unknown,
             FAT12,
             FAT16,
             FAT32
         };
Constructor & Destructor Documentation
FAT()
FileSystem::FAT::FAT (void * partition)
Definition at line 104 of file fat.cpp.
     {
         DiskManager::Partition::Part *Partition = (DiskManager::Partition::Part *)partition;
         void *buffer = RequestPage();
         Partition->Read(0, 1, buffer);
         switch (GetFATType((BIOSParameterBlock *)buffer))
         {
         case FAT12:
         // TODO: Implement reading and writing files
             debug("FAT12");
             mountfs->MountFileSystem(&fat, 0666, "stubfat12");
             break;
         case FAT16:
         // TODO: Implement reading and writing files
             debug("FAT16");
             mountfs->MountFileSystem(&fat, 0666, "stubfat16");
             break;
         case FAT32:
             debug("FAT32");
             // TODO: Implement reading and writing files
             mountfs->MountFileSystem(&fat, 0666, "stubfat32");
             break;
         default:
             break;
         }
         FreePage(buffer);
     }
References debug, FileSystem::fat, FAT12, FAT16, FAT32, FreePage(), GetFATType(), FileSystem::Mount::MountFileSystem(), mountfs, DiskManager::Partition::Part::Read(), and RequestPage().
~FAT()
FileSystem::FAT::~FAT ()
Definition at line 134 of file fat.cpp.
 { warn("Destroyed"); }
References warn.
Member Function Documentation
__attribute__()
struct FileSystem::FAT::BIOSParameterBlock FileSystem::FAT::__attribute__ ((__packed__))
GetFATType()
FAT::FatType FileSystem::FAT::GetFATType (BIOSParameterBlock * bpb)
Definition at line 25 of file fat.cpp.
     {
         if (bpb == nullptr || bpb == 0)
             return Unknown;
         if (bpb->BytesPerSector == 0)
             return Unknown;
         if (bpb->SectorsPerCluster == 0)
             return Unknown;
         if (bpb->JumpBoot[0] == 0xEB)
         {
             if (bpb->JumpBoot[2] != 0x90)
                 return Unknown;
         }
         else if (bpb->JumpBoot[0] != 0xE9)
             return Unknown;
         // TODO: https://en.wikipedia.org/wiki/Design_of_the_FAT_file_system#BPB20_OFS_0Ah
         if (bpb->Media != 0xF0 && bpb->Media < 0xF8)
             return Unknown;
         uint32_t Size;
         uint32_t Sectors;
         if (bpb->Sectors16 != 0)
             Size = bpb->Sectors16;
         else
             Size = bpb->Sectors32;
         if (bpb->Sectors16 != 0)
             Sectors = bpb->Sectors16;
         else
             Sectors = bpb->Sectors32;
         if (bpb->BytesPerSector != 512 && bpb->BytesPerSector != 1024 && bpb->BytesPerSector != 2048 && bpb->BytesPerSector != 4096)
             return Unknown;
         if (bpb->SectorsPerCluster * bpb->BytesPerSector > 32 * 1024)
             return Unknown;
         if (bpb->ReservedSectors == 0)
             return Unknown;
         if (bpb->NumberOfFATs < 2)
             return Unknown;
         uint32_t Clusters = (Sectors - (bpb->ReservedSectors + (bpb->NumberOfFATs * Size) + (((bpb->RootDirectoryEntries * 32) + (bpb->BytesPerSector - 1)) / bpb->BytesPerSector))) / bpb->SectorsPerCluster;
         if (Clusters < 4085)
         {
             debug("Detected FAT12");
             return FAT12;
         }
         else if (Clusters < 65525)
         {
             debug("Detected FAT16");
             return FAT16;
         }
         if (bpb->RootDirectoryEntries != 0)
         {
             debug("FAT12/16? (RootDirectoryEntries != 0)");
             return Unknown;
         }
         if (bpb->Sectors16 != 0)
         {
             debug("FAT12/16? (Sectors16 != 0)");
             return Unknown;
         }
         if (bpb->Sectors32 == 0)
         {
             debug("FAT12/16? (Sectors32 == 0)");
             return Unknown;
         }
         debug("OEM NAME: %c%c%c%c%c%c%c%c", bpb->OEM[0], bpb->OEM[1], bpb->OEM[2], bpb->OEM[3], bpb->OEM[4], bpb->OEM[5], bpb->OEM[6], bpb->OEM[7]);
         debug("JUMP BOOT: %c%c%c", bpb->JumpBoot[0], bpb->JumpBoot[1], bpb->JumpBoot[2]);
         return FAT32;
     }
References FileSystem::FAT::BIOSParameterBlock::BytesPerSector, debug, FAT12, FAT16, FAT32, FileSystem::FAT::BIOSParameterBlock::JumpBoot, FileSystem::FAT::BIOSParameterBlock::Media, FileSystem::FAT::BIOSParameterBlock::NumberOfFATs, FileSystem::FAT::BIOSParameterBlock::OEM, FileSystem::FAT::BIOSParameterBlock::ReservedSectors, FileSystem::FAT::BIOSParameterBlock::RootDirectoryEntries, Sectors, FileSystem::FAT::BIOSParameterBlock::Sectors16, FileSystem::FAT::BIOSParameterBlock::Sectors32, FileSystem::FAT::BIOSParameterBlock::SectorsPerCluster, and Unknown.
Referenced by FAT().
The documentation for this class was generated from the following files:
kernel/include/filesystem.h
kernel/fs/fat.cpp