Fennix Project: SymmetricMultiprocessing::SMP Class Reference
SymmetricMultiprocessing::SMP Class Reference
#include <smp.hpp>
Public Member Functions
SMP ()
~SMP ()
Detailed Description
Definition at line 34 of file smp.hpp.
Constructor & Destructor Documentation
SMP()
SymmetricMultiprocessing::SMP::SMP ()
Definition at line 172 of file SMP.cpp.
     {
         trace("Initializing symmetric multiprocessing (%d Cores)", madt->CPUCores);
         uint32_t rax, rbx, rcx, rdx;
         char HyperVendor[13];
         cpuid(0x40000000, &rax, &rbx, &rcx, &rdx);
         memcpy(HyperVendor + 0, &rbx, 4);
         memcpy(HyperVendor + 4, &rcx, 4);
         memcpy(HyperVendor + 8, &rdx, 4);
         HyperVendor[12] = '\0';
         debug("Hyper Vendor: %s", HyperVendor);
         if (!strcmp(HyperVendor, CPUID_VENDOR_VIRTUALBOX))
         {
             err("VirtualBox Hypervisor detected, disabling SMP support...");
             EnableCPUFeatures();
             return;
         }
         // TODO: VBox doesn't like this.
         for (size_t i = 0; i < madt->CPUCores; i++)
             if ((apic->Read(APIC::APIC::APIC_ID) >> 24) != madt->lapic[i]->ACPIProcessorId)
                 InitializeCPU(madt->lapic[i]);
             else
                 EnableCPUFeatures();
     }
References apic, APIC::APIC::APIC_ID, ACPI::MADT::CPUCores, cpuid(), CPUID_VENDOR_VIRTUALBOX, debug, EnableCPUFeatures(), err, InitializeCPU(), ACPI::MADT::lapic, madt, memcpy(), APIC::APIC::Read(), strcmp(), and trace.
~SMP()
SymmetricMultiprocessing::SMP::~SMP ()
Definition at line 200 of file SMP.cpp.
     {
     }
The documentation for this class was generated from the following files:
kernel/cpu/smp.hpp
kernel/cpu/SMP.cpp