Fennix Project: KernelSymbols::Symbols Class Reference
KernelSymbols::Symbols Class Reference
#include <symbols.hpp>
Data Structures
struct SymbolTable
Public Member Functions
Symbols ()
~Symbols ()
string GetSymbolFromAddress (uint64_t Address)
Detailed Description
Definition at line 6 of file symbols.hpp.
Data Structure Documentation
KernelSymbols::Symbols::SymbolTable
struct KernelSymbols::Symbols::SymbolTable
Definition at line 9 of file symbols.hpp.
Data Fields
uint64_t Address
char * FunctionName
Constructor & Destructor Documentation
Symbols()
KernelSymbols::Symbols::Symbols ()
Definition at line 20 of file Symbols.cpp.
     {
         Elf64_Ehdr *KernelHeader = (Elf64_Ehdr *)bootparams->kernel.file;
         Elf64_Shdr *ElfSections = (Elf64_Shdr *)(bootparams->kernel.file + KernelHeader->e_shoff);
         Elf64_Sym *ElfSymbols = nullptr;
         char *strtab = nullptr;
         for (uint64_t i = 0; i < KernelHeader->e_shnum; i++)
             switch (ElfSections[i].sh_type)
             {
             case SHT_SYMTAB:
                 ElfSymbols = (Elf64_Sym *)(bootparams->kernel.file + ElfSections[i].sh_offset);
                 TotalEntries = ElfSections[i].sh_size / sizeof(Elf64_Sym);
                 debug("Symbol table found, %d entries", TotalEntries);
                 break;
             case SHT_STRTAB:
                 if (KernelHeader->e_shstrndx == i)
                 {
                     debug("String table found, %d entries", ElfSections[i].sh_size);
                 }
                 else
                 {
                     strtab = (char *)bootparams->kernel.file + ElfSections[i].sh_offset;
                     debug("String table found, %d entries", ElfSections[i].sh_size);
                 }
                 break;
             }
         if (ElfSymbols != nullptr && strtab != nullptr)
         {
             size_t Index, MinimumIndex;
             for (size_t i = 0; i < TotalEntries - 1; i++)
             {
                 MinimumIndex = i;
                 for (Index = i + 1; Index < TotalEntries; Index++)
                     if (ElfSymbols[Index].st_value < ElfSymbols[MinimumIndex].st_value)
                         MinimumIndex = Index;
                 Elf64_Sym tmp = ElfSymbols[MinimumIndex];
                 ElfSymbols[MinimumIndex] = ElfSymbols[i];
                 ElfSymbols[i] = tmp;
             }
             while (ElfSymbols[0].st_value == 0)
             {
                 ElfSymbols++;
                 TotalEntries--;
             }
             trace("Symbol table loaded, %d entries (%ldKB)", TotalEntries, TO_KB(TotalEntries * sizeof(SymbolTable)));
             // TODO: broken?
             // SymTable = new SymbolTable[TotalEntries];
             SymTable = (SymbolTable *)KernelAllocator.RequestPages((TotalEntries * sizeof(SymbolTable)) / PAGE_SIZE + 1);
             // do_mem_test();
             for (size_t i = 0, g = TotalEntries; i < g; i++)
             {
                 SymTable[i].Address = ElfSymbols[i].st_value;
                 SymTable[i].FunctionName = &strtab[ElfSymbols[i].st_name];
             }
         }
         BS->IncreaseProgres();
     }
References KernelSymbols::Symbols::SymbolTable::Address, bootparams, BS, debug, elf64_hdr::e_shnum, elf64_hdr::e_shoff, elf64_hdr::e_shstrndx, kernel_file::file, KernelSymbols::Symbols::SymbolTable::FunctionName, BootScreen::Screen::IncreaseProgres(), _GlobalBootParams::kernel, KernelAllocator, PAGE_SIZE, SHT_STRTAB, SHT_SYMTAB, elf64_sym::st_name, elf64_sym::st_value, KernelSymbols::SymTable, TO_KB, KernelSymbols::TotalEntries, and trace.
~Symbols()
KernelSymbols::Symbols::~Symbols ()
Definition at line 83 of file Symbols.cpp.
     {
         // delete SymTable;
         KernelAllocator.FreePages(SymTable, (TotalEntries * sizeof(SymbolTable)) / PAGE_SIZE + 1);
     }
References KernelAllocator, PAGE_SIZE, KernelSymbols::SymTable, and KernelSymbols::TotalEntries.
Member Function Documentation
GetSymbolFromAddress()
string KernelSymbols::Symbols::GetSymbolFromAddress (uint64_t Address)
Definition at line 89 of file Symbols.cpp.
     {
         Symbols::SymbolTable Result{0, (char *)"<unknown>"};
         for (size_t i = 0; i < TotalEntries; i++)
             if (SymTable[i].Address <= Address && SymTable[i].Address > Result.Address)
                 Result = SymTable[i];
         return Result.FunctionName;
     }
References Address, KernelSymbols::Symbols::SymbolTable::FunctionName, KernelSymbols::SymTable, and KernelSymbols::TotalEntries.
Referenced by isrcrash(), operator new(), and operator new[]().
The documentation for this class was generated from the following files:
kernel/include/symbols.hpp
kernel/Symbols.cpp