Fennix Project: kernel/include/list.h File Reference
list.h File Reference
#include <types.h>
Data Structures
struct list_head
Macros
#define LIST_HEAD_INIT(name)
#define LIST_HEAD(name) struct list_head name = LIST_HEAD_INIT(name)
#define INIT_LIST_HEAD(ptr)
#define list_entry(ptr, type, member) ((type *)((char *)(ptr) - (unsigned long)(&((type *)0)->member)))
#define list_for_each(pos, head) for (pos = (head)->next; pos != (head); pos = pos->next)
#define list_for_each_safe(pos, pnext, head) for (pos = (head)->next, pnext = pos->next; pos != (head); pos = pnext, pnext = pos->next)
#define list_next_entry(pos, member) list_entry((pos)->member.next, typeof(*(pos)), member)
#define list_for_each_entry_continue(pos, head, member)
#define list_first_entry(ptr, type, member) list_entry((ptr)->next, type, member)
#define list_for_each_entry(pos, head, member)
#define list_for_each_entry_safe(pos, n, head, member)
Functions
static void list_init (struct list_head *list)
static void __list_add (struct list_head *add, struct list_head *prev, struct list_head *next)
static void __list_del (struct list_head *prev, struct list_head *next)
static void list_add (struct list_head *add, struct list_head *head)
static void list_add_tail (struct list_head *add, struct list_head *head)
static void list_del (struct list_head *entry)
static void list_del_init (struct list_head *entry)
static void list_replace (struct list_head *old, struct list_head *add)
static void list_splice (struct list_head *list, struct list_head *head)
static int list_is_first (const struct list_head *list, const struct list_head *head)
static int list_is_last (const struct list_head *list, const struct list_head *head)
static int list_empty (const struct list_head *head)
Data Structure Documentation
list_head
struct list_head
Definition at line 6 of file list.h.
Data Fields
struct list_head * next
struct list_head * prev
Macro Definition Documentation
INIT_LIST_HEAD
#define INIT_LIST_HEAD (ptr)
Value:
    do                       \
    {                        \
        (ptr)->next = (ptr); \
        (ptr)->prev = (ptr); \
    } while (0)
Definition at line 20 of file list.h.
list_entry
#define list_entry (ptr, type, member) ((type *)((char *)(ptr) - (unsigned long)(&((type *)0)->member)))
Definition at line 105 of file list.h.
list_first_entry
#define list_first_entry (ptr, type, member) list_entry((ptr)->next, type, member)
Definition at line 120 of file list.h.
list_for_each
#define list_for_each (pos, head) for (pos = (head)->next; pos != (head); pos = pos->next)
Definition at line 107 of file list.h.
list_for_each_entry
#define list_for_each_entry (pos, head, member)
Value:
    for (pos = list_first_entry(head, typeof(*pos), member); \
         &pos->member != (head);                             \
         pos = list_next_entry(pos, member))
Definition at line 123 of file list.h.
list_for_each_entry_continue
#define list_for_each_entry_continue (pos, head, member)
Value:
    for (pos = list_next_entry(pos, member);            \
         &pos->member != (head);                        \
         pos = list_next_entry(pos, member))
Definition at line 115 of file list.h.
list_for_each_entry_safe
#define list_for_each_entry_safe (pos, n, head, member)
Value:
    for (pos = list_first_entry(head, typeof(*pos), member), \
        n = list_next_entry(pos, member);                    \
         &pos->member != (head);                             \
         pos = n, n = list_next_entry(n, member))
Definition at line 128 of file list.h.
list_for_each_safe
#define list_for_each_safe (pos, pnext, head) for (pos = (head)->next, pnext = pos->next; pos != (head); pos = pnext, pnext = pos->next)
Definition at line 109 of file list.h.
LIST_HEAD
#define LIST_HEAD (name) struct list_head name = LIST_HEAD_INIT(name)
Definition at line 18 of file list.h.
LIST_HEAD_INIT
#define LIST_HEAD_INIT (name)
Value:
    {                        \
        &(name), &(name)     \
    }
Definition at line 13 of file list.h.
list_next_entry
#define list_next_entry (pos, member) list_entry((pos)->member.next, typeof(*(pos)), member)
Definition at line 112 of file list.h.
Function Documentation
__list_add()
static void __list_add (struct list_head * add, struct list_head * prev, struct list_head * next) inline static
Definition at line 33 of file list.h.
 {
     next->prev = add;
     add->next = next;
     add->prev = prev;
     prev->next = add;
 }
References list_head::next, and list_head::prev.
Referenced by list_add(), and list_add_tail().
__list_del()
static void __list_del (struct list_head * prev, struct list_head * next) inline static
Definition at line 41 of file list.h.
 {
     next->prev = prev;
     prev->next = next;
 }
References list_head::next, and list_head::prev.
Referenced by list_del(), and list_del_init().
list_add()
static void list_add (struct list_head * add, struct list_head * head) inline static
Definition at line 47 of file list.h.
 {
     __list_add(add, head, head->next);
 }
References __list_add(), and list_head::next.
list_add_tail()
static void list_add_tail (struct list_head * add, struct list_head * head) inline static
Definition at line 52 of file list.h.
 {
     __list_add(add, head->prev, head);
 }
References __list_add(), and list_head::prev.
list_del()
static void list_del (struct list_head * entry) inline static
Definition at line 57 of file list.h.
 {
     __list_del(entry->prev, entry->next);
 }
References __list_del(), list_head::next, and list_head::prev.
list_del_init()
static void list_del_init (struct list_head * entry) inline static
Definition at line 62 of file list.h.
 {
     __list_del(entry->prev, entry->next);
     INIT_LIST_HEAD(entry);
 }
References __list_del(), INIT_LIST_HEAD, list_head::next, and list_head::prev.
list_empty()
static int list_empty (const struct list_head * head) inline static
Definition at line 100 of file list.h.
 {
     return head->next == head;
 }
References list_head::next.
list_init()
static void list_init (struct list_head * list) inline static
Definition at line 27 of file list.h.
 {
     list->next = list;
     list->prev = list;
 }
References list_head::next, and list_head::prev.
list_is_first()
static int list_is_first (const struct list_head * list, const struct list_head * head) inline static
Definition at line 90 of file list.h.
 {
     return list->prev == head;
 }
References list_head::prev.
list_is_last()
static int list_is_last (const struct list_head * list, const struct list_head * head) inline static
Definition at line 95 of file list.h.
 {
     return list->next == head;
 }
References list_head::next.
list_replace()
static void list_replace (struct list_head * old, struct list_head * add) inline static
Definition at line 68 of file list.h.
 {
     add->next = old->next;
     add->next->prev = add;
     add->prev = old->prev;
     add->prev->next = add;
 }
References list_head::next, and list_head::prev.
list_splice()
static void list_splice (struct list_head * list, struct list_head * head) inline static
Definition at line 76 of file list.h.
 {
     struct list_head *first = list->next;
     if (first != list)
     {
         struct list_head *last = list->prev;
         struct list_head *at = head->next;
         first->prev = head;
         head->next = first;
         last->next = at;
         at->prev = last;
     }
 }
References list_head::next, and list_head::prev.