Fennix Project: Floppy::FloppyDriver Class Reference
Floppy::FloppyDriver Class Reference
#include <floppy.h>
Public Member Functions
FloppyDriver ()
~FloppyDriver ()
Data Fields
FloppyDrive Drives [2]
Private Member Functions
string ReturnFloppyType (int i)
void SendByte_FDC (char b)
unsigned char RecByte_FDC ()
void Recal ()
void SeekTrackSide (unsigned char track, unsigned char side)
void MotorOn ()
void MotorOff ()
void ResetFloppy ()
void WaitForIRQ ()
Detailed Description
Definition at line 67 of file floppy.h.
Constructor & Destructor Documentation
FloppyDriver()
Floppy::FloppyDriver::FloppyDriver ()
Definition at line 138 of file floppy.cpp.
     {
         RegisterInterrupt(FloppyDriveHandler, IRQ6, true);
         unsigned int c;
         outb(0x70, 0x10);
         c = inb(0x71);
         trace("1: %s", ReturnFloppyType(c >> 4));
         trace("2: %s", ReturnFloppyType(c & 0xF));
         if ((c >> 4) != 0)
             this->Drives[0].Name = "fd0";
         if ((c & 0xF) != 0)
             this->Drives[1].Name = "fd1";
         // TODO: implement read/writing to floppy
     }
References Drives, inb, IRQ6, Floppy::FloppyDrive::Name, outb, RegisterInterrupt(), ReturnFloppyType(), and trace.
~FloppyDriver()
Floppy::FloppyDriver::~FloppyDriver ()
Definition at line 155 of file floppy.cpp.
     {
         warn("Tried to uninitialize Floppy driver!");
     }
References warn.
Member Function Documentation
MotorOff()
void Floppy::FloppyDriver::MotorOff () private
Definition at line 114 of file floppy.cpp.
 { outb(DOR, 0x0); }
References DOR, and outb.
MotorOn()
void Floppy::FloppyDriver::MotorOn () private
Definition at line 112 of file floppy.cpp.
 { outb(DOR, 0x1C); }
References DOR, and outb.
Recal()
void Floppy::FloppyDriver::Recal () private
Definition at line 74 of file floppy.cpp.
     {
         unsigned char res = 0;
         unsigned char cres = 0;
         while (true)
         {
             SendByte_FDC(7);
             SendByte_FDC(0);
             SendByte_FDC(0x08);
             res = RecByte_FDC();
             cres = res & 0x80;
             if (cres == 0x80)
                 continue;
             res = RecByte_FDC();
             if (res == 0)
                 break;
         }
     }
References RecByte_FDC(), and SendByte_FDC().
RecByte_FDC()
unsigned char Floppy::FloppyDriver::RecByte_FDC () private
Definition at line 58 of file floppy.cpp.
     {
         unsigned char a;
         unsigned char b;
         while (true)
         {
             // usleep(100);
             a = inb(0x3F4);
             a &= 0x80;
             if (a == 0x80)
                 break;
         }
         b = inb(0x3F5);
         return b;
     }
References inb.
Referenced by Recal(), and SeekTrackSide().
ResetFloppy()
void Floppy::FloppyDriver::ResetFloppy () private
Definition at line 123 of file floppy.cpp.
     {
         // TODO: as the osdev wiki said "Sure this code looks OK, but some emulators or floppy drives might manage to be faster than your code. What if you've just returned from EnableController() and the floppy already issued the IRQ6? Then ReceivedIRQ will be set to true, your driver will enter WaitForIRQ(), set it to false again and then infinitely loop, waiting for an IRQ that has already been received."
         outb(DOR, 0x00);
         outb(DOR, 0x0C);
         outb(CCR, 0x00);
         WaitForIRQ();
     }
References CCR, DOR, outb, and WaitForIRQ().
ReturnFloppyType()
string Floppy::FloppyDriver::ReturnFloppyType (int i) private
Definition at line 15 of file floppy.cpp.
     {
         switch (i)
         {
         case 0:
             return "No floppy drive.";
             break;
         case 1:
             return "360KB 5.25in floppy";
             break;
         case 2:
             return "1.2MB 5.25in floppy";
             break;
         case 3:
             return "720KB 3.5in floppy";
             break;
         case 4:
             return "1.44MB 3.5in floppy";
             break;
         case 5:
             return "2.88MB 3.5in floppy";
             break;
         default:
             return "error";
             break;
         }
     }
Referenced by FloppyDriver().
SeekTrackSide()
void Floppy::FloppyDriver::SeekTrackSide (unsigned char track, unsigned char side) private
Definition at line 93 of file floppy.cpp.
     {
         unsigned char a, b, c;
         while (true)
         {
             SendByte_FDC(0x0F);
             SendByte_FDC(side * 4);
             SendByte_FDC(track);
             SendByte_FDC(0x08);
             a = RecByte_FDC();
             a &= 0x80;
             if (a != 0x80)
                 break;
             a = RecByte_FDC();
             if (a == track)
                 break;
         }
     }
References RecByte_FDC(), and SendByte_FDC().
SendByte_FDC()
void Floppy::FloppyDriver::SendByte_FDC (char b) private
Definition at line 43 of file floppy.cpp.
     {
         unsigned char a = 0;
         while (true)
         {
             // usleep(100);
             a = inb(0x3F4);
             a &= 0x80;
             if (a == 0x80)
                 break;
         }
         // usleep(100);
         outb(0x3F5, b);
     }
References inb, and outb.
Referenced by Recal(), and SeekTrackSide().
WaitForIRQ()
void Floppy::FloppyDriver::WaitForIRQ () private
Definition at line 116 of file floppy.cpp.
     {
         ReceivedIRQ = false;
         while (ReceivedIRQ == false)
             HLT;
     }
References HLT, and ReceivedIRQ.
Referenced by ResetFloppy().
Field Documentation
Drives
FloppyDrive Floppy::FloppyDriver::Drives[2]
Definition at line 70 of file floppy.h.
Referenced by FloppyDriver().
The documentation for this class was generated from the following files:
kernel/drivers/storage/floppy.h
kernel/drivers/storage/floppy.cpp