Fennix Project: Intel8254x::NetworkInterfaceController Class Reference
Intel8254x::NetworkInterfaceController Class Reference
#include <Intel8254x.hpp>
Data Structures
struct BARData
Public Member Functions
MediaAccessControl GetMAC ()
InternetProtocol4 GetIP ()
void SetIP (InternetProtocol4 IP)
NetworkInterfaceController (PCI::PCIDeviceHeader *PCIBaseAddress)
~NetworkInterfaceController ()
void Send (uint8_t *Data, uint64_t Length)
void Receive ()
virtual void HandleInterrupt ()
Public Member Functions inherited from NetworkInterfaceManager::DeviceInterface
virtual void Send (void *Data, uint64_t Length)
Private Attributes
InternetProtocol4 IP
BARData BAR
Additional Inherited Members
Data Fields inherited from NetworkInterfaceManager::DeviceInterface
char Name [128]
Device interface name.
uint64_t ID
Device interface index.
MediaAccessControl MAC
Device interface MAC address (Big-endian)
InternetProtocol4 IP
Device interface IP address (Big-endian)
Detailed Description
Definition at line 10 of file Intel8254x.hpp.
Data Structure Documentation
Intel8254x::NetworkInterfaceController::BARData
struct Intel8254x::NetworkInterfaceController::BARData
Definition at line 13 of file Intel8254x.hpp.
Data Fields
uint16_t IOBase
uint32_t MemoryBase
uint8_t Type
Constructor & Destructor Documentation
NetworkInterfaceController()
Intel8254x::NetworkInterfaceController::NetworkInterfaceController (PCI::PCIDeviceHeader * PCIBaseAddress)
Definition at line 22 of file Intel8254x.cpp.
                                                                                              : DriverInterrupts::Register(((PCI::PCIHeader0 *)PCIBaseAddress)->InterruptLine + IRQ0)
     {
         if (PCIBaseAddress->VendorID != 0x8086 && PCIBaseAddress->DeviceID != 0x109A && PCIBaseAddress->DeviceID != 0x100F)
         {
             netdbg("Not a Intel-Ethernet-i217 network card");
             return;
         }
         netdbg("Found %s network card", PCI::GetDeviceName(PCIBaseAddress->VendorID, PCIBaseAddress->DeviceID));
         memcpy(this->Name, "Intel-Ethernet-i217 Network Driver", sizeof(this->Name));
         uint32_t PCIBAR = ((PCI::PCIHeader0 *)PCIBaseAddress)->BAR0;
         BAR.Type = PCIBAR & 1;
         BAR.IOBase = PCIBAR & (~3);
         BAR.MemoryBase = PCIBAR & (~15);
         netdbg("BAR Type: %d - BAR IOBase: %#x - BAR MemoryBase: %#x", BAR.Type, BAR.IOBase, BAR.MemoryBase);
         warn("Driver for %s is not implemented yet!", PCI::GetDeviceName(PCIBaseAddress->VendorID, PCIBaseAddress->DeviceID));
         this->MAC = this->GetMAC();
     }
References BAR, PCI::GetDeviceName(), GetMAC(), Intel8254x::NetworkInterfaceController::BARData::IOBase, NetworkInterfaceManager::DeviceInterface::MAC, memcpy(), Intel8254x::NetworkInterfaceController::BARData::MemoryBase, NetworkInterfaceManager::DeviceInterface::Name, netdbg, Intel8254x::NetworkInterfaceController::BARData::Type, and warn.
~NetworkInterfaceController()
Intel8254x::NetworkInterfaceController::~NetworkInterfaceController ()
Definition at line 42 of file Intel8254x.cpp.
     {
     }
Member Function Documentation
GetIP()
InternetProtocol4 Intel8254x::NetworkInterfaceController::GetIP ()
Definition at line 12 of file Intel8254x.cpp.
     {
         return IP;
     }
References IP.
GetMAC()
MediaAccessControl Intel8254x::NetworkInterfaceController::GetMAC ()
Definition at line 7 of file Intel8254x.cpp.
     {
         return MediaAccessControl();
     }
Referenced by NetworkInterfaceController().
HandleInterrupt()
void Intel8254x::NetworkInterfaceController::HandleInterrupt () virtual
Definition at line 56 of file Intel8254x.cpp.
     {
         fixme("NetworkInterfaceController::HandleInterrupt( )");
     }
References fixme().
Receive()
void Intel8254x::NetworkInterfaceController::Receive () virtual
Reimplemented from NetworkInterfaceManager::DeviceInterface.
Definition at line 51 of file Intel8254x.cpp.
     {
         fixme("NetworkInterfaceController::Receive( )");
     }
References fixme().
Send()
void Intel8254x::NetworkInterfaceController::Send (uint8_t * Data, uint64_t Length)
Definition at line 46 of file Intel8254x.cpp.
     {
         fixme("NetworkInterfaceController::Send( %p %ld )", Data, Length);
     }
References fixme(), and Length.
SetIP()
void Intel8254x::NetworkInterfaceController::SetIP (InternetProtocol4 IP)
Definition at line 17 of file Intel8254x.cpp.
     {
         this->IP = IP;
     }
References IP.
Field Documentation
BAR
BARData Intel8254x::NetworkInterfaceController::BAR private
Definition at line 21 of file Intel8254x.hpp.
Referenced by NetworkInterfaceController().
IP
InternetProtocol4 Intel8254x::NetworkInterfaceController::IP private
Definition at line 20 of file Intel8254x.hpp.
Referenced by GetIP(), and SetIP().
The documentation for this class was generated from the following files:
kernel/drivers/network/Intel8254x/Intel8254x.hpp
kernel/drivers/network/Intel8254x/Intel8254x.cpp