Fennix Project: libc/libgcc/cxa.cpp File Reference
cxa.cpp File Reference
#include <stdint.h>
#include <syscalls.h>
Data Structures
struct atexit_func_entry_t
struct _Unwind_Exception
Macros
#define ATEXIT_MAX_FUNCS 128
Typedefs
typedef unsigned uarch_t
typedef unsigned _Unwind_Exception_Class __attribute__((__mode__(__DI__)))
typedef void(* _Unwind_Exception_Cleanup_Fn) (_Unwind_Reason_Code, struct _Unwind_Exception *)
typedef int _Unwind_Action
Enumerations
enum _Unwind_Reason_Code {
_URC_NO_REASON = 0, _URC_FOREIGN_EXCEPTION_CAUGHT = 1, _URC_FATAL_PHASE2_ERROR = 2, _URC_FATAL_PHASE1_ERROR = 3,
_URC_NORMAL_STOP = 4, _URC_END_OF_STACK = 5, _URC_HANDLER_FOUND = 6, _URC_INSTALL_CONTEXT = 7,
_URC_CONTINUE_UNWIND = 8, _URC_NO_REASON = 0, _URC_FOREIGN_EXCEPTION_CAUGHT = 1, _URC_FATAL_PHASE2_ERROR = 2,
_URC_FATAL_PHASE1_ERROR = 3, _URC_NORMAL_STOP = 4, _URC_END_OF_STACK = 5, _URC_HANDLER_FOUND = 6,
_URC_INSTALL_CONTEXT = 7, _URC_CONTINUE_UNWIND = 8
}
Functions
struct _Unwind_Exception __attribute__ ((__aligned__))
void fixme (char *m)
void * _ZTIl ()
int __cxa_atexit (void(*f)(void *), void *objptr, void *dso)
void __cxa_finalize (void *f)
_Unwind_Reason_Code __gxx_personality_v0 (int version, _Unwind_Action actions, _Unwind_Exception_Class exception_class, _Unwind_Exception *ue_header, _Unwind_Context *context)
void _Unwind_Resume (struct _Unwind_Exception *exc)
void * __cxa_allocate_exception (uint64_t thrown_size) throw ()
void __cxa_throw (void *thrown_object, void *tinfo, void(*dest)(void *))
void __cxa_rethrow ()
void __cxa_pure_virtual ()
void __cxa_throw_bad_array_new_length ()
void __cxa_free_exception (void *thrown_exception)
void * __cxa_begin_catch (void *e)
void __cxa_end_catch ()
Variables
_Unwind_Exception_Class exception_class
_Unwind_Exception_Cleanup_Fn exception_cleanup
_Unwind_Word private_1
_Unwind_Word private_2
void * __dso_handle = 0
atexit_func_entry_t __atexit_funcs [ATEXIT_MAX_FUNCS]
uarch_t __atexit_func_count = 0
Data Structure Documentation
_Unwind_Exception
struct _Unwind_Exception
Definition at line 41 of file cxxabi.cpp.
Data Fields
_Unwind_Exception_Class exception_class
_Unwind_Exception_Cleanup_Fn exception_cleanup
_Unwind_Word private_1
_Unwind_Word private_2
Macro Definition Documentation
ATEXIT_MAX_FUNCS
#define ATEXIT_MAX_FUNCS 128
Definition at line 4 of file cxa.cpp.
Typedef Documentation
__attribute__
typedef unsigned _Unwind_Word __attribute__((__mode__(__unwind_word__)))
Definition at line 33 of file cxa.cpp.
_Unwind_Action
typedef int _Unwind_Action
Definition at line 36 of file cxa.cpp.
_Unwind_Exception_Cleanup_Fn
typedef void(* _Unwind_Exception_Cleanup_Fn) (_Unwind_Reason_Code, struct _Unwind_Exception *)
Definition at line 35 of file cxa.cpp.
uarch_t
typedef unsigned uarch_t
Definition at line 6 of file cxa.cpp.
Enumeration Type Documentation
_Unwind_Reason_Code
enum _Unwind_Reason_Code
Enumerator
_URC_NO_REASON
_URC_FOREIGN_EXCEPTION_CAUGHT
_URC_FATAL_PHASE2_ERROR
_URC_FATAL_PHASE1_ERROR
_URC_NORMAL_STOP
_URC_END_OF_STACK
_URC_HANDLER_FOUND
_URC_INSTALL_CONTEXT
_URC_CONTINUE_UNWIND
_URC_NO_REASON
_URC_FOREIGN_EXCEPTION_CAUGHT
_URC_FATAL_PHASE2_ERROR
_URC_FATAL_PHASE1_ERROR
_URC_NORMAL_STOP
_URC_END_OF_STACK
_URC_HANDLER_FOUND
_URC_INSTALL_CONTEXT
_URC_CONTINUE_UNWIND
Definition at line 19 of file cxa.cpp.
 {
     _URC_NO_REASON = 0,
     _URC_FOREIGN_EXCEPTION_CAUGHT = 1,
     _URC_FATAL_PHASE2_ERROR = 2,
     _URC_FATAL_PHASE1_ERROR = 3,
     _URC_NORMAL_STOP = 4,
     _URC_END_OF_STACK = 5,
     _URC_HANDLER_FOUND = 6,
     _URC_INSTALL_CONTEXT = 7,
     _URC_CONTINUE_UNWIND = 8
 } _Unwind_Reason_Code;
Function Documentation
__attribute__()
struct _Unwind_Exception __attribute__ ((__aligned__))
__cxa_allocate_exception()
void* __cxa_allocate_exception (uint64_t thrown_size) throw ()
Definition at line 122 of file cxa.cpp.
 {
     // fixme((char *)"__cxa_allocate_exception( %#llu ) triggered.", thrown_size);
     fixme((char *)"__cxa_allocate_exception() triggered.");
     return (void *)0;
 }
References fixme().
__cxa_atexit()
int __cxa_atexit (void(*)(void *) f, void * objptr, void * dso)
Definition at line 67 of file cxa.cpp.
 {
     // fixme((char *)"__cxa_atexit( %p %p %p ) triggered.", f, objptr, dso);
     fixme((char *)"__cxa_atexit() triggered.");
     if (__atexit_func_count >= ATEXIT_MAX_FUNCS)
     {
         return -1;
     }
     __atexit_funcs[__atexit_func_count].destructor_func = f;
     __atexit_funcs[__atexit_func_count].obj_ptr = objptr;
     __atexit_funcs[__atexit_func_count].dso_handle = dso;
     __atexit_func_count++;
     return 0;
 }
References __atexit_func_count, __atexit_funcs, ATEXIT_MAX_FUNCS, atexit_func_entry_t::destructor_func, atexit_func_entry_t::dso_handle, fixme(), and atexit_func_entry_t::obj_ptr.
__cxa_begin_catch()
void* __cxa_begin_catch (void * e)
Definition at line 162 of file cxa.cpp.
 {
     // fixme((char *)"__cxa_begin_catch( %p ) triggered.", e);
     fixme((char *)"__cxa_begin_catch() triggered.");
     return (void *)0;
 }
References fixme().
__cxa_end_catch()
void __cxa_end_catch ()
Definition at line 170 of file cxa.cpp.
 {
     // fixme((char *)"__cxa_end_catch() triggered.");
     fixme((char *)"__cxa_end_catch() triggered.");
 }
References fixme().
__cxa_finalize()
void __cxa_finalize (void * f)
Definition at line 82 of file cxa.cpp.
 {
     // fixme((char *)"__cxa_finalize( %p ) triggered.", f);
     fixme((char *)"__cxa_finalize() triggered.");
     uarch_t i = __atexit_func_count;
     if (!f)
     {
         while (i--)
         {
             if (__atexit_funcs[i].destructor_func)
             {
                 (*__atexit_funcs[i].destructor_func)(__atexit_funcs[i].obj_ptr);
             }
         }
         return;
     }
     while (i--)
     {
         if (__atexit_funcs[i].destructor_func == f)
         {
             (*__atexit_funcs[i].destructor_func)(__atexit_funcs[i].obj_ptr);
             __atexit_funcs[i].destructor_func = 0;
         }
     }
 }
References __atexit_func_count, __atexit_funcs, atexit_func_entry_t::destructor_func, and fixme().
Referenced by _start().
__cxa_free_exception()
void __cxa_free_exception (void * thrown_exception)
Definition at line 153 of file cxa.cpp.
 {
     // fixme((char *)"__cxa_free_exception( %p ) triggered.", thrown_exception);
     fixme((char *)"__cxa_free_exception() triggered.");
 }
References fixme().
__cxa_pure_virtual()
void __cxa_pure_virtual ()
Definition at line 141 of file cxa.cpp.
 {
     // fixme((char *)"__cxa_pure_virtual() triggered.");
     fixme((char *)"__cxa_pure_virtual() triggered.");
 }
References fixme().
__cxa_rethrow()
void __cxa_rethrow ()
Definition at line 135 of file cxa.cpp.
 {
     // fixme((char *)"__cxa_rethrow() triggered.");
     fixme((char *)"__cxa_rethrow() triggered.");
 }
References fixme().
__cxa_throw()
void __cxa_throw (void * thrown_object, void * tinfo, void(*)(void *) dest)
Definition at line 129 of file cxa.cpp.
 {
     // fixme((char *)"__cxa_throw( %p %p %p ) triggered.", thrown_object, tinfo, dest);
     fixme((char *)"__cxa_throw() triggered.");
 }
References fixme().
__cxa_throw_bad_array_new_length()
void __cxa_throw_bad_array_new_length ()
Definition at line 147 of file cxa.cpp.
 {
     // fixme((char *)"__cxa_throw_bad_array_new_length() triggered.");
     fixme((char *)"__cxa_throw_bad_array_new_length() triggered.");
 }
References fixme().
__gxx_personality_v0()
_Unwind_Reason_Code __gxx_personality_v0 (int version, _Unwind_Action actions, _Unwind_Exception_Class exception_class, _Unwind_Exception * ue_header, _Unwind_Context * context)
Definition at line 109 of file cxa.cpp.
 {
     // fixme((char *)"__gxx_personality_v0( %d %p %p %p %p ) triggered.", version, actions, exception_class, ue_header, context);
     fixme((char *)"__gxx_personality_v0() triggered.");
     return _URC_NO_REASON;
 }
References _URC_NO_REASON, and fixme().
_Unwind_Resume()
void _Unwind_Resume (struct _Unwind_Exception * exc)
Definition at line 116 of file cxa.cpp.
 {
     // fixme((char *)"_Unwind_Resume( %p ) triggered.", exc);
     fixme((char *)"_Unwind_Resume() triggered.");
 }
References fixme().
_ZTIl()
void* _ZTIl ()
Definition at line 61 of file cxa.cpp.
 {
     fixme((char *)"_ZTIl triggered.");
     return (void *)0xdeadbeef; // TODO: do something with this
 }
References fixme().
fixme()
void fixme (char * m)
Definition at line 54 of file cxa.cpp.
 {
     syscall_dbg(0x3F8, (char *)"[libgcc] ");
     syscall_dbg(0x3F8, m);
     syscall_dbg(0x3F8, (char *)"\n");
 }
Referenced by __cxa_allocate_exception(), __cxa_atexit(), __cxa_begin_catch(), __cxa_end_catch(), __cxa_finalize(), __cxa_free_exception(), __cxa_guard_abort(), __cxa_guard_acquire(), __cxa_guard_release(), __cxa_pure_virtual(), __cxa_rethrow(), __cxa_throw(), __cxa_throw_bad_array_new_length(), __gxx_personality_v0(), _Unwind_Resume(), _ZTIl(), PCI::BaseSystemPeripheralSubclassName(), PCI::BridgeDeviceSubclassName(), PCI::CommunicationControllerSubclassName(), PCI::DisplayControllerSubclassName(), EnableCPUFeatures(), FunctionCallHandler(), PCI::GetDeviceName(), PCI::GetSubclassName(), PCI::GetVendorName(), Intel8254x::NetworkInterfaceController::HandleInterrupt(), HandleLinuxSyscalls(), internal_unimpl(), Driver::KernelDriver::LoadKernelDriverFromFile(), PCI::MassStorageControllerSubclassName(), PCI::NetworkControllerSubclassName(), NetworkARP::ARP::OnEthernetPacketReceived(), Floppy::FloppyDrive::read(), Driver::ReadFSFunction(), NetworkInterfaceManager::ReadFSFunction(), NetworkNTP::ReadTime(), ACPI::DSDT::reboot(), Intel8254x::NetworkInterfaceController::Receive(), NetworkICMPv6::ICMPv6::Receive(), Intel8254x::NetworkInterfaceController::Send(), NetworkICMPv4::ICMPv4::Send(), NetworkICMPv6::ICMPv6::Send(), PCI::SerialBusControllerSubclassName(), RTL8139::NetworkInterfaceController::SetIP(), NetworkInterfaceManager::NetworkInterface::StopNetworkStack(), sys_close(), sys_open(), sys_read(), sys_stat(), sys_write(), SysCreateProcessFromFile(), PCI::WirelessControllerSubclassName(), Floppy::FloppyDrive::write(), Driver::WriteFSFunction(), and NetworkInterfaceManager::WriteFSFunction().
Variable Documentation
__atexit_func_count
uarch_t __atexit_func_count = 0
Definition at line 52 of file cxa.cpp.
Referenced by __cxa_atexit(), and __cxa_finalize().
__atexit_funcs
atexit_func_entry_t __atexit_funcs[ATEXIT_MAX_FUNCS]
Definition at line 51 of file cxa.cpp.
Referenced by __cxa_atexit(), and __cxa_finalize().
__dso_handle
void* __dso_handle = 0
exception_class
_Unwind_Exception_Class exception_class
Definition at line 37 of file cxa.cpp.
exception_cleanup
_Unwind_Exception_Cleanup_Fn exception_cleanup
Definition at line 38 of file cxa.cpp.
private_1
_Unwind_Word private_1
Definition at line 42 of file cxa.cpp.
private_2
_Unwind_Word private_2
Definition at line 43 of file cxa.cpp.