Fennix Project: NetworkARP Namespace Reference
NetworkARP Namespace Reference
Data Structures
class ARP
struct ARPHeader
struct DiscoveredAddress
Enumerations
enum DAType { DA_ADD = 1, DA_DEL = 2, DA_SEARCH = 3, DA_UPDATE = 4 }
enum ARPHardwareType {
HTYPE_ETHERNET = 1, HTYPE_802_3 = 6, HTYPE_ARCNET = 7, HTYPE_FRAME_RELAY = 15,
HTYPE_ATM = 16, HTYPE_HDLC = 17, HTYPE_FIBRE_CHANNEL = 18, HTYPE_ATM_2 = 19,
HTYPE_SERIAL_LINE = 20
}
Functions
DiscoveredAddress * ManageDA (DAType Type, InternetProtocol IP, MediaAccessControl MAC)
Variables
enum NetworkARP::DAType __attribute__
Data Structure Documentation
NetworkARP::ARPHeader
struct NetworkARP::ARPHeader
Definition at line 200 of file NetworkController.hpp.
Data Fields
uint8_t HardwareSize
ARPHardwareType HardwareType
uint16_t Operation
uint8_t ProtocolSize
ProtocolType ProtocolType
InternetProtocol SenderIP
MediaAccessControl SenderMAC
InternetProtocol TargetIP
MediaAccessControl TargetMAC
NetworkARP::DiscoveredAddress
struct NetworkARP::DiscoveredAddress
Definition at line 213 of file NetworkController.hpp.
Data Fields
InternetProtocol IP
MediaAccessControl MAC
Enumeration Type Documentation
ARPHardwareType
enum NetworkARP::ARPHardwareType
Enumerator
HTYPE_ETHERNET
HTYPE_802_3
HTYPE_ARCNET
HTYPE_FRAME_RELAY
HTYPE_ATM
HTYPE_HDLC
HTYPE_FIBRE_CHANNEL
HTYPE_ATM_2
HTYPE_SERIAL_LINE
Definition at line 187 of file NetworkController.hpp.
     {
         HTYPE_ETHERNET = 1,
         HTYPE_802_3 = 6,
         HTYPE_ARCNET = 7,
         HTYPE_FRAME_RELAY = 15,
         HTYPE_ATM = 16,
         HTYPE_HDLC = 17,
         HTYPE_FIBRE_CHANNEL = 18,
         HTYPE_ATM_2 = 19,
         HTYPE_SERIAL_LINE = 20
     };
DAType
enum NetworkARP::DAType
Enumerator
DA_ADD
DA_DEL
DA_SEARCH
DA_UPDATE
Definition at line 11 of file AddressResolutionProtocol.cpp.
     {
         DA_ADD = 1,
         DA_DEL = 2,
         DA_SEARCH = 3,
         DA_UPDATE = 4
     };
Function Documentation
ManageDA()
DiscoveredAddress* NetworkARP::ManageDA (DAType Type, InternetProtocol IP, MediaAccessControl MAC)
Definition at line 19 of file AddressResolutionProtocol.cpp.
     {
         // TODO: Compare IPv6 too.
         DiscoveredAddress *tmp = new DiscoveredAddress;
         switch (Type)
         {
         case DA_ADD:
             tmp->IP = IP;
             tmp->MAC = MAC;
             DiscoveredAddresses.push_back(tmp);
             return tmp;
         case DA_DEL:
             for (int i = 0; i < DiscoveredAddresses.size(); i++)
                 if (CompareIP(DiscoveredAddresses[i]->IP, IP, CompareIPv4))
                 {
                     DiscoveredAddress *tmp = DiscoveredAddresses[i];
                     DiscoveredAddresses.remove(i);
                     return tmp;
                 }
             delete tmp;
             return nullptr;
         case DA_SEARCH:
             delete tmp;
             for (int i = 0; i < DiscoveredAddresses.size(); i++)
                 if (CompareIP(DiscoveredAddresses[i]->IP, IP, CompareIPv4))
                 {
                     return DiscoveredAddresses[i];
                 }
             return nullptr;
         case DA_UPDATE:
             delete tmp;
             for (int i = 0; i < DiscoveredAddresses.size(); i++)
                 if (CompareIP(DiscoveredAddresses[i]->IP, IP, CompareIPv4))
                 {
                     DiscoveredAddresses[i]->MAC = MAC;
                     return DiscoveredAddresses[i];
                 }
             return nullptr;
         }
         delete tmp;
         return nullptr;
     }
References CompareIP(), CompareIPv4, DA_ADD, DA_DEL, DA_SEARCH, DA_UPDATE, DiscoveredAddresses, NetworkARP::DiscoveredAddress::IP, NetworkARP::DiscoveredAddress::MAC, and Type.
Referenced by NetworkARP::ARP::Receive(), NetworkARP::ARP::Search(), and NetworkARP::ARP::Update().
Variable Documentation
__attribute__
enum NetworkARP::DAType NetworkARP::__attribute__