Fennix Project: kernel/proc/ProcessAPI.cpp File Reference
ProcessAPI.cpp File Reference
#include <internal_task.h>
#include <filesystem.h>
#include <critical.hpp>
#include <msexec.h>
#include <debug.h>
#include <heap.h>
#include <elf.h>
#include "../cpu/smp.hpp"
#include "binary.hpp"
Functions
PCB * ConvertTaskCBToPCB (TaskControlBlock *task)
TCB * ConvertTaskCBToTCB (TaskControlBlock *task)
PCB * SysGetProcessByPID (uint64_t ID)
Get a running process by PID.
TCB * SysGetThreadByTID (uint64_t ID)
Get a running thread by PID.
PCB * SysGetCurrentProcess ()
Get current process.
TCB * SysGetCurrentThread ()
Get current thread.
void SysSetProcessPriority (int Priority)
Set current process priority.
int SysGetProcessPriority ()
Get current process priority.
void SysSetThreadPriority (int Priority)
Get current thread priority.
int SysGetThreadPriority ()
Get current thread priority.
PCB * SysCreateProcess (const char *Name, ELEVATION Elevation)
Create a new simple process with custom name and address space.
TCB * SysCreateThread (PCB *Parent, uint64_t InstructionPointer, uint64_t arg0, uint64_t arg1)
Create a new thread.
PCB * SysCreateProcessFromFile (const char *File, uint64_t arg0, uint64_t arg1, ELEVATION Elevation)
Create a new process from a file.
Variables
int CurrentTaskingMode = TaskingMode::None
Function Documentation
ConvertTaskCBToPCB()
PCB* ConvertTaskCBToPCB (TaskControlBlock * task)
Definition at line 18 of file ProcessAPI.cpp.
 {
     CR3 tmpcr3;
     tmpcr3.raw = (uint64_t)task->pml4;
     static PCB pcb = {
         .ID = task->id,
         .Name = {'\0'},
         .Status = STATUS::UnknownStatus,
         .Elevation = task->UserMode ? ELEVATION::User : ELEVATION::Kernel,
         .ExitCode = 0,
         .Offset = 0,
         .Parent = nullptr,
         .PageTable = tmpcr3,
         .Info = {},
         .Security = {},
         .Threads = {},
         .Children = {},
         .Checksum = PROCESS_CHECKSUM};
     memcpy(pcb.Name, task->name, sizeof(pcb.Name));
     return &pcb;
 }
References PCB::ID, and CR3::raw.
Referenced by SysGetCurrentProcess().
ConvertTaskCBToTCB()
TCB* ConvertTaskCBToTCB (TaskControlBlock * task)
Definition at line 41 of file ProcessAPI.cpp.
 {
     static TCB tcb = {
         .ID = task->id,
         .Name = {'\0'},
         .Status = STATUS::UnknownStatus,
         .ExitCode = 0,
         .Parent = nullptr,
         .Stack = 0x0,
         .FXRegion = 0,
         .Registers = {},
         .fs = 0,
         .gs = 0,
         .cs = 0,
         .ss = 0,
         .ds = 0,
         .es = 0,
         .argc = task->argc,
         .argv = task->argv,
         .envp = task->envp,
         .Info = {},
         .Security = {},
         .Checksum = THREAD_CHECKSUM};
     memcpy(tcb.Name, task->name, sizeof(tcb.Name));
     return &tcb;
 }
References TCB::ID, memcpy(), TCB::Name, THREAD_CHECKSUM, and UnknownStatus.
Referenced by SysGetCurrentThread().
SysCreateProcess()
PCB* SysCreateProcess (const char * Name, ELEVATION Elevation)
Create a new simple process with custom name and address space.
Parameters
Name
PageTable
Returns
PCB*
Definition at line 262 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         static int once = 0;
         if (!once++)
             err("The current tasking mode does not support the request.");
         static PCB pcb = {
             .ID = 0,
             .Name = {'\0'},
             .Status = STATUS::UnknownStatus,
             .Elevation = ELEVATION::UnknownElevation,
             .ExitCode = 0,
             .Offset = 0,
             .Parent = nullptr,
             .PageTable = {},
             .Info = {},
             .Security = {},
             .Threads = {},
             .Children = {},
             .Checksum = PROCESS_CHECKSUM};
         memcpy(pcb.Name, "Unknown Task", sizeof(pcb.Name));
         return &pcb;
     }
     case TaskingMode::Multi:
         return mt->CreateProcess(SysGetCurrentProcess(), (char *)Name, Elevation);
     default:
         return nullptr;
     }
 }
References CurrentTaskingMode, err, PCB::ID, memcpy(), Mono, Tasking::mt, Multi, PCB::Name, PROCESS_CHECKSUM, SysGetCurrentProcess(), UnknownElevation, and UnknownStatus.
Referenced by ExecuteBinary(), Driver::KernelDriver::KernelDriver(), and NetworkInterfaceManager::NetworkInterface::StartService().
SysCreateProcessFromFile()
PCB* SysCreateProcessFromFile (const char * File, uint64_t arg0, uint64_t arg1, ELEVATION Elevation)
Create a new process from a file.
Parameters
File TODO: more
Returns
PCB
Definition at line 333 of file ProcessAPI.cpp.
 {
     return ExecuteBinary(File, arg0, arg1, Elevation);
 }
References ExecuteBinary().
Referenced by internal_createprocess(), KernelTask(), and TriggerUserModeCrash().
SysCreateThread()
TCB* SysCreateThread (PCB * Parent, uint64_t InstructionPointer, uint64_t arg0, uint64_t arg1)
Create a new thread.
Parameters
Parent if null is using the current running
InstructionPointer
Returns
TCB*
Definition at line 295 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         static int once = 0;
         if (!once++)
             err("The current tasking mode does not support the request.");
         static TCB tcb = {
             .ID = 0,
             .Name = {'\0'},
             .Status = STATUS::UnknownStatus,
             .ExitCode = 0,
             .Parent = nullptr,
             .Stack = 0x0,
             .FXRegion = 0,
             .Registers = {},
             .fs = 0,
             .gs = 0,
             .cs = 0,
             .ss = 0,
             .ds = 0,
             .es = 0,
             .Info = {},
             .Security = {},
             .Checksum = THREAD_CHECKSUM};
         memcpy(tcb.Name, "Unknown Task", sizeof(tcb.Name));
         return &tcb;
     }
     case TaskingMode::Multi:
         return mt->CreateThread(Parent, InstructionPointer, arg0, arg1);
     default:
         return nullptr;
     }
 }
References CurrentTaskingMode, err, TCB::ID, memcpy(), Mono, Tasking::mt, Multi, TCB::Name, THREAD_CHECKSUM, and UnknownStatus.
Referenced by ExecuteBinary(), internal_createthread(), Driver::KernelDriver::KernelDriver(), and NetworkInterfaceManager::NetworkInterface::StartService().
SysGetCurrentProcess()
PCB* SysGetCurrentProcess ()
Get current process.
Returns
PCB
Definition at line 170 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
         return ConvertTaskCBToPCB(monot->GetCurrentTask());
     case TaskingMode::Multi:
         return CurrentCPU->CurrentProcess;
     default:
         return nullptr;
     }
 }
References ConvertTaskCBToPCB(), CurrentCPU, CurrentTaskingMode, Mono, Tasking::monot, and Multi.
Referenced by internal_createthread(), internal_getcurrentprocess(), internal_getcurrentprocessid(), and SysCreateProcess().
SysGetCurrentThread()
TCB* SysGetCurrentThread ()
Get current thread.
Returns
TCB
Definition at line 183 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
         return ConvertTaskCBToTCB(monot->GetCurrentTask());
     case TaskingMode::Multi:
         return CurrentCPU->CurrentThread;
     default:
         return nullptr;
     }
 }
References ConvertTaskCBToTCB(), CurrentCPU, CurrentTaskingMode, Mono, Tasking::monot, and Multi.
Referenced by CanSyscall(), internal_exit(), internal_getargc(), internal_getargv(), internal_getcurrentthread(), internal_getcurrentthreadid(), internal_getenvp(), syscall_handler(), and TriggerUserModeCrash().
SysGetProcessByPID()
PCB* SysGetProcessByPID (uint64_t ID)
Get a running process by PID.
Parameters
pid Process identifier
Returns
PCB
Definition at line 68 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         static int once = 0;
         if (!once++)
             err("The current tasking mode does not support the request.");
         static PCB pcb = {
             .ID = 0,
             .Name = {'\0'},
             .Status = STATUS::UnknownStatus,
             .Elevation = ELEVATION::UnknownElevation,
             .ExitCode = 0,
             .Offset = 0,
             .Parent = nullptr,
             .PageTable = {},
             .Info = {},
             .Security = {},
             .Threads = {},
             .Children = {},
             .Checksum = PROCESS_CHECKSUM};
         memcpy(pcb.Name, "Unknown Task", sizeof(pcb.Name));
         return &pcb;
     }
     case TaskingMode::Multi:
     {
         EnterCriticalSection;
         foreach (PCB *pcb in mt->ListProcess)
         {
             if (pcb == nullptr || pcb->Checksum != Checksum::PROCESS_CHECKSUM || pcb->Elevation == ELEVATION::Idle)
                 continue;
             if (pcb->ID == ID)
             {
                 LeaveCriticalSection;
                 return pcb;
             }
         }
         LeaveCriticalSection;
         return nullptr;
     }
     default:
         return nullptr;
     }
 }
References PCB::Checksum, CurrentTaskingMode, PCB::Elevation, EnterCriticalSection, err, ID, PCB::ID, Idle, LeaveCriticalSection, memcpy(), Mono, Tasking::mt, Multi, PCB::Name, PROCESS_CHECKSUM, UnknownElevation, and UnknownStatus.
SysGetProcessPriority()
int SysGetProcessPriority ()
Get current process priority.
Returns
int
Definition at line 213 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         trace("Priority get not supported in current tasking mode. Ignoring...");
         return 0;
     }
     case TaskingMode::Multi:
         return CurrentCPU->CurrentProcess->Info.Priority;
     default:
         return 0;
     }
 }
References CurrentCPU, CurrentTaskingMode, Mono, Multi, and trace.
SysGetThreadByTID()
TCB* SysGetThreadByTID (uint64_t ID)
Get a running thread by PID.
Parameters
pid Thread identifier
Returns
TCB
Definition at line 115 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         static int once = 0;
         if (!once++)
             err("The current tasking mode does not support the request.");
         static TCB tcb = {
             .ID = 0,
             .Name = {'\0'},
             .Status = STATUS::UnknownStatus,
             .ExitCode = 0,
             .Parent = nullptr,
             .Stack = 0x0,
             .FXRegion = 0,
             .Registers = {},
             .fs = 0,
             .gs = 0,
             .cs = 0,
             .ss = 0,
             .ds = 0,
             .es = 0,
             .Info = {},
             .Security = {},
             .Checksum = THREAD_CHECKSUM};
         memcpy(tcb.Name, "Unknown Task", sizeof(tcb.Name));
         return &tcb;
     }
     case TaskingMode::Multi:
     {
         EnterCriticalSection;
         foreach (PCB *pcb in mt->ListProcess)
         {
             if (pcb == nullptr || pcb->Checksum != Checksum::PROCESS_CHECKSUM || pcb->Elevation == ELEVATION::Idle)
                 continue;
             foreach (TCB *tcb in pcb->Threads)
             {
                 if (tcb->ID == ID)
                 {
                     LeaveCriticalSection;
                     return tcb;
                 }
             }
         }
         LeaveCriticalSection;
         return nullptr;
     }
     default:
         return nullptr;
     }
 }
References PCB::Checksum, CurrentTaskingMode, PCB::Elevation, EnterCriticalSection, err, ID, TCB::ID, Idle, LeaveCriticalSection, memcpy(), Mono, Tasking::mt, Multi, TCB::Name, PROCESS_CHECKSUM, THREAD_CHECKSUM, PCB::Threads, and UnknownStatus.
SysGetThreadPriority()
int SysGetThreadPriority ()
Get current thread priority.
Returns
int
Definition at line 246 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         trace("Priority get not supported in current tasking mode. Ignoring...");
         return 0;
     }
     case TaskingMode::Multi:
         return CurrentCPU->CurrentThread->Info.Priority;
     default:
         return 0;
     }
 }
References CurrentCPU, CurrentTaskingMode, Mono, Multi, and trace.
SysSetProcessPriority()
void SysSetProcessPriority (int Priority)
Set current process priority.
Parameters
Priority
Definition at line 196 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         trace("Priority change not supported in current tasking mode. Ignoring...");
         return;
     }
     case TaskingMode::Multi:
         CurrentCPU->CurrentProcess->Info.Priority = Priority;
         return;
     default:
         return;
     }
 }
References CurrentCPU, CurrentTaskingMode, Mono, Multi, and trace.
SysSetThreadPriority()
void SysSetThreadPriority (int Priority)
Get current thread priority.
Parameters
Priority
Definition at line 229 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         trace("Priority change not supported in current tasking mode. Ignoring...");
         return;
     }
     case TaskingMode::Multi:
         CurrentCPU->CurrentThread->Info.Priority = Priority;
         return;
     default:
         return;
     }
 }
References CurrentCPU, CurrentTaskingMode, Mono, Multi, and trace.
Referenced by Driver::DriverManagerMainLoop(), KernelTask(), and NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
Variable Documentation
CurrentTaskingMode
int CurrentTaskingMode = TaskingMode::None
Definition at line 16 of file ProcessAPI.cpp.
Referenced by ExecuteBinary(), internal_exit(), internal_fadebootlogo(), internal_getschedulemode(), internal_usleep(), KernelTask(), SysCreateProcess(), SysCreateThread(), SysGetCurrentProcess(), SysGetCurrentThread(), SysGetProcessByPID(), SysGetProcessPriority(), SysGetThreadByTID(), SysGetThreadPriority(), SysSetProcessPriority(), SysSetThreadPriority(), and TriggerUserModeCrash().