Fennix Project: FileSystem::USTAR Class Reference
FileSystem::USTAR Class Reference
#include <filesystem.h>
Data Structures
struct FileHeader
Public Member Functions
USTAR (uint64_t Address)
~USTAR ()
Private Types
enum FileType {
REGULAR_FILE = '0', HARDLINK = '1', SYMLINK = '2', CHARDEV = '3',
BLOCKDEV = '4', DIRECTORY = '5', FIFO = '6'
}
Private Member Functions
uint32_t getsize (string s)
int string2int (string str)
Detailed Description
Definition at line 217 of file filesystem.h.
Data Structure Documentation
FileSystem::USTAR::FileHeader
struct FileSystem::USTAR::FileHeader
Definition at line 230 of file filesystem.h.
Data Fields
char chksum[8]
char dev_maj[8]
char dev_min[8]
char gid[8]
char group[32]
char link[100]
char mode[8]
char mtime[12]
char name[100]
char owner[32]
char pad[12]
char prefix[155]
char signature[6]
char size[12]
char typeflag[1]
char uid[8]
char version[2]
Member Enumeration Documentation
FileType
enum FileSystem::USTAR::FileType private
Enumerator
REGULAR_FILE
HARDLINK
SYMLINK
CHARDEV
BLOCKDEV
DIRECTORY
FIFO
Definition at line 219 of file filesystem.h.
         {
             REGULAR_FILE = '0',
             HARDLINK = '1',
             SYMLINK = '2',
             CHARDEV = '3',
             BLOCKDEV = '4',
             DIRECTORY = '5',
             FIFO = '6'
         };
Constructor & Destructor Documentation
USTAR()
FileSystem::USTAR::USTAR (uint64_t Address)
Definition at line 23 of file ustar.cpp.
     {
         trace("INitializing USTAR with address %#llx", Address);
         if (memcmp(((FileHeader *)Address)->signature, "ustar", 5) != 0)
         {
             err("ustar signature invalid!");
             return;
         }
         debug("USTAR signature valid! Name:%s Signature:%s Mode:%c Size:%lu",
               ((FileHeader *)Address)->name,
               ((FileHeader *)Address)->signature,
               string2int(((FileHeader *)Address)->mode),
               ((FileHeader *)Address)->size);
         vfs->CreateRoot(&ustar, "/");
         uint64_t errorsallowed = 20;
         for (uint64_t i = 0;; i++)
         {
             FileHeader *header = (FileHeader *)Address;
             if (memcmp(((FileHeader *)Address)->signature, "ustar", 5) != 0)
                 break;
             memmove(header->name, header->name + 1, strlen(header->name));
             if (header->name[strlen(header->name) - 1] == '/')
                 header->name[strlen(header->name) - 1] = 0;
             uint64_t size = getsize(header->size);
             FileSystemNode *node = vfs->Create(nullptr, header->name);
             if (node == nullptr)
             {
                 if (errorsallowed > 0)
                 {
                     errorsallowed--;
                     goto NextFileAddress;
                 }
                 else
                 {
                     err("Adding USTAR files failed because too many files were corrputed or invalid.");
                     break;
                 }
             }
             else
             {
                 trace("%s %dKB Type:%c", header->name, TO_KB(size), header->typeflag[0]);
                 node->Mode = string2int(header->mode);
                 node->Address = (Address + 512);
                 node->Length = size;
                 node->GroupIdentifier = getsize(header->gid);
                 node->UserIdentifier = getsize(header->uid);
                 node->IndexNode = i;
                 switch (header->typeflag[0])
                 {
                 case REGULAR_FILE:
                     node->Flags = NodeFlags::FS_FILE;
                     break;
                 case SYMLINK:
                     node->Flags = NodeFlags::FS_SYMLINK;
                     break;
                 case DIRECTORY:
                     node->Flags = NodeFlags::FS_DIRECTORY;
                     break;
                 case CHARDEV:
                     node->Flags = NodeFlags::FS_CHARDEVICE;
                     break;
                 case BLOCKDEV:
                     node->Flags = NodeFlags::FS_BLOCKDEVICE;
                     break;
                 default:
                     warn("Unknown type: %d", header->typeflag[0]);
                     break;
                 }
             NextFileAddress:
                 Address += ((size / 512) + 1) * 512;
                 if (size % 512)
                     Address += 512;
             }
         }
     }
References FileSystem::FileSystemNode::Address, Address, BLOCKDEV, CHARDEV, FileSystem::Virtual::Create(), FileSystem::Virtual::CreateRoot(), debug, DIRECTORY, err, FileSystem::FileSystemNode::Flags, FS_BLOCKDEVICE, FS_CHARDEVICE, FS_DIRECTORY, FS_FILE, FS_SYMLINK, getsize(), FileSystem::FileSystemNode::GroupIdentifier, header, FileSystem::FileSystemNode::IndexNode, FileSystem::FileSystemNode::Length, memcmp(), memmove(), FileSystem::FileSystemNode::Mode, REGULAR_FILE, string2int(), strlen(), SYMLINK, TO_KB, trace, FileSystem::FileSystemNode::UserIdentifier, FileSystem::ustar, vfs, and warn.
~USTAR()
FileSystem::USTAR::~USTAR ()
Definition at line 104 of file ustar.cpp.
 { warn("Destroyed"); }
References warn.
Member Function Documentation
getsize()
uint32_t FileSystem::USTAR::getsize (string s) inline private
Definition at line 252 of file filesystem.h.
         {
             uint64_t ret = 0;
             while (*s)
             {
                 ret *= 8;
                 ret += *s - '0';
                 s++;
             }
             return ret;
         }
Referenced by USTAR().
string2int()
int FileSystem::USTAR::string2int (string str) inline private
Definition at line 264 of file filesystem.h.
         {
             int res = 0;
             for (int i = 0; str[i] != '\0'; ++i)
                 res = res * 10 + str[i] - '0';
             return res;
         }
Referenced by USTAR().
The documentation for this class was generated from the following files:
kernel/include/filesystem.h
kernel/filesystem/fs/ustar.cpp