Fennix Project: kernel/mem/buddyalloc/buddy_alloc.h File Reference
buddy_alloc.h File Reference
#include <limits.h>
#include <types.h>
#include <debug.h>
#include <string.h>
Macros
#define BUDDY_ALLOC_H
Functions
size_t buddy_sizeof (size_t memory_size)
struct buddy * buddy_init (unsigned char *at, unsigned char *main, size_t memory_size)
struct buddy * buddy_embed (unsigned char *main, size_t memory_size)
struct buddy * buddy_resize (struct buddy *buddy, size_t new_memory_size)
unsigned int buddy_can_shrink (struct buddy *buddy)
unsigned int buddy_is_empty (struct buddy *buddy)
size_t buddy_arena_size (struct buddy *buddy)
void * buddy_malloc (struct buddy *buddy, size_t requested_size)
void * buddy_calloc (struct buddy *buddy, size_t members_count, size_t member_size)
void * buddy_realloc (struct buddy *buddy, void *ptr, size_t requested_size)
void * buddy_reallocarray (struct buddy *buddy, void *ptr, size_t members_count, size_t member_size)
void buddy_free (struct buddy *buddy, void *ptr)
void buddy_safe_free (struct buddy *buddy, void *ptr, size_t requested_size)
void * buddy_walk (struct buddy *buddy, void *(fp)(void *ctx, void *addr, size_t slot_size), void *ctx)
Macro Definition Documentation
BUDDY_ALLOC_H
#define BUDDY_ALLOC_H
Definition at line 23 of file buddy_alloc.h.
Function Documentation
buddy_arena_size()
size_t buddy_arena_size (struct buddy * buddy)
buddy_calloc()
void* buddy_calloc (struct buddy * buddy, size_t members_count, size_t member_size)
Referenced by HeapCalloc().
buddy_can_shrink()
unsigned int buddy_can_shrink (struct buddy * buddy)
buddy_embed()
struct buddy* buddy_embed (unsigned char * main, size_t memory_size)
buddy_free()
void buddy_free (struct buddy * buddy, void * ptr)
Referenced by HeapFree().
buddy_init()
struct buddy* buddy_init (unsigned char * at, unsigned char * main, size_t memory_size)
Referenced by init_heap().
buddy_is_empty()
unsigned int buddy_is_empty (struct buddy * buddy)
buddy_malloc()
void* buddy_malloc (struct buddy * buddy, size_t requested_size)
Referenced by HeapMalloc().
buddy_realloc()
void* buddy_realloc (struct buddy * buddy, void * ptr, size_t requested_size)
Referenced by HeapRealloc().
buddy_reallocarray()
void* buddy_reallocarray (struct buddy * buddy, void * ptr, size_t members_count, size_t member_size)
buddy_resize()
struct buddy* buddy_resize (struct buddy * buddy, size_t new_memory_size)
buddy_safe_free()
void buddy_safe_free (struct buddy * buddy, void * ptr, size_t requested_size)
buddy_sizeof()
size_t buddy_sizeof (size_t memory_size)
Referenced by init_heap().
buddy_walk()
void* buddy_walk (struct buddy * buddy, void * fp)(void *ctx, void *addr, size_t slot_size, void * ctx)