Fennix Project: libc/include/convert.h File Reference
convert.h File Reference
#include <cdefs.h>
Functions
E int abs (int i)
Returns the absolute value of an integer.
E void swap (char *x, char *y)
Exchange values of two objects.
E char * reverse (char *Buffer, int i, int j)
E int atoi (const char *String)
Convert string to integer.
E double atof (const char *String)
Convert string to double.
E char * itoa (int Value, char *Buffer, int Base)
Convert integer to string.
Function Documentation
abs()
E int abs (int i)
Returns the absolute value of an integer.
Parameters
i Integral value.
Returns
Absolute value of i.
Definition at line 6 of file convert.c.
 { return i < 0 ? -i : i; }
Referenced by itoa().
atof()
E double atof (const char * String)
Convert string to double.
Parameters
String String to convert to double.
Returns
Converted floating point as a double value.
Definition at line 36 of file convert.c.
 {
     double a = 0.0;
     int e = 0;
     int c;
     while ((c = *String++) != '\0' && isdigit(c))
     {
         a = a * 10.0 + (c - '0');
     }
     if (c == '.')
     {
         while ((c = *String++) != '\0' && isdigit(c))
         {
             a = a * 10.0 + (c - '0');
             e = e - 1;
         }
     }
     if (c == 'e' || c == 'E')
     {
         int sign = 1;
         int i = 0;
         c = *String++;
         if (c == '+')
             c = *String++;
         else if (c == '-')
         {
             c = *String++;
             sign = -1;
         }
         while (isdigit(c))
         {
             i = i * 10 + (c - '0');
             c = *String++;
         }
         e += i * sign;
     }
     while (e > 0)
     {
         a *= 10.0;
         e--;
     }
     while (e < 0)
     {
         a *= 0.1;
         e++;
     }
     return a;
 }
References isdigit().
atoi()
E int atoi (const char * String)
Convert string to integer.
Parameters
String String to convert to integer.
Returns
Converted integral number as an int value.
Definition at line 22 of file convert.c.
 {
     uint64_t Length = strlen((char *)String);
     uint64_t OutBuffer = 0;
     uint64_t Power = 1;
     for (uint64_t i = Length; i > 0; --i)
     {
         OutBuffer += (String[i - 1] - 48) * Power;
         Power *= 10;
     }
     return OutBuffer;
 }
References Length, and strlen().
itoa()
E char* itoa (int Value, char * Buffer, int Base)
Convert integer to string.
Parameters
Value Value to be converted to a string.
Buffer Array in memory where to store the resulting null-terminated string.
Base Numerical base used to represent the value as a string, between 2 and 36, where 10 means decimal base, 16 hexadecimal, 8 octal, and 2 binary.
Returns
A pointer to the resulting null-terminated string.
Definition at line 85 of file convert.c.
 {
     if (Base < 2 || Base > 32)
         return Buffer;
     int n = abs(Value);
     int i = 0;
     while (n)
     {
         int r = n % Base;
         if (r >= 10)
             Buffer[i++] = 65 + (r - 10);
         else
             Buffer[i++] = 48 + r;
         n = n / Base;
     }
     if (i == 0)
         Buffer[i++] = '0';
     if (Value < 0 && Base == 10)
         Buffer[i++] = '-';
     Buffer[i] = '\0';
     return reverse(Buffer, 0, i - 1);
 }
References abs(), and reverse().
Referenced by ParseBuffer().
reverse()
E char* reverse (char * Buffer, int i, int j)
Parameters
Buffer
i
j
Returns
char*
Definition at line 15 of file convert.c.
 {
     while (i < j)
         swap(&Buffer[i++], &Buffer[j--]);
     return Buffer;
 }
References swap().
Referenced by itoa().
swap()
E void swap (char * x, char * y)
Exchange values of two objects.
Parameters
x
y
Returns
void
Definition at line 8 of file convert.c.
 {
     char t = *x;
     *x = *y;
     *y = t;
 }
Referenced by reverse().