Fennix Project: NetworkIPv4::IPv4 Class Reference
NetworkIPv4::IPv4 Class Reference
#include <NetworkController.hpp>
Public Member Functions
IPv4 (NetworkARP::ARP *ARP, NetworkEthernet::Ethernet *Ethernet)
~IPv4 ()
void Send (uint8_t *Data, uint64_t Length, uint8_t Protocol, InternetProtocol4 DestinationIP)
Send an IPv4 packet.
Public Member Functions inherited from NetworkEthernet::EthernetEvents
FrameType GetFrameType ()
virtual void OnEthernetPacketSent (EthernetPacket *Packet)
Data Fields
InternetProtocol4 GatewayIP = {.Address = {0xFF, 0xFF, 0xFF, 0xFF}}
InternetProtocol4 SubnetworkMaskIP = {.Address = {0xFF, 0xFF, 0xFF, 0xFF}}
Private Member Functions
virtual bool OnEthernetPacketReceived (uint8_t *Data, uint64_t Length)
Private Attributes
NetworkARP::ARP * ARP
NetworkEthernet::Ethernet * Ethernet
Additional Inherited Members
Protected Member Functions inherited from NetworkEthernet::EthernetEvents
EthernetEvents (FrameType Type)
~EthernetEvents ()
Detailed Description
Definition at line 456 of file NetworkController.hpp.
Constructor & Destructor Documentation
IPv4()
NetworkIPv4::IPv4::IPv4 (NetworkARP::ARP * ARP, NetworkEthernet::Ethernet * Ethernet)
Definition at line 7 of file InternetProtocol.cpp.
                                                                     : NetworkEthernet::EthernetEvents(NetworkEthernet::TYPE_IPV4)
     {
         netdbg("IPv4: Initializing.");
         this->ARP = ARP;
         this->Ethernet = Ethernet;
     }
References ARP, Ethernet, and netdbg.
~IPv4()
NetworkIPv4::IPv4::~IPv4 ()
Definition at line 14 of file InternetProtocol.cpp.
     {
     }
Member Function Documentation
OnEthernetPacketReceived()
bool NetworkIPv4::IPv4::OnEthernetPacketReceived (uint8_t * Data, uint64_t Length) private virtual
Reimplemented from NetworkEthernet::EthernetEvents.
Definition at line 50 of file InternetProtocol.cpp.
     {
         IPv4Packet *Packet = (IPv4Packet *)Data;
         netdbg("IPv4: Received %d bytes [Protocol %ld]", Length, Packet->Header.Protocol);
         if (Length < sizeof(IPv4Header))
         {
             warn("IPv4: Packet too short");
             return false;
         }
         bool Reply = false;
         if (Packet->Header.DestinationIP == Ethernet->GetInterface()->IP.ToHex() || Packet->Header.DestinationIP == 0xFFFFFFFF || Ethernet->GetInterface()->IP.ToHex() == 0)
         {
             uint64_t TotalLength = Packet->Header.TotalLength;
             if (TotalLength > Length)
                 TotalLength = Length;
             foreach (auto Event in RegisteredEvents)
                 if (Packet->Header.Protocol == Event->GetProtocol())
                     if (Event->OnIPv4PacketReceived(InternetProtocol4().FromHex(b32(Packet->Header.SourceIP)), InternetProtocol4().FromHex(b32(Packet->Header.DestinationIP)), (uint8_t *)((uint64_t)Data + 4 * Packet->Header.IHL), TotalLength - 4 * Packet->Header.IHL))
                         Reply = true;
         }
         if (Reply)
         {
             uint32_t SwapIP = Packet->Header.DestinationIP;
             Packet->Header.DestinationIP = Packet->Header.SourceIP;
             Packet->Header.SourceIP = SwapIP;
             Packet->Header.TimeToLive = 0x40;
             Packet->Header.HeaderChecksum = 0x0;
             Packet->Header.HeaderChecksum = CalculateChecksum((uint16_t *)Data, 4 * Packet->Header.TotalLength);
             Ethernet->GetInterface()->Send((uint8_t *)Data, Length);
         }
         return Reply;
     }
References b32, CalculateChecksum(), Data, Ethernet, NetworkEthernet::Ethernet::GetInterface(), NetworkInterfaceManager::DeviceInterface::IP, Length, netdbg, PS2Mouse::Packet, NetworkIPv4::RegisteredEvents, NetworkInterfaceManager::DeviceInterface::Send(), InternetProtocol4::ToHex(), and warn.
Send()
void NetworkIPv4::IPv4::Send (uint8_t * Data, uint64_t Length, uint8_t Protocol, InternetProtocol4 DestinationIP)
Send an IPv4 packet.
Parameters
Data The data to send.
Length The length of the data.
Protocol The protocol of the packet.
DestinationIP The IP address of the destination. (Big-endian)
Definition at line 18 of file InternetProtocol.cpp.
     {
         netdbg("IPv4: Sending %ld bytes to %d.%d.%d.%d", Length, DestinationIP.Address[0], DestinationIP.Address[1], DestinationIP.Address[2], DestinationIP.Address[3]);
         IPv4Packet *Packet = (IPv4Packet *)kmalloc(Length + sizeof(IPv4Header));
         Packet->Header.Version = 4;
         Packet->Header.IHL = sizeof(IPv4Header) / 4;
         Packet->Header.TypeOfService = 0;
         Packet->Header.TotalLength = Length + sizeof(IPv4Header);
         Packet->Header.TotalLength = ((Packet->Header.TotalLength & 0xFF00) >> 8) | ((Packet->Header.TotalLength & 0x00FF) << 8);
         Packet->Header.Identification = 0;
         // Packet->Header.Flags = 0x0;
         // Packet->Header.FragmentOffset = 0x0;
         Packet->Header.FlagsAndFragmentOffset = 0x0;
         Packet->Header.TimeToLive = 64;
         Packet->Header.Protocol = Protocol;
         Packet->Header.DestinationIP = b32(DestinationIP.ToHex());
         Packet->Header.SourceIP = b32(Ethernet->GetInterface()->IP.ToHex());
         Packet->Header.HeaderChecksum = 0x0;
         Packet->Header.HeaderChecksum = CalculateChecksum((uint16_t *)Packet, sizeof(IPv4Header));
         memcpy(Packet->Data, Data, Length);
         InternetProtocol4 DestinationRoute = DestinationIP;
         if ((b32(DestinationIP.ToHex()) & SubnetworkMaskIP.ToHex()) != (Packet->Header.SourceIP & SubnetworkMaskIP.ToHex()))
             DestinationRoute = SubnetworkMaskIP;
         Ethernet->Send(MediaAccessControl().FromHex(ARP->Resolve(DestinationRoute)), this->GetFrameType(), (uint8_t *)Packet, Length + sizeof(IPv4Header));
         kfree(Packet);
     }
References InternetProtocol4::Address, ARP, b32, CalculateChecksum(), Data, Ethernet, NetworkEthernet::Ethernet::GetInterface(), NetworkInterfaceManager::DeviceInterface::IP, kfree, kmalloc, Length, memcpy(), netdbg, PS2Mouse::Packet, NetworkARP::ARP::Resolve(), NetworkEthernet::Ethernet::Send(), SubnetworkMaskIP, and InternetProtocol4::ToHex().
Referenced by NetworkUDP::UDP::Send().
Field Documentation
ARP
NetworkARP::ARP* NetworkIPv4::IPv4::ARP private
Definition at line 459 of file NetworkController.hpp.
Referenced by IPv4(), and Send().
Ethernet
NetworkEthernet::Ethernet* NetworkIPv4::IPv4::Ethernet private
Definition at line 460 of file NetworkController.hpp.
Referenced by IPv4(), OnEthernetPacketReceived(), and Send().
GatewayIP
InternetProtocol4 NetworkIPv4::IPv4::GatewayIP = {.Address = {0xFF, 0xFF, 0xFF, 0xFF}}
Definition at line 465 of file NetworkController.hpp.
Referenced by NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
SubnetworkMaskIP
InternetProtocol4 NetworkIPv4::IPv4::SubnetworkMaskIP = {.Address = {0xFF, 0xFF, 0xFF, 0xFF}}
Definition at line 466 of file NetworkController.hpp.
Referenced by Send(), and NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
The documentation for this class was generated from the following files:
kernel/network/NetworkController.hpp
kernel/network/InternetProtocol.cpp