Fennix Project: Tasking::Monotasking Class Reference
Tasking::Monotasking Class Reference
#include <internal_task.h>
Public Member Functions
TaskControlBlock * CreateTask (uint64_t InstructionPointer, uint64_t FirstArgument, uint64_t SecondArgument, char *Name, bool UserMode)
Create a new Task.
void KillMe ()
Kill the current Task.
void PushTask (uint64_t rip)
Move to the next Task and suspending the current.
void PopTask ()
Move to the previous Task and suspending the current.
Monotasking (uint64_t FirstTask)
Construct a new Mono Tasking object.
~Monotasking ()
Destroy the Mono Tasking object (Make sure that all other processes are destroyed and no stack is used!)
Detailed Description
Definition at line 46 of file internal_task.h.
Constructor & Destructor Documentation
Monotasking()
Tasking::Monotasking::Monotasking (uint64_t FirstTask)
Construct a new Mono Tasking object.
Parameters
firstThread The first Instruction Pointer to be executed
Definition at line 337 of file Monotasking.cpp.
     {
         for (uint64_t i = 0; i < MAX_TASKS; i++)
             TaskQueue[i] = nullptr; // Make sure that all tasks have value nullptr
         CreateTask((uint64_t)FirstTask, 0, 0, (char *)"kernel", false);
         CurrentTaskingMode = TaskingMode::Mono;
         // apic->RedirectIRQ(0, SchedulerInterrupt - 32, 1);
         SchedulerInterrupt;
     }
References CreateTask(), CurrentTaskingMode, MAX_TASKS, Mono, SchedulerInterrupt, and Tasking::TaskQueue.
~Monotasking()
Tasking::Monotasking::~Monotasking ()
Destroy the Mono Tasking object (Make sure that all other processes are destroyed and no stack is used!)
Definition at line 347 of file Monotasking.cpp.
     {
         for (uint64_t i = 0; i < MAX_TASKS; i++)
         {
             if (TaskQueue[i] == nullptr)
                 continue;
             if (TaskQueue[i] == CurrentTask)
                 continue; // We ignore the current task because it's the task that invoked the unitialization.
             TaskControlBlock *task = TaskQueue[i];
             trace("Task %s has been forcibly terminated and removed.", task->name);
             FreeTask(task);
             CurrentTaskingMode = TaskingMode::None;
         }
     }
References Tasking::CurrentTask, CurrentTaskingMode, Tasking::FreeTask(), MAX_TASKS, Tasking::TaskControlBlock::name, None, Tasking::TaskQueue, and trace.
Member Function Documentation
CreateTask()
TaskControlBlock * Tasking::Monotasking::CreateTask (uint64_t InstructionPointer, uint64_t FirstArgument, uint64_t SecondArgument, char * Name, bool UserMode)
Create a new Task.
Parameters
rip Instruction Pointer
args0 First argument
args1 Second argument
name The name of the new Task
Returns
The new created Task
Definition at line 195 of file Monotasking.cpp.
     {
         TaskControlBlock *task = new TaskControlBlock;
         task->id = TaskIDs++;
         memcpy(((char *)task->name), Name, sizeof(task->name));
         task->checksum = TASK_CHECKSUM;
         task->UserMode = UserMode;
         task->state = TaskState::TaskStateReady;
         task->stack = KernelStackAllocator->AllocateStack(UserMode);
         task->pml4 = KernelPageTableAllocator->CreatePageTable(UserMode);
         memset(&task->regs, 0, sizeof(TrapFrame));
         if (!UserMode)
         {
             task->regs.ss = GDT_KERNEL_DATA;
             task->regs.cs = GDT_KERNEL_CODE;
             task->gs = (uint64_t)task;
             task->fs = rdmsr(MSR_FS_BASE);
             task->regs.rflags.always_one = 1;
             task->regs.rflags.IF = 1;
             task->regs.rflags.ID = 1;
             task->regs.STACK = (uint64_t)task->stack;
             POKE(uint64_t, task->regs.rsp) = (uint64_t)MonoTaskingTaskExit;
         }
         else
         {
             task->regs.cs = GDT_USER_CODE;
             task->regs.ss = GDT_USER_DATA;
             task->gs = 0;
             task->fs = rdmsr(MSR_FS_BASE);
             task->regs.rflags.always_one = 1;
             task->regs.rflags.IF = 1;
             task->regs.rflags.ID = 1;
             task->regs.STACK = (uint64_t)task->stack;
         }
         task->regs.FUNCTION = (uint64_t)InstructionPointer;
         task->regs.ARG0 = (uint64_t)FirstArgument;
         task->regs.ARG1 = (uint64_t)SecondArgument;
         task->SpawnTick = counter();
         uint32_t t = 0;
         outb(0x70, 0x00);
         t = inb(0x71);
         task->Second = ((t & 0x0F) + ((t >> 4) * 10));
         outb(0x70, 0x02);
         t = inb(0x71);
         task->Minute = ((t & 0x0F) + ((t >> 4) * 10));
         outb(0x70, 0x04);
         t = inb(0x71);
         task->Hour = ((t & 0x0F) + ((t >> 4) * 10));
         outb(0x70, 0x07);
         t = inb(0x71);
         task->Day = ((t & 0x0F) + ((t >> 4) * 10));
         outb(0x70, 0x08);
         t = inb(0x71);
         task->Month = ((t & 0x0F) + ((t >> 4) * 10));
         outb(0x70, 0x09);
         t = inb(0x71);
         task->Year = ((t & 0x0F) + ((t >> 4) * 10));
         trace("Task %s has been created. (IP %#llx)", task->name, InstructionPointer);
         AllocateTask(task);
         return task;
     }
References Tasking::AllocateTask(), Tasking::TaskControlBlock::checksum, counter(), Tasking::TaskControlBlock::Day, Tasking::TaskControlBlock::fs, GDT_KERNEL_CODE, GDT_KERNEL_DATA, GDT_USER_CODE, GDT_USER_DATA, Tasking::TaskControlBlock::gs, Tasking::TaskControlBlock::Hour, Tasking::TaskControlBlock::id, inb, KernelPageTableAllocator, KernelStackAllocator, memcpy(), memset(), Tasking::TaskControlBlock::Minute, Tasking::TaskControlBlock::Month, MSR_FS_BASE, Tasking::TaskControlBlock::name, outb, Tasking::TaskControlBlock::pml4, POKE, rdmsr(), Tasking::TaskControlBlock::regs, Tasking::TaskControlBlock::Second, Tasking::TaskControlBlock::SpawnTick, Tasking::TaskControlBlock::stack, Tasking::TaskControlBlock::state, TASK_CHECKSUM, Tasking::TaskIDs, Tasking::TaskStateReady, trace, Tasking::TaskControlBlock::UserMode, and Tasking::TaskControlBlock::Year.
Referenced by internal_createtask(), Monotasking(), and SysCreateProcessFromFile().
KillMe()
void Tasking::Monotasking::KillMe ()
Kill the current Task.
Definition at line 259 of file Monotasking.cpp.
     {
         CurrentTask->state = TaskState::TaskStateTerminated;
         trace("Task %s commited suicide.", CurrentTask->name);
         for (uint64_t i = 0; i < MAX_TASKS; i++)
             if (CurrentTask == TaskQueue[i])
                 if (TaskQueue[i - 1] != nullptr &&
                     TaskQueue[i - 1]->checksum == TASK_CHECKSUM)
                     this->PopTask();
         SchedulerInterrupt;
         CPU_STOP;
     }
References CPU_STOP, Tasking::CurrentTask, MAX_TASKS, Tasking::TaskControlBlock::name, PopTask(), SchedulerInterrupt, Tasking::TaskControlBlock::state, TASK_CHECKSUM, Tasking::TaskQueue, Tasking::TaskStateTerminated, and trace.
Referenced by internal_exit().
PopTask()
void Tasking::Monotasking::PopTask ()
Move to the previous Task and suspending the current.
Definition at line 306 of file Monotasking.cpp.
     {
         if (TaskQueue[0] == CurrentTask)
         {
             err("The current task is the first task in queue.");
             return;
         }
         for (uint64_t i = 0; i < MAX_TASKS; i++)
         {
             if (TaskQueue[i] == nullptr)
                 continue;
             if (TaskQueue[i]->checksum != TASK_CHECKSUM)
                 continue;
             if (CurrentTask == TaskQueue[i])
             {
                 if (TaskQueue[i - 1] == nullptr)
                     continue;
                 if (TaskQueue[i - 1]->checksum != TASK_CHECKSUM)
                     continue;
                 if (TaskQueue[i]->state != TaskState::TaskStateTerminated)
                     TaskQueue[i]->state = TaskState::TaskPoped;
                 TaskQueue[i - 1]->state = TaskState::TaskStateReady;
                 trace("Task popped to %s.", TaskQueue[i - 1]->name);
                 SchedulerInterrupt;
                 return;
             }
         }
         err("Cannot move to the previous task.");
     }
References Tasking::CurrentTask, err, MAX_TASKS, SchedulerInterrupt, Tasking::TaskControlBlock::state, TASK_CHECKSUM, Tasking::TaskPoped, Tasking::TaskQueue, Tasking::TaskStateReady, Tasking::TaskStateTerminated, and trace.
Referenced by internal_poptask(), and KillMe().
PushTask()
void Tasking::Monotasking::PushTask (uint64_t rip)
Move to the next Task and suspending the current.
Definition at line 274 of file Monotasking.cpp.
     {
         if (FindLastTask() == CurrentTask)
         {
             err("The current task is the last task in queue.");
             return;
         }
         for (uint64_t i = 0; i < MAX_TASKS; i++)
         {
             if (TaskQueue[i] == nullptr)
                 continue;
             if (TaskQueue[i]->checksum != TASK_CHECKSUM)
                 continue;
             if (CurrentTask == TaskQueue[i])
             {
                 if (TaskQueue[i + 1] == nullptr)
                     continue;
                 if (TaskQueue[i + 1]->checksum != TASK_CHECKSUM)
                     continue;
                 if (TaskQueue[i]->state != TaskState::TaskStateTerminated)
                     TaskQueue[i]->state = TaskState::TaskPushed;
                 TaskQueue[i + 1]->state = TaskState::TaskStateReady;
                 // CurrentTask->regs.rip = rip; // i need to find anoter way to get the instruction pointer
                 trace("Task pushed to %s with instruction pointer %#llx.", TaskQueue[i + 1]->name, rip);
                 SchedulerInterrupt;
                 return;
             }
         }
         err("Cannot move to the next task.");
     }
References Tasking::CurrentTask, err, Tasking::FindLastTask(), MAX_TASKS, SchedulerInterrupt, Tasking::TaskControlBlock::state, TASK_CHECKSUM, Tasking::TaskPushed, Tasking::TaskQueue, Tasking::TaskStateReady, Tasking::TaskStateTerminated, and trace.
Referenced by internal_pushtask().
The documentation for this class was generated from the following files:
kernel/include/internal_task.h
kernel/proc/Monotasking.cpp