Fennix Project: BootScreen Namespace Reference
BootScreen Namespace Reference
Data Structures
class Screen
Functions
static void bootscreenprint_wrapper (char c, void *unused)
int bootscreenhelper_vprintf (const char *format, va_list list)
void bootscreenprint (const char *format,...)
Variables
Display * BootDisplay = nullptr
Function Documentation
bootscreenhelper_vprintf()
int BootScreen::bootscreenhelper_vprintf (const char * format, va_list list)
Definition at line 106 of file BootScreen.cpp.
 { return vfctprintf(bootscreenprint_wrapper, NULL, format, list); }
References bootscreenprint_wrapper(), and vfctprintf().
Referenced by bootscreenprint().
bootscreenprint()
void BootScreen::bootscreenprint (const char * format, ...)
Definition at line 108 of file BootScreen.cpp.
     {
         va_list args;
         va_start(args, format);
         bootscreenhelper_vprintf(format, args);
         va_end(args);
     }
References bootscreenhelper_vprintf(), va_end, and va_start.
bootscreenprint_wrapper()
static void BootScreen::bootscreenprint_wrapper (char c, void * unused) inline static
Definition at line 100 of file BootScreen.cpp.
     {
         (void)unused;
         BootDisplay->KernelPrint(c);
     }
References BootDisplay.
Referenced by bootscreenhelper_vprintf().
Variable Documentation
BootDisplay
Display* BootScreen::BootDisplay = nullptr
Definition at line 98 of file BootScreen.cpp.
Referenced by bootscreenprint_wrapper(), BootScreen::Screen::DrawVendorLogo(), BootScreen::Screen::FadeLogo(), BootScreen::Screen::Progress(), and BootScreen::Screen::Screen().