Fennix Project: libc/src/FennixStandardLibrary/print.c File Reference
print.c File Reference
#include <print.h>
#include "../printf.h"
#include <string.h>
#include <system.h>
#include <syscalls.h>
Functions
static void append_printf (char s[], char n)
static void syswritedbgprint_wrapper (char c, void *unused)
int fprintf (FILE *Stream, const char *Format,...)
int sprintf (char *s, const char *format,...)
int printf (const char *Format,...)
int vfprintf (FILE *Stream, const char *Format, va_list Args)
int vprintf (const char *Format, va_list Args)
int snprintf (char *String, size_t Length, const char *Format,...)
int vsnprintf (char *String, size_t Length, const char *Format, va_list Args)
int vsscanf (const char *String, const char *Format, va_list Args)
int sscanf (const char *String, const char *Format,...)
int fputs (const char *String, FILE *Stream)
int puts (const char *String)
int fputc (int Char, FILE *Stream)
int putchar (int Char)
int fflush (FILE *stream)
Variables
FILE * fslin
FILE * fslout
FILE * fslerr
Function Documentation
append_printf()
static void append_printf (char s[], char n) inline static
Definition at line 13 of file print.c.
 {
     long unsigned i = 0;
     while (s[i] != '\0')
         ++i;
     int len = i;
     s[len] = n;
     s[len + 1] = '\0';
 }
References len.
Referenced by fputc(), fputs(), putchar(), puts(), and syswritedbgprint_wrapper().
fflush()
int fflush (FILE * stream)
Definition at line 172 of file print.c.
 {
     WriteSysDebugger("fflush( %p ) stub\n", stream);
     syscall_dbg(0x3F8, (char *)"\nfslout: ");
     syscall_dbg(0x3F8, (char *)fslout->PrintBuffer);
     syscall_dbg(0x3F8, (char *)"\nfslerr: ");
     syscall_dbg(0x3F8, (char *)fslerr->PrintBuffer);
     syscall_dbg(0x3F8, (char *)"\n");
     fslout->PrintBuffer[0] = '\0';
     fslerr->PrintBuffer[0] = '\0';
     return 0;
 }
References fslerr, fslout, _FILE::PrintBuffer, and WriteSysDebugger().
fprintf()
int fprintf (FILE * Stream, const char * Format, ...)
Definition at line 29 of file print.c.
 {
     WriteSysDebugger("fprintf( %p %s ) stub\n", Stream, Format);
     return 0;
 }
References WriteSysDebugger().
Referenced by cag_option_print(), cag_option_print_letters(), cag_option_print_name(), and cag_option_print_value().
fputc()
int fputc (int Char, FILE * Stream)
Definition at line 160 of file print.c.
 {
     append_printf(Stream->PrintBuffer, Char);
     return Char;
 }
References append_printf(), and _FILE::PrintBuffer.
fputs()
int fputs (const char * String, FILE * Stream)
Definition at line 145 of file print.c.
 {
     size_t i = 0;
     for (i = 0; i < strlen((char *)String); i++)
         append_printf(Stream->PrintBuffer, String[i]);
     return i;
 }
References append_printf(), _FILE::PrintBuffer, and strlen().
Referenced by cag_option_print(), and puts().
printf()
int printf (const char * Format, ...)
Definition at line 41 of file print.c.
 {
     va_list Args;
     va_start(Args, Format);
     int ret = vfctprintf(syswritedbgprint_wrapper, 0, Format, Args);
     va_end(Args);
     return ret;
 }
References syswritedbgprint_wrapper(), va_end, va_start, and vfctprintf().
putchar()
int putchar (int Char)
Definition at line 166 of file print.c.
 {
     append_printf(fslout->PrintBuffer, Char);
     return 0;
 }
References append_printf(), fslout, and _FILE::PrintBuffer.
puts()
int puts (const char * String)
Definition at line 153 of file print.c.
 {
     int ret = fputs(String, fslout);
     append_printf(fslout->PrintBuffer, '\n');
     return ret;
 }
References append_printf(), fputs(), fslout, and _FILE::PrintBuffer.
snprintf()
int snprintf (char * String, size_t Length, const char * Format, ...)
Definition at line 60 of file print.c.
 {
     va_list Args;
     va_start(Args, Format);
     int ret = snprintf_(String, Length, Format, Args);
     va_end(Args);
     return ret;
 }
References Length, snprintf_(), va_end, and va_start.
sprintf()
int sprintf (char * s, const char * format, ...)
Definition at line 35 of file print.c.
 {
     WriteSysDebugger("sprintf( %p %s ) stub\n", s, format);
     return 0;
 }
References WriteSysDebugger().
sscanf()
int sscanf (const char * String, const char * Format, ...)
Definition at line 136 of file print.c.
 {
     va_list Args;
     va_start(Args, Format);
     int ret = vsscanf(String, Format, Args);
     va_end(Args);
     return ret;
 }
References va_end, va_start, and vsscanf().
syswritedbgprint_wrapper()
static void syswritedbgprint_wrapper (char c, void * unused) inline static
Definition at line 23 of file print.c.
 {
     append_printf(fslout->PrintBuffer, c);
     (void)unused;
 }
References append_printf(), fslout, and _FILE::PrintBuffer.
Referenced by printf(), vfprintf(), and vprintf().
vfprintf()
int vfprintf (FILE * Stream, const char * Format, va_list Args)
Definition at line 50 of file print.c.
 {
     return vfctprintf(syswritedbgprint_wrapper, 0, Format, Args);
 }
References syswritedbgprint_wrapper(), and vfctprintf().
vprintf()
int vprintf (const char * Format, va_list Args)
Definition at line 55 of file print.c.
 {
     return vfctprintf(syswritedbgprint_wrapper, 0, Format, Args);
 }
References syswritedbgprint_wrapper(), and vfctprintf().
vsnprintf()
int vsnprintf (char * String, size_t Length, const char * Format, va_list Args)
Definition at line 69 of file print.c.
 {
     return vsnprintf_(String, Length, Format, Args);
 }
References Length, and vsnprintf_().
vsscanf()
int vsscanf (const char * String, const char * Format, va_list Args)
Definition at line 74 of file print.c.
 {
     int count = 0;
     for (;;)
     {
         char c = *Format++;
         if (!c)
             break;
         if (isspace(c))
             while (isspace(*String))
                 ++String;
         else if (c != '%')
         {
         match:
             if (*String == '\0')
                 goto end;
             if (*String != c)
                 goto fail;
             ++String;
         }
         else
         {
             c = *Format++;
             char type = c;
             switch (type)
             {
             case '%':
                 goto match;
             case 'd':
             {
                 int sign = 1;
                 c = *String++;
                 if (c == '\0')
                     goto end;
                 if (c == '-')
                 {
                     sign = -1;
                     c = *String++;
                 }
                 int n = 0;
                 while (isdigit(c))
                 {
                     n = n * 10 + c - '0';
                     c = *String++;
                 }
                 n *= sign;
                 --String;
                 int *result = va_arg(Args, int *);
                 *result = n;
                 ++count;
             }
             break;
             }
         }
     }
 fail:
     return count;
 end:
     return count ? count : -1;
 }
References isdigit(), isspace(), type, and va_arg.
Referenced by sscanf().
Variable Documentation
fslerr
FILE* fslerr
Definition at line 11 of file print.c.
Referenced by fflush().
fslin
FILE* fslin
Definition at line 9 of file print.c.
fslout
FILE* fslout
Definition at line 10 of file print.c.
Referenced by fflush(), putchar(), puts(), and syswritedbgprint_wrapper().