Fennix Project: kernel/timer/Timer.c File Reference
Timer.c File Reference
#include "../timer.h"
#include <interrupts.h>
#include <int.h>
#include <asm.h>
#include "apic_timer.h"
#include "hpet.h"
#include "pit.h"
#include "tsc.h"
#include "../cpu/idt.h"
Functions
void nsleep (uint64_t Nanoseconds)
void usleep (uint64_t Microseconds)
void msleep (uint64_t Miliseconds)
void sleep (uint64_t Seconds)
uint64_t counter ()
uint32_t get_timer_clock ()
InterruptHandler (timer_interrupt_handler)
void TimerOneShot (uint32_t Vector, uint64_t Miliseconds)
void init_timer ()
Variables
struct ActiveTimers active_timers
volatile uint64_t ticks = 0
Function Documentation
counter()
uint64_t counter ()
Definition at line 80 of file Timer.c.
 {
     if (APICTimer_initialized)
         return apictimer_read_counter();
     else if (HPET_initialized)
         return hpet_read_counter();
     else
         return ticks;
 }
References APICTimer_initialized, apictimer_read_counter(), HPET_initialized, hpet_read_counter(), and ticks.
Referenced by Tasking::Monotasking::CreateTask(), cwk_path_segment_back_will_be_removed(), cwk_path_segment_normal_will_be_removed(), Tasking::SetInfo(), and Tasking::UpdateTimeUsed().
get_timer_clock()
uint32_t get_timer_clock ()
Definition at line 90 of file Timer.c.
 {
     if (APICTimer_initialized)
         return apictimer_read_clock();
     else if (HPET_initialized)
         return get_clk();
     else
         return get_freq();
 }
References APICTimer_initialized, apictimer_read_clock(), get_clk(), get_freq(), and HPET_initialized.
init_timer()
void init_timer ()
Definition at line 122 of file Timer.c.
 {
     CRegisterInterrupt(timer_interrupt_handler, IRQ0, true);
     init_APICTimer();
     if (!APICTimer_initialized)
     {
         init_HPET();
         if (!HPET_initialized)
             init_pit();
     }
     if (APICTimer_initialized)
     {
         active_timers.APIC = true;
         debug("APIC timer is supported.");
     }
     else if (HPET_initialized)
     {
         active_timers.HPET = true;
         debug("HPET timer is supported.");
     }
     else if (PIC_initialized)
     {
         active_timers.PIT = true;
         debug("PIT timer is supported.");
     }
     else
     {
         active_timers.TSC = true;
         debug("TSC timer is supported.");
     }
 }
References active_timers, ActiveTimers::APIC, APICTimer_initialized, CRegisterInterrupt(), debug, ActiveTimers::HPET, HPET_initialized, init_APICTimer(), init_HPET(), init_pit(), PIC_initialized, ActiveTimers::PIT, and ActiveTimers::TSC.
Referenced by KernelInit().
InterruptHandler()
InterruptHandler (timer_interrupt_handler)
Definition at line 100 of file Timer.c.
 {
     if (APICTimer_initialized)
         return;
     else if (HPET_initialized)
         return;
     else if (PIC_initialized)
         ticks++;
 }
References APICTimer_initialized, HPET_initialized, PIC_initialized, and ticks.
msleep()
void msleep (uint64_t Miliseconds)
Definition at line 54 of file Timer.c.
 {
     if (APICTimer_initialized)
         apictimer_mwait(Miliseconds);
     else if (HPET_initialized)
         hpet_mwait(Miliseconds);
     else if (PIC_initialized)
         pit_wait(Miliseconds);
     else
         usleep(Miliseconds * 1000);
 }
References APICTimer_initialized, apictimer_mwait(), HPET_initialized, hpet_mwait(), PIC_initialized, pit_wait(), and usleep().
Referenced by sleep().
nsleep()
void nsleep (uint64_t Nanoseconds)
Definition at line 13 of file Timer.c.
 {
     if (APICTimer_initialized)
         apictimer_nwait(Nanoseconds);
     else if (HPET_initialized)
     {
         static int once = 0;
         if (!once++)
             warn("HPET is not supposed to work with nanoseconds!");
         hpet_uwait(Nanoseconds);
     }
     else if (PIC_initialized)
     {
         static int once = 0;
         if (!once++)
             warn("PIT is not supposed to work with nanoseconds!");
         pit_wait(Nanoseconds / 1000);
     }
     else
     {
         TSC_sleep(Nanoseconds);
     }
 }
References APICTimer_initialized, apictimer_nwait(), HPET_initialized, hpet_uwait(), PIC_initialized, pit_wait(), TSC_sleep(), and warn.
Referenced by usleep().
sleep()
void sleep (uint64_t Seconds)
Definition at line 66 of file Timer.c.
 {
     if (APICTimer_initialized)
         apictimer_wait(Seconds);
     else if (HPET_initialized)
         hpet_wait(Seconds);
     else if (PIC_initialized)
         pit_wait(Seconds * 1000);
     else
         msleep(Seconds * 1000000);
 }
References APICTimer_initialized, apictimer_wait(), HPET_initialized, hpet_wait(), msleep(), PIC_initialized, and pit_wait().
TimerOneShot()
void TimerOneShot (uint32_t Vector, uint64_t Miliseconds)
Definition at line 110 of file Timer.c.
 {
     if (APICTimer_initialized)
         APIC_oneshot(Vector, Miliseconds);
     else if (HPET_initialized)
         HPET_oneshot(Vector, Miliseconds);
     else if (PIC_initialized)
         pit_oneshot(Vector, Miliseconds);
     else
         TSC_oneshot(Vector, Miliseconds);
 }
References APIC_oneshot(), APICTimer_initialized, HPET_initialized, HPET_oneshot(), PIC_initialized, pit_oneshot(), and TSC_oneshot().
Referenced by Tasking::TriggerOneShot().
usleep()
void usleep (uint64_t Microseconds)
Definition at line 37 of file Timer.c.
 {
     if (APICTimer_initialized)
         apictimer_uwait(Microseconds);
     else if (HPET_initialized)
         hpet_uwait(Microseconds);
     else if (PIC_initialized)
     {
         static int once = 0;
         if (!once++)
             warn("PIT is not supposed to work with microseconds!");
         pit_wait(Microseconds / 1000);
     }
     else
         nsleep(Microseconds * 1000);
 }
References APICTimer_initialized, apictimer_uwait(), HPET_initialized, hpet_uwait(), nsleep(), PIC_initialized, pit_wait(), and warn.
Referenced by msleep().
Variable Documentation
active_timers
struct ActiveTimers active_timers
Definition at line 11 of file Timer.c.
Referenced by init_timer().
ticks
volatile uint64_t ticks = 0
Definition at line 78 of file Timer.c.
Referenced by counter(), InterruptHandler(), and pit_wait().