Fennix Project: kernel/syscalls/syscalls.hpp File Reference
syscalls.hpp File Reference
#include <stdint.h>
Data Structures
struct _SyscallsRegs
Macros
#define syscldbg(m, ...)
Typedefs
typedef struct _SyscallsRegs SyscallsRegs
Functions
uint64_t HandleFennixSyscalls (SyscallsRegs *regs)
uint64_t HandleLinuxSyscalls (SyscallsRegs *regs)
Data Structure Documentation
_SyscallsRegs
struct _SyscallsRegs
Definition at line 13 of file syscalls.hpp.
Data Fields
uint64_t cs
uint64_t error_code
uint64_t int_num
uint64_t r10
uint64_t r11
uint64_t r12
uint64_t r13
uint64_t r14
uint64_t r15
uint64_t r8
uint64_t r9
uint64_t rax
uint64_t rbp
uint64_t rbx
uint64_t rcx
uint64_t rdi
uint64_t rdx
uint64_t rflags
uint64_t rip
uint64_t rsi
uint64_t rsp
uint64_t ss
Macro Definition Documentation
syscldbg
#define syscldbg (m, ...)
Definition at line 10 of file syscalls.hpp.
Typedef Documentation
SyscallsRegs
typedef struct _SyscallsRegs SyscallsRegs
Function Documentation
HandleFennixSyscalls()
uint64_t HandleFennixSyscalls (SyscallsRegs * regs)
Definition at line 353 of file Native.cpp.
 {
     if (RAX > sizeof(FennixSyscallsTable))
     {
         return internal_unimpl(regs->rax, regs->rbx, regs->rcx, regs->rdx, regs->rsi, regs->rdi, regs->rbp);
     }
     uint64_t (*call)(uint64_t, ...) = reinterpret_cast<uint64_t (*)(uint64_t, ...)>(FennixSyscallsTable[RAX]);
     if (!call)
     {
         err("Syscall %#llx failed.", RAX);
         return failedcall;
     }
     syscldbg("SYSCALL->CALLDATA->(r:%lx a:%lx b:%lx c:%lx d:%lx S:%lx D:%lx)[CALLID:%d]", regs, RAX, RBX, RCX, RDX, RSI, RDI, RAX);
     uint64_t ret = call((uint64_t)regs, RBX, RDX, RSI, RDI);
     RAX = ret;
     return ret;
 }
References err, failedcall, FennixSyscallsTable, internal_unimpl(), _SyscallsRegs::rax, _SyscallsRegs::rbp, _SyscallsRegs::rbx, _SyscallsRegs::rcx, _SyscallsRegs::rdi, _SyscallsRegs::rdx, _SyscallsRegs::rsi, and syscldbg.
Referenced by syscall_handler().
HandleLinuxSyscalls()
uint64_t HandleLinuxSyscalls (SyscallsRegs * regs)
Definition at line 691 of file Linux.cpp.
 {
     if (RAX > sizeof(LinuxSyscallsTable))
     {
         return internal_unimpl(regs->rax, regs->rbx, regs->rcx, regs->rdx, regs->rsi, regs->rdi, regs->rbp);
     }
     uint64_t (*call)(uint64_t, ...) = reinterpret_cast<uint64_t (*)(uint64_t, ...)>(LinuxSyscallsTable[RAX]);
     if (!call)
     {
         err("Syscall %#llx failed.", RAX);
         return -1;
     }
     uint64_t ret = call(regs->int_num, 0, 0, 0, 0);
     RAX = ret;
     return ret;
 }
References err, _SyscallsRegs::int_num, internal_unimpl(), LinuxSyscallsTable, _SyscallsRegs::rax, _SyscallsRegs::rbp, _SyscallsRegs::rbx, _SyscallsRegs::rcx, _SyscallsRegs::rdi, _SyscallsRegs::rdx, and _SyscallsRegs::rsi.
Referenced by syscall_handler().