Fennix Project: kernel/libs/converter.cpp File Reference
converter.cpp File Reference
#include "converter.h"
Functions
const char * u64ToString (uint64_t Value)
const char * u64ToHexString (uint64_t Value)
const char * u32ToHexString (uint32_t Value)
const char * u16ToHexString (uint16_t Value)
const char * u8ToHexString (uint8_t Value)
const char * i64ToString (int64_t Value)
Variables
char UIntToStringOutput [128]
char HexToStringOutput [128]
char HexToStringOutput32 [128]
char HexToStringOutput16 [128]
char HexToStringOutput8 [128]
char IntToStringOutput [128]
Function Documentation
i64ToString()
const char* i64ToString (int64_t Value)
Definition at line 106 of file converter.cpp.
 {
     uint8_t IsNegative = 0;
     if (Value < 0)
     {
         IsNegative = 1;
         Value *= -1;
         IntToStringOutput[0] = '-';
     }
     uint8_t Size = 0;
     uint64_t SizeTest = Value;
     while (SizeTest / 10 > 0)
     {
         SizeTest /= 10;
         Size++;
     }
     uint8_t Index = 0;
     while (Value / 10 > 0)
     {
         uint8_t Remainder = Value % 10;
         Value /= 10;
         IntToStringOutput[IsNegative + Size - Index] = Remainder + '0';
         Index++;
     }
     uint8_t Remainder = Value % 10;
     IntToStringOutput[IsNegative + Size - Index] = Remainder + '0';
     IntToStringOutput[IsNegative + Size + 1] = 0;
     return IntToStringOutput;
 }
References IntToStringOutput.
u16ToHexString()
const char* u16ToHexString (uint16_t Value)
Definition at line 68 of file converter.cpp.
 {
     uint16_t *ValuePtr = &Value;
     uint8_t *Ptr;
     uint8_t Temp;
     uint8_t Size = 2 * 2 - 1;
     for (uint8_t i = 0; i < Size; i++)
     {
         Ptr = ((uint8_t *)ValuePtr + i);
         Temp = ((*Ptr & 0xF0) >> 4);
         HexToStringOutput16[Size - (i * 2 + 1)] = Temp + (Temp > 9 ? 55 : '0');
         Temp = ((*Ptr & 0x0F));
         HexToStringOutput16[Size - (i * 2)] = Temp + (Temp > 9 ? 55 : '0');
     }
     HexToStringOutput16[Size + 1] = 0;
     return HexToStringOutput16;
 }
References HexToStringOutput16.
u32ToHexString()
const char* u32ToHexString (uint32_t Value)
Definition at line 49 of file converter.cpp.
 {
     uint32_t *ValuePtr = &Value;
     uint8_t *Ptr;
     uint8_t Temp;
     uint8_t Size = 4 * 2 - 1;
     for (uint8_t i = 0; i < Size; i++)
     {
         Ptr = ((uint8_t *)ValuePtr + i);
         Temp = ((*Ptr & 0xF0) >> 4);
         HexToStringOutput32[Size - (i * 2 + 1)] = Temp + (Temp > 9 ? 55 : '0');
         Temp = ((*Ptr & 0x0F));
         HexToStringOutput32[Size - (i * 2)] = Temp + (Temp > 9 ? 55 : '0');
     }
     HexToStringOutput32[Size + 1] = 0;
     return HexToStringOutput32;
 }
References HexToStringOutput32.
Referenced by PCI::GetDeviceName(), and PCI::GetVendorName().
u64ToHexString()
const char* u64ToHexString (uint64_t Value)
Definition at line 29 of file converter.cpp.
 {
     uint64_t *ValuePtr = &Value;
     uint8_t *Ptr;
     uint8_t Temp;
     uint8_t Size = 8 * 2 - 1;
     // for (uint8_t i = 0; i < Size; i++)
     for (uint8_t i = 0; i < Size / 2 + 1; i++)
     {
         Ptr = ((uint8_t *)ValuePtr + i);
         Temp = ((*Ptr & 0xF0) >> 4);
         HexToStringOutput[Size - (i * 2 + 1)] = Temp + (Temp > 9 ? 55 : '0');
         Temp = ((*Ptr & 0x0F));
         HexToStringOutput[Size - (i * 2)] = Temp + (Temp > 9 ? 55 : '0');
     }
     HexToStringOutput[Size + 1] = 0;
     return HexToStringOutput;
 }
References HexToStringOutput.
u64ToString()
const char* u64ToString (uint64_t Value)
Definition at line 4 of file converter.cpp.
 {
     uint8_t Size = 0;
     uint64_t SizeTest = Value;
     while (SizeTest / 10 > 0)
     {
         SizeTest /= 10;
         Size++;
     }
     uint8_t Index = 0;
     while (Value / 10 > 0)
     {
         uint8_t Remainder = Value % 10;
         Value /= 10;
         UIntToStringOutput[Size - Index] = Remainder + '0';
         Index++;
     }
     uint8_t Remainder = Value % 10;
     UIntToStringOutput[Size - Index] = Remainder + '0';
     UIntToStringOutput[Size + 1] = 0;
     return UIntToStringOutput;
 }
References UIntToStringOutput.
u8ToHexString()
const char* u8ToHexString (uint8_t Value)
Definition at line 87 of file converter.cpp.
 {
     uint8_t *ValuePtr = &Value;
     uint8_t *Ptr;
     uint8_t Temp;
     uint8_t Size = 1 * 2 - 1;
     for (uint8_t i = 0; i < Size; i++)
     {
         Ptr = ((uint8_t *)ValuePtr + i);
         Temp = ((*Ptr & 0xF0) >> 4);
         HexToStringOutput8[Size - (i * 2 + 1)] = Temp + (Temp > 9 ? 55 : '0');
         Temp = ((*Ptr & 0x0F));
         HexToStringOutput8[Size - (i * 2)] = Temp + (Temp > 9 ? 55 : '0');
     }
     HexToStringOutput8[Size + 1] = 0;
     return HexToStringOutput8;
 }
References HexToStringOutput8.
Referenced by PCI::BaseSystemPeripheralSubclassName(), PCI::BridgeDeviceSubclassName(), PCI::CommunicationControllerSubclassName(), PCI::DisplayControllerSubclassName(), PCI::GetProgIFName(), PCI::GetSubclassName(), PCI::MassStorageControllerSubclassName(), PCI::NetworkControllerSubclassName(), PCI::SerialBusControllerSubclassName(), and PCI::WirelessControllerSubclassName().
Variable Documentation
HexToStringOutput
char HexToStringOutput[128]
Definition at line 28 of file converter.cpp.
Referenced by u64ToHexString().
HexToStringOutput16
char HexToStringOutput16[128]
Definition at line 67 of file converter.cpp.
Referenced by u16ToHexString().
HexToStringOutput32
char HexToStringOutput32[128]
Definition at line 48 of file converter.cpp.
Referenced by u32ToHexString().
HexToStringOutput8
char HexToStringOutput8[128]
Definition at line 86 of file converter.cpp.
Referenced by u8ToHexString().
IntToStringOutput
char IntToStringOutput[128]
Definition at line 105 of file converter.cpp.
Referenced by i64ToString().
UIntToStringOutput
char UIntToStringOutput[128]
Definition at line 3 of file converter.cpp.
Referenced by u64ToString().