Fennix Project: NetworkInterfaceManager Namespace Reference
NetworkInterfaceManager Namespace Reference
Data Structures
struct DeviceInterface
class Events
class NetworkInterface
Functions
ReadFSFunction (NetRead)
WriteFSFunction (NetWrite)
void CallStartNetworkStackWrapper ()
Variables
FileSystem::FileSystemOpeations netsvcfs
Vector< Events * > RegisteredEvents
Function Documentation
CallStartNetworkStackWrapper()
void NetworkInterfaceManager::CallStartNetworkStackWrapper ()
Definition at line 251 of file NetworkController.cpp.
 { nimgr->StartNetworkStack(); }
References nimgr, and NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
Referenced by NetworkInterfaceManager::NetworkInterface::StartService().
ReadFSFunction()
NetworkInterfaceManager::ReadFSFunction (NetRead)
Definition at line 234 of file NetworkController.cpp.
     {
         fixme("Not implemented.");
         return Size;
     }
References fixme().
WriteFSFunction()
NetworkInterfaceManager::WriteFSFunction (NetWrite)
Definition at line 240 of file NetworkController.cpp.
     {
         fixme("Not implemented.");
         return Size;
     }
References fixme().
Variable Documentation
netsvcfs
FileSystem::FileSystemOpeations NetworkInterfaceManager::netsvcfs
Initial value:
= {
        .Name = "Network Service",
        .Read = NetRead,
        .Write = NetWrite}
Definition at line 246 of file NetworkController.cpp.
Referenced by NetworkInterfaceManager::NetworkInterface::StartService().
RegisteredEvents
Vector<Events *> NetworkInterfaceManager::RegisteredEvents
Definition at line 262 of file NetworkController.cpp.
Referenced by NetworkInterfaceManager::Events::Events(), NetworkInterfaceManager::NetworkInterface::Receive(), NetworkInterfaceManager::NetworkInterface::Send(), and NetworkInterfaceManager::Events::~Events().