Fennix Project: Driver::KernelDriver Class Reference
Driver::KernelDriver Class Reference
#include <driver.hpp>
Public Member Functions
uint64_t LoadKernelDriverFromFile (FileSystem::FileSystemNode *Node)
KernelDriver ()
~KernelDriver ()
Private Attributes
void * DrvMgrProc
void * DrvMgrThrd
Detailed Description
Definition at line 8 of file driver.hpp.
Constructor & Destructor Documentation
KernelDriver()
Driver::KernelDriver::KernelDriver ()
Definition at line 261 of file Driver.cpp.
     {
         drvfs = new FileSystem::Driver;
         drvfs->AddDriver(&kdrvfs, 0666, "default", FileSystem::NodeFlags::FS_PIPE);
         DrvMgrProc = SysCreateProcess("Driver Manager", ELEVATION::System);
         DrvMgrThrd = SysCreateThread((PCB *)DrvMgrProc, (uint64_t)DriverManagerMainLoop, 0, 0);
     }
References FileSystem::Driver::AddDriver(), Driver::DriverManagerMainLoop(), drvfs, DrvMgrProc, DrvMgrThrd, FS_PIPE, Driver::kdrvfs, SysCreateProcess(), and SysCreateThread().
~KernelDriver()
Driver::KernelDriver::~KernelDriver ()
Definition at line 269 of file Driver.cpp.
     {
         // TODO: kill driver manager process
     }
Member Function Documentation
LoadKernelDriverFromFile()
uint64_t Driver::KernelDriver::LoadKernelDriverFromFile (FileSystem::FileSystemNode * Node)
Definition at line 90 of file Driver.cpp.
     {
         void *DriverBuffer = KernelAllocator.RequestPages(Node->Length / 0x1000 + 1);
         FileSystem::FILE *driverfile = vfs->ConvertNodeToFILE(Node);
         vfs->Read(driverfile, 0, (uint8_t *)DriverBuffer, Node->Length);
         delete driverfile;
         Elf64_Ehdr *header = (Elf64_Ehdr *)DriverBuffer;
         if (header->e_ident[EI_MAG0] != ELFMAG0)
         {
             KernelAllocator.FreePages(DriverBuffer, Node->Length / 0x1000 + 1);
             return 0xDE0;
         }
         if (header->e_ident[EI_MAG1] != ELFMAG1)
         {
             KernelAllocator.FreePages(DriverBuffer, Node->Length / 0x1000 + 1);
             return 0xDE1;
         }
         if (header->e_ident[EI_MAG2] != ELFMAG2)
         {
             KernelAllocator.FreePages(DriverBuffer, Node->Length / 0x1000 + 1);
             return 0xDE2;
         }
         if (header->e_ident[EI_MAG3] != ELFMAG3)
         {
             KernelAllocator.FreePages(DriverBuffer, Node->Length / 0x1000 + 1);
             return 0xDE3;
         }
         if (header->e_ident[EI_CLASS] == ELFCLASS32)
         {
             KernelAllocator.FreePages(DriverBuffer, Node->Length / 0x1000 + 1);
             return 0xDEC32;
         }
         if (header->e_ident[EI_CLASS] == ELFCLASS64)
         {
             Elf64_Phdr *pheader = (Elf64_Phdr *)(((char *)DriverBuffer) + header->e_phoff);
             void *addr;
             for (int i = 0; i < header->e_phnum; i++, pheader++)
             {
                 if (pheader->p_type != PT_LOAD)
                     continue;
                 addr = (void *)((uint64_t)pheader->p_vaddr + pheader->p_memsz);
             }
             void *offset = KernelAllocator.RequestPages((uint64_t)addr / 0x1000 + 1);
             pheader = (Elf64_Phdr *)(((char *)DriverBuffer) + header->e_phoff);
             for (int i = 0; i < header->e_phnum; i++, pheader++)
             {
                 if (pheader->p_type != PT_LOAD)
                     continue;
                 void *dst = (void *)((uint64_t)pheader->p_vaddr + (uint64_t)offset);
                 memset(dst, 0, pheader->p_memsz);
                 memcpy(dst, ((char *)DriverBuffer) + pheader->p_offset, pheader->p_filesz);
             }
             // process pages -> addr / 0x1000 + 1;
             // KernelAllocator.FreePages(DriverBuffer, Node->Length / 0x1000 + 1);
             Elf64_Shdr shstrtab;
             memcpy(&shstrtab, (void *)((uint64_t)DriverBuffer + (header->e_shoff + static_cast<uint64_t>(header->e_shstrndx) * header->e_shentsize)), sizeof(Elf64_Shdr));
             char *names = (char *)kmalloc(shstrtab.sh_size);
             memcpy(names, (void *)((uint64_t)DriverBuffer + (shstrtab.sh_offset)), shstrtab.sh_size);
             for (uint16_t i = 0; i < header->e_shnum; i++)
             {
                 struct elf64_shdr section;
                 memcpy(&section, (void *)((uint64_t)DriverBuffer + (header->e_shoff + (uint64_t)i * header->e_shentsize)), sizeof(elf64_shdr));
                 if (!strcmp(&names[section.sh_name], ".driverdata"))
                 {
                     kfree(names);
                     DriverDefinition def;
                     DriverKernelMainData kerndata = {.KFctCall = FunctionCallHandler};
                     memcpy(&def, (void *)((uint64_t)DriverBuffer + (section.sh_offset)), section.sh_size);
                     void *DriverStartFunction = (void *)(header->e_entry + (Elf64_Addr)offset);
                     debug("Driver Name: %s", def.Name);
                     debug("Entry:%#llx + Offset:%#llx -> %#llx", header->e_entry, offset, DriverStartFunction);
                     uint64_t ret = DRIVER_SUCCESS; // ((uint64_t(*)(DriverKernelMainData *))(DriverStartFunction))(&kerndata);
                     fixme("Driver will not be loaded.");
                     if (ret == DRIVER_SUCCESS)
                     {
                         // TODO: unloaded drivers need to be removed
                         FileSystem::FileSystemNode *drvnode = vfs->Create(DriverNode, Node->Name);
                         drvnode->Mode = 000;
                         drvnode->Address = (uint64_t)(header->e_entry + (uint64_t)offset);
                         drvnode->Flags = FileSystem::NodeFlags::FS_PIPE;
                         return 0;
                     }
                     else
                     {
                         KernelAllocator.FreePages(DriverBuffer, Node->Length / 0x1000 + 1);
                         return 0xDF01;
                     }
                 }
             }
             KernelAllocator.FreePages(DriverBuffer, Node->Length / 0x1000 + 1);
             kfree(names);
             return 0xDEC64;
         }
         return 0;
     }
References addr, FileSystem::FileSystemNode::Address, FileSystem::Virtual::ConvertNodeToFILE(), FileSystem::Virtual::Create(), debug, DRIVER_SUCCESS, Driver::DriverNode, EI_CLASS, EI_MAG0, EI_MAG1, EI_MAG2, EI_MAG3, ELFCLASS32, ELFCLASS64, ELFMAG0, ELFMAG1, ELFMAG2, ELFMAG3, fixme(), FileSystem::FileSystemNode::Flags, FS_PIPE, FunctionCallHandler(), header, KernelAllocator, kfree, kmalloc, FileSystem::FileSystemNode::Length, memcpy(), memset(), FileSystem::FileSystemNode::Mode, FileSystem::FileSystemNode::Name, Elf64_Phdr::p_filesz, Elf64_Phdr::p_memsz, Elf64_Phdr::p_offset, Elf64_Phdr::p_type, Elf64_Phdr::p_vaddr, PT_LOAD, FileSystem::Virtual::Read(), elf64_shdr::sh_name, elf64_shdr::sh_offset, elf64_shdr::sh_size, strcmp(), and vfs.
Referenced by Driver::DriverManagerMainLoop().
Field Documentation
DrvMgrProc
void* Driver::KernelDriver::DrvMgrProc private
Definition at line 11 of file driver.hpp.
Referenced by KernelDriver().
DrvMgrThrd
void* Driver::KernelDriver::DrvMgrThrd private
Definition at line 12 of file driver.hpp.
Referenced by KernelDriver().
The documentation for this class was generated from the following files:
kernel/driver.hpp
kernel/Driver.cpp