Fennix Project: kernel/mem/HeapManager.cpp File Reference
HeapManager.cpp File Reference
#include <heap.h>
#include <string.h>
#include <sys.h>
#include <stdalign.h>
#include <asm.h>
#include <lock.h>
#include <symbols.hpp>
#include <assert.h>
#include "../drivers/serial.h"
#include "liballoc/liballoc_1_1.h"
#include "liballoc/liballoc.h"
#include "defaultalloc/defaultalloc.hpp"
#include "buddyalloc/buddy_alloc.h"
#include "xalloc/Xalloc.hpp"
Macros
#define syskernel
#define BUDDY_ALLOC_IMPLEMENTATION
Functions
NEWLOCK (heap_lock)
void init_heap (AllocationAlgorithm Type)
void HeapFree (void *Address)
void * HeapMalloc (size_t Size)
void * HeapCalloc (size_t n, size_t Size)
void * HeapRealloc (void *Address, size_t Size)
void * RequestPage ()
void FreePage (void *address)
void * RequestPages (uint64_t pages)
void FreePages (void *address, uint64_t pages)
uint64_t GetFreeMemory ()
uint64_t GetUsedMemory ()
uint64_t GetReservedMemory ()
void * operator new (size_t Size)
void * operator new[] (size_t Size)
void operator delete (void *Pointer)
void operator delete[] (void *Pointer)
void operator delete (void *Pointer, long unsigned int n)
void operator delete[] (void *Pointer, long unsigned int n)
Variables
static AllocationAlgorithm AlgorithmToUse = AllocationAlgorithm::NoAllocationAlgorithm
static struct buddy * buddy = nullptr
static Xalloc::AllocatorV1 * xalloc = nullptr
Macro Definition Documentation
BUDDY_ALLOC_IMPLEMENTATION
#define BUDDY_ALLOC_IMPLEMENTATION
Definition at line 17 of file HeapManager.cpp.
syskernel
#define syskernel
Definition at line 8 of file HeapManager.cpp.
Function Documentation
FreePage()
void FreePage (void * address)
Definition at line 219 of file HeapManager.cpp.
 { KernelAllocator.FreePage(address); }
References Address, address, FreeMemory, KernelAllocator, LOCK, PageBitmapIndex, UNLOCK, UsedMemory, and warn.
Referenced by FileSystem::EXT2::EXT2(), FileSystem::FAT::FAT(), and FreePages().
FreePages()
void FreePages (void * address, uint64_t pages)
Definition at line 223 of file HeapManager.cpp.
 { KernelAllocator.FreePages(address, pages); }
References Address, address, FreePage(), KernelAllocator, and warn.
Referenced by free(), and liballoc_free().
GetFreeMemory()
uint64_t GetFreeMemory ()
Definition at line 225 of file HeapManager.cpp.
 { return KernelAllocator.GetFreeRAM(); }
References KernelAllocator.
Referenced by init_pmm().
GetReservedMemory()
uint64_t GetReservedMemory ()
Definition at line 229 of file HeapManager.cpp.
 { return KernelAllocator.GetReservedRAM(); }
References KernelAllocator.
Referenced by init_pmm().
GetUsedMemory()
uint64_t GetUsedMemory ()
Definition at line 227 of file HeapManager.cpp.
 { return KernelAllocator.GetUsedRAM(); }
References KernelAllocator.
Referenced by init_pmm().
HeapCalloc()
void* HeapCalloc (size_t n, size_t Size)
Definition at line 137 of file HeapManager.cpp.
 {
     LOCK(heap_lock);
     bool inten = InterruptsEnabled();
     CLI;
     void *ret = nullptr;
     switch (AlgorithmToUse)
     {
     case AllocationAlgorithm::Default:
         ret = defPREFIX(calloc)(n, Size);
         break;
     case AllocationAlgorithm::LibAlloc:
         ret = liballoc_calloc(n, Size);
         break;
     case AllocationAlgorithm::LibAlloc11:
         ret = libPREFIX(calloc)(n, Size);
         break;
     case AllocationAlgorithm::BuddyAlloc:
         ret = buddy_calloc(buddy, n, Size);
         break;
     case AllocationAlgorithm::XallocV1:
         ret = xalloc->Calloc(n, Size);
         break;
     case AllocationAlgorithm::NoAllocationAlgorithm:
         panic("HeapFree called before heap initialized!", true);
         break;
     default:
         panic("Unknown allocation algorithm!", true);
         break;
     }
     memset(ret, 0, n * Size);
     UNLOCK(heap_lock);
     if (inten)
         STI;
     return ret;
 }
References AlgorithmToUse, buddy, buddy_calloc(), BuddyAlloc, Xalloc::AllocatorV1::Calloc(), calloc(), CLI, Default, defPREFIX, InterruptsEnabled(), LibAlloc, LibAlloc11, liballoc_calloc(), libPREFIX, LOCK, memset(), NoAllocationAlgorithm, panic, STI, UNLOCK, xalloc, and XallocV1.
HeapFree()
void HeapFree (void * Address)
Definition at line 63 of file HeapManager.cpp.
 {
     LOCK(heap_lock);
     bool inten = InterruptsEnabled();
     CLI;
     switch (AlgorithmToUse)
     {
     case AllocationAlgorithm::Default:
         defPREFIX(free)(Address);
         break;
     case AllocationAlgorithm::LibAlloc:
         liballoc_free(Address);
         break;
     case AllocationAlgorithm::LibAlloc11:
         libPREFIX(free)(Address);
         break;
     case AllocationAlgorithm::BuddyAlloc:
         buddy_free(buddy, Address);
         break;
     case AllocationAlgorithm::XallocV1:
         xalloc->Free(Address);
         break;
     case AllocationAlgorithm::NoAllocationAlgorithm:
         panic("HeapFree called before heap initialized!", true);
         break;
     default:
         panic("Unknown allocation algorithm!", true);
         break;
     }
     UNLOCK(heap_lock);
     if (inten)
         STI;
 }
References Address, AlgorithmToUse, buddy, buddy_free(), BuddyAlloc, CLI, Default, defPREFIX, free(), Xalloc::AllocatorV1::Free(), InterruptsEnabled(), LibAlloc, LibAlloc11, liballoc_free(), libPREFIX, LOCK, NoAllocationAlgorithm, panic, STI, UNLOCK, xalloc, and XallocV1.
Referenced by operator delete(), and operator delete[]().
HeapMalloc()
void* HeapMalloc (size_t Size)
Definition at line 97 of file HeapManager.cpp.
 {
     LOCK(heap_lock);
     bool inten = InterruptsEnabled();
     CLI;
     void *ret = nullptr;
     switch (AlgorithmToUse)
     {
     case AllocationAlgorithm::Default:
         ret = defPREFIX(malloc)(Size);
         break;
     case AllocationAlgorithm::LibAlloc:
         ret = liballoc_malloc(Size);
         break;
     case AllocationAlgorithm::LibAlloc11: // TODO: Make that the Liballoc 1.1 start at KERNEL_HEAP_BASE
         ret = libPREFIX(malloc)(Size);
         break;
     case AllocationAlgorithm::BuddyAlloc:
         ret = buddy_malloc(buddy, Size);
         break;
     case AllocationAlgorithm::XallocV1:
         ret = xalloc->Malloc(Size);
         break;
     case AllocationAlgorithm::NoAllocationAlgorithm:
         panic("HeapFree called before heap initialized!", true);
         break;
     default:
         panic("Unknown allocation algorithm!", true);
         break;
     }
     memset(ret, 0, Size);
     UNLOCK(heap_lock);
     if (inten)
         STI;
     return ret;
 }
References AlgorithmToUse, buddy, buddy_malloc(), BuddyAlloc, CLI, Default, defPREFIX, InterruptsEnabled(), LibAlloc, LibAlloc11, liballoc_malloc(), libPREFIX, LOCK, malloc(), Xalloc::AllocatorV1::Malloc(), memset(), NoAllocationAlgorithm, panic, STI, UNLOCK, xalloc, and XallocV1.
Referenced by operator new(), and operator new[]().
HeapRealloc()
void* HeapRealloc (void * Address, size_t Size)
Definition at line 177 of file HeapManager.cpp.
 {
     LOCK(heap_lock);
     bool inten = InterruptsEnabled();
     CLI;
     void *ret = nullptr;
     switch (AlgorithmToUse)
     {
     case AllocationAlgorithm::Default:
         ret = defPREFIX(realloc)(Address, Size);
         break;
     case AllocationAlgorithm::LibAlloc:
         ret = liballoc_realloc(Address, Size);
         break;
     case AllocationAlgorithm::LibAlloc11:
         ret = libPREFIX(realloc)(Address, Size);
         break;
     case AllocationAlgorithm::BuddyAlloc:
         ret = buddy_realloc(buddy, Address, Size);
         break;
     case AllocationAlgorithm::XallocV1:
         ret = xalloc->Realloc(Address, Size);
         break;
     case AllocationAlgorithm::NoAllocationAlgorithm:
         panic("HeapFree called before heap initialized!", true);
         break;
     default:
         panic("Unknown allocation algorithm!", true);
         break;
     }
     memset(ret, 0, Size);
     UNLOCK(heap_lock);
     if (inten)
         STI;
     return ret;
 }
References Address, AlgorithmToUse, buddy, buddy_realloc(), BuddyAlloc, CLI, Default, defPREFIX, InterruptsEnabled(), LibAlloc, LibAlloc11, liballoc_realloc(), libPREFIX, LOCK, memset(), NoAllocationAlgorithm, panic, Xalloc::AllocatorV1::Realloc(), realloc(), STI, UNLOCK, xalloc, and XallocV1.
init_heap()
void init_heap (AllocationAlgorithm Type)
Definition at line 29 of file HeapManager.cpp.
 {
     LOCK(heap_lock);
     switch (Type)
     {
     case AllocationAlgorithm::Default:
         InitHeap((void *)KERNEL_HEAP_BASE, 0x20);
         break;
     case AllocationAlgorithm::LibAlloc:
         break;
     case AllocationAlgorithm::LibAlloc11:
         break;
     case AllocationAlgorithm::BuddyAlloc:
     {
         alignas(max_align_t) unsigned char buddy_buf[buddy_sizeof(4096)];
         alignas(max_align_t) unsigned char data_buf[4096];
         {
             buddy = buddy_init(buddy_buf, data_buf, 4096);
             assert(buddy != NULL);
         }
         break;
     }
     case AllocationAlgorithm::XallocV1:
     {
         xalloc = new Xalloc::AllocatorV1((void *)KERNEL_HEAP_BASE, false, false);
         break;
     }
     default:
         panic("Unknown allocation algorithm!", true);
     }
     AlgorithmToUse = Type;
     UNLOCK(heap_lock);
 }
References AlgorithmToUse, assert, buddy, buddy_init(), buddy_sizeof(), BuddyAlloc, Default, InitHeap(), KERNEL_HEAP_BASE, LibAlloc, LibAlloc11, LOCK, panic, Type, UNLOCK, xalloc, and XallocV1.
Referenced by stivale2_initializator().
NEWLOCK()
NEWLOCK (heap_lock)
operator delete() [1/2]
void operator delete (void * Pointer)
Definition at line 324 of file HeapManager.cpp.
 {
     if (AlgorithmToUse == AllocationAlgorithm::NoAllocationAlgorithm)
     {
         warn("No allocator specified. Aborting...");
         return;
     }
 #ifdef DEBUG_MEM_ALLOCATION
     dbg_free(Pointer, __FILE__, __LINE__, __FUNCTION__);
 #else
     HeapFree(Pointer);
 #endif
 }
References AlgorithmToUse, HeapFree(), NoAllocationAlgorithm, and warn.
operator delete() [2/2]
void operator delete (void * Pointer, long unsigned int n)
Definition at line 352 of file HeapManager.cpp.
 {
     if (AlgorithmToUse == AllocationAlgorithm::NoAllocationAlgorithm)
     {
         warn("No allocator specified. Aborting...");
         return;
     }
 #ifdef DEBUG_MEM_ALLOCATION
     dbg_free(Pointer, __FILE__, __LINE__, __FUNCTION__);
 #else
     HeapFree(Pointer);
 #endif
 }
References AlgorithmToUse, HeapFree(), NoAllocationAlgorithm, and warn.
operator delete[]() [1/2]
void operator delete[] (void * Pointer)
Definition at line 338 of file HeapManager.cpp.
 {
     if (AlgorithmToUse == AllocationAlgorithm::NoAllocationAlgorithm)
     {
         warn("No allocator specified. Aborting...");
         return;
     }
 #ifdef DEBUG_MEM_ALLOCATION
     dbg_free(Pointer, __FILE__, __LINE__, __FUNCTION__);
 #else
     HeapFree(Pointer);
 #endif
 }
References AlgorithmToUse, HeapFree(), NoAllocationAlgorithm, and warn.
operator delete[]() [2/2]
void operator delete[] (void * Pointer, long unsigned int n)
Definition at line 366 of file HeapManager.cpp.
 {
     if (AlgorithmToUse == AllocationAlgorithm::NoAllocationAlgorithm)
     {
         warn("No allocator specified. Aborting...");
         return;
     }
 #ifdef DEBUG_MEM_ALLOCATION
     dbg_free(Pointer, __FILE__, __LINE__, __FUNCTION__);
 #else
     HeapFree(Pointer);
 #endif
 }
References AlgorithmToUse, HeapFree(), NoAllocationAlgorithm, and warn.
operator new()
void* operator new (size_t Size)
Definition at line 260 of file HeapManager.cpp.
 {
     if (AlgorithmToUse == AllocationAlgorithm::NoAllocationAlgorithm)
     {
         if (Size == 0)
             Size = 1;
         warn("No allocator specified. Requesting %d page(s)...", Size / PAGE_SIZE + 1);
         return KernelAllocator.RequestPages(Size / PAGE_SIZE + 1);
     }
     if (Size == 0)
         warn("Trying to allocate 0 bytes!");
 #ifdef DEBUG_MEM_ALLOCATION
     if (void *Pointer = dbg_malloc(Size, __FILE__, __LINE__, __FUNCTION__))
 #else
     if (void *Pointer = HeapMalloc(Size))
 #endif
         return Pointer;
     warn("new( %llx ) failed! [Request by %s] Trying again...", Size, SymTbl->GetSymbolFromAddress((uint64_t)__builtin_return_address(0)));
     for (size_t i = 0; i < 16; i++)
     {
         if (void *Pointer = HeapMalloc(Size))
             return Pointer;
         else
             warn("new( %llx ) failed! Retrying... (%d)", Size, i);
     }
     err("new( %llx ) failed!", Size);
     throw;
 }
References AlgorithmToUse, err, KernelSymbols::Symbols::GetSymbolFromAddress(), HeapMalloc(), KernelAllocator, NoAllocationAlgorithm, PAGE_SIZE, SymTbl, and warn.
operator new[]()
void* operator new[] (size_t Size)
Definition at line 292 of file HeapManager.cpp.
 {
     if (AlgorithmToUse == AllocationAlgorithm::NoAllocationAlgorithm)
     {
         if (Size == 0)
             Size = 1;
         warn("No allocator specified. Requesting %d page(s)...", Size / PAGE_SIZE + 1);
         return KernelAllocator.RequestPages(Size / PAGE_SIZE + 1);
     }
     if (Size == 0)
         warn("Trying to allocate 0 bytes!");
 #ifdef DEBUG_MEM_ALLOCATION
     if (void *Pointer = dbg_malloc(Size, __FILE__, __LINE__, __FUNCTION__))
 #else
     if (void *Pointer = HeapMalloc(Size))
 #endif
         return Pointer;
     warn("new[]( %llx ) failed! [Request by %s] Trying again...", Size, SymTbl->GetSymbolFromAddress((uint64_t)__builtin_return_address(0)));
     for (size_t i = 0; i < 16; i++)
     {
         if (void *Pointer = HeapMalloc(Size))
             return Pointer;
         else
             warn("new[]( %llx ) failed! Retrying... (%d)", Size, i);
     }
     err("new[]( %llx ) failed!", Size);
     throw;
 }
References AlgorithmToUse, err, KernelSymbols::Symbols::GetSymbolFromAddress(), HeapMalloc(), KernelAllocator, NoAllocationAlgorithm, PAGE_SIZE, SymTbl, and warn.
RequestPage()
void* RequestPage ()
Definition at line 217 of file HeapManager.cpp.
 { return KernelAllocator.RequestPage(); }
References debug, FreeMemory, KernelAllocator, KernelPageTableManager, LOCK, PageBitmapIndex, panic, ReservedMemory, sprintf_(), TO_MB, UNLOCK, and UsedMemory.
Referenced by allocate_new_tag(), CreateNewTSS(), FileSystem::EXT2::EXT2(), FileSystem::FAT::FAT(), and init_tss().
RequestPages()
void* RequestPages (uint64_t pages)
Definition at line 221 of file HeapManager.cpp.
 { return KernelAllocator.RequestPages(pages); }
References debug, err, FreeMemory, KernelAllocator, LOCK, PageBitmapIndex, ReservedMemory, TO_MB, UNLOCK, UsedMemory, and warn.
Referenced by allocate_new_page().
Variable Documentation
AlgorithmToUse
AllocationAlgorithm AlgorithmToUse = AllocationAlgorithm::NoAllocationAlgorithm static
Definition at line 25 of file HeapManager.cpp.
Referenced by HeapCalloc(), HeapFree(), HeapMalloc(), HeapRealloc(), init_heap(), operator delete(), operator delete[](), operator new(), and operator new[]().
buddy
struct buddy* buddy = nullptr static
Definition at line 26 of file HeapManager.cpp.
Referenced by HeapCalloc(), HeapFree(), HeapMalloc(), HeapRealloc(), and init_heap().
xalloc
Xalloc::AllocatorV1* xalloc = nullptr static
Definition at line 27 of file HeapManager.cpp.
Referenced by HeapCalloc(), HeapFree(), HeapMalloc(), HeapRealloc(), and init_heap().