Fennix Project: Driver Namespace Reference
Driver Namespace Reference
Data Structures
class KernelDriver
Functions
ReadFSFunction (DriverRead)
WriteFSFunction (DriverWrite)
void DriverManagerMainLoop ()
Variables
PCB * DrvMgrProc = nullptr
FileSystem::FileSystemNode * DriverNode = nullptr
FileSystem::FileSystemOpeations kdrvfs
Function Documentation
DriverManagerMainLoop()
void Driver::DriverManagerMainLoop ()
Definition at line 206 of file Driver.cpp.
     {
         SysSetThreadPriority(100);
         // PCB *drvpcb = SysCreateProcessFromFile("/system/drvmgr", 0, 0, ELEVATION::User);
         // if (!drvpcb)
         // {
         //     CurrentDisplay->SetPrintColor(0xFC4444);
         //     printf("Failed to load /system/drvmgr process. The file is missing or corrupted.\n");
         //     delete kdrv;
         //     CPU_HALT;
         // }
         // TrustToken(drvpcb->Security.Token, true, drvpcb->ID, TokenTrustLevel::TrustedByKernel);
         FileSystem::FILE *driverDirectory = vfs->Open("/system/drivers");
         if (driverDirectory->Status == FileSystem::FILESTATUS::OK)
         {
             foreach (auto driver in driverDirectory->Node->Children)
             {
                 if (driver->Flags == FileSystem::NodeFlags::FS_FILE)
                     if (cwk_path_has_extension(driver->Name))
                     {
                         const char *extension;
                         cwk_path_get_extension(driver->Name, &extension, nullptr);
                         if (!strcmp(extension, ".drv"))
{
                             CurrentDisplay->SetPrintColor(0xCCCCCC);
                             printf("Loading driver %s... ", driver->Name);
                             uint64_t ret = kdrv->LoadKernelDriverFromFile(driver);
                             if (ret == 0)
{
                                 CurrentDisplay->SetPrintColor(0x058C19);
                                 printf("OK\n");
                             }
                             else
{
                                 CurrentDisplay->SetPrintColor(0xE85230);
                                 printf("FAILED (%#lx)\n", ret);
                             }
                             CurrentDisplay->ResetPrintColor();
                             // TODO: get instruction pointer of the elf entry point.
                         }
                     }
             }
         }
         vfs->Close(driverDirectory);
         SysSetThreadPriority(5);
         while (1)
         {
             // do IPC here.
             PAUSE;
         }
     }
References FileSystem::FileSystemNode::Children, FileSystem::Virtual::Close(), CurrentDisplay, cwk_path_get_extension(), cwk_path_has_extension(), FS_FILE, kdrv, Driver::KernelDriver::LoadKernelDriverFromFile(), FileSystem::FILE::Node, OK, FileSystem::Virtual::Open(), PAUSE, printf, FileSystem::FILE::Status, strcmp(), SysSetThreadPriority(), and vfs.
Referenced by Driver::KernelDriver::KernelDriver().
ReadFSFunction()
Driver::ReadFSFunction (DriverRead)
Definition at line 189 of file Driver.cpp.
     {
         fixme("Not implemented.");
         return Size;
     }
References fixme().
WriteFSFunction()
Driver::WriteFSFunction (DriverWrite)
Definition at line 195 of file Driver.cpp.
     {
         fixme("Not implemented.");
         return Size;
     }
References fixme().
Variable Documentation
DriverNode
FileSystem::FileSystemNode* Driver::DriverNode = nullptr
Definition at line 88 of file Driver.cpp.
Referenced by Driver::KernelDriver::LoadKernelDriverFromFile().
DrvMgrProc
PCB* Driver::DrvMgrProc = nullptr
Definition at line 87 of file Driver.cpp.
kdrvfs
FileSystem::FileSystemOpeations Driver::kdrvfs
Initial value:
= {
        .Name = "System Drivers",
        .Read = DriverRead,
        .Write = DriverWrite}
Definition at line 201 of file Driver.cpp.
Referenced by Driver::KernelDriver::KernelDriver().