Fennix Project: FileSystem::Virtual Class Reference
FileSystem::Virtual Class Reference
#include <filesystem.h>
Public Member Functions
FileSystemNode * GetRootNode ()
FILE * ConvertNodeToFILE (FileSystemNode *Node)
char * GetPathFromNode (FileSystemNode *Node)
FileSystemNode * GetNodeFromPath (FileSystemNode *Parent, string Path)
char * NormalizePath (FileSystemNode *Parent, string Path)
FILESTATUS FileExists (FileSystemNode *Parent, string Path)
FILE * Mount (FileSystemOpeations *Operator, string Path)
FILESTATUS Unmount (FILE *File)
FILE * Open (string Path, FileSystemNode *Parent=nullptr)
uint64_t Read (FILE *File, uint64_t Offset, uint8_t *Buffer, uint64_t Size)
uint64_t Write (FILE *File, uint64_t Offset, uint8_t *Buffer, uint64_t Size)
FILESTATUS Close (FILE *File)
FileSystemNode * CreateRoot (FileSystemOpeations *Operator, string RootName)
FileSystemNode * Create (FileSystemNode *Parent, string Path)
Virtual ()
~Virtual ()
Private Attributes
FileSystemNode * FileSystemRoot = nullptr
Detailed Description
Definition at line 130 of file filesystem.h.
Constructor & Destructor Documentation
Virtual()
FileSystem::Virtual::Virtual ()
Definition at line 474 of file FileSystem.cpp.
     {
         trace("Initializing virtual file system...");
         FileSystemRoot = new FileSystemNode;
         FileSystemRoot->Flags = NodeFlags::FS_MOUNTPOINT;
         FileSystemRoot->Operator = nullptr;
         FileSystemRoot->Parent = nullptr;
         strcpy(FileSystemRoot->Name, "root");
         cwk_path_set_style(CWK_STYLE_UNIX);
         BS->IncreaseProgres();
     }
References BS, cwk_path_set_style(), CWK_STYLE_UNIX, FileSystemRoot, FileSystem::FileSystemNode::Flags, FS_MOUNTPOINT, BootScreen::Screen::IncreaseProgres(), FileSystem::FileSystemNode::Name, FileSystem::FileSystemNode::Operator, FileSystem::FileSystemNode::Parent, strcpy(), and trace.
~Virtual()
FileSystem::Virtual::~Virtual ()
Definition at line 486 of file FileSystem.cpp.
     {
         warn("Tried to uninitialize Virtual File System!");
     }
References warn.
Member Function Documentation
Close()
FILESTATUS FileSystem::Virtual::Close (FILE * File)
Definition at line 464 of file FileSystem.cpp.
     {
         SMART_LOCK(VFSLock);
         if (File == nullptr)
             return FILESTATUS::INVALID_HANDLE;
         vfsdbg("Closing %s", File->Name);
         delete File;
         return FILESTATUS::OK;
     }
References INVALID_HANDLE, _File::Name, OK, and vfsdbg.
Referenced by Driver::DriverManagerMainLoop(), internal_fileClose(), and SysCreateProcessFromFile().
ConvertNodeToFILE()
FILE* FileSystem::Virtual::ConvertNodeToFILE (FileSystemNode * Node) inline
Definition at line 137 of file filesystem.h.
         {
             FILE *File = new FILE;
             File->Name = Node->Name;
             File->Status = FILESTATUS::OK;
             File->Node = Node;
             return File;
         }
References FileSystem::FileSystemNode::Name, _File::Name, OK, and _File::Status.
Referenced by Driver::KernelDriver::LoadKernelDriverFromFile().
Create()
FileSystemNode * FileSystem::Virtual::Create (FileSystemNode * Parent, string Path)
Definition at line 197 of file FileSystem.cpp.
     {
         SMART_LOCK(VFSLock);
         if (isempty((char *)Path))
             return nullptr;
         vfsdbg("Virtual::Create( Parent: \"%s\" Path: \"%s\" )", Parent->Name, Path);
         FileSystemNode *CurrentParent = nullptr;
         if (Parent == nullptr)
         {
             if (FileSystemRoot->Children.size() >= 1)
             {
                 if (FileSystemRoot->Children[0] == nullptr)
                     panic("Root node is null!", true);
                 CurrentParent = FileSystemRoot->Children[0]; // 0 - filesystem root
             }
             else
             {
                 // TODO: check if here is a bug or something...
                 string PathCopy;
                 size_t length;
                 PathCopy = (char *)Path;
                 cwk_path_get_root(PathCopy, &length); // not working?
                 foreach (auto var in FileSystemRoot->Children)
                     if (!strcmp(var->Name, PathCopy))
                     {
                         CurrentParent = var;
                         break;
                     }
             }
         }
         else
             CurrentParent = Parent;
         char *CleanPath = NormalizePath(CurrentParent, Path);
         if (FileExists(CurrentParent, CleanPath) != FILESTATUS::NOT_FOUND)
         {
             err("File %s already exists.", CleanPath);
             goto CreatePathError;
         }
         cwk_segment segment;
         if (!cwk_path_get_first_segment(CleanPath, &segment))
         {
             err("Path doesn't have any segments.");
             goto CreatePathError;
         }
         warn("Virtual::Create( ) is not working properly.");
         do
         {
             char *SegmentName = new char[segment.end - segment.begin + 1];
             memcpy(SegmentName, segment.begin, segment.end - segment.begin);
             if (GetChild(CurrentParent, SegmentName) == nullptr)
                 CurrentParent = AddNewChild(CurrentParent, SegmentName);
             else
                 CurrentParent = GetChild(CurrentParent, SegmentName);
             delete[] SegmentName;
         } while (cwk_path_get_next_segment(&segment));
         delete CleanPath;
         vfsdbg("Virtual::Create()->\"%s\"", CurrentParent->Name);
         return CurrentParent;
     CreatePathError:
         vfsdbg("Virtual::Create()->nullptr");
         delete CleanPath;
         return nullptr;
     }
References FileSystem::AddNewChild(), cwk_segment::begin, FileSystem::FileSystemNode::Children, cwk_path_get_first_segment(), cwk_path_get_next_segment(), cwk_path_get_root(), cwk_segment::end, err, FileExists(), FileSystemRoot, FileSystem::GetChild(), isempty(), memcpy(), FileSystem::FileSystemNode::Name, NormalizePath(), NOT_FOUND, panic, strcmp(), vfsdbg, and warn.
Referenced by FileSystem::Device::Device(), FileSystem::Driver::Driver(), Driver::KernelDriver::LoadKernelDriverFromFile(), Mount(), FileSystem::Mount::Mount(), FileSystem::Network::Network(), FileSystem::Process::Process(), FileSystem::SysInfo::SysInfo(), and FileSystem::USTAR::USTAR().
CreateRoot()
FileSystemNode * FileSystem::Virtual::CreateRoot (FileSystemOpeations * Operator, string RootName)
Definition at line 274 of file FileSystem.cpp.
     {
         if (Operator == nullptr)
             return nullptr;
         vfsdbg("Setting root to %s", RootName);
         FileSystemNode *newNode = new FileSystemNode;
         strcpy(newNode->Name, RootName);
         newNode->Flags = NodeFlags::FS_DIRECTORY;
         newNode->Operator = Operator;
         FileSystemRoot->Children.push_back(newNode);
         return newNode;
     }
References FileSystem::FileSystemNode::Children, FileSystemRoot, FileSystem::FileSystemNode::Flags, FS_DIRECTORY, FileSystem::FileSystemNode::Name, FileSystem::FileSystemNode::Operator, strcpy(), and vfsdbg.
Referenced by FileSystem::USTAR::USTAR().
FileExists()
FILESTATUS FileSystem::Virtual::FileExists (FileSystemNode * Parent, string Path)
Definition at line 174 of file FileSystem.cpp.
     {
         vfsdbg("FileExists( Parent: \"%s\" Path: \"%s\" )", Parent->Name, Path);
         if (isempty((char *)Path))
             return FILESTATUS::INVALID_PATH;
         if (Parent == nullptr)
             Parent = FileSystemRoot;
         char *NormalizedPath = NormalizePath(Parent, Path);
         FileSystemNode *Node = GetNodeFromPath(Parent, NormalizedPath);
         if (Node == nullptr)
         {
             vfsdbg("FileExists()->NOT_FOUND");
             return FILESTATUS::NOT_FOUND;
         }
         else
         {
             vfsdbg("FileExists()->OK");
             return FILESTATUS::OK;
         }
     }
References FileSystemRoot, GetNodeFromPath(), INVALID_PATH, isempty(), FileSystem::FileSystemNode::Name, NormalizePath(), NOT_FOUND, OK, and vfsdbg.
Referenced by Create(), and Open().
GetNodeFromPath()
FileSystemNode * FileSystem::Virtual::GetNodeFromPath (FileSystemNode * Parent, string Path)
Definition at line 63 of file FileSystem.cpp.
     {
         vfsdbg("GetNodeFromPath( Parent: \"%s\" Path: \"%s\" )", Parent->Name, Path);
         if (strcmp(Parent->Name, Path))
         {
             cwk_segment segment;
             if (!cwk_path_get_first_segment(Path, &segment))
             {
                 err("Path doesn't have any segments.");
                 return nullptr;
             }
             do
             {
                 char *SegmentName = new char[segment.end - segment.begin + 1];
                 memcpy(SegmentName, segment.begin, segment.end - segment.begin);
             GetNodeFromPathNextParent:
                 foreach (auto var in Parent->Children)
                 {
                     if (!strcmp(var->Name, SegmentName))
                     {
                         Parent = var;
                         goto GetNodeFromPathNextParent;
                     }
                 }
                 delete[] SegmentName;
             } while (cwk_path_get_next_segment(&segment));
             const char *basename;
             cwk_path_get_basename(Path, &basename, nullptr);
             if (!strcmp(basename, Parent->Name))
             {
                 vfsdbg("GetNodeFromPath()->\"%s\"", Parent->Name);
                 return Parent;
             }
             vfsdbg("GetNodeFromPath()->\"%s\"", nullptr);
             return nullptr;
         }
         else
         {
             vfsdbg("GetNodeFromPath()->\"%s\"", Parent->Name);
             return Parent;
         }
     }
References cwk_segment::begin, FileSystem::FileSystemNode::Children, cwk_path_get_basename(), cwk_path_get_first_segment(), cwk_path_get_next_segment(), cwk_segment::end, err, memcpy(), FileSystem::FileSystemNode::Name, strcmp(), and vfsdbg.
Referenced by FileExists(), and Open().
GetPathFromNode()
char * FileSystem::Virtual::GetPathFromNode (FileSystemNode * Node)
Definition at line 26 of file FileSystem.cpp.
     {
         vfsdbg("GetPathFromNode( Node: \"%s\" )", Node->Name);
         FileSystemNode *Parent = Node;
         Vector<char *> Path;
         size_t Size = 1;
         while (Parent != FileSystemRoot && Parent != nullptr)
         {
             foreach (auto var in FileSystemRoot->Children)
                 if (var == Parent)
                     goto PathFromNodeContinue;
             Path.push_back(Parent->Name);
             Path.push_back((char *)"/");
             Parent = Parent->Parent;
         }
     PathFromNodeContinue:
         Path.reverse();
         foreach (auto var in Path)
             Size += strlen(var);
         char *FinalPath = new char[Size];
         foreach (auto var in Path)
             strcat(FinalPath, var);
         // for (size_t i = 0; i < Path.size(); i++)
         //     strcat(FinalPath, Path[i]);
         // for (size_t i = 0; i < Path.size(); i++)
         //     Size += strlen(Path[i]);
         vfsdbg("GetPathFromNode()->\"%s\"", FinalPath);
         return FinalPath;
     }
References FileSystem::FileSystemNode::Children, FileSystemRoot, FileSystem::FileSystemNode::Name, FileSystem::FileSystemNode::Parent, strcat(), strlen(), and vfsdbg.
Referenced by internal_filefullpath(), NormalizePath(), and Open().
GetRootNode()
FileSystemNode* FileSystem::Virtual::GetRootNode () inline
Definition at line 136 of file filesystem.h.
 { return FileSystemRoot; }
References FileSystemRoot.
Mount()
FILE * FileSystem::Virtual::Mount (FileSystemOpeations * Operator, string Path)
Definition at line 287 of file FileSystem.cpp.
     {
         SMART_LOCK(VFSLock);
         if (Operator == nullptr)
             return nullptr;
         if (isempty((char *)Path))
             return nullptr;
         vfsdbg("Mounting %s", Path);
         FILE *file = new FILE;
         cwk_path_get_basename(Path, &file->Name, 0);
         file->Status = FILESTATUS::OK;
         file->Node = Create(nullptr, Path);
         file->Node->Operator = Operator;
         file->Node->Flags = NodeFlags::FS_MOUNTPOINT;
         return file;
     }
References Create(), cwk_path_get_basename(), FileSystem::FileSystemNode::Flags, FS_MOUNTPOINT, isempty(), FileSystem::FILE::Name, FileSystem::FILE::Node, OK, FileSystem::FileSystemNode::Operator, FileSystem::FILE::Status, and vfsdbg.
NormalizePath()
char * FileSystem::Virtual::NormalizePath (FileSystemNode * Parent, string Path)
Definition at line 148 of file FileSystem.cpp.
     {
         vfsdbg("NormalizePath( Parent: \"%s\" Path: \"%s\" )", Parent->Name, Path);
         char *NormalizedPath = new char[strlen((char *)Path) + 1];
         char *RelativePath = nullptr;
         cwk_path_normalize(Path, NormalizedPath, strlen((char *)Path) + 1);
         if (cwk_path_is_relative(NormalizedPath))
         {
             char *ParentPath = GetPathFromNode(Parent);
             size_t PathSize = cwk_path_get_absolute(ParentPath, NormalizedPath, nullptr, 0);
             RelativePath = new char[PathSize + 1];
             cwk_path_get_absolute(ParentPath, NormalizedPath, RelativePath, PathSize + 1);
             delete[] ParentPath;
         }
         else
         {
             RelativePath = new char[strlen(NormalizedPath) + 1];
             strcpy(RelativePath, NormalizedPath);
         }
         delete[] NormalizedPath;
         vfsdbg("NormalizePath()->\"%s\"", RelativePath);
         return RelativePath;
     }
References cwk_path_get_absolute(), cwk_path_is_relative(), cwk_path_normalize(), GetPathFromNode(), FileSystem::FileSystemNode::Name, strcpy(), strlen(), and vfsdbg.
Referenced by Create(), FileExists(), and Open().
Open()
FILE * FileSystem::Virtual::Open (string Path, FileSystemNode * Parent = nullptr)
Definition at line 316 of file FileSystem.cpp.
     {
         SMART_LOCK(VFSLock);
         vfsdbg("Opening %s with parent %s", Path, Parent->Name);
         if (strcmp(Path, ".") == 0)
         {
             FILE *file = new FILE;
             FILESTATUS filestatus = FILESTATUS::OK;
             file->Node = Parent;
             if (file->Node == nullptr)
                 file->Status = FILESTATUS::NOT_FOUND;
             const char *basename;
             cwk_path_get_basename(GetPathFromNode(Parent), &basename, nullptr);
             file->Name = basename;
             return file;
         }
         if (strcmp(Path, "..") == 0)
         {
             if (Parent->Parent != nullptr)
                 Parent = Parent->Parent;
             FILE *file = new FILE;
             FILESTATUS filestatus = FILESTATUS::OK;
             file->Node = Parent;
             if (file->Node == nullptr)
                 file->Status = FILESTATUS::NOT_FOUND;
             const char *basename;
             cwk_path_get_basename(GetPathFromNode(Parent), &basename, nullptr);
             file->Name = basename;
             return file;
         }
         if (Parent == nullptr)
         {
             if (FileSystemRoot->Children.size() >= 1)
                 Parent = FileSystemRoot->Children[0]; // 0 - filesystem root
             else
             {
                 // TODO: check if here is a bug or something...
                 string PathCopy;
                 size_t length;
                 PathCopy = (char *)Path;
                 cwk_path_get_root(PathCopy, &length); // not working?
                 foreach (auto var in FileSystemRoot->Children)
                     if (!strcmp(var->Name, PathCopy))
                     {
                         Parent = var;
                         break;
                     }
             }
         }
         char *CleanPath = NormalizePath(Parent, Path);
         FILE *file = new FILE;
         FILESTATUS filestatus = FILESTATUS::OK;
         filestatus = FileExists(Parent, CleanPath);
         /* TODO: Check for other errors */
         if (filestatus != FILESTATUS::OK)
         {
             foreach (auto var in FileSystemRoot->Children)
                 if (!strcmp(var->Name, CleanPath))
                 {
                     file->Node = var;
                     if (file->Node == nullptr)
                         goto OpenNodeFail;
                     const char *basename;
                     cwk_path_get_basename(GetPathFromNode(var), &basename, nullptr);
                     file->Name = basename;
                     goto OpenNodeExit;
                 }
             file->Node = GetNodeFromPath(FileSystemRoot->Children[0], CleanPath);
             if (file->Node != nullptr)
             {
                 const char *basename;
                 cwk_path_get_basename(GetPathFromNode(file->Node), &basename, nullptr);
                 file->Name = basename;
                 goto OpenNodeExit;
             }
         OpenNodeFail:
             file->Status = filestatus;
             file->Node = nullptr;
         }
         else
         {
             file->Node = GetNodeFromPath(Parent, CleanPath);
             if (file->Node == nullptr)
                 file->Status = FILESTATUS::NOT_FOUND;
             const char *basename;
             cwk_path_get_basename(CleanPath, &basename, nullptr);
             file->Name = basename;
             return file;
         }
     OpenNodeExit:
         return file;
     }
References FileSystem::FileSystemNode::Children, cwk_path_get_basename(), cwk_path_get_root(), FileExists(), FileSystemRoot, GetNodeFromPath(), GetPathFromNode(), FileSystem::FileSystemNode::Name, FileSystem::FILE::Name, FileSystem::FILE::Node, NormalizePath(), NOT_FOUND, OK, FileSystem::FileSystemNode::Parent, FileSystem::FILE::Status, strcmp(), and vfsdbg.
Referenced by Driver::DriverManagerMainLoop(), internal_fileOpen(), internal_fileOpenWithParent(), and SysCreateProcessFromFile().
Read()
uint64_t FileSystem::Virtual::Read (FILE * File, uint64_t Offset, uint8_t * Buffer, uint64_t Size)
Definition at line 418 of file FileSystem.cpp.
     {
         SMART_LOCK(VFSLock);
         if (File == nullptr)
             return 0;
         File->Status = FILESTATUS::OK;
         if (File->Node == nullptr)
         {
             File->Status = FILESTATUS::INVALID_PARAMETER;
             return 0;
         }
         if (File->Node->Operator == nullptr)
         {
             File->Status = FILESTATUS::INVALID_PARAMETER;
             return 0;
         }
         vfsdbg("Reading %s out->%016x", File->Name, Buffer);
         return File->Node->Operator->Read(File->Node, Offset, Size, Buffer);
     }
References INVALID_PARAMETER, _File::Name, OK, _File::Operator, _File::Status, and vfsdbg.
Referenced by internal_fileRead(), Driver::KernelDriver::LoadKernelDriverFromFile(), and SysCreateProcessFromFile().
Unmount()
FILESTATUS FileSystem::Virtual::Unmount (FILE * File)
Definition at line 307 of file FileSystem.cpp.
     {
         SMART_LOCK(VFSLock);
         if (File == nullptr)
             return FILESTATUS::INVALID_PARAMETER;
         vfsdbg("Unmounting %s", File->Name);
         return FILESTATUS::OK;
     }
References INVALID_PARAMETER, _File::Name, OK, and vfsdbg.
Write()
uint64_t FileSystem::Virtual::Write (FILE * File, uint64_t Offset, uint8_t * Buffer, uint64_t Size)
Definition at line 441 of file FileSystem.cpp.
     {
         SMART_LOCK(VFSLock);
         if (File == nullptr)
             return 0;
         File->Status = FILESTATUS::OK;
         if (File->Node == nullptr)
         {
             File->Status = FILESTATUS::INVALID_PARAMETER;
             return 0;
         }
         if (File->Node->Operator == nullptr)
         {
             File->Status = FILESTATUS::INVALID_PARAMETER;
             return 0;
         }
         vfsdbg("Writing %s out->%016x", File->Name, Buffer);
         return File->Node->Operator->Write(File->Node, Offset, Size, Buffer);
     }
References INVALID_PARAMETER, _File::Name, OK, _File::Operator, _File::Status, and vfsdbg.
Referenced by internal_fileWrite().
Field Documentation
FileSystemRoot
FileSystemNode* FileSystem::Virtual::FileSystemRoot = nullptr private
Definition at line 133 of file filesystem.h.
Referenced by Create(), CreateRoot(), FileExists(), GetPathFromNode(), GetRootNode(), Open(), and Virtual().
The documentation for this class was generated from the following files:
kernel/include/filesystem.h
kernel/filesystem/FileSystem.cpp