Fennix Project: kernel/kernel.h File Reference
kernel.h File Reference
#include <types.h>
#include <boot/gbp.h>
#include <heap.h>
#include "boot/limine.h"
#include "boot/stivale2.h"
Functions
EXTERNC void stivale2_initializator (struct stivale2_struct *bootloaderdata)
void KernelTask ()
Variables
uint8_t kernel_stack [STACK_SIZE]
GlobalBootParams earlyparams
GlobalBootParams * bootparams
SysFlags * sysflags
bool ShowRecoveryScreen
Function Documentation
KernelTask()
void KernelTask ()
Definition at line 125 of file Kernel.cpp.
 {
 #ifdef DEBUG
     debug("Hello World!");
     printf("This is a text to test if the OS is working properly.\n");
     uint32_t test = 0x00FF00;
     CurrentDisplay->SetPrintColor(test);
     for (size_t i = 0; i < 128; i++)
     {
         if (i != '\n')
             CurrentDisplay->KernelPrint(i);
         CurrentDisplay->SetPrintColor(test + i * 2);
     }
     CurrentDisplay->ResetPrintColor();
     CurrentDisplay->KernelPrint('\n');
     printf("Kernel Compiled at: %s %s with C++ Standard: %d\n", __DATE__, __TIME__, CPP_LANGUAGE_STANDARD);
     printf("C++ Language Version (__cplusplus) :%ld\n", __cplusplus);
     if (CheckRunningUnderVM())
     {
         printf("Running under VM.\n");
     }
     else
     {
         printf("Running under physical hardware.\n");
     }
     printf("%s", cpu_get_info());
 #endif
     // for now i'll not load this.
     // if (CurrentTaskingMode != TaskingMode::Mono)
     if (0 != 0)
     {
         kdrv = new Driver::KernelDriver;
         FileSystem::FILE *driverDirectory = vfs->Open("/system/drivers");
         if (driverDirectory->Status == FileSystem::FILESTATUS::OK)
         {
             foreach (auto driver in driverDirectory->Node->Children)
             {
                 if (driver->Flags == FileSystem::NodeFlags::FS_FILE)
                     if (cwk_path_has_extension(driver->Name))
                     {
                         const char *extension;
                         cwk_path_get_extension(driver->Name, &extension, nullptr);
                         if (!strcmp(extension, ".drv"))
{
                             CurrentDisplay->SetPrintColor(0xCCCCCC);
                             printf("Loading driver %s... ", driver->Name);
                             uint64_t ret = kdrv->LoadKernelDriverFromFile(driver);
                             if (ret == 0)
{
                                 CurrentDisplay->SetPrintColor(0x058C19);
                                 printf("OK\n");
                             }
                             else
{
                                 CurrentDisplay->SetPrintColor(0xE85230);
                                 printf("FAILED (%#lx)\n", ret);
                             }
                             CurrentDisplay->ResetPrintColor();
                             // TODO: get instruction pointer of the elf entry point.
                             BS->IncreaseProgres();
                         }
                     }
             }
         }
         vfs->Close(driverDirectory);
     }
     BS->Progress(100);
     if (ShowRecoveryScreen)
         new SystemRecovery::Recovery;
     if (!SysCreateProcessFromFile("/system/init", 0, 0, User))
     {
         CurrentDisplay->SetPrintColor(0xFC4444);
         printf("Failed to load /system/init process. The file is missing or corrupted.\n");
         CPU_HALT;
     }
     trace("End Of Kernel Task");
     if (CurrentTaskingMode != TaskingMode::Mono)
         CPU_STOP;
 }
References BS, CheckRunningUnderVM(), FileSystem::FileSystemNode::Children, FileSystem::Virtual::Close(), cpu_get_info(), CPU_HALT, CPU_STOP, CurrentDisplay, CurrentTaskingMode, cwk_path_get_extension(), cwk_path_has_extension(), debug, FS_FILE, BootScreen::Screen::IncreaseProgres(), kdrv, Driver::KernelDriver::LoadKernelDriverFromFile(), Mono, FileSystem::FILE::Node, OK, FileSystem::Virtual::Open(), printf, BootScreen::Screen::Progress(), ShowRecoveryScreen, FileSystem::FILE::Status, strcmp(), SysCreateProcessFromFile(), trace, and vfs.
Referenced by KernelInit().
stivale2_initializator()
EXTERNC void stivale2_initializator (struct stivale2_struct * bootloaderdata)
Definition at line 42 of file Kernel.cpp.
 {
     init_stivale2(bootloaderdata, &earlyparams, false);
     // asm volatile("andq $-16, %rsp");
     // asm volatile("movw $0, %ax");
     // asm volatile("movw %ax, %fs");
     // wrmsr(MSR_FS_BASE, 0);
     init_pmm();
     init_vmm();
     init_kernelpml();
     // init_heap(AllocationAlgorithm::XallocV1);
     init_heap(AllocationAlgorithm::LibAlloc11);
     bootparams = new GlobalBootParams;
     debug("bootparams is allocated at %p", bootparams);
     debug("bootparams framebuffer is allocated at %p", bootparams->Framebuffer);
     debug("bootparams rsdp is allocated at %p", bootparams->rsdp);
     sysflags = new SysFlags;
     init_stivale2(bootloaderdata, bootparams, true);
     KernelInit();
 }
References bootparams, debug, earlyparams, _GlobalBootParams::Framebuffer, init_heap(), init_kernelpml(), init_pmm(), init_stivale2(), init_vmm(), KernelInit(), LibAlloc11, _GlobalBootParams::rsdp, and sysflags.
Referenced by __attribute__(), and kernel_entry().
Variable Documentation
bootparams
GlobalBootParams* bootparams
Definition at line 34 of file Kernel.cpp.
Referenced by ACPI::ACPI::ACPI(), do_mem_test(), FunctionCallHandler(), init_tss(), initializeKernelFlags(), KernelInit(), stivale2_initializator(), and KernelSymbols::Symbols::Symbols().
earlyparams
GlobalBootParams earlyparams
Definition at line 33 of file Kernel.cpp.
Referenced by init_kernelpml(), init_pmm(), limine_initializator(), and stivale2_initializator().
kernel_stack
uint8_t kernel_stack[STACK_SIZE]
Definition at line 36 of file Kernel.cpp.
Referenced by __attribute__(), and CreateNewTSS().
ShowRecoveryScreen
bool ShowRecoveryScreen
Definition at line 123 of file Kernel.cpp.
Referenced by PS2Keyboard::InterruptHandler(), and KernelTask().
sysflags
SysFlags* sysflags
Definition at line 35 of file Kernel.cpp.
Referenced by initializeKernelFlags(), KernelInit(), and stivale2_initializator().