build:
	make -C init build
	make -C drvmgr
	make -C monoton build
	make -C uiserver build
	make -C wm build
	make -C fesktop build
	make -C shutdown build
	make -C reboot build

clean:
	make -C init clean
	make -C drvmgr clean
	make -C monoton clean
	make -C uiserver clean
	make -C wm clean
	make -C fesktop clean
	make -C shutdown clean
	make -C reboot clean