Fennix Project: kernel/interrupts/Interrputs.cpp File Reference
Interrputs.cpp File Reference
#include <int.h>
#include "../cpu/apic.hpp"
#include "../cpu/idt.h"
#include "../cpu/smp.hpp"
#include "pic.h"
Namespaces
DriverInterrupts
Functions
void EndOfInterrupt (int interrupt)
void MainInterruptHandler (TrapFrame *regs)
void MainRegisterInterrupt (uint8_t vector, INTERRUPT_HANDLER handle)
void MainUnregisterInterrupt (uint8_t vector)
InterruptVector RegisterInterrupt (INTERRUPT_HANDLER Handler)
Register interrupt to an interrupt handler.
bool RegisterInterrupt (INTERRUPT_HANDLER Handler, InterruptVector Vector, bool Override, bool RedirectIRQ, InterruptVector RedirectVector)
bool CRegisterInterrupt (INTERRUPT_HANDLER Handler, InterruptVector Vector, bool Override)
Register interrupt to an interrupt handler.
bool UnregisterInterrupt (InterruptVector Vector)
Unregister interrupt from an interrupt handler.
Variables
INTERRUPT_HANDLER MainRegisteredInterrupts [256]
DriverInterrupts::Register * MainDriverRegisteredInterrupts [256]
static bool RegisteredInterrupts [255]
Function Documentation
CRegisterInterrupt()
bool CRegisterInterrupt (INTERRUPT_HANDLER Handler, InterruptVector Vector, bool Override)
Register interrupt to an interrupt handler.
Parameters
Handler Handler
Vector Vector to register
Override Override if already registered (Some interrupts are unable to be registered even if this is set to true)
Returns
true if successful, false otherwise
Definition at line 152 of file Interrputs.cpp.
 {
     return RegisterInterrupt(Handler, Vector, Override);
 }
References RegisterInterrupt().
Referenced by init_timer().
EndOfInterrupt()
void EndOfInterrupt (int interrupt)
Definition at line 7 of file Interrputs.cpp.
 {
 #if defined(__amd64__) || defined(__i386__)
     if (apic)
         if (apic->APICSupported())
         {
             apic->EOI();
             return;
         }
     PIC_sendEOI(interrupt);
 #endif
 }
References apic, APIC::APIC::APICSupported(), APIC::APIC::EOI(), and PIC_sendEOI().
Referenced by FunctionCallHandler(), Tasking::InterruptHandler(), MainInterruptHandler(), and Tasking::MultiTaskingSchedulerHandler().
MainInterruptHandler()
void MainInterruptHandler (TrapFrame * regs)
Definition at line 25 of file Interrputs.cpp.
 {
 #if defined(__amd64__) || defined(__i386__)
     if (((long)((int32_t)regs->int_num)) < ISR0 || regs->int_num > IRQ223)
     {
         err("Invalid interrupt received %#llx", regs->int_num);
         goto EndOfHandler;
     }
     if (MainDriverRegisteredInterrupts[regs->int_num] != nullptr)
     {
         MainDriverRegisteredInterrupts[regs->int_num]->HandleInterrupt(regs);
         goto EndOfHandler;
     }
     if (MainRegisteredInterrupts[regs->int_num] != nullptr)
     {
         MainRegisteredInterrupts[regs->int_num](regs);
         goto EndOfHandler;
     }
     err("IRQ%d is not registered!", regs->int_num - IRQ0);
 #endif
 EndOfHandler:
     EndOfInterrupt(regs->int_num);
 }
References EndOfInterrupt(), err, _TrapFrame::int_num, IRQ0, IRQ223, ISR0, MainDriverRegisteredInterrupts, and MainRegisteredInterrupts.
MainRegisterInterrupt()
void MainRegisterInterrupt (uint8_t vector, INTERRUPT_HANDLER handle)
Definition at line 53 of file Interrputs.cpp.
 {
     MainRegisteredInterrupts[vector] = handle;
     debug("Vector %#llx(IRQ%d) has been registered to handle %#llx", vector, vector - IRQ0, handle);
 }
References debug, IRQ0, and MainRegisteredInterrupts.
Referenced by RegisterInterrupt().
MainUnregisterInterrupt()
void MainUnregisterInterrupt (uint8_t vector)
Definition at line 59 of file Interrputs.cpp.
 {
     MainRegisteredInterrupts[vector] = nullptr;
     debug("Vector %#llx(IRQ%d) has been unregistered", vector, vector - IRQ0);
 }
References debug, IRQ0, and MainRegisteredInterrupts.
Referenced by UnregisterInterrupt().
RegisterInterrupt() [1/2]
InterruptVector RegisterInterrupt (INTERRUPT_HANDLER Handler)
Register interrupt to an interrupt handler.
Parameters
Handler Handler
Returns
Interrupt vector
Definition at line 97 of file Interrputs.cpp.
 {
     for (int i = IRQ18; i < IRQ223; i++)
         if (!RegisteredInterrupts[i])
         {
             RegisteredInterrupts[i] = true;
             MainRegisterInterrupt(i, Handler);
 #if defined(__amd64__) || defined(__i386__)
             apic->RedirectIRQ(CurrentCPU->ID, i - IRQ0, 1);
 #endif
             trace("Registered interrupt handler for IRQ%d.", i - IRQ0);
             return i;
         }
     err("No available interrupt vector found.");
     return -1;
 }
References apic, CurrentCPU, err, IRQ0, IRQ18, IRQ223, MainRegisterInterrupt(), APIC::APIC::RedirectIRQ(), RegisteredInterrupts, and trace.
Referenced by CRegisterInterrupt(), do_interrupts_mem_test(), Floppy::FloppyDriver::FloppyDriver(), FunctionCallHandler(), PS2Keyboard::PS2KeyboardDriver::PS2KeyboardDriver(), and PS2Mouse::PS2MouseDriver::PS2MouseDriver().
RegisterInterrupt() [2/2]
bool RegisterInterrupt (INTERRUPT_HANDLER Handler, InterruptVector Vector, bool Override, bool RedirectIRQ, InterruptVector RedirectVector)
Definition at line 114 of file Interrputs.cpp.
 {
     if (!Override)
         if (Vector < IRQ18 || Vector > IRQ223)
         {
             err("Invalid interrupt vector %#lx.", Vector);
             return false;
         }
     if (!RegisteredInterrupts[Vector])
     {
         RegisteredInterrupts[Vector] = true;
         MainRegisterInterrupt(Vector, Handler);
         goto Success;
     }
     else if (Override)
     {
         RegisteredInterrupts[Vector] = true;
         MainRegisterInterrupt(Vector, Handler);
         goto Success;
     }
     err("No available interrupt for vector IRQ%d found (override? %s).",
         Vector - IRQ0, Override ? "yes" : "no");
     return false;
 Success:
     if (RedirectIRQ)
     {
 #if defined(__amd64__) || defined(__i386__)
         if (RedirectVector == 0xDEADBEEF)
             apic->RedirectIRQ(CurrentCPU->ID, Vector - IRQ0, 1);
         else
             apic->RedirectIRQ(CurrentCPU->ID, RedirectVector, 1);
 #endif
     }
     trace("Registered interrupt handler for IRQ%d.", Vector - IRQ0);
     return true;
 }
References apic, CurrentCPU, err, IRQ0, IRQ223, MainRegisterInterrupt(), APIC::APIC::RedirectIRQ(), RegisteredInterrupts, and trace.
UnregisterInterrupt()
bool UnregisterInterrupt (InterruptVector vector)
Unregister interrupt from an interrupt handler.
Parameters
Vector Vector to unregister
Returns
true if successful, false otherwise
Definition at line 157 of file Interrputs.cpp.
 {
     if (Vector < IRQ18 || Vector > IRQ223)
         return false;
     RegisteredInterrupts[Vector] = false;
     MainUnregisterInterrupt(Vector);
     trace("IRQ%d unregistered.", Vector - IRQ0);
     return true;
 }
References IRQ0, IRQ223, MainUnregisterInterrupt(), RegisteredInterrupts, and trace.
Referenced by do_interrupts_mem_test().
Variable Documentation
MainDriverRegisteredInterrupts
DriverInterrupts::Register* MainDriverRegisteredInterrupts[256]
Definition at line 23 of file Interrputs.cpp.
Referenced by MainInterruptHandler().
MainRegisteredInterrupts
INTERRUPT_HANDLER MainRegisteredInterrupts[256]
Definition at line 22 of file Interrputs.cpp.
Referenced by MainInterruptHandler(), MainRegisterInterrupt(), and MainUnregisterInterrupt().
RegisteredInterrupts
bool RegisteredInterrupts[255] static
Definition at line 95 of file Interrputs.cpp.
Referenced by RegisterInterrupt(), and UnregisterInterrupt().