Fennix Project: libc/crt/crt1.c File Reference
crt1.c File Reference
Functions
int main (int argc, char *argv[])
void __cxa_finalize (void *f)
void _start ()
Variables
long * stckptr
static char * argv [20]
Function Documentation
__cxa_finalize()
void __cxa_finalize (void * f)
Definition at line 71 of file CXXABI.cpp.
 {
     fixme("__cxa_finalize( %p ) triggered.", f);
     uarch_t i = __atexit_func_count;
     if (!f)
     {
         while (i--)
         {
             if (__atexit_funcs[i].destructor_func)
             {
                 (*__atexit_funcs[i].destructor_func)(__atexit_funcs[i].obj_ptr);
             }
         }
         return;
     }
     while (i--)
     {
         if (__atexit_funcs[i].destructor_func == f)
         {
             (*__atexit_funcs[i].destructor_func)(__atexit_funcs[i].obj_ptr);
             __atexit_funcs[i].destructor_func = 0;
         }
     }
 }
References __atexit_func_count, __atexit_funcs, atexit_func_entry_t::destructor_func, and fixme().
Referenced by _start().
_start()
void _start ()
Definition at line 8 of file crt1.c.
 {
     __asm__("mov %%rsp, %%rcx"
             : "=c"(stckptr)
             :);
     int argc = *((int *)(stckptr + 1));
     int mainret = 0;
     if (argc > 0 && argc < 5)
     {
         for (int i = 0; i < argc; i++)
             argv[i] = ((char *)(stckptr + 2 + 8 * i));
         mainret = main(argc, argv);
     }
     else
         mainret = main(0, (void *)0);
     __cxa_finalize(0);
     unsigned long syscall_return = 0;
     __asm__ __volatile__(
         "pushq %%r11\n"
         "pushq %%rcx\n"
         "syscall\n"
         "popq %%rcx\n"
         "popq %%r11\n"
         : "=a"(syscall_return)
         : "a"(1), "b"(mainret)
         : "memory");
     while (1)
         ;
 }
References __cxa_finalize(), argv, main(), and stckptr.
main()
int main (int argc, char * argv[])
Definition at line 3 of file tictactoe.cpp.
 {
     return -1;
 }
References address, AlreadyInitialized, argv, brainfuck(), CurrentPath, Desktop(), Dock(), EventListener(), scren::Height, InitLogin(), InitScreen(), key_buffer, loop(), mono, monotasking_shell_exit(), MonotonLib::mtl::print(), printf, PrintShellPrefix(), PutRect(), Screen, MonotonLib::mtl::SetForegroundColor(), scren::Width, and WriteSysDebugger().
Referenced by _start().
Variable Documentation
argv
char* argv[20] static
Definition at line 4 of file crt1.c.
Referenced by _start().
stckptr
long* stckptr
Definition at line 3 of file crt1.c.
Referenced by _start().