Fennix Project: RTL8169::NetworkInterfaceController Class Reference
RTL8169::NetworkInterfaceController Class Reference
#include <RTL8169.hpp>
Data Structures
struct BARData
Public Member Functions
MediaAccessControl GetMAC ()
InternetProtocol4 GetIP ()
void SetIP (InternetProtocol4 IP)
NetworkInterfaceController (PCI::PCIDeviceHeader *PCIBaseAddress)
~NetworkInterfaceController ()
void Send (uint8_t *Data, uint64_t Length)
void Receive ()
virtual void HandleInterrupt ()
Public Member Functions inherited from NetworkInterfaceManager::DeviceInterface
virtual void Send (void *Data, uint64_t Length)
Private Attributes
char * RXBuffer
int TXCurrent
InternetProtocol4 IP
uint32_t CurrentPacket
BARData BAR
Additional Inherited Members
Data Fields inherited from NetworkInterfaceManager::DeviceInterface
char Name [128]
Device interface name.
uint64_t ID
Device interface index.
MediaAccessControl MAC
Device interface MAC address (Big-endian)
InternetProtocol4 IP
Device interface IP address (Big-endian)
Detailed Description
Definition at line 10 of file RTL8169.hpp.
Data Structure Documentation
RTL8169::NetworkInterfaceController::BARData
struct RTL8169::NetworkInterfaceController::BARData
Definition at line 13 of file RTL8169.hpp.
Data Fields
uint16_t IOBase
uint32_t MemoryBase
uint8_t Type
Constructor & Destructor Documentation
NetworkInterfaceController()
RTL8169::NetworkInterfaceController::NetworkInterfaceController (PCI::PCIDeviceHeader * PCIBaseAddress)
Definition at line 22 of file RTL8169.cpp.
                                                                                              : DriverInterrupts::Register(((PCI::PCIHeader0 *)PCIBaseAddress)->InterruptLine + IRQ0)
     {
         if (PCIBaseAddress->VendorID != 0x10EC && PCIBaseAddress->DeviceID != 0x8169)
         {
             netdbg("Not a RTL-8169 network card");
             return;
         }
         netdbg("Found %s network card", PCI::GetDeviceName(PCIBaseAddress->VendorID, PCIBaseAddress->DeviceID));
         memcpy(this->Name, "RTL-8169 Network Driver", sizeof(this->Name));
         uint32_t PCIBAR = ((PCI::PCIHeader0 *)PCIBaseAddress)->BAR0;
         BAR.Type = PCIBAR & 1;
         BAR.IOBase = PCIBAR & (~3);
         BAR.MemoryBase = PCIBAR & (~15);
         netdbg("BAR Type: %d - BAR IOBase: %#x - BAR MemoryBase: %#x", BAR.Type, BAR.IOBase, BAR.MemoryBase);
         this->MAC = this->GetMAC();
     }
References BAR, PCI::GetDeviceName(), GetMAC(), RTL8169::NetworkInterfaceController::BARData::IOBase, NetworkInterfaceManager::DeviceInterface::MAC, memcpy(), RTL8169::NetworkInterfaceController::BARData::MemoryBase, NetworkInterfaceManager::DeviceInterface::Name, netdbg, and RTL8169::NetworkInterfaceController::BARData::Type.
~NetworkInterfaceController()
RTL8169::NetworkInterfaceController::~NetworkInterfaceController ()
Definition at line 41 of file RTL8169.cpp.
     {
     }
Member Function Documentation
GetIP()
InternetProtocol4 RTL8169::NetworkInterfaceController::GetIP ()
Definition at line 12 of file RTL8169.cpp.
     {
         return IP;
     }
References IP.
GetMAC()
MediaAccessControl RTL8169::NetworkInterfaceController::GetMAC ()
Definition at line 7 of file RTL8169.cpp.
     {
         return MediaAccessControl();
     }
Referenced by NetworkInterfaceController().
HandleInterrupt()
void RTL8169::NetworkInterfaceController::HandleInterrupt () virtual
Definition at line 53 of file RTL8169.cpp.
     {
     }
Receive()
void RTL8169::NetworkInterfaceController::Receive () virtual
Reimplemented from NetworkInterfaceManager::DeviceInterface.
Definition at line 49 of file RTL8169.cpp.
     {
     }
Send()
void RTL8169::NetworkInterfaceController::Send (uint8_t * Data, uint64_t Length)
Definition at line 45 of file RTL8169.cpp.
     {
     }
SetIP()
void RTL8169::NetworkInterfaceController::SetIP (InternetProtocol4 IP)
Definition at line 17 of file RTL8169.cpp.
     {
         this->IP = IP;
     }
References IP.
Field Documentation
BAR
BARData RTL8169::NetworkInterfaceController::BAR private
Definition at line 24 of file RTL8169.hpp.
Referenced by NetworkInterfaceController().
CurrentPacket
uint32_t RTL8169::NetworkInterfaceController::CurrentPacket private
Definition at line 23 of file RTL8169.hpp.
IP
InternetProtocol4 RTL8169::NetworkInterfaceController::IP private
Definition at line 22 of file RTL8169.hpp.
Referenced by GetIP(), and SetIP().
RXBuffer
char* RTL8169::NetworkInterfaceController::RXBuffer private
Definition at line 20 of file RTL8169.hpp.
TXCurrent
int RTL8169::NetworkInterfaceController::TXCurrent private
Definition at line 21 of file RTL8169.hpp.
The documentation for this class was generated from the following files:
kernel/drivers/network/RTL8169/RTL8169.hpp
kernel/drivers/network/RTL8169/RTL8169.cpp