Fennix Project: kernel/timer/pit.h File Reference
pit.h File Reference
#include <types.h>
Macros
#define PIT_COUNTER0 0x40
#define PIT_CMD 0x43
#define CMD_MODE0 0x00
#define CMD_MODE1 0x02
#define CMD_MODE2 0x04
#define CMD_MODE3 0x06
#define CMD_MODE4 0x08
#define CMD_MODE5 0x0a
#define CMD_COUNTER0 0x00
#define CMD_COUNTER1 0x40
#define CMD_COUNTER2 0x80
#define CMD_READBACK 0xc0
#define CMD_LATCH 0x00
#define CMD_RW_LOW 0x10
#define CMD_RW_HI 0x20
#define CMD_RW_BOTH 0x30
#define CMD_BINARY 0x00
#define CMD_BCD 0x01
Functions
uint32_t get_freq ()
void init_pit ()
void pit_wait (uint32_t miliseconds)
uint64_t pit_get_uptime ()
void pit_oneshot (uint32_t Vector, uint64_t Miliseconds)
Variables
bool PIC_initialized
Macro Definition Documentation
CMD_BCD
#define CMD_BCD 0x01
Definition at line 24 of file pit.h.
CMD_BINARY
#define CMD_BINARY 0x00
Definition at line 23 of file pit.h.
CMD_COUNTER0
#define CMD_COUNTER0 0x00
Definition at line 15 of file pit.h.
CMD_COUNTER1
#define CMD_COUNTER1 0x40
Definition at line 16 of file pit.h.
CMD_COUNTER2
#define CMD_COUNTER2 0x80
Definition at line 17 of file pit.h.
CMD_LATCH
#define CMD_LATCH 0x00
Definition at line 19 of file pit.h.
CMD_MODE0
#define CMD_MODE0 0x00
Definition at line 9 of file pit.h.
CMD_MODE1
#define CMD_MODE1 0x02
Definition at line 10 of file pit.h.
CMD_MODE2
#define CMD_MODE2 0x04
Definition at line 11 of file pit.h.
CMD_MODE3
#define CMD_MODE3 0x06
Definition at line 12 of file pit.h.
CMD_MODE4
#define CMD_MODE4 0x08
Definition at line 13 of file pit.h.
CMD_MODE5
#define CMD_MODE5 0x0a
Definition at line 14 of file pit.h.
CMD_READBACK
#define CMD_READBACK 0xc0
Definition at line 18 of file pit.h.
CMD_RW_BOTH
#define CMD_RW_BOTH 0x30
Definition at line 22 of file pit.h.
CMD_RW_HI
#define CMD_RW_HI 0x20
Definition at line 21 of file pit.h.
CMD_RW_LOW
#define CMD_RW_LOW 0x10
Definition at line 20 of file pit.h.
PIT_CMD
#define PIT_CMD 0x43
Definition at line 7 of file pit.h.
PIT_COUNTER0
#define PIT_COUNTER0 0x40
Definition at line 6 of file pit.h.
Function Documentation
get_freq()
uint32_t get_freq ()
Definition at line 11 of file PIT.c.
 {
     return freq;
 }
References freq.
Referenced by get_timer_clock().
init_pit()
void init_pit ()
Definition at line 22 of file PIT.c.
 {
     trace("Initializing PIT timer");
     uint32_t divisor = freq / hertz;
     outb(PIT_CMD, CMD_BINARY | CMD_MODE3 | CMD_RW_BOTH | CMD_COUNTER0);
     outb(PIT_COUNTER0, divisor);
     outb(PIT_COUNTER0, divisor >> 8);
     PIC_initialized = true;
 }
References CMD_BINARY, CMD_COUNTER0, CMD_MODE3, CMD_RW_BOTH, freq, hertz, outb, PIC_initialized, PIT_CMD, PIT_COUNTER0, and trace.
Referenced by init_timer().
pit_get_uptime()
uint64_t pit_get_uptime ()
Definition at line 45 of file PIT.c.
 {
     return TimeSinceBoot;
 }
References TimeSinceBoot.
pit_oneshot()
void pit_oneshot (uint32_t Vector, uint64_t Miliseconds)
Definition at line 50 of file PIT.c.
 {
     err("PIT One-Shot mode is not implemented!");
 }
References err.
Referenced by TimerOneShot().
pit_wait()
void pit_wait (uint32_t miliseconds)
Definition at line 32 of file PIT.c.
 {
     uint32_t now = ticks;
     ++miliseconds;
     if (ticks <= 0)
     {
         err("PIT timer is not enabled!!");
     }
     else
         while (ticks - now < miliseconds)
             ;
 }
References err, and ticks.
Referenced by msleep(), nsleep(), sleep(), and usleep().
Variable Documentation
PIC_initialized
bool PIC_initialized
Definition at line 6 of file PIT.c.
Referenced by init_pit(), init_timer(), msleep(), nsleep(), sleep(), TimerOneShot(), and usleep().