Fennix Project: kernel/include/int.h File Reference
int.h File Reference
#include <types.h>
#include <interrupts.h>
#include <cputables.h>
Typedefs
typedef void(* INTERRUPT_HANDLER) (TrapFrame *)
typedef unsigned int InterruptVector
Functions
EXTERNC void EndOfInterrupt (int interrupt)
InterruptVector RegisterInterrupt (INTERRUPT_HANDLER Handler)
Register interrupt to an interrupt handler.
bool CRegisterInterrupt (INTERRUPT_HANDLER Handler, InterruptVector Vector, bool Override)
Register interrupt to an interrupt handler.
bool UnregisterInterrupt (InterruptVector vector)
Unregister interrupt from an interrupt handler.
Typedef Documentation
INTERRUPT_HANDLER
typedef void(* INTERRUPT_HANDLER) (TrapFrame *)
Definition at line 10 of file int.h.
InterruptVector
typedef unsigned int InterruptVector
Definition at line 11 of file int.h.
Function Documentation
CRegisterInterrupt()
bool CRegisterInterrupt (INTERRUPT_HANDLER Handler, InterruptVector Vector, bool Override)
Register interrupt to an interrupt handler.
Parameters
Handler Handler
Vector Vector to register
Override Override if already registered (Some interrupts are unable to be registered even if this is set to true)
Returns
true if successful, false otherwise
Definition at line 144 of file Interrputs.cpp.
 {
     return RegisterInterrupt(Handler, Vector, Override);
 }
References RegisterInterrupt().
Referenced by init_timer().
EndOfInterrupt()
EXTERNC void EndOfInterrupt (int interrupt)
Definition at line 7 of file Interrputs.cpp.
 {
     if (apic)
         if (apic->APICSupported())
         {
             apic->EOI();
             return;
         }
     PIC_sendEOI(interrupt);
 }
References apic, APIC::APIC::APICSupported(), APIC::APIC::EOI(), and PIC_sendEOI().
Referenced by FunctionCallHandler(), Tasking::InterruptHandler(), MainInterruptHandler(), and Tasking::MultiTaskingSchedulerHandler().
RegisterInterrupt()
InterruptVector RegisterInterrupt (INTERRUPT_HANDLER Handler)
Register interrupt to an interrupt handler.
Parameters
Handler Handler
Returns
Interrupt vector
Definition at line 93 of file Interrputs.cpp.
 {
     for (int i = IRQ18; i < IRQ223; i++)
         if (!RegisteredInterrupts[i])
         {
             RegisteredInterrupts[i] = true;
             MainRegisterInterrupt(i, Handler);
             apic->RedirectIRQ(CurrentCPU->ID, i - IRQ0, 1);
             trace("Registered interrupt handler for IRQ%d.", i - IRQ0);
             return i;
         }
     err("No available interrupt vector found.");
     return -1;
 }
References apic, CurrentCPU, err, MainRegisterInterrupt(), APIC::APIC::RedirectIRQ(), RegisteredInterrupts, and trace.
Referenced by CRegisterInterrupt(), do_interrupts_mem_test(), Floppy::FloppyDriver::FloppyDriver(), FunctionCallHandler(), ACPI::DSDT::InitSCI(), PS2Keyboard::PS2KeyboardDriver::PS2KeyboardDriver(), and PS2Mouse::PS2MouseDriver::PS2MouseDriver().
UnregisterInterrupt()
bool UnregisterInterrupt (InterruptVector vector)
Unregister interrupt from an interrupt handler.
Parameters
Vector Vector to unregister
Returns
true if successful, false otherwise
Definition at line 149 of file Interrputs.cpp.
 {
     if (Vector < IRQ18 || Vector > IRQ223)
         return false;
     RegisteredInterrupts[Vector] = false;
     MainUnregisterInterrupt(Vector);
     trace("IRQ%d unregistered.", Vector - IRQ0);
     return true;
 }
References MainUnregisterInterrupt(), RegisteredInterrupts, and trace.
Referenced by do_interrupts_mem_test().