Fennix Project: MonotonLib::mtl Class Reference
MonotonLib::mtl Class Reference
#include <monotonlib.h>
Data Structures
struct _PSF2_FONT
struct Framebuffer
struct PSF2_HEADER
Public Member Functions
mtl (char *FontPath)
~mtl ()
void SetPrintPosition (PrintPos Position)
PrintPos GetPrintPosition ()
void Clear ()
void Scroll ()
void RemoveChar ()
void RemoveChar (uint32_t X, uint32_t Y)
void printchar (char Char)
void printchar (char Char, PrintPos Position)
void print (const char *Text, PrintPos Position)
void print (const char *Text)
Private Types
typedef struct MonotonLib::mtl::_PSF2_FONT PSF2_FONT
Private Attributes
uint32_t Xpos = 0
uint32_t Ypos = 0
PSF2_FONT * PSF2Font = nullptr
Framebuffer FB = {0, 0, 0, 0}
uint32_t Background = 0x000000
uint32_t Foreground = 0xFFFFFF
Detailed Description
Definition at line 13 of file monotonlib.h.
Data Structure Documentation
MonotonLib::mtl::_PSF2_FONT
struct MonotonLib::mtl::_PSF2_FONT
Definition at line 32 of file monotonlib.h.
Data Fields
void * GlyphBuffer
PSF2_HEADER * Header
MonotonLib::mtl::Framebuffer
struct MonotonLib::mtl::Framebuffer
Definition at line 38 of file monotonlib.h.
Data Fields
uint64_t Address
uint32_t Height
uint32_t PixelsPerScanLine
uint32_t Width
MonotonLib::mtl::PSF2_HEADER
struct MonotonLib::mtl::PSF2_HEADER
Definition at line 21 of file monotonlib.h.
Data Fields
uint32_t charsize
uint32_t flags
uint32_t headersize
uint32_t height
uint32_t length
uint8_t magic[4]
uint32_t version
uint32_t width
Member Typedef Documentation
PSF2_FONT
typedef struct MonotonLib::mtl::_PSF2_FONT MonotonLib::mtl::PSF2_FONT private
Constructor & Destructor Documentation
mtl()
MonotonLib::mtl::mtl (char * FontPath)
Definition at line 8 of file monotonlib.cpp.
     {
         syscall_dbg(0x3F8, (char *)"[MonotonLib] Started.\n");
         File *FontBinary = (File *)syscall_FileOpen(FontPath);
         if (FontBinary == nullptr)
         {
             syscall_dbg(0x3F8, (char *)"[LoadFont] Error! Could not open file.\n");
             syscall_FileClose(FontBinary);
             return;
         }
         syscall_dbg(0x3F8, (char *)"[LoadFont] File opened.\n");
         uint64_t FontFileSize = FontBinary->Length;
         void *FontAllocatedData = malloc(FontFileSize);
         syscall_FileRead(FontBinary, 0, FontAllocatedData, FontFileSize);
         PSF2Font = new PSF2_FONT;
         uint16_t glyph2 = 0;
         PSF2_HEADER *font2 = (PSF2_HEADER *)FontAllocatedData;
         if (font2->magic[0] != PSF2_MAGIC0 || font2->magic[1] != PSF2_MAGIC1 || font2->magic[2] != PSF2_MAGIC2 || font2->magic[3] != PSF2_MAGIC3)
         {
             syscall_dbg(0x3F8, (char *)"[LoadFont] Invalid PSF2 file.\n");
             syscall_FileClose(FontBinary);
             free(FontAllocatedData);
             delete PSF2Font;
             return;
         }
         PSF2Font->Header = font2;
         PSF2Font->GlyphBuffer = (void *)((uint64_t)FontAllocatedData + sizeof(PSF2_HEADER));
         syscall_dbg(0x3F8, (char *)"[LoadFont] Font loaded.\n");
         FB.Address = syscall_displayAddress();
         FB.Width = syscall_displayWidth();
         FB.Height = syscall_displayHeight();
         FB.PixelsPerScanLine = syscall_displayPixelsPerScanLine();
         syscall_FileClose(FontBinary);
     }
References MonotonLib::mtl::Framebuffer::Address, FB, free(), MonotonLib::mtl::_PSF2_FONT::GlyphBuffer, MonotonLib::mtl::_PSF2_FONT::Header, MonotonLib::mtl::Framebuffer::Height, _File::Length, MonotonLib::mtl::PSF2_HEADER::magic, malloc(), MonotonLib::mtl::Framebuffer::PixelsPerScanLine, PSF2_MAGIC0, PSF2_MAGIC1, PSF2_MAGIC2, PSF2_MAGIC3, PSF2Font, and MonotonLib::mtl::Framebuffer::Width.
~mtl()
MonotonLib::mtl::~mtl ()
Definition at line 47 of file monotonlib.cpp.
     {
         free(PSF2Font->Header);
         delete PSF2Font;
     }
References free(), MonotonLib::mtl::_PSF2_FONT::Header, and PSF2Font.
Member Function Documentation
Clear()
void MonotonLib::mtl::Clear ()
Definition at line 84 of file monotonlib.cpp.
     {
         for (int VerticalScanline = 0; VerticalScanline < FB.Height; VerticalScanline++)
         {
             uint64_t PixelPtrBase = FB.Address + ((FB.PixelsPerScanLine * 4) * VerticalScanline);
             for (uint32_t *PixelPtr = (uint32_t *)PixelPtrBase; PixelPtr < (uint32_t *)(PixelPtrBase + (FB.PixelsPerScanLine * 4)); PixelPtr++)
                 *PixelPtr = Background;
         }
         this->SetPrintPosition({0, 0});
     }
References MonotonLib::mtl::Framebuffer::Address, Background, FB, MonotonLib::mtl::Framebuffer::Height, MonotonLib::mtl::Framebuffer::PixelsPerScanLine, and SetPrintPosition().
Referenced by ParseBuffer().
GetPrintPosition()
PrintPos MonotonLib::mtl::GetPrintPosition ()
Definition at line 79 of file monotonlib.cpp.
     {
         return {Xpos, Ypos};
     }
References Xpos, and Ypos.
print() [1/2]
void MonotonLib::mtl::print (const char * Text)
Definition at line 231 of file monotonlib.cpp.
     {
         this->print(Text, {Xpos, Ypos});
     }
References print(), Xpos, and Ypos.
print() [2/2]
void MonotonLib::mtl::print (const char * Text, PrintPos Position)
Definition at line 187 of file monotonlib.cpp.
     {
         uint32_t Xi = Position.x, Yi = Position.y;
         long unsigned textlength = 0;
         while (Text[textlength] != '\0')
             ++textlength;
         for (int i = 0; i < textlength; i++)
         {
             char Char = Text[i];
             if (Char == '\n')
             {
                 Xi = 0;
                 Yi += PSF2Font->Header->height;
                 if (Ypos >= (FB.Height - PSF2Font->Header->height))
                 {
                     this->Scroll();
                     this->SetPrintPosition({Xpos, Ypos - PSF2Font->Header->height});
                 }
                 continue;
             }
             else if (Char == '\r')
             {
                 Xi = 0;
                 continue;
             }
             if (Char < 0 || (unsigned char)Char > 127)
                 Char = '?';
             int bytesperline = (PSF2Font->Header->width + 7) / 8;
             uint32_t *PixelPtr = (uint32_t *)FB.Address;
             char *FontPtr = (char *)PSF2Font->Header + PSF2Font->Header->headersize + (Char > 0 && (unsigned char)Char < PSF2Font->Header->length ? Char : 0) * PSF2Font->Header->charsize;
             for (unsigned long Y = Yi; Y < Yi + PSF2Font->Header->height; Y++)
             {
                 for (unsigned long X = Xi; X < Xi + PSF2Font->Header->width; X++)
                     if ((*FontPtr & (0b10000000 >> (X - Xi))) > 0)
                         *(uint32_t *)(PixelPtr + X + (Y * FB.PixelsPerScanLine)) = Foreground;
                 FontPtr += bytesperline;
             }
             Xi += PSF2Font->Header->width;
         }
         this->SetPrintPosition({Xi, Yi});
     }
References MonotonLib::mtl::Framebuffer::Address, MonotonLib::mtl::PSF2_HEADER::charsize, FB, Foreground, MonotonLib::mtl::_PSF2_FONT::Header, Header, MonotonLib::mtl::PSF2_HEADER::headersize, MonotonLib::mtl::PSF2_HEADER::height, MonotonLib::mtl::Framebuffer::Height, MonotonLib::mtl::Framebuffer::PixelsPerScanLine, PSF2Font, Scroll(), SetPrintPosition(), MonotonLib::mtl::PSF2_HEADER::width, MonotonLib::PrintPos::x, Xpos, MonotonLib::PrintPos::y, and Ypos.
Referenced by InitLogin(), main(), ParseBuffer(), and print().
printchar() [1/2]
void MonotonLib::mtl::printchar (char Char)
Definition at line 155 of file monotonlib.cpp.
     {
         if (Char == '\n')
         {
             this->SetPrintPosition({0, Ypos + PSF2Font->Header->height});
             if (Ypos >= (FB.Height - PSF2Font->Header->height))
             {
                 this->Scroll();
                 this->SetPrintPosition({Xpos, Ypos - PSF2Font->Header->height});
             }
             return;
         }
         else if (Char == '\r')
         {
             this->SetPrintPosition({0, Ypos});
             return;
         }
         if (Char < 0 || (unsigned char)Char > 127)
             Char = '?';
         int bytesperline = (PSF2Font->Header->width + 7) / 8;
         uint32_t *PixelPtr = (uint32_t *)FB.Address;
         char *FontPtr = (char *)PSF2Font->Header + PSF2Font->Header->headersize + (Char > 0 && (unsigned char)Char < PSF2Font->Header->length ? Char : 0) * PSF2Font->Header->charsize;
         for (unsigned long Y = Ypos; Y < Ypos + PSF2Font->Header->height; Y++)
         {
             for (unsigned long X = Xpos; X < Xpos + PSF2Font->Header->width; X++)
                 if ((*FontPtr & (0b10000000 >> (X - Xpos))) > 0)
                     *(uint32_t *)(PixelPtr + X + (Y * FB.PixelsPerScanLine)) = Foreground;
             FontPtr += bytesperline;
         }
         Xpos += PSF2Font->Header->width;
     }
References MonotonLib::mtl::Framebuffer::Address, MonotonLib::mtl::PSF2_HEADER::charsize, FB, Foreground, MonotonLib::mtl::_PSF2_FONT::Header, Header, MonotonLib::mtl::PSF2_HEADER::headersize, MonotonLib::mtl::PSF2_HEADER::height, MonotonLib::mtl::Framebuffer::Height, MonotonLib::mtl::Framebuffer::PixelsPerScanLine, PSF2Font, Scroll(), SetPrintPosition(), MonotonLib::mtl::PSF2_HEADER::width, Xpos, and Ypos.
Referenced by InitLogin(), loop(), and ParseBuffer().
printchar() [2/2]
void MonotonLib::mtl::printchar (char Char, PrintPos Position)
Definition at line 117 of file monotonlib.cpp.
     {
         uint32_t Xi = Position.x, Yi = Position.y;
         if (Char == '\n')
         {
             Xi = 0;
             Yi += PSF2Font->Header->height;
             this->SetPrintPosition({Xi, Yi});
             if (Ypos >= (FB.Height - PSF2Font->Header->height))
             {
                 this->Scroll();
                 this->SetPrintPosition({Xpos, Ypos - PSF2Font->Header->height});
             }
             return;
         }
         else if (Char == '\r')
         {
             Xi = 0;
             this->SetPrintPosition({Xi, Yi});
             return;
         }
         if (Char < 0 || (unsigned char)Char > 127)
             Char = '?';
         int bytesperline = (PSF2Font->Header->width + 7) / 8;
         uint32_t *PixelPtr = (uint32_t *)FB.Address;
         char *FontPtr = (char *)PSF2Font->Header + PSF2Font->Header->headersize + (Char > 0 && (unsigned char)Char < PSF2Font->Header->length ? Char : 0) * PSF2Font->Header->charsize;
         for (unsigned long Y = Yi; Y < Yi + PSF2Font->Header->height; Y++)
         {
             for (unsigned long X = Xi; X < Xi + PSF2Font->Header->width; X++)
                 if ((*FontPtr & (0b10000000 >> (X - Xi))) > 0)
                     *(uint32_t *)(PixelPtr + X + (Y * FB.PixelsPerScanLine)) = Foreground;
             FontPtr += bytesperline;
         }
         Xi += PSF2Font->Header->width;
         this->SetPrintPosition({Xi, Yi});
     }
References MonotonLib::mtl::Framebuffer::Address, MonotonLib::mtl::PSF2_HEADER::charsize, FB, Foreground, MonotonLib::mtl::_PSF2_FONT::Header, Header, MonotonLib::mtl::PSF2_HEADER::headersize, MonotonLib::mtl::PSF2_HEADER::height, MonotonLib::mtl::Framebuffer::Height, MonotonLib::mtl::Framebuffer::PixelsPerScanLine, PSF2Font, Scroll(), SetPrintPosition(), MonotonLib::mtl::PSF2_HEADER::width, MonotonLib::PrintPos::x, Xpos, MonotonLib::PrintPos::y, and Ypos.
RemoveChar() [1/2]
void MonotonLib::mtl::RemoveChar ()
Definition at line 102 of file monotonlib.cpp.
     {
         for (unsigned long Y = Ypos; Y < Ypos + PSF2Font->Header->height; Y++)
             for (unsigned long X = Xpos - PSF2Font->Header->width; X < Xpos; X++)
                 *(unsigned int *)((unsigned int *)FB.Address + X + (Y * FB.PixelsPerScanLine)) = Background;
         this->SetPrintPosition({Xpos - PSF2Font->Header->width, Ypos});
     }
References MonotonLib::mtl::Framebuffer::Address, Background, FB, MonotonLib::mtl::_PSF2_FONT::Header, MonotonLib::mtl::PSF2_HEADER::height, MonotonLib::mtl::Framebuffer::PixelsPerScanLine, PSF2Font, SetPrintPosition(), MonotonLib::mtl::PSF2_HEADER::width, Xpos, and Ypos.
Referenced by InitLogin(), and loop().
RemoveChar() [2/2]
void MonotonLib::mtl::RemoveChar (uint32_t X, uint32_t Y)
Definition at line 110 of file monotonlib.cpp.
     {
         for (unsigned long Y = y; Y < y + PSF2Font->Header->height; Y++)
             for (unsigned long X = x - PSF2Font->Header->width; X < x; X++)
                 *(unsigned int *)((unsigned int *)FB.Address + X + (Y * FB.PixelsPerScanLine)) = Background;
     }
References MonotonLib::mtl::Framebuffer::Address, Background, FB, MonotonLib::mtl::_PSF2_FONT::Header, MonotonLib::mtl::PSF2_HEADER::height, MonotonLib::mtl::Framebuffer::PixelsPerScanLine, PSF2Font, and MonotonLib::mtl::PSF2_HEADER::width.
Scroll()
void MonotonLib::mtl::Scroll ()
Definition at line 95 of file monotonlib.cpp.
     {
         memmove((void *)FB.Address,
                 (void *)(FB.Address + static_cast<uint64_t>(FB.Width) * PSF2Font->Header->height * 4),
                 static_cast<uint64_t>(FB.Width) * (FB.Height - PSF2Font->Header->height) * 4);
     }
References MonotonLib::mtl::Framebuffer::Address, FB, MonotonLib::mtl::_PSF2_FONT::Header, MonotonLib::mtl::PSF2_HEADER::height, MonotonLib::mtl::Framebuffer::Height, memmove(), PSF2Font, and MonotonLib::mtl::Framebuffer::Width.
Referenced by print(), and printchar().
SetPrintPosition()
void MonotonLib::mtl::SetPrintPosition (PrintPos Position)
Definition at line 53 of file monotonlib.cpp.
     {
         if (Position.x > FB.Width)
         {
             Xpos = FB.Width;
             return;
         }
         else if (Position.y > FB.Height)
         {
             Ypos = FB.Height;
             return;
         }
         else if (Position.x < 0)
         {
             Xpos = 0;
             return;
         }
         else if (Position.y < 0)
         {
             Ypos = 0;
             return;
         }
         Xpos = Position.x;
         Ypos = Position.y;
     }
References FB, MonotonLib::mtl::Framebuffer::Height, MonotonLib::mtl::Framebuffer::Width, MonotonLib::PrintPos::x, Xpos, MonotonLib::PrintPos::y, and Ypos.
Referenced by Clear(), print(), printchar(), and RemoveChar().
Field Documentation
Background
uint32_t MonotonLib::mtl::Background = 0x000000 private
Definition at line 48 of file monotonlib.h.
Referenced by Clear(), and RemoveChar().
FB
Framebuffer MonotonLib::mtl::FB = {0, 0, 0, 0} private
Definition at line 47 of file monotonlib.h.
Referenced by Clear(), mtl(), print(), printchar(), RemoveChar(), Scroll(), and SetPrintPosition().
Foreground
uint32_t MonotonLib::mtl::Foreground = 0xFFFFFF private
Definition at line 48 of file monotonlib.h.
Referenced by print(), and printchar().
PSF2Font
PSF2_FONT* MonotonLib::mtl::PSF2Font = nullptr private
Definition at line 46 of file monotonlib.h.
Referenced by mtl(), print(), printchar(), RemoveChar(), Scroll(), and ~mtl().
Xpos
uint32_t MonotonLib::mtl::Xpos = 0 private
Definition at line 45 of file monotonlib.h.
Referenced by GetPrintPosition(), print(), printchar(), RemoveChar(), and SetPrintPosition().
Ypos
uint32_t MonotonLib::mtl::Ypos = 0 private
Definition at line 45 of file monotonlib.h.
Referenced by GetPrintPosition(), print(), printchar(), RemoveChar(), and SetPrintPosition().
The documentation for this class was generated from the following files:
userspace/libs/monoton/monotonlib.h
userspace/libs/monoton/monotonlib.cpp