Fennix Project: APIC::APIC Class Reference
APIC::APIC Class Reference
#include <apic.hpp>
Public Types
enum APICRegisters {
APIC_ONESHOT = (0 << 17), APIC_PERIODIC = (1 << 17), APIC_TSC_DEADLINE = (2 << 17), APIC_ID = 0x20,
APIC_VER = 0x30, APIC_TPR = 0x80, APIC_APR = 0x90, APIC_PPR = 0xa0,
APIC_EOI = 0xb0, APIC_RRD = 0xc0, APIC_LDR = 0xd0, APIC_DFR = 0xe0,
APIC_SVR = 0xf0, APIC_ISR = 0x100, APIC_TMR = 0x180, APIC_IRR = 0x200,
APIC_ESR = 0x280, APIC_ICRLO = 0x300, APIC_ICRHI = 0x310, APIC_TIMER = 0x320,
APIC_THERMAL = 0x330, APIC_PERF = 0x340, APIC_LINT0 = 0x350, APIC_LINT1 = 0x360,
APIC_ERROR = 0x370, APIC_TICR = 0x380, APIC_TCCR = 0x390, APIC_TDCR = 0x3e0
}
Public Member Functions
uint32_t Read (uint32_t Register)
void Write (uint32_t Register, uint32_t Value)
void IOWrite (uint64_t Base, uint32_t Register, uint32_t Value)
uint32_t IORead (uint64_t Base, uint32_t Register)
void EOI ()
void RedirectIRQs (int CPU=0)
void IPI (uint8_t CPU, uint32_t InterruptNumber)
void OneShot (uint32_t Vector, uint64_t Miliseconds)
bool APICSupported ()
uint32_t IOGetMaxRedirect (uint32_t APICID)
void RawRedirectIRQ (uint8_t Vector, uint32_t GSI, uint16_t Flags, int CPU, int Status)
void RedirectIRQ (int CPU, uint8_t IRQ, int Status)
APIC ()
~APIC ()
Private Attributes
bool x2APICSupported = false
Detailed Description
Definition at line 10 of file apic.hpp.
Member Enumeration Documentation
APICRegisters
enum APIC::APIC::APICRegisters
Enumerator
APIC_ONESHOT
APIC_PERIODIC
APIC_TSC_DEADLINE
APIC_ID
APIC_VER
APIC_TPR
APIC_APR
APIC_PPR
APIC_EOI
APIC_RRD
APIC_LDR
APIC_DFR
APIC_SVR
APIC_ISR
APIC_TMR
APIC_IRR
APIC_ESR
APIC_ICRLO
APIC_ICRHI
APIC_TIMER
APIC_THERMAL
APIC_PERF
APIC_LINT0
APIC_LINT1
APIC_ERROR
APIC_TICR
APIC_TCCR
APIC_TDCR
Definition at line 16 of file apic.hpp.
         {
             APIC_ONESHOT = (0 << 17),      // LVT One-Shot Mode  (for Timer)
             APIC_PERIODIC = (1 << 17),     // LVT Periodic Mode (for Timer)
             APIC_TSC_DEADLINE = (2 << 17), // LVT Timer/sDeadline (for Timer)
             // source from: https://github.com/pdoane/osdev/blob/master/intr/local_apic.c
             APIC_ID = 0x20,       // Local APIC ID
             APIC_VER = 0x30,      // Local APIC Version
             APIC_TPR = 0x80,      // Task Priority
             APIC_APR = 0x90,      // Arbitration Priority
             APIC_PPR = 0xa0,      // Processor Priority
             APIC_EOI = 0xb0,      // EOI
             APIC_RRD = 0xc0,      // Remote Read
             APIC_LDR = 0xd0,      // Logical Destination
             APIC_DFR = 0xe0,      // Destination Format
             APIC_SVR = 0xf0,      // Spurious Interrupt Vector
             APIC_ISR = 0x100,     // In-Service (8 registers)
             APIC_TMR = 0x180,     // Trigger Mode (8 registers)
             APIC_IRR = 0x200,     // Interrupt Request (8 registers)
             APIC_ESR = 0x280,     // Error Status
             APIC_ICRLO = 0x300,   // Interrupt Command
             APIC_ICRHI = 0x310,   // Interrupt Command [63:32]
             APIC_TIMER = 0x320,   // LVT Timer
             APIC_THERMAL = 0x330, // LVT Thermal Sensor
             APIC_PERF = 0x340,    // LVT Performance Counter
             APIC_LINT0 = 0x350,   // LVT LINT0
             APIC_LINT1 = 0x360,   // LVT LINT1
             APIC_ERROR = 0x370,   // LVT Error
             APIC_TICR = 0x380,    // Initial Count (for Timer)
             APIC_TCCR = 0x390,    // Current Count (for Timer)
             APIC_TDCR = 0x3e0,    // Divide Configuration (for Timer)
         };
Constructor & Destructor Documentation
APIC()
APIC::APIC::APIC ()
Definition at line 195 of file APIC.cpp.
     {
         trace("Initializing APIC...");
         EnterCriticalSection;
         if (!this->APICSupported())
             return;
         uint32_t rax, rbx, rcx, rdx;
         cpuid(1, &rax, &rbx, &rcx, &rdx);
         if (rcx & CPUID_FEAT_RCX_x2APIC)
         {
             // trace("x2APIC Supported!");
             // x2APICSupported = true;
             trace("x2APIC is supported by the system but disabled because of an unknown error.");
             // wrmsr(MSR_APIC_BASE, (rdmsr(MSR_APIC_BASE) | (1 << 11)) & ~(1 << 10));
             wrmsr(MSR_APIC_BASE, (rdmsr(MSR_APIC_BASE) | (1 << 11)));
         }
         else
         {
             wrmsr(MSR_APIC_BASE, (rdmsr(MSR_APIC_BASE) | (1 << 11)));
         }
         debug("APIC Base Address is %#lx", rdmsr(MSR_APIC_BASE));
         this->Write(APIC_TPR, 0x0);
         this->Write(APIC_SVR, this->Read(APIC_SVR) | 0x100); // 0x1FF or 0x100 ? on https://wiki.osdev.org/APIC is 0x100
         if (!x2APICSupported)
         {
             this->Write(APIC_DFR, 0xF0000000);
             this->Write(APIC_LDR, this->Read(APIC_ID)); // APIC ID or 0xFF000000 ?
         }
         foreach (ACPI::MADT::MADTNmi *nmi in madt->nmi)
         {
             if (nmi->processor != 0xFF)
                 if (nmi->processor == 0)
                 {
                     uint32_t value = 0x400 | 2;
                     if (nmi->flags & 2)
                         value |= 1 << 13;
                     if (nmi->flags & 8)
                         value |= 1 << 15;
                     if (nmi->lint == 0)
                         this->Write(0x350, value);
                     else if (nmi->lint == 1)
                         this->Write(0x360, value);
                 }
         }
         PIC_disable();
         LeaveCriticalSection;
     }
References cpuid(), CPUID_FEAT_RCX_x2APIC, debug, EnterCriticalSection, ACPI::MADT::MADTNmi::flags, LeaveCriticalSection, ACPI::MADT::MADTNmi::lint, madt, MSR_APIC_BASE, ACPI::MADT::nmi, PIC_disable(), ACPI::MADT::MADTNmi::processor, rdmsr(), trace, and wrmsr().
~APIC()
APIC::APIC::~APIC ()
Definition at line 249 of file APIC.cpp.
     {
     }
Member Function Documentation
APICSupported()
bool APIC::APIC::APICSupported ()
Definition at line 130 of file APIC.cpp.
     {
         if (!madt->LAPICAddr)
             return false;
         uint32_t rax, rbx, rcx, rdx;
         cpuid(1, &rax, &rbx, &rcx, &rdx);
         return (rdx & CPUID_FEAT_RDX_APIC);
     }
References cpuid(), CPUID_FEAT_RDX_APIC, ACPI::MADT::LAPICAddr, and madt.
Referenced by EndOfInterrupt(), and KernelInit().
EOI()
void APIC::APIC::EOI ()
Definition at line 94 of file APIC.cpp.
     {
         this->Write(APIC_EOI, 0);
     }
Referenced by EndOfInterrupt().
IOGetMaxRedirect()
uint32_t APIC::APIC::IOGetMaxRedirect (uint32_t APICID)
Definition at line 139 of file APIC.cpp.
     {
         uint32_t TableAddress = (this->IORead((madt->ioapic[APICID]->addr), GetIOAPICVersion));
         return ((IOAPICVersion *)&TableAddress)->MaximumRedirectionEntry;
     }
References APICID, APIC::GetIOAPICVersion, ACPI::MADT::ioapic, and madt.
IORead()
uint32_t APIC::APIC::IORead (uint64_t Base, uint32_t Register)
Definition at line 87 of file APIC.cpp.
     {
         debug("APIC::IORead(%#lx, %#lx)", Base, Register);
         *((volatile uint32_t *)(((uintptr_t)Base))) = Register;
         return *((volatile uint32_t *)(((uintptr_t)Base + 16)));
     }
References debug.
IOWrite()
void APIC::APIC::IOWrite (uint64_t Base, uint32_t Register, uint32_t Value)
Definition at line 80 of file APIC.cpp.
     {
         debug("APIC::IOWrite(%#lx, %#lx, %#lx)", Base, Register, Value);
         *((volatile uint32_t *)(((uintptr_t)Base))) = Register;
         *((volatile uint32_t *)(((uintptr_t)Base + 16))) = Value;
     }
References debug.
IPI()
void APIC::APIC::IPI (uint8_t CPU, uint32_t InterruptNumber)
Definition at line 107 of file APIC.cpp.
     {
         if (x2APICSupported)
         {
             wrmsr(MSR_X2APIC_ICR, ((uint64_t)CPU) << 32 | InterruptNumber);
         }
         else
         {
             InterruptNumber = (1 << 14) | InterruptNumber;
             this->Write(APIC_ICRHI, (CPU << 24));
             this->Write(APIC_ICRLO, InterruptNumber);
         }
     }
References MSR_X2APIC_ICR, and wrmsr().
OneShot()
void APIC::APIC::OneShot (uint32_t Vector, uint64_t Miliseconds)
Definition at line 121 of file APIC.cpp.
     {
         // apic->Write(APIC::APIC::APIC_TIMER, apic->Read(APIC::APIC::APIC_TIMER) & ~(1 << 0x10));
         this->Write(APIC_TDCR, 0x03);
         this->Write(APIC_TIMER, (APIC::APIC::APICRegisters::APIC_ONESHOT | Vector));
         this->Write(APIC_TICR, apic_timer_ticks * Miliseconds);
         // apic->Write(APIC::APIC::APIC_TIMER, apic->Read(APIC::APIC::APIC_TIMER) | (1 << 0x10));
     }
References apic_timer_ticks.
Referenced by APIC_oneshot().
RawRedirectIRQ()
void APIC::APIC::RawRedirectIRQ (uint8_t Vector, uint32_t GSI, uint16_t Flags, int CPU, int Status)
Definition at line 145 of file APIC.cpp.
     {
         uint64_t end = Vector;
         int64_t io_apic_target = -1;
         for (uint64_t i = 0; madt->ioapic[i] != 0; i++)
             if (madt->ioapic[i]->gsib <= GSI)
                 if (madt->ioapic[i]->gsib + IOGetMaxRedirect(i) > GSI)
                 {
                     io_apic_target = i;
                     break;
                 }
         if (io_apic_target == -1)
         {
             err("No ISO table found for I/O APIC");
             return;
         }
         if (Flags & ActiveHighLow)
             end |= (1 << 13);
         if (Flags & EdgeLevel)
             end |= (1 << 15);
         if (!Status)
             end |= (1 << 16);
         end |= (((uintptr_t)GetCPU(CPU)->LAPIC.APICId) << 56);
         uint32_t io_reg = (GSI - madt->ioapic[io_apic_target]->gsib) * 2 + 16;
         this->IOWrite(madt->ioapic[io_apic_target]->addr, io_reg, (uint32_t)end);
         this->IOWrite(madt->ioapic[io_apic_target]->addr, io_reg + 1, (uint32_t)(end >> 32));
     }
References APIC::ActiveHighLow, ACPI::MADT::LocalAPIC::APICId, APIC::EdgeLevel, err, Flags, GetCPU(), GSI, ACPI::MADT::ioapic, CPUData::LAPIC, madt, and Status.
Read()
uint32_t APIC::APIC::Read (uint32_t Register)
Definition at line 40 of file APIC.cpp.
     {
         // Too repetitive
         if (Register != APIC_EOI &&
             Register != APIC_TIMER &&
             Register != APIC_TDCR &&
             Register != APIC_TICR &&
             Register != APIC_TCCR)
             debug("APIC::Read(%#lx)", Register);
         if (x2APICSupported)
         {
             if (Register != APIC_ICRHI)
                 return rdmsr((Register >> 4) + 0x800);
             else
                 return rdmsr(0x30 + 0x800);
         }
         else
             return *((volatile uint32_t *)((uintptr_t)madt->LAPICAddr + Register));
     }
References debug, ACPI::MADT::LAPICAddr, madt, and rdmsr().
Referenced by apictimer_read_counter(), init_APICTimer(), SymmetricMultiprocessing::SMP::SMP(), and StartCPU().
RedirectIRQ()
void APIC::APIC::RedirectIRQ (int CPU, uint8_t IRQ, int Status)
Definition at line 180 of file APIC.cpp.
     {
         for (uint64_t i = 0; i < madt->iso.size(); i++)
             if (madt->iso[i]->IRQSource == IRQ)
             {
                 debug("[ISO %d] Mapping to source IRQ%#d GSI:%#lx on CPU %d",
                       i, madt->iso[i]->IRQSource, madt->iso[i]->GSI, CPU);
                 this->RawRedirectIRQ(madt->iso[i]->IRQSource + 0x20, madt->iso[i]->GSI, madt->iso[i]->Flags, CPU, Status);
                 return;
             }
         debug("Mapping IRQ%d on CPU %d", IRQ, CPU);
         this->RawRedirectIRQ(IRQ + 0x20, IRQ, 0, CPU, Status);
     }
References debug, ACPI::MADT::iso, madt, and Status.
Referenced by Tasking::Multitasking::Multitasking(), and RegisterInterrupt().
RedirectIRQs()
void APIC::APIC::RedirectIRQs (int CPU = 0)
Definition at line 99 of file APIC.cpp.
     {
         debug("redirecting irqs...");
         for (int i = 0; i < 16; i++)
             this->RedirectIRQ(CPU, i, 1);
         debug("redirecting irqs complete");
     }
References debug.
Referenced by KernelInit().
Write()
void APIC::APIC::Write (uint32_t Register, uint32_t Value)
Definition at line 60 of file APIC.cpp.
     {
         // Too repetitive
         if (Register != APIC_EOI &&
             Register != APIC_TIMER &&
             Register != APIC_TDCR &&
             Register != APIC_TICR &&
             Register != APIC_TCCR)
             debug("APIC::Write(%#lx, %#lx)", Register, Value);
         if (x2APICSupported)
         {
             if (Register != APIC_ICRHI)
                 wrmsr((Register >> 4) + 0x800, Value);
             else
                 wrmsr(MSR_X2APIC_ICR, Value);
         }
         else
             *((volatile uint32_t *)(((uintptr_t)madt->LAPICAddr) + Register)) = Value;
     }
References debug, ACPI::MADT::LAPICAddr, madt, MSR_X2APIC_ICR, and wrmsr().
Referenced by init_APICTimer(), InitializeCPU(), and StartCPU().
Field Documentation
x2APICSupported
bool APIC::APIC::x2APICSupported = false private
Definition at line 13 of file apic.hpp.
The documentation for this class was generated from the following files:
kernel/cpu/apic.hpp
kernel/cpu/APIC.cpp