Fennix Project: libc/src/FennixStandardLibrary/system.c File Reference
system.c File Reference
#include <system.h>
#include <syscalls.h>
#include "../printf.h"
Functions
static void append_syswritedbg (char s[], char n)
static void syswritedbgprint_wrapper (char c, void *unused)
void WriteSysDebugger (const char *Format,...)
Write to the system debugger.
void usleep (unsigned long Microseconds)
Sleep for a given number of microseconds.
int system (const char *Command)
Execute a command in the system shell.
void Exit (int Status)
Exit the program with a status code.
Variables
char syswritedbgbuf [2048]
Function Documentation
append_syswritedbg()
static void append_syswritedbg (char s[], char n) inline static
Definition at line 8 of file system.c.
 {
     long unsigned i = 0;
     while (s[i] != '\0')
         ++i;
     int len = i;
     s[len] = n;
     s[len + 1] = '\0';
 }
Referenced by syswritedbgprint_wrapper().
Exit()
void Exit (int Status)
Exit the program with a status code.
Parameters
Status
Returns
void
Definition at line 54 of file system.c.
 {
     syscall_exit(Status);
     while (1)
         ;
 }
References Status.
system()
int system (const char * Command)
Execute a command in the system shell.
Parameters
Command
Returns
int
Definition at line 45 of file system.c.
 {
     // mono 1 - multi 2
     if (syscall_getScheduleMode() == 2)
         return syscall_createProcess((char *)Command, 0, 0);
     else if (syscall_getScheduleMode() == 1)
         return -1;
 }
References Command.
syswritedbgprint_wrapper()
static void syswritedbgprint_wrapper (char c, void * unused) inline static
Definition at line 19 of file system.c.
 {
     append_syswritedbg(syswritedbgbuf, c);
     (void)unused;
 }
References append_syswritedbg(), and syswritedbgbuf.
Referenced by WriteSysDebugger().
usleep()
void usleep (unsigned long Microseconds)
Sleep for a given number of microseconds.
Parameters
Microseconds
Returns
void
Definition at line 40 of file system.c.
 {
     syscall_usleep(Microseconds);
 }
WriteSysDebugger()
void WriteSysDebugger (const char * Format, ...)
Write to the system debugger.
Parameters
Format
...
Returns
void
Definition at line 25 of file system.c.
 {
     // mono 1 - multi 2
     if (syscall_getScheduleMode() == 2)
     {
         // write info about the current thread
     }
     syswritedbgbuf[0] = '\0';
     va_list args;
     va_start(args, Format);
     vfctprintf(syswritedbgprint_wrapper, NULL, Format, args);
     va_end(args);
     syscall_dbg(0x3F8, (char *)syswritedbgbuf);
 }
References NULL, syswritedbgbuf, syswritedbgprint_wrapper(), va_end, va_start, and vfctprintf().
Referenced by Cat(), fflush(), FileSeek(), FileTell(), fprintf(), loop(), main(), MakeDirectory(), ParseBuffer(), RemoveFile(), RenameFile(), and sprintf().
Variable Documentation
syswritedbgbuf
char syswritedbgbuf[2048]
Definition at line 6 of file system.c.
Referenced by syswritedbgprint_wrapper(), and WriteSysDebugger().