Fennix Project: kernel/Driver.cpp File Reference
Driver.cpp File Reference
#include "driver.hpp"
#include <internal_task.h>
#include <filesystem.h>
#include <display.h>
#include <stdarg.h>
#include <cwalk.h>
#include <heap.h>
#include <elf.h>
#include <int.h>
#include <asm.h>
#include "security/security.hpp"
#include "kernel.h"
Namespaces
Driver
Functions
void * FunctionCallHandler (KernelCallType type,...)
Driver::ReadFSFunction (DriverRead)
Driver::WriteFSFunction (DriverWrite)
void Driver::DriverManagerMainLoop ()
Variables
Driver::KernelDriver * kdrv = nullptr
PCB * Driver::DrvMgrProc = nullptr
FileSystem::FileSystemNode * Driver::DriverNode = nullptr
FileSystem::FileSystemOpeations Driver::kdrvfs
Function Documentation
FunctionCallHandler()
void* FunctionCallHandler (KernelCallType type, ...)
Definition at line 20 of file Driver.cpp.
 {
     int maxargs = 16;
     int argsn = 0;
     uint64_t ArgList[maxargs];
     va_list args;
     va_start(args, maxargs);
     while (argsn < maxargs)
     {
         ArgList[argsn] = va_arg(args, uint64_t);
         argsn++;
     }
     va_end(args);
     switch (type)
     {
     case KCALL_REQ_PAGE:
     {
         return KernelAllocator.RequestPage();
     }
     case KCALL_FREE_PAGE:
     {
         KernelAllocator.FreePage((void *)ArgList[0]);
         return 0;
     }
     case KCALL_KMALLOC:
     {
         return kmalloc(ArgList[0]);
     }
     case KCALL_KFREE:
     {
         kfree((void *)ArgList[0]);
         return 0;
     }
     case KCALL_KCALLOC:
     {
         return kcalloc(ArgList[0], ArgList[1]);
     }
     case KCALL_KCREALLOC:
     {
         return krealloc((void *)ArgList[0], ArgList[1]);
     }
     case KCALL_GET_BOOTPARAMS:
     {
         return (void *)&bootparams;
     }
     case KCALL_HOOK_INTERRUPT:
     {
         return (void *)RegisterInterrupt((INTERRUPT_HANDLER)ArgList[1], (InterruptVector)ArgList[0], false);
     }
     case KCALL_UNHOOK_INTERRUPT:
         break;
     case KCALL_END_OF_INTERRUPT:
     {
         EndOfInterrupt(ArgList[0]);
         return 0;
     }
     default:
         fixme("Call %d not implemented.", type);
         return (void *)deadbeef;
     }
     return (void *)badfennec;
 }
References badfennec, bootparams, deadbeef, EndOfInterrupt(), fixme(), KCALL_END_OF_INTERRUPT, KCALL_FREE_PAGE, KCALL_GET_BOOTPARAMS, KCALL_HOOK_INTERRUPT, KCALL_KCALLOC, KCALL_KCREALLOC, KCALL_KFREE, KCALL_KMALLOC, KCALL_REQ_PAGE, KCALL_UNHOOK_INTERRUPT, kcalloc, KernelAllocator, kfree, kmalloc, krealloc, RegisterInterrupt(), va_arg, va_end, and va_start.
Referenced by Driver::KernelDriver::LoadKernelDriverFromFile().
Variable Documentation
kdrv
Driver::KernelDriver* kdrv = nullptr
Definition at line 18 of file Driver.cpp.
Referenced by Driver::DriverManagerMainLoop(), and KernelTask().