Fennix Project: kernel/timer/apic_timer.h File Reference
apic_timer.h File Reference
#include <types.h>
Functions
EXTERNC uint64_t apictimer_read_counter ()
EXTERNC uint64_t apictimer_read_clock ()
EXTERNC void apictimer_nwait (uint64_t Nanoseconds)
EXTERNC void apictimer_uwait (uint64_t Microseconds)
EXTERNC void apictimer_mwait (uint64_t Miliseconds)
EXTERNC void apictimer_wait (uint64_t Seconds)
EXTERNC void init_APICTimer ()
EXTERNC void APIC_oneshot (uint32_t Vector, uint64_t Miliseconds)
Variables
bool APICTimer_initialized
uint64_t apic_timer_ticks
Function Documentation
APIC_oneshot()
EXTERNC void APIC_oneshot (uint32_t Vector, uint64_t Miliseconds)
Definition at line 56 of file APICTimer.cpp.
 {
     apic->OneShot(Vector, Miliseconds);
 }
References apic, and APIC::APIC::OneShot().
Referenced by TimerOneShot().
apictimer_mwait()
EXTERNC void apictimer_mwait (uint64_t Miliseconds)
Definition at line 27 of file APICTimer.cpp.
 { apictimer_uwait(Miliseconds * 1000); }
References apictimer_uwait().
Referenced by apictimer_wait(), init_APICTimer(), and msleep().
apictimer_nwait()
EXTERNC void apictimer_nwait (uint64_t Nanoseconds)
Definition at line 25 of file APICTimer.cpp.
 { TSC_sleep(Nanoseconds); }
References TSC_sleep().
Referenced by apictimer_uwait(), and nsleep().
apictimer_read_clock()
EXTERNC uint64_t apictimer_read_clock ()
Definition at line 24 of file APICTimer.cpp.
 { return apic_timer_ticks; }
References apic_timer_ticks.
Referenced by get_timer_clock().
apictimer_read_counter()
EXTERNC uint64_t apictimer_read_counter ()
Definition at line 17 of file APICTimer.cpp.
 {
     if (cpu_feature(CPUID_FEAT_RDX_TSC))
         return tsc();
     else
         return apic->Read(APIC::APIC::APIC_TCCR);
 }
References apic, APIC::APIC::APIC_TCCR, cpu_feature(), CPUID_FEAT_RDX_TSC, APIC::APIC::Read(), and tsc().
Referenced by counter().
apictimer_uwait()
EXTERNC void apictimer_uwait (uint64_t Microseconds)
Definition at line 26 of file APICTimer.cpp.
 { apictimer_nwait(Microseconds * 1000); }
References apictimer_nwait().
Referenced by apictimer_mwait(), and usleep().
apictimer_wait()
EXTERNC void apictimer_wait (uint64_t Seconds)
Definition at line 28 of file APICTimer.cpp.
 { apictimer_mwait(Seconds * 1000); }
References apictimer_mwait(), and Seconds.
Referenced by sleep().
init_APICTimer()
EXTERNC void init_APICTimer ()
Definition at line 30 of file APICTimer.cpp.
 {
     trace("Initializing APIC Timer...");
     // Initializing the APIC timer corrups the memory? Or something else?
     apic->Write(APIC::APIC::APIC_TIMER, apic->Read(APIC::APIC::APIC_TIMER) & ~(1 << 0x10));
     apic->Write(APIC::APIC::APIC_TDCR, 0x3);
     apic->Write(APIC::APIC::APIC_TICR, 0xFFFFFFFF);
     apictimer_mwait(100);
     apic->Write(APIC::APIC::APIC_TIMER, 0x10000);
     apic_timer_ticks = 0xFFFFFFFF - apic->Read(APIC::APIC::APIC_TCCR);
     apic_timer_ticks /= 100;
     apic->Write(APIC::APIC::APIC_TIMER, (long)IRQ0 | (long)APIC::APIC::APICRegisters::APIC_PERIODIC);
     apic->Write(APIC::APIC::APIC_TDCR, 0x3);
     apic->Write(APIC::APIC::APIC_TICR, apic_timer_ticks);
     APICTimer_initialized = true;
     trace("APIC timer ticks %lld", apic_timer_ticks);
     apic->Write(APIC::APIC::APIC_TIMER, apic->Read(APIC::APIC::APIC_TIMER) | (1 << 0x10));
 }
References apic, APIC::APIC::APIC_TCCR, APIC::APIC::APIC_TDCR, APIC::APIC::APIC_TICR, APIC::APIC::APIC_TIMER, apic_timer_ticks, APICTimer_initialized, apictimer_mwait(), IRQ0, APIC::APIC::Read(), trace, and APIC::APIC::Write().
Referenced by init_timer().
Variable Documentation
apic_timer_ticks
uint64_t apic_timer_ticks
Definition at line 15 of file APICTimer.cpp.
Referenced by apictimer_read_clock(), and init_APICTimer().
APICTimer_initialized
bool APICTimer_initialized
Definition at line 14 of file APICTimer.cpp.
Referenced by counter(), get_timer_clock(), init_APICTimer(), init_timer(), msleep(), nsleep(), sleep(), TimerOneShot(), and usleep().