Fennix Project: kernel/timer/hpet.h File Reference
hpet.h File Reference
#include <types.h>
Data Structures
struct HPET
Functions
EXTERNC uint32_t get_clk ()
EXTERNC uint64_t hpet_read_counter ()
EXTERNC void hpet_uwait (uint64_t Microseconds)
EXTERNC void hpet_mwait (uint64_t Miliseconds)
EXTERNC void hpet_wait (uint64_t Seconds)
EXTERNC void init_HPET ()
EXTERNC void HPET_oneshot (uint32_t Vector, uint64_t Miliseconds)
EXTERNC void disable_HPET ()
Variables
bool HPET_initialized
Data Structure Documentation
HPET
struct HPET
Definition at line 6 of file hpet.h.
Data Fields
uint64_t general_capabilities
uint64_t general_configuration
uint64_t general_int_status
uint64_t main_counter_value
uint64_t reserved
uint64_t reserved2
uint64_t reserved3
uint64_t reserved4[24]
uint64_t reserved5
Function Documentation
disable_HPET()
EXTERNC void disable_HPET ()
Definition at line 60 of file HPETTimer.cpp.
 {
     HPET_initialized = false;
 }
References HPET_initialized.
get_clk()
EXTERNC uint32_t get_clk ()
Definition at line 10 of file HPETTimer.cpp.
 {
     return clk;
 }
References clk.
Referenced by get_timer_clock().
hpet_mwait()
EXTERNC void hpet_mwait (uint64_t Miliseconds)
Definition at line 27 of file HPETTimer.cpp.
 {
     hpet_uwait(Miliseconds * 10000);
 }
References hpet_uwait().
Referenced by msleep().
HPET_oneshot()
EXTERNC void HPET_oneshot (uint32_t Vector, uint64_t Miliseconds)
Definition at line 55 of file HPETTimer.cpp.
 {
     err("HPET One-Shot is not implemented!");
 }
References err.
Referenced by TimerOneShot().
hpet_read_counter()
EXTERNC uint64_t hpet_read_counter ()
Definition at line 15 of file HPETTimer.cpp.
 {
     return mminq(&hpet->main_counter_value);
 }
References hpet, HPET::main_counter_value, and mminq().
Referenced by counter(), and hpet_uwait().
hpet_uwait()
EXTERNC void hpet_uwait (uint64_t Microseconds)
Definition at line 20 of file HPETTimer.cpp.
 {
     uint64_t target = hpet_read_counter() + (Microseconds * 1000000000) / clk;
     while (hpet_read_counter() < target)
         ;
 }
References clk, and hpet_read_counter().
Referenced by hpet_mwait(), hpet_wait(), nsleep(), and usleep().
hpet_wait()
EXTERNC void hpet_wait (uint64_t Seconds)
Definition at line 32 of file HPETTimer.cpp.
 {
     hpet_uwait(Seconds * 1000000);
 }
References hpet_uwait(), and Seconds.
Referenced by sleep().
init_HPET()
EXTERNC void init_HPET ()
Definition at line 37 of file HPETTimer.cpp.
 {
     trace("Initializing HPET timer");
     if (!acpi->HPET)
     {
         warn("HPET timer is not supported");
         return;
     }
     MapMemory(NULL, (void *)acpi->HPET->address.Address, (void *)acpi->HPET->address.Address, RW | PCD);
     hpet = (HPET *)(acpi->HPET->address.Address);
     debug("%s timer is at address %016p", acpi->HPET->header.OEMID, (void *)acpi->HPET->address.Address);
     clk = hpet->general_capabilities >> 32;
     mmoutq(&hpet->general_configuration, 0);
     mmoutq(&hpet->main_counter_value, 0);
     mmoutq(&hpet->general_configuration, 1);
     HPET_initialized = true;
 }
References acpi, ACPI::ACPI::GenericAddressStructure::Address, ACPI::ACPI::HPETHeader::address, clk, debug, HPET::general_capabilities, HPET::general_configuration, ACPI::ACPI::HPETHeader::header, hpet, ACPI::ACPI::HPET, HPET_initialized, HPET::main_counter_value, MapMemory(), mmoutq(), ACPI::ACPI::ACPIHeader::OEMID, PCD, RW, trace, and warn.
Referenced by init_timer().
Variable Documentation
HPET_initialized
bool HPET_initialized
Definition at line 6 of file HPETTimer.cpp.
Referenced by counter(), disable_HPET(), get_timer_clock(), init_HPET(), init_timer(), InterruptHandler(), msleep(), nsleep(), sleep(), TimerOneShot(), and usleep().