build:
	make -C monoton build
	make -C scparse build
	make -C algo build
	make -C cwalk build
	make -C cargs build

clean:
	make -C monoton clean
	make -C scparse clean
	make -C algo clean
	make -C cwalk clean
	make -C cargs clean
