Fennix Project: kernel/syscalls/Native.cpp File Reference
Native.cpp File Reference
#include "syscalls.hpp"
#include "../../libc/include/syscalls.h"
#include "../security/security.hpp"
#include "../drivers/keyboard.hpp"
#include "../drivers/mouse.hpp"
#include "../drivers/serial.h"
#include "../cpu/acpi.hpp"
#include "../kernel.h"
#include "../timer.h"
#include <internal_task.h>
#include <filesystem.h>
#include <bootscreen.h>
#include <display.h>
Functions
static uint64_t internal_unimpl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g)
static uint64_t internal_exit (SyscallsRegs *regs, uint64_t code)
static uint64_t internal_createprocess (SyscallsRegs *regs, char *Path, uint64_t arg0, uint64_t arg1)
static TCB * internal_createthread (SyscallsRegs *regs, uint64_t rip, uint64_t arg0, uint64_t arg1)
static PCB * internal_getcurrentprocess (SyscallsRegs *regs)
static TCB * internal_getcurrentthread (SyscallsRegs *regs)
static uint64_t internal_getcurrentprocessid (SyscallsRegs *regs)
static uint64_t internal_getcurrentthreadid (SyscallsRegs *regs)
static uint64_t internal_getargc (SyscallsRegs *regs)
static uint64_t internal_getargv (SyscallsRegs *regs)
static uint64_t internal_getenvp (SyscallsRegs *regs)
static int internal_getschedulemode (SyscallsRegs *regs)
static Tasking::TaskControlBlock * internal_createtask (SyscallsRegs *regs, uint64_t rip, uint64_t arg0, uint64_t arg1, char *name)
static void internal_pushtask (SyscallsRegs *regs, uint64_t jumpbackIP)
static void internal_poptask (SyscallsRegs *regs)
static void * internal_requestpage (SyscallsRegs *regs)
static void internal_freepage (SyscallsRegs *regs, void *page)
static void * internal_requestpages (SyscallsRegs *regs, uint64_t pages)
static void internal_freepages (SyscallsRegs *regs, void *page, uint64_t pages)
static void internal_shutdown (SyscallsRegs *regs)
static void internal_reboot (SyscallsRegs *regs)
static void internal_fadebootlogo (SyscallsRegs *regs)
static uint64_t internal_fbaddress (SyscallsRegs *regs)
static uint64_t internal_fbsize (SyscallsRegs *regs)
static uint64_t internal_fbwidth (SyscallsRegs *regs)
static uint64_t internal_fbheight (SyscallsRegs *regs)
static uint64_t internal_fbppsl (SyscallsRegs *regs)
static uint8_t internal_getlastkeyboardscancode (SyscallsRegs *regs)
static File * internal_fileOpen (SyscallsRegs *regs, char *Path)
static File * internal_fileOpenWithParent (SyscallsRegs *regs, char *Path, File *Parent)
static void internal_fileClose (SyscallsRegs *regs, File *F)
static uint64_t internal_fileRead (SyscallsRegs *regs, File *F, uint64_t Offset, uint8_t *Buffer, uint64_t Size)
static uint64_t internal_fileWrite (SyscallsRegs *regs, File *F, uint64_t Offset, uint8_t *Buffer, uint64_t Size)
static uint64_t internal_filesize (SyscallsRegs *regs, File *File)
static char * internal_filefullpath (SyscallsRegs *regs, File *File)
static uint64_t internal_filechildrensize (SyscallsRegs *regs, File *File)
static File * internal_filegetchildren (SyscallsRegs *regs, File *F, uint64_t Index)
static void internal_usleep (SyscallsRegs *regs, uint64_t us)
static void internal_beep (SyscallsRegs *regs, BeepState state, uint64_t Frequency)
static void internal_cli (SyscallsRegs *regs)
static void internal_sti (SyscallsRegs *regs)
static uint64_t internal_dbg (SyscallsRegs *regs, int port, char *message)
uint64_t HandleFennixSyscalls (SyscallsRegs *regs)
Variables
static void * FennixSyscallsTable []
Function Documentation
HandleFennixSyscalls()
uint64_t HandleFennixSyscalls (SyscallsRegs * regs)
Definition at line 585 of file Native.cpp.
 {
     if (RAX > sizeof(FennixSyscallsTable))
     {
         return internal_unimpl(regs->rax, regs->rbx, regs->rcx, regs->rdx, regs->rsi, regs->rdi, regs->rbp);
     }
     uint64_t (*call)(uint64_t, ...) = reinterpret_cast<uint64_t (*)(uint64_t, ...)>(FennixSyscallsTable[RAX]);
     if (!call)
     {
         err("Syscall %#llx failed.", RAX);
         return failedcall;
     }
     syscldbg("SYSCALL->CALLDATA->(r:%lx a:%lx b:%lx c:%lx d:%lx S:%lx D:%lx)[CALLID:%d]", regs, RAX, RBX, RCX, RDX, RSI, RDI, RAX);
     uint64_t ret = call((uint64_t)regs, RBX, RDX, RSI, RDI);
     RAX = ret;
     return ret;
 }
References err, failedcall, FennixSyscallsTable, internal_unimpl(), _SyscallsRegs::rax, _SyscallsRegs::rbp, _SyscallsRegs::rbx, _SyscallsRegs::rcx, _SyscallsRegs::rdi, _SyscallsRegs::rdx, _SyscallsRegs::rsi, and syscldbg.
Referenced by syscall_handler().
internal_beep()
static void internal_beep (SyscallsRegs * regs, BeepState state, uint64_t Frequency) static
Definition at line 451 of file Native.cpp.
 {
     syscldbg("syscall: beep( %d, %#llx )", state, Frequency);
     if (!CanSyscall(regs))
         return;
     /* https://wiki.osdev.org/PC_Speaker */
     static bool isBeeping = false;
     switch (state)
     {
     case BEEP_OFF:
     {
         outportb(0x61, inportb(0x61) & 0xFC);
         isBeeping = false;
         break;
     }
     case BEEP_ON:
     {
         uint64_t div = 1193180 / Frequency;
         outportb(0x43, 0xB6);
         outportb(0x42, (uint8_t)div);
         outportb(0x42, (uint8_t)(div >> 8));
         outportb(0x61, inportb(0x61) | 0x3);
         // uint8_t tmp = inportb(0x61);
         // if (tmp != (tmp | 3))
         //     outportb(0x61, tmp | 3);
         isBeeping = true;
         break;
     }
     case BEEP_TOGGLE:
     {
         if (isBeeping)
             internal_beep(regs, BEEP_OFF, 0);
         else
             internal_beep(regs, BEEP_ON, Frequency);
         break;
     }
     default:
         break;
     }
 }
References BEEP_OFF, BEEP_ON, BEEP_TOGGLE, CanSyscall(), inportb(), outportb(), and syscldbg.
internal_cli()
static void internal_cli (SyscallsRegs * regs) static
Definition at line 492 of file Native.cpp.
 {
     syscldbg("syscall: cli()");
     if (!CanSyscall(regs))
         return;
     asm volatile("cli");
 }
References CanSyscall(), and syscldbg.
internal_createprocess()
static uint64_t internal_createprocess (SyscallsRegs * regs, char * Path, uint64_t arg0, uint64_t arg1) static
Definition at line 36 of file Native.cpp.
 {
     syscldbg("syscall: createprocess( %s %#llx %#llx )", Path, arg0, arg1);
     if (!CanSyscall(regs))
         return deniedcall;
     return SysCreateProcessFromFile(Path, arg0, arg1, User)->ID;
 }
References CanSyscall(), deniedcall, PCB::ID, syscldbg, SysCreateProcessFromFile(), and User.
internal_createtask()
static Tasking::TaskControlBlock* internal_createtask (SyscallsRegs * regs, uint64_t rip, uint64_t arg0, uint64_t arg1, char * name) static
Definition at line 114 of file Native.cpp.
 {
     syscldbg("syscall: createtask( %#llx %#llx %#llx %s )", rip, arg0, arg1, name);
     if (!CanSyscall(regs))
         return (Tasking::TaskControlBlock *)deniedcall;
     return Tasking::monot->CreateTask(rip, arg0, arg1, name, true, true);
 }
References CanSyscall(), deniedcall, Tasking::monot, and syscldbg.
internal_createthread()
static TCB* internal_createthread (SyscallsRegs * regs, uint64_t rip, uint64_t arg0, uint64_t arg1) static
Definition at line 44 of file Native.cpp.
 {
     syscldbg("syscall: createthread( %#llx %#llx %#llx )", rip, arg0, arg1);
     if (!CanSyscall(regs))
         return (TCB *)deniedcall;
     return SysCreateThread(SysGetCurrentProcess(), rip, arg0, arg1);
 }
References CanSyscall(), deniedcall, syscldbg, SysCreateThread(), and SysGetCurrentProcess().
internal_dbg()
static uint64_t internal_dbg (SyscallsRegs * regs, int port, char * message) static
Definition at line 508 of file Native.cpp.
 {
     syscldbg("syscall: dbg( %d, %s )", port, message);
     if (!CanSyscall(regs))
         return deniedcall;
     serial_write_text(port, message);
     return 0;
 }
References CanSyscall(), deniedcall, serial_write_text(), and syscldbg.
internal_exit()
static uint64_t internal_exit (SyscallsRegs * regs, uint64_t code) static
Definition at line 23 of file Native.cpp.
 {
     if (CurrentTaskingMode == TaskingMode::Mono)
     {
         Tasking::monot->KillMe();
         return 0;
     }
     trace("Userspace thread %s(%lld) exited with code %#llx", SysGetCurrentThread()->Name, SysGetCurrentThread()->ID, code);
     SysGetCurrentThread()->ExitCode = code;
     SysGetCurrentThread()->Status = Terminated;
     return 0;
 }
References CurrentTaskingMode, TCB::ExitCode, ID, Mono, Tasking::monot, TCB::Status, SysGetCurrentThread(), Terminated, and trace.
internal_fadebootlogo()
static void internal_fadebootlogo (SyscallsRegs * regs) static
Definition at line 198 of file Native.cpp.
 {
     syscldbg("syscall: fadebootlogo()");
     if (!CanSyscall(regs))
         return;
     if (CurrentTaskingMode != TaskingMode::Mono)
         FadeScreenNow = true;
     else
         BS->FadeLogo();
 }
References BS, CanSyscall(), CurrentTaskingMode, BootScreen::Screen::FadeLogo(), FadeScreenNow, Mono, and syscldbg.
internal_fbaddress()
static uint64_t internal_fbaddress (SyscallsRegs * regs) static
Definition at line 209 of file Native.cpp.
 {
     syscldbg("syscall: fbaddress()");
     if (!CanSyscall(regs))
         return deniedcall;
     return CurrentDisplay->GetFramebuffer()->Address;
 }
References CanSyscall(), CurrentDisplay, deniedcall, and syscldbg.
internal_fbheight()
static uint64_t internal_fbheight (SyscallsRegs * regs) static
Definition at line 233 of file Native.cpp.
 {
     syscldbg("syscall: fbheight()");
     if (!CanSyscall(regs))
         return deniedcall;
     return CurrentDisplay->GetFramebuffer()->Height;
 }
References CanSyscall(), CurrentDisplay, deniedcall, and syscldbg.
internal_fbppsl()
static uint64_t internal_fbppsl (SyscallsRegs * regs) static
Definition at line 241 of file Native.cpp.
 {
     syscldbg("syscall: fbppsl()");
     if (!CanSyscall(regs))
         return deniedcall;
     return CurrentDisplay->GetFramebuffer()->PixelsPerScanLine;
 }
References CanSyscall(), CurrentDisplay, deniedcall, and syscldbg.
internal_fbsize()
static uint64_t internal_fbsize (SyscallsRegs * regs) static
Definition at line 217 of file Native.cpp.
 {
     syscldbg("syscall: fbsize()");
     if (!CanSyscall(regs))
         return deniedcall;
     return CurrentDisplay->GetFramebuffer()->Size;
 }
References CanSyscall(), CurrentDisplay, deniedcall, and syscldbg.
internal_fbwidth()
static uint64_t internal_fbwidth (SyscallsRegs * regs) static
Definition at line 225 of file Native.cpp.
 {
     syscldbg("syscall: fbwidth()");
     if (!CanSyscall(regs))
         return deniedcall;
     return CurrentDisplay->GetFramebuffer()->Width;
 }
References CanSyscall(), CurrentDisplay, deniedcall, and syscldbg.
internal_filechildrensize()
static uint64_t internal_filechildrensize (SyscallsRegs * regs, File * File) static
Definition at line 390 of file Native.cpp.
 {
     syscldbg("syscall: filechildrensize( %p )", File);
     if (!CanSyscall(regs))
         return deniedcall;
     UserAllocator->Xstac();
     uint64_t ret = static_cast<FileSystem::FILE *>(File->Handle)->Node->Children.size();
     UserAllocator->Xclac();
     return ret;
 }
References CanSyscall(), deniedcall, _File::Handle, syscldbg, UserAllocator, Xalloc::AllocatorV1::Xclac(), and Xalloc::AllocatorV1::Xstac().
internal_fileClose()
static void internal_fileClose (SyscallsRegs * regs, File * F) static
Definition at line 326 of file Native.cpp.
 {
     syscldbg("syscall: fileClose( %p )", F);
     if (!CanSyscall(regs))
         return;
     UserAllocator->Xstac();
     if (static_cast<FileSystem::FILE *>(F->Handle) != (void *)deadbeef)
         vfs->Close(static_cast<FileSystem::FILE *>(F->Handle));
     UserAllocator->Xclac();
     UserAllocator->Free(F);
 }
References CanSyscall(), FileSystem::Virtual::Close(), deadbeef, Xalloc::AllocatorV1::Free(), _File::Handle, syscldbg, UserAllocator, vfs, Xalloc::AllocatorV1::Xclac(), and Xalloc::AllocatorV1::Xstac().
internal_filefullpath()
static char* internal_filefullpath (SyscallsRegs * regs, File * File) static
Definition at line 374 of file Native.cpp.
 {
     syscldbg("syscall: filefullpath( %p )", File);
     if (!CanSyscall(regs))
         return (char *)deniedcall;
     UserAllocator->Xstac();
     char *retmp = vfs->GetPathFromNode(static_cast<FileSystem::FILE *>(File->Handle)->Node);
     UserAllocator->Xclac();
     char *ret = (char *)UserAllocator->Malloc(strlen(retmp) + 1);
     UserAllocator->Xstac();
     strcpy(ret, retmp);
     delete[] retmp;
     UserAllocator->Xclac();
     return ret;
 }
References CanSyscall(), deniedcall, FileSystem::Virtual::GetPathFromNode(), _File::Handle, Xalloc::AllocatorV1::Malloc(), FileSystem::FILE::Node, strcpy(), strlen(), syscldbg, UserAllocator, vfs, Xalloc::AllocatorV1::Xclac(), and Xalloc::AllocatorV1::Xstac().
internal_filegetchildren()
static File* internal_filegetchildren (SyscallsRegs * regs, File * F, uint64_t Index) static
Definition at line 401 of file Native.cpp.
 {
     syscldbg("syscall: filegetchildren( %p, %#llx )", F, Index);
     if (!CanSyscall(regs))
         return (File *)deniedcall;
     File *f = (File *)UserAllocator->Malloc(sizeof(File));
     UserAllocator->Xstac();
     FileSystem::FileSystemNode *node = static_cast<FileSystem::FILE *>(F->Handle)->Node->Children[Index];
     memcpy(f->Name, node->Name, sizeof(f->Name));
     if (node)
     {
         f->Status = FileStatus::OK;
         f->Handle = (void *)deadbeef;
         f->IndexNode = node->IndexNode;
         f->Mask = node->Mask;
         f->Mode = node->Mode;
         f->Flags = node->Flags;
         f->UserIdentifier = node->UserIdentifier;
         f->GroupIdentifier = node->GroupIdentifier;
         f->Address = node->Address;
         f->Length = node->Length;
         f->Parent = node->Parent;
         f->Operator = node->Operator;
     }
     else
         f->Status = FileStatus::NOT_SUPPORTED;
     UserAllocator->Xclac();
     return f;
 }
References FileSystem::FileSystemNode::Address, _File::Address, CanSyscall(), deadbeef, deniedcall, FileSystem::FileSystemNode::Flags, _File::Flags, FileSystem::FileSystemNode::GroupIdentifier, _File::GroupIdentifier, _File::Handle, FileSystem::FileSystemNode::IndexNode, _File::IndexNode, FileSystem::FileSystemNode::Length, _File::Length, Xalloc::AllocatorV1::Malloc(), FileSystem::FileSystemNode::Mask, _File::Mask, memcpy(), FileSystem::FileSystemNode::Mode, _File::Mode, FileSystem::FileSystemNode::Name, _File::Name, NOT_SUPPORTED, OK, FileSystem::FileSystemNode::Operator, _File::Operator, FileSystem::FileSystemNode::Parent, _File::Parent, _File::Status, syscldbg, UserAllocator, FileSystem::FileSystemNode::UserIdentifier, _File::UserIdentifier, Xalloc::AllocatorV1::Xclac(), and Xalloc::AllocatorV1::Xstac().
internal_fileOpen()
static File* internal_fileOpen (SyscallsRegs * regs, char * Path) static
Definition at line 255 of file Native.cpp.
 {
     syscldbg("syscall: fileOpen( %s )", Path);
     if (!CanSyscall(regs))
         return (File *)deniedcall;
     File *f = (File *)UserAllocator->Malloc(sizeof(File));
     FileSystem::FILE *fo = vfs->Open(Path, nullptr);
     UserAllocator->Xstac();
     f->Status = static_cast<FileStatus>(fo->Status);
     memcpy(f->Name, fo->Name, sizeof(f->Name));
     if (fo)
     {
         f->Handle = fo;
         if (fo->Node)
         {
             f->IndexNode = fo->Node->IndexNode;
             f->Mask = fo->Node->Mask;
             f->Mode = fo->Node->Mode;
             f->Flags = fo->Node->Flags;
             f->UserIdentifier = fo->Node->UserIdentifier;
             f->GroupIdentifier = fo->Node->GroupIdentifier;
             f->Address = fo->Node->Address;
             f->Length = fo->Node->Length;
             f->Parent = fo->Node->Parent;
             f->Operator = fo->Node->Operator;
         }
     }
     UserAllocator->Xclac();
     return f;
 }
References FileSystem::FileSystemNode::Address, _File::Address, CanSyscall(), deniedcall, FileSystem::FileSystemNode::Flags, _File::Flags, FileSystem::FileSystemNode::GroupIdentifier, _File::GroupIdentifier, _File::Handle, FileSystem::FileSystemNode::IndexNode, _File::IndexNode, FileSystem::FileSystemNode::Length, _File::Length, Xalloc::AllocatorV1::Malloc(), FileSystem::FileSystemNode::Mask, _File::Mask, memcpy(), FileSystem::FileSystemNode::Mode, _File::Mode, FileSystem::FILE::Name, _File::Name, FileSystem::FILE::Node, FileSystem::Virtual::Open(), FileSystem::FileSystemNode::Operator, _File::Operator, FileSystem::FileSystemNode::Parent, _File::Parent, FileSystem::FILE::Status, _File::Status, syscldbg, UserAllocator, FileSystem::FileSystemNode::UserIdentifier, _File::UserIdentifier, vfs, Xalloc::AllocatorV1::Xclac(), and Xalloc::AllocatorV1::Xstac().
internal_fileOpenWithParent()
static File* internal_fileOpenWithParent (SyscallsRegs * regs, char * Path, File * Parent) static
Definition at line 291 of file Native.cpp.
 {
     syscldbg("syscall: fileOpenWithParent( %s, %p )", Path, Parent);
     if (!CanSyscall(regs))
         return (File *)deniedcall;
     File *f = (File *)UserAllocator->Malloc(sizeof(File));
     UserAllocator->Xstac();
     FileSystem::FILE *fo = vfs->Open(Path, static_cast<FileSystem::FILE *>(Parent->Handle)->Node);
     f->Status = static_cast<FileStatus>(fo->Status);
     memcpy(f->Name, fo->Name, sizeof(f->Name));
     if (fo)
     {
         f->Handle = fo;
         if (fo->Node)
         {
             f->IndexNode = fo->Node->IndexNode;
             f->Mask = fo->Node->Mask;
             f->Mode = fo->Node->Mode;
             f->Flags = fo->Node->Flags;
             f->UserIdentifier = fo->Node->UserIdentifier;
             f->GroupIdentifier = fo->Node->GroupIdentifier;
             f->Address = fo->Node->Address;
             f->Length = fo->Node->Length;
             f->Parent = fo->Node->Parent;
             f->Operator = fo->Node->Operator;
         }
     }
     UserAllocator->Xclac();
     return f;
 }
References FileSystem::FileSystemNode::Address, _File::Address, CanSyscall(), deniedcall, FileSystem::FileSystemNode::Flags, _File::Flags, FileSystem::FileSystemNode::GroupIdentifier, _File::GroupIdentifier, _File::Handle, FileSystem::FileSystemNode::IndexNode, _File::IndexNode, FileSystem::FileSystemNode::Length, _File::Length, Xalloc::AllocatorV1::Malloc(), FileSystem::FileSystemNode::Mask, _File::Mask, memcpy(), FileSystem::FileSystemNode::Mode, _File::Mode, FileSystem::FILE::Name, _File::Name, FileSystem::FILE::Node, FileSystem::Virtual::Open(), FileSystem::FileSystemNode::Operator, _File::Operator, FileSystem::FileSystemNode::Parent, _File::Parent, FileSystem::FILE::Status, _File::Status, syscldbg, UserAllocator, FileSystem::FileSystemNode::UserIdentifier, _File::UserIdentifier, vfs, Xalloc::AllocatorV1::Xclac(), and Xalloc::AllocatorV1::Xstac().
internal_fileRead()
static uint64_t internal_fileRead (SyscallsRegs * regs, File * F, uint64_t Offset, uint8_t * Buffer, uint64_t Size) static
Definition at line 341 of file Native.cpp.
 {
     syscldbg("syscall: fileRead( %p, %#llx, %p, %#llx )", F, Offset, Buffer, Size);
     if (!CanSyscall(regs))
         return deniedcall;
     UserAllocator->Xstac();
     uint64_t ret = vfs->Read(static_cast<FileSystem::FILE *>(F->Handle), Offset, Buffer, Size);
     UserAllocator->Xclac();
     return ret;
 }
References CanSyscall(), deniedcall, _File::Handle, FileSystem::Virtual::Read(), syscldbg, UserAllocator, vfs, Xalloc::AllocatorV1::Xclac(), and Xalloc::AllocatorV1::Xstac().
internal_filesize()
static uint64_t internal_filesize (SyscallsRegs * regs, File * File) static
Definition at line 363 of file Native.cpp.
 {
     syscldbg("syscall: filesize( %p )", File);
     if (!CanSyscall(regs))
         return deniedcall;
     UserAllocator->Xstac();
     uint64_t ret = static_cast<FileSystem::FILE *>(File->Handle)->Node->Length;
     UserAllocator->Xclac();
     return ret;
 }
References CanSyscall(), deniedcall, _File::Handle, syscldbg, UserAllocator, Xalloc::AllocatorV1::Xclac(), and Xalloc::AllocatorV1::Xstac().
internal_fileWrite()
static uint64_t internal_fileWrite (SyscallsRegs * regs, File * F, uint64_t Offset, uint8_t * Buffer, uint64_t Size) static
Definition at line 352 of file Native.cpp.
 {
     syscldbg("syscall: fileWrite( %p, %#llx, %p, %#llx )", F, Offset, Buffer, Size);
     if (!CanSyscall(regs))
         return deniedcall;
     UserAllocator->Xstac();
     uint64_t ret = vfs->Write(static_cast<FileSystem::FILE *>(F->Handle), Offset, Buffer, Size);
     UserAllocator->Xclac();
     return ret;
 }
References CanSyscall(), deniedcall, _File::Handle, syscldbg, UserAllocator, vfs, FileSystem::Virtual::Write(), Xalloc::AllocatorV1::Xclac(), and Xalloc::AllocatorV1::Xstac().
internal_freepage()
static void internal_freepage (SyscallsRegs * regs, void * page) static
Definition at line 148 of file Native.cpp.
 {
     syscldbg("syscall: freepage( %p )", page);
     if (!CanSyscall(regs))
         return;
     KernelAllocator.FreePage(page);
     KernelPageTableManager.UnmapMemory(page);
     KernelPageTableManager.MapMemory(page, page, PTFlag::RW);
 }
References CanSyscall(), KernelAllocator, KernelPageTableManager, RW, and syscldbg.
internal_freepages()
static void internal_freepages (SyscallsRegs * regs, void * page, uint64_t pages) static
Definition at line 169 of file Native.cpp.
 {
     syscldbg("syscall: freepages( %p, %#llx )", page, pages);
     if (!CanSyscall(regs))
         return;
     KernelAllocator.FreePages(page, pages);
     for (uint64_t i = (uint64_t)page; i < ((uint64_t)page + (pages * PAGE_SIZE)); i += PAGE_SIZE)
     {
         KernelPageTableManager.UnmapMemory((void *)i);
         KernelPageTableManager.MapMemory((void *)i, (void *)i, PTFlag::RW);
     }
 }
References CanSyscall(), KernelAllocator, KernelPageTableManager, PAGE_SIZE, RW, and syscldbg.
internal_getargc()
static uint64_t internal_getargc (SyscallsRegs * regs) static
Definition at line 84 of file Native.cpp.
 {
     syscldbg("syscall: getargc( )");
     if (!CanSyscall(regs))
         return deniedcall;
     return (uint64_t)SysGetCurrentThread()->argc;
 }
References TCB::argc, CanSyscall(), deniedcall, syscldbg, and SysGetCurrentThread().
internal_getargv()
static uint64_t internal_getargv (SyscallsRegs * regs) static
Definition at line 92 of file Native.cpp.
 {
     syscldbg("syscall: getargv( )");
     if (!CanSyscall(regs))
         return deniedcall;
     return (uint64_t)SysGetCurrentThread()->argv;
 }
References TCB::argv, CanSyscall(), deniedcall, syscldbg, and SysGetCurrentThread().
internal_getcurrentprocess()
static PCB* internal_getcurrentprocess (SyscallsRegs * regs) static
Definition at line 52 of file Native.cpp.
 {
     syscldbg("syscall: getcurrentprocess()");
     if (!CanSyscall(regs))
         return (PCB *)deniedcall;
     return SysGetCurrentProcess();
 }
References CanSyscall(), deniedcall, syscldbg, and SysGetCurrentProcess().
internal_getcurrentprocessid()
static uint64_t internal_getcurrentprocessid (SyscallsRegs * regs) static
Definition at line 68 of file Native.cpp.
 {
     syscldbg("syscall: getcurrentprocessid()");
     if (!CanSyscall(regs))
         return deniedcall;
     return SysGetCurrentProcess()->ID;
 }
References CanSyscall(), deniedcall, PCB::ID, syscldbg, and SysGetCurrentProcess().
internal_getcurrentthread()
static TCB* internal_getcurrentthread (SyscallsRegs * regs) static
Definition at line 60 of file Native.cpp.
 {
     syscldbg("syscall: getcurrentthread()");
     if (!CanSyscall(regs))
         return (TCB *)deniedcall;
     return SysGetCurrentThread();
 }
References CanSyscall(), deniedcall, syscldbg, and SysGetCurrentThread().
internal_getcurrentthreadid()
static uint64_t internal_getcurrentthreadid (SyscallsRegs * regs) static
Definition at line 76 of file Native.cpp.
 {
     syscldbg("syscall: getcurrentthreadid()");
     if (!CanSyscall(regs))
         return deniedcall;
     return SysGetCurrentThread()->ID;
 }
References CanSyscall(), deniedcall, TCB::ID, syscldbg, and SysGetCurrentThread().
internal_getenvp()
static uint64_t internal_getenvp (SyscallsRegs * regs) static
Definition at line 100 of file Native.cpp.
 {
     syscldbg("syscall: getenvc( )");
     if (!CanSyscall(regs))
         return deniedcall;
     return (uint64_t)SysGetCurrentThread()->envp;
 }
References CanSyscall(), deniedcall, TCB::envp, syscldbg, and SysGetCurrentThread().
internal_getlastkeyboardscancode()
static uint8_t internal_getlastkeyboardscancode (SyscallsRegs * regs) static
Definition at line 249 of file Native.cpp.
 {
     syscldbg("syscall: getlastkeyboardscancode()");
     return ps2keyboard->WaitScanCode();
 }
References ps2keyboard, syscldbg, and PS2Keyboard::PS2KeyboardDriver::WaitScanCode().
internal_getschedulemode()
static int internal_getschedulemode (SyscallsRegs * regs) static
Definition at line 108 of file Native.cpp.
 {
     syscldbg("syscall: getschedulemode()");
     return CurrentTaskingMode;
 }
References CurrentTaskingMode, and syscldbg.
internal_poptask()
static void internal_poptask (SyscallsRegs * regs) static
Definition at line 130 of file Native.cpp.
 {
     syscldbg("syscall: poptask()");
     if (!CanSyscall(regs))
         return;
     Tasking::monot->PopTask();
 }
References CanSyscall(), Tasking::monot, and syscldbg.
internal_pushtask()
static void internal_pushtask (SyscallsRegs * regs, uint64_t jumpbackIP) static
Definition at line 122 of file Native.cpp.
 {
     syscldbg("syscall: pushtask( %#llx )", jumpbackIP);
     if (!CanSyscall(regs))
         return;
     Tasking::monot->PushTask(jumpbackIP);
 }
References CanSyscall(), Tasking::monot, and syscldbg.
internal_reboot()
static void internal_reboot (SyscallsRegs * regs) static
Definition at line 190 of file Native.cpp.
 {
     syscldbg("syscall: reboot()");
     if (!CanSyscall(regs))
         return;
     dsdt->reboot();
 }
References CanSyscall(), dsdt, ACPI::DSDT::reboot(), and syscldbg.
internal_requestpage()
static void* internal_requestpage (SyscallsRegs * regs) static
Definition at line 138 of file Native.cpp.
 {
     syscldbg("syscall: requestpage()");
     if (!CanSyscall(regs))
         return (void *)deniedcall;
     void *ret = KernelAllocator.RequestPage();
     KernelPageTableManager.MapMemory(ret, ret, PTFlag::US | PTFlag::RW);
     return ret;
 }
References CanSyscall(), deniedcall, KernelAllocator, KernelPageTableManager, RW, syscldbg, and US.
internal_requestpages()
static void* internal_requestpages (SyscallsRegs * regs, uint64_t pages) static
Definition at line 158 of file Native.cpp.
 {
     syscldbg("syscall: requestpages( %#llx )", pages);
     if (!CanSyscall(regs))
         return (void *)deniedcall;
     void *ret = KernelAllocator.RequestPages(pages);
     for (uint64_t i = (uint64_t)ret; i < ((uint64_t)ret + (pages * PAGE_SIZE)); i += PAGE_SIZE)
         KernelPageTableManager.MapMemory((void *)i, (void *)i, PTFlag::US | PTFlag::RW);
     return ret;
 }
References CanSyscall(), deniedcall, KernelAllocator, KernelPageTableManager, PAGE_SIZE, RW, syscldbg, and US.
internal_shutdown()
static void internal_shutdown (SyscallsRegs * regs) static
Definition at line 182 of file Native.cpp.
 {
     syscldbg("syscall: shutdown()");
     if (!CanSyscall(regs))
         return;
     dsdt->shutdown();
 }
References CanSyscall(), dsdt, ACPI::DSDT::shutdown(), and syscldbg.
internal_sti()
static void internal_sti (SyscallsRegs * regs) static
Definition at line 500 of file Native.cpp.
 {
     syscldbg("syscall: sti()");
     if (!CanSyscall(regs))
         return;
     asm volatile("sti");
 }
References CanSyscall(), and syscldbg.
internal_unimpl()
static uint64_t internal_unimpl (uint64_t a, uint64_t b, uint64_t c, uint64_t d, uint64_t e, uint64_t f, uint64_t g) static
Definition at line 17 of file Native.cpp.
 {
     fixme("Unimplemented Syscall: %d %d %d %d %d %d %d", a, b, c, d, e, f, g);
     return deadcall;
 }
References deadcall, and fixme().
Referenced by HandleFennixSyscalls().
internal_usleep()
static void internal_usleep (SyscallsRegs * regs, uint64_t us) static
Definition at line 434 of file Native.cpp.
 {
     syscldbg("syscall: usleep( %#llx )", us);
     if (!CanSyscall(regs))
         return;
     if (CurrentTaskingMode == TaskingMode::Mono)
     {
         usleep(us);
         return;
     }
     else if (CurrentTaskingMode == TaskingMode::Multi)
     {
         warn("Sleeping in multi-tasking mode is not implemented yet!");
         return;
     }
 }
References CanSyscall(), CurrentTaskingMode, Mono, Multi, syscldbg, usleep(), and warn.
Variable Documentation
FennixSyscallsTable
void* FennixSyscallsTable[] static
Definition at line 517 of file Native.cpp.
Referenced by HandleFennixSyscalls().