Fennix Project: kernel/timer/TSC.cpp File Reference
TSC.cpp File Reference
#include "tsc.h"
#include "../cpu/cpuid.h"
#include <asm.h>
Functions
void TSC_sleep (uint64_t Nanoseconds)
void TSC_oneshot (uint32_t Vector, uint64_t Miliseconds)
Function Documentation
TSC_oneshot()
void TSC_oneshot (uint32_t Vector, uint64_t Miliseconds)
Definition at line 23 of file TSC.cpp.
 {
     err("TSC One-Shot is not implemented!");
 }
References err.
Referenced by TimerOneShot().
TSC_sleep()
void TSC_sleep (uint64_t Nanoseconds)
Definition at line 5 of file TSC.cpp.
 {
     if (cpu_feature(CPUID_FEAT_RDX_TSC))
     {
         // TODO: Calibrate the TSC timer
         static int once = 0;
         if (!once++)
             warn("Sleeping using TSC is not fully supported.");
         uint64_t start = tsc();
         while (tsc() - start < Nanoseconds)
             ;
     }
     else
     {
         warn("RDTSC is not supported.");
     }
 }
References cpu_feature(), CPUID_FEAT_RDX_TSC, tsc(), and warn.
Referenced by apictimer_nwait(), and nsleep().