Fennix Project: libc/src/alloc/liballoc_1_1.h File Reference
liballoc_1_1.h File Reference
#include <stddef.h>
#include <stdbool.h>
#include <stdint.h>
Macros
#define libPREFIX(func) func
Functions
void *libPREFIX() malloc (size_t)
The standard function.
void *libPREFIX() realloc (void *, size_t)
The standard function.
void *libPREFIX() calloc (size_t, size_t)
The standard function.
void libPREFIX() free (void *)
The standard function.
Macro Definition Documentation
libPREFIX
#define libPREFIX (func) func
Definition at line 5 of file liballoc_1_1.h.
Function Documentation
calloc()
void* libPREFIX() calloc (size_t , size_t)
The standard function.
Definition at line 578 of file liballoc_1_1.c.
 {
     int real_size;
     void *p;
     real_size = nobj * size;
     p = libPREFIX(malloc)(real_size);
     liballoc_memset(p, 0, real_size);
     return p;
 }
References liballoc_memset(), libPREFIX, malloc(), and size.
free()
void libPREFIX() free (void *)
The standard function.
Definition at line 99 of file defaultalloc.cpp.
 {
     if (HeapStart == nullptr)
     {
         err("Memory allocation not initialized yet!");
         return;
     }
     HeapSegHdr *Segment = (HeapSegHdr *)Address - 1;
     Segment->IsFree = true;
     Segment->CombineForward();
     Segment->CombineBackward();
 }
References Address, liballoc_minor::block, Heap::HeapSegHdr::CombineBackward(), Heap::HeapSegHdr::CombineForward(), err, liballoc_major::first, FreePages(), HeapStart, Heap::HeapSegHdr::IsFree, l_allocated, l_bestBet, l_errorCount, l_inuse, l_memRoot, l_possibleOverruns, l_warningCount, LIBALLOC_DEAD, LIBALLOC_MAGIC, LOCK, liballoc_minor::magic, liballoc_major::next, liballoc_minor::next, liballoc_major::pages, liballoc_major::prev, liballoc_minor::prev, liballoc_major::size, liballoc_minor::size, UNALIGN, UNLOCK, liballoc_major::usage, and warn.
Referenced by FileClose(), HeapFree(), MonotonLib::mtl::mtl(), ParseBuffer(), realloc(), and MonotonLib::mtl::~mtl().
malloc()
void* libPREFIX() malloc (size_t)
The standard function.
Definition at line 210 of file liballoc_1_1.c.
 {
     int startedBet = 0;
     unsigned long long bestSize = 0;
     void *p = NULL;
     uintptr_t diff;
     struct liballoc_major *maj;
     struct liballoc_minor *min;
     struct liballoc_minor *new_min;
     unsigned long size = req_size;
     // For alignment, we adjust size so there's enough space to align.
     if (ALIGNMENT > 1)
         size += ALIGNMENT + ALIGN_INFO;
     // So, ideally, we really want an alignment of 0 or 1 in order
     // to save space.
     LOCK(liballoc11_lock);
     if (size == 0)
     {
         l_warningCount += 1;
 #if defined DEBUG || defined INFO
         warn("malloc( 0 ) called from %llx", __builtin_return_address(0));
 #endif
         UNLOCK(liballoc11_lock);
         return libPREFIX(malloc)(1);
     }
     if (l_memRoot == NULL)
     {
 #if defined DEBUG || defined INFO
 #ifdef DEBUG
         debug("Initialization of liballoc %s", VERSION);
 #endif
         liballoc_dump();
 #endif
         // This is the first time we are being used.
         l_memRoot = allocate_new_page(size);
         if (l_memRoot == NULL)
         {
             UNLOCK(liballoc11_lock);
 #ifdef DEBUG
             err("Initial l_memRoot initialization failed %llp", p);
 #endif
             return NULL;
         }
 #ifdef DEBUG
         trace("Set up first memory major %llx", l_memRoot);
 #endif
     }
 #ifdef DEBUG
     // trace("%llx -> malloc( %i ): ", __builtin_return_address(0), size);
 #endif
     // Now we need to bounce through every major and find enough space....
     maj = l_memRoot;
     startedBet = 0;
     // Start at the best bet....
     if (l_bestBet != NULL)
     {
         bestSize = l_bestBet->size - l_bestBet->usage;
         if (bestSize > (size + sizeof(struct liballoc_minor)))
         {
             maj = l_bestBet;
             startedBet = 1;
         }
     }
     while (maj != NULL)
     {
         diff = maj->size - maj->usage;
         // free memory in the block
         if (bestSize < diff)
         {
             // Hmm.. this one has more memory then our bestBet. Remember!
             l_bestBet = maj;
             bestSize = diff;
         }
 #ifdef USE_CASE1
         // CASE 1:  There is not enough space in this major block.
         if (diff < (size + sizeof(struct liballoc_minor)))
         {
 #ifdef DEBUG
             // printf("CASE 1: Insufficient space in block %llx", maj);
 #endif
             // Another major block next to this one?
             if (maj->next != NULL)
             {
                 maj = maj->next; // Hop to that one.
                 continue;
             }
             if (startedBet == 1) // If we started at the best bet,
             {                    // let's start all over again.
                 maj = l_memRoot;
                 startedBet = 0;
                 continue;
             }
             // Create a new major block next to this one and...
             maj->next = allocate_new_page(size); // next one will be okay.
             if (maj->next == NULL)
                 break; // no more memory.
             maj->next->prev = maj;
             maj = maj->next;
             // .. fall through to CASE 2 ..
         }
 #endif
 #ifdef USE_CASE2
         // CASE 2: It's a brand new block.
         if (maj->first == NULL)
         {
             maj->first = (struct liballoc_minor *)((uintptr_t)maj + sizeof(struct liballoc_major));
             maj->first->magic = LIBALLOC_MAGIC;
             maj->first->prev = NULL;
             maj->first->next = NULL;
             maj->first->block = maj;
             maj->first->size = size;
             maj->first->req_size = req_size;
             maj->usage += size + sizeof(struct liballoc_minor);
             l_inuse += size;
             p = (void *)((uintptr_t)(maj->first) + sizeof(struct liballoc_minor));
             ALIGN(p);
 #ifdef DEBUG
             // printf("CASE 2: returning %llx", p);
 #endif
             UNLOCK(liballoc11_lock); // release the lock
             return p;
         }
 #endif
 #ifdef USE_CASE3
         // CASE 3: Block in use and enough space at the start of the block.
         diff = (uintptr_t)(maj->first);
         diff -= (uintptr_t)maj;
         diff -= sizeof(struct liballoc_major);
         if (diff >= (size + sizeof(struct liballoc_minor)))
         {
             // Yes, space in front. Squeeze in.
             maj->first->prev = (struct liballoc_minor *)((uintptr_t)maj + sizeof(struct liballoc_major));
             maj->first->prev->next = maj->first;
             maj->first = maj->first->prev;
             maj->first->magic = LIBALLOC_MAGIC;
             maj->first->prev = NULL;
             maj->first->block = maj;
             maj->first->size = size;
             maj->first->req_size = req_size;
             maj->usage += size + sizeof(struct liballoc_minor);
             l_inuse += size;
             p = (void *)((uintptr_t)(maj->first) + sizeof(struct liballoc_minor));
             ALIGN(p);
 #ifdef DEBUG
             // printf("CASE 3: returning %llx", p);
 #endif
             UNLOCK(liballoc11_lock); // release the lock
             return p;
         }
 #endif
 #ifdef USE_CASE4
         // CASE 4: There is enough space in this block. But is it contiguous?
         min = maj->first;
         // Looping within the block now...
         while (min != NULL)
         {
             // CASE 4.1: End of minors in a block. Space from last and end?
             if (min->next == NULL)
             {
                 // the rest of this block is free...  is it big enough?
                 diff = (uintptr_t)(maj) + maj->size;
                 diff -= (uintptr_t)min;
                 diff -= sizeof(struct liballoc_minor);
                 diff -= min->size;
                 // minus already existing usage..
                 if (diff >= (size + sizeof(struct liballoc_minor)))
                 {
                     // yay....
                     min->next = (struct liballoc_minor *)((uintptr_t)min + sizeof(struct liballoc_minor) + min->size);
                     min->next->prev = min;
                     min = min->next;
                     min->next = NULL;
                     min->magic = LIBALLOC_MAGIC;
                     min->block = maj;
                     min->size = size;
                     min->req_size = req_size;
                     maj->usage += size + sizeof(struct liballoc_minor);
                     l_inuse += size;
                     p = (void *)((uintptr_t)min + sizeof(struct liballoc_minor));
                     ALIGN(p);
 #ifdef DEBUG
                     // printf("CASE 4.1: returning %llx", p);
 #endif
                     UNLOCK(liballoc11_lock); // release the lock
                     return p;
                 }
             }
             // CASE 4.2: Is there space between two minors?
             if (min->next != NULL)
             {
                 // is the difference between here and next big enough?
                 diff = (uintptr_t)(min->next);
                 diff -= (uintptr_t)min;
                 diff -= sizeof(struct liballoc_minor);
                 diff -= min->size;
                 // minus our existing usage.
                 if (diff >= (size + sizeof(struct liballoc_minor)))
                 {
                     // yay......
                     new_min = (struct liballoc_minor *)((uintptr_t)min + sizeof(struct liballoc_minor) + min->size);
                     new_min->magic = LIBALLOC_MAGIC;
                     new_min->next = min->next;
                     new_min->prev = min;
                     new_min->size = size;
                     new_min->req_size = req_size;
                     new_min->block = maj;
                     min->next->prev = new_min;
                     min->next = new_min;
                     maj->usage += size + sizeof(struct liballoc_minor);
                     l_inuse += size;
                     p = (void *)((uintptr_t)new_min + sizeof(struct liballoc_minor));
                     ALIGN(p);
 #ifdef DEBUG
                     // printf("CASE 4.2: returning %llx", p);
 #endif
                     UNLOCK(liballoc11_lock); // release the lock
                     return p;
                 }
             } // min->next != NULL
             min = min->next;
         } // while min != NULL ...
 #endif
 #ifdef USE_CASE5
         // CASE 5: Block full! Ensure next block and loop.
         if (maj->next == NULL)
         {
 #ifdef DEBUG
             // printf("CASE 5: block full");
 #endif
             if (startedBet == 1)
             {
                 maj = l_memRoot;
                 startedBet = 0;
                 continue;
             }
             // we've run out. we need more...
             maj->next = allocate_new_page(size); // next one guaranteed to be okay
             if (maj->next == NULL)
                 break; //  uh oh,  no more memory.....
             maj->next->prev = maj;
         }
 #endif
         maj = maj->next;
     } // while (maj != NULL)
     UNLOCK(liballoc11_lock); // release the lock
 #ifdef DEBUG
     debug("All cases exhausted. No memory available.");
 #endif
 #if defined DEBUG || defined INFO
     warn("malloc( %i ) returning NULL.", size);
     liballoc_dump();
 #endif
     return NULL;
 }
References ALIGN, ALIGN_INFO, ALIGNMENT, allocate_new_page(), liballoc_minor::block, debug, err, liballoc_major::first, l_bestBet, l_inuse, l_memRoot, l_warningCount, LIBALLOC_MAGIC, libPREFIX, LOCK, liballoc_minor::magic, malloc(), liballoc_major::next, liballoc_minor::next, liballoc_major::prev, liballoc_minor::prev, liballoc_minor::req_size, liballoc_major::size, liballoc_minor::size, size, trace, UNLOCK, liballoc_major::usage, VERSION, and warn.
Referenced by calloc(), malloc(), and realloc().
realloc()
void* libPREFIX() realloc (void * , size_t)
The standard function.
Definition at line 588 of file liballoc_1_1.c.
 {
     void *ptr;
     struct liballoc_minor *min;
     unsigned int real_size;
     // Honour the case of size == 0 => free old and return NULL
     if (size == 0)
     {
         libPREFIX(free)(p);
         return NULL;
     }
     // In the case of a NULL pointer, return a simple malloc.
     if (p == NULL)
         return libPREFIX(malloc)(size);
     // Unalign the pointer if required.
     ptr = p;
     UNALIGN(ptr);
     LOCK(liballoc11_lock); // lockit
     min = (struct liballoc_minor *)((uintptr_t)ptr - sizeof(struct liballoc_minor));
     // Ensure it is a valid structure.
     if (min->magic != LIBALLOC_MAGIC)
     {
         l_errorCount += 1;
         // Check for overrun errors. For all bytes of LIBALLOC_MAGIC
         if (
             ((min->magic & 0xFFFFFF) == (LIBALLOC_MAGIC & 0xFFFFFF)) ||
             ((min->magic & 0xFFFF) == (LIBALLOC_MAGIC & 0xFFFF)) ||
             ((min->magic & 0xFF) == (LIBALLOC_MAGIC & 0xFF)))
         {
             l_possibleOverruns += 1;
 #if defined DEBUG || defined INFO
             err("Possible 1-3 byte overrun for magic %llx != %llx", min->magic, LIBALLOC_MAGIC);
 #endif
         }
         if (min->magic == LIBALLOC_DEAD)
         {
 #if defined DEBUG || defined INFO
             err("multiple free( %llx ) attempt from %llx.", ptr, __builtin_return_address(0));
 #endif
         }
         else
         {
 #if defined DEBUG || defined INFO
             err("Bad free( %llx ) called from %llx", ptr, __builtin_return_address(0));
 #endif
         }
         // being lied to...
         UNLOCK(liballoc11_lock); // release the lock
         return NULL;
     }
     // Definitely a memory block.
     real_size = min->req_size;
     if (real_size >= size)
     {
         min->req_size = size;
         UNLOCK(liballoc11_lock);
         return p;
     }
     UNLOCK(liballoc11_lock);
     // If we got here then we're reallocating to a block bigger than us.
     ptr = libPREFIX(malloc)(size); // We need to allocate new memory
     liballoc_memcpy(ptr, p, real_size);
     libPREFIX(free)(p);
     return ptr;
 }
References err, free(), l_errorCount, l_possibleOverruns, LIBALLOC_DEAD, LIBALLOC_MAGIC, liballoc_memcpy(), libPREFIX, LOCK, liballoc_minor::magic, malloc(), liballoc_minor::req_size, size, UNALIGN, and UNLOCK.