Fennix Project: PS2Mouse::PS2MouseDriver Class Reference
PS2Mouse::PS2MouseDriver Class Reference
#include <mouse.hpp>
Public Member Functions
MouseInfo GetMouseInfo ()
PS2MouseDriver ()
~PS2MouseDriver ()
Private Types
enum Config { READ_CONFIG = 0x20, WRITE_CONFIG = 0x60 }
enum Ports { DATA = 0x60, STATUS = 0x64, COMMAND = 0x64 }
enum State { OUTPUT_FULL = (1 << 0), INPUT_FULL = (1 << 1), MOUSE_BYTE = (1 << 5) }
Private Member Functions
void WaitRead ()
void WaitWrite ()
void Write (uint16_t Port, uint8_t Value)
uint8_t Read ()
Detailed Description
Definition at line 21 of file mouse.hpp.
Member Enumeration Documentation
Config
enum PS2Mouse::PS2MouseDriver::Config private
Enumerator
READ_CONFIG
WRITE_CONFIG
Definition at line 24 of file mouse.hpp.
         {
             READ_CONFIG = 0x20,
             WRITE_CONFIG = 0x60
         };
Ports
enum PS2Mouse::PS2MouseDriver::Ports private
Enumerator
DATA
STATUS
COMMAND
Definition at line 30 of file mouse.hpp.
         {
             DATA = 0x60,
             STATUS = 0x64,
             COMMAND = 0x64,
         };
State
enum PS2Mouse::PS2MouseDriver::State private
Enumerator
OUTPUT_FULL
INPUT_FULL
MOUSE_BYTE
Definition at line 37 of file mouse.hpp.
         {
             OUTPUT_FULL = (1 << 0),
             INPUT_FULL = (1 << 1),
             MOUSE_BYTE = (1 << 5)
         };
Constructor & Destructor Documentation
PS2MouseDriver()
PS2Mouse::PS2MouseDriver::PS2MouseDriver ()
Definition at line 154 of file mouse.cpp.
     {
         RegisterInterrupt(PS2MouseInterruptHandler, IRQ12, true);
         outb(COMMAND, 0xA8);
         Write(COMMAND, READ_CONFIG);
         uint8_t Status = Read();
         Status |= 0b10;
         Write(COMMAND, WRITE_CONFIG);
         Write(DATA, Status);
         Write(COMMAND, 0xD4);
         Write(DATA, 0xF6);
         Read();
         Write(COMMAND, 0xD4);
         Write(DATA, 0xF4);
         Read();
         devfs->AddFileSystem(&mouse, 0666, "mouse", FileSystem::NodeFlags::FS_PIPE);
     }
References FileSystem::Device::AddFileSystem(), COMMAND, DATA, devfs, FS_PIPE, IRQ12, PS2Mouse::mouse, outb, Read(), READ_CONFIG, RegisterInterrupt(), Status, Write(), and WRITE_CONFIG.
~PS2MouseDriver()
PS2Mouse::PS2MouseDriver::~PS2MouseDriver ()
Definition at line 172 of file mouse.cpp.
     {
         warn("Unloading default mouse driver is not supported.");
     }
References warn.
Member Function Documentation
GetMouseInfo()
MouseInfo PS2Mouse::PS2MouseDriver::GetMouseInfo ()
Definition at line 152 of file mouse.cpp.
 { return minfo; }
References PS2Mouse::minfo.
Read()
uint8_t PS2Mouse::PS2MouseDriver::Read () inline private
Definition at line 66 of file mouse.hpp.
         {
             WaitRead();
             return inb(Ports::DATA);
         }
References inb, and WaitRead().
Referenced by PS2MouseDriver().
WaitRead()
void PS2Mouse::PS2MouseDriver::WaitRead () inline private
Definition at line 44 of file mouse.hpp.
         {
             uint64_t Timeout = 100000;
             while (Timeout--)
                 if (inb(Ports::STATUS) & State::OUTPUT_FULL)
                     return;
         }
References inb.
Referenced by Read().
WaitWrite()
void PS2Mouse::PS2MouseDriver::WaitWrite () inline private
Definition at line 52 of file mouse.hpp.
         {
             uint64_t Timeout = 100000;
             while (Timeout--)
                 if ((inb(Ports::STATUS) & State::INPUT_FULL) == 0)
                     return;
         }
References inb.
Referenced by Write().
Write()
void PS2Mouse::PS2MouseDriver::Write (uint16_t Port, uint8_t Value) inline private
Definition at line 60 of file mouse.hpp.
         {
             WaitWrite();
             outb(Port, Value);
         }
References outb, and WaitWrite().
Referenced by PS2MouseDriver().
The documentation for this class was generated from the following files:
kernel/drivers/mouse.hpp
kernel/drivers/mouse.cpp