Fennix Project: FileSystem Namespace Reference
FileSystem Namespace Reference
Data Structures
class Device
class Driver
class EXT2
class FAT
class FB
struct FILE
struct FileSystemNode
struct FileSystemOpeations
class Initrd
class Mount
class Network
class Null
class Process
class Random
class Serial
class SysInfo
class USTAR
class Virtual
class Zero
Typedefs
typedef uint64_t(* OperationMount) (const char *, unsigned long, const void *)
typedef uint64_t(* OperationUmount) (int)
typedef uint64_t(* OperationRead) (FileSystemNode *Node, uint64_t Offset, uint64_t Size, uint8_t *Buffer)
typedef uint64_t(* OperationWrite) (FileSystemNode *Node, uint64_t Offset, uint64_t Size, uint8_t *Buffer)
typedef void(* OperationOpen) (FileSystemNode *Node, uint8_t Mode, uint8_t Flags)
typedef void(* OperationClose) (FileSystemNode *Node)
typedef uint64_t(* OperationSync) (void)
typedef void(* OperationCreate) (FileSystemNode *Node, char *Name, uint16_t NameLength)
typedef void(* OperationMkdir) (FileSystemNode *Node, char *Name, uint16_t NameLength)
Enumerations
enum FILESTATUS {
OK = 0, NOT_FOUND = 1, ACCESS_DENIED = 2, INVALID_NAME = 3,
INVALID_PARAMETER = 4, INVALID_HANDLE = 5, INVALID_PATH = 6, INVALID_FILE = 7,
INVALID_DEVICE = 8, NOT_EMPTY = 9, NOT_SUPPORTED = 10, INVALID_DRIVE = 11,
VOLUME_IN_USE = 12, TIMEOUT = 13, NO_MORE_FILES = 14, END_OF_FILE = 15,
FILE_EXISTS = 16, PIPE_BUSY = 17, PIPE_DISCONNECTED = 18, MORE_DATA = 19,
NO_DATA = 20, PIPE_NOT_CONNECTED = 21, MORE_ENTRIES = 22, DIRECTORY_NOT_EMPTY = 23,
NOT_A_DIRECTORY = 24, FILE_IS_A_DIRECTORY = 25, DIRECTORY_NOT_ROOT = 26, DIRECTORY_NOT_EMPTY_2 = 27,
END_OF_MEDIA = 28, NO_MEDIA = 29, UNRECOGNIZED_MEDIA = 30, SECTOR_NOT_FOUND = 31
}
enum NodeFlags {
FS_ERROR = 0x0, FS_FILE = 0x01, FS_DIRECTORY = 0x02, FS_CHARDEVICE = 0x03,
FS_BLOCKDEVICE = 0x04, FS_PIPE = 0x05, FS_SYMLINK = 0x06, FS_MOUNTPOINT = 0x08
}
Functions
FileSystemNode * AddNewChild (FileSystemNode *Parent, string Name)
FileSystemNode * GetChild (FileSystemNode *Parent, string Name)
FILESTATUS RemoveChild (FileSystemNode *Parent, string Name)
ReadFSFunction (EXT2_Read)
WriteFSFunction (EXT2_Write)
ReadFSFunction (FAT_Read)
WriteFSFunction (FAT_Write)
ReadFSFunction (FB_Read)
WriteFSFunction (FB_Write)
ReadFSFunction (Initrd_Read)
ReadFSFunction (Null_Read)
WriteFSFunction (Null_Write)
ReadFSFunction (Random_Read)
WriteFSFunction (Random_Write)
ReadFSFunction (Serial_Read1)
WriteFSFunction (Serial_Write1)
ReadFSFunction (Serial_Read2)
WriteFSFunction (Serial_Write2)
ReadFSFunction (Serial_Read3)
WriteFSFunction (Serial_Write3)
ReadFSFunction (Serial_Read4)
WriteFSFunction (Serial_Write4)
ReadFSFunction (USTAR_Read)
ReadFSFunction (Zero_Read)
WriteFSFunction (Zero_Write)
ReadFSFunction (FB_Address_Read)
ReadFSFunction (FB_Width_Read)
ReadFSFunction (FB_Height_Read)
ReadFSFunction (FB_PixelsPerScanLine_Read)
ReadFSFunction (FB_Size_Read)
ReadFSFunction (CPU_Vendor_Read)
ReadFSFunction (CPU_Name_Read)
ReadFSFunction (CPU_Hyper_Read)
Variables
EXT2::SuperBlock sb
FileSystemOpeations ext2
FileSystemOpeations fat
uint64_t fbAddress
uint64_t fbSize
uint32_t fbWidth
uint32_t fbHeight
uint32_t fbPixelsPerScanLine
FileSystemOpeations fb
FileSystemOpeations null
FileSystemOpeations random
FileSystemOpeations serial1
FileSystemOpeations serial2
FileSystemOpeations serial3
FileSystemOpeations serial4
FileSystemOpeations ustar
FileSystemOpeations zero
FileSystemNode * DeviceRootNode = nullptr
static uint64_t DeviceNodeIndexNodeCount = 0
FileSystemNode * DriverRootNode = nullptr
static uint64_t DriverNodeIndexNodeCount = 0
FileSystemNode * MountRootNode = nullptr
static uint64_t MountNodeIndexNodeCount = 0
FileSystemNode * NetworkRootNode = nullptr
static uint64_t NetworkNodeIndexNodeCount = 0
FileSystemNode * ProcessRootNode = nullptr
FileSystemNode * SysInfoRootNode = nullptr
static uint64_t SysInfoNodeIndexNodeCount = 0
FileSystemOpeations sysinfo_fb_address = {.Name = "SysInfo Data", .Read = FB_Address_Read}
FileSystemOpeations sysinfo_fb_width = {.Name = "SysInfo Data", .Read = FB_Width_Read}
FileSystemOpeations sysinfo_fb_height = {.Name = "SysInfo Data", .Read = FB_Height_Read}
FileSystemOpeations sysinfo_fb_ppsl = {.Name = "SysInfo Data", .Read = FB_PixelsPerScanLine_Read}
FileSystemOpeations sysinfo_fb_size = {.Name = "SysInfo Data", .Read = FB_Size_Read}
FileSystemOpeations sysinfo_cpu_vendor = {.Name = "SysInfo Data", .Read = CPU_Vendor_Read}
FileSystemOpeations sysinfo_cpu_name = {.Name = "SysInfo Data", .Read = CPU_Name_Read}
FileSystemOpeations sysinfo_cpu_hyper = {.Name = "SysInfo Data", .Read = CPU_Hyper_Read}
Data Structure Documentation
FileSystem::FILE
struct FileSystem::FILE
Definition at line 122 of file filesystem.h.
Data Fields
string Name
FileSystemNode * Node
FILESTATUS Status
FileSystem::FileSystemNode
struct FileSystem::FileSystemNode
Definition at line 102 of file filesystem.h.
Data Fields
uint64_t Address
Vector< FileSystemNode * > Children
uint64_t Flags
uint64_t GroupIdentifier
uint64_t IndexNode
uint64_t Length
uint64_t Mask
uint64_t Mode
char Name[FILENAME_LENGTH]
FileSystemOpeations * Operator
FileSystemNode * Parent
uint64_t UserIdentifier
FileSystem::FileSystemOpeations
struct FileSystem::FileSystemOpeations
Definition at line 89 of file filesystem.h.
Data Fields
OperationClose Close
OperationCreate Create
OperationMkdir MakeDirectory
OperationMount Mount
char Name[FILENAME_LENGTH]
OperationOpen Open
OperationRead Read
OperationUmount Umount
OperationWrite Write
Typedef Documentation
OperationClose
typedef void(* FileSystem::OperationClose) (FileSystemNode *Node)
Definition at line 25 of file filesystem.h.
OperationCreate
typedef void(* FileSystem::OperationCreate) (FileSystemNode *Node, char *Name, uint16_t NameLength)
Definition at line 27 of file filesystem.h.
OperationMkdir
typedef void(* FileSystem::OperationMkdir) (FileSystemNode *Node, char *Name, uint16_t NameLength)
Definition at line 28 of file filesystem.h.
OperationMount
typedef uint64_t(* FileSystem::OperationMount) (const char *, unsigned long, const void *)
Definition at line 20 of file filesystem.h.
OperationOpen
typedef void(* FileSystem::OperationOpen) (FileSystemNode *Node, uint8_t Mode, uint8_t Flags)
Definition at line 24 of file filesystem.h.
OperationRead
typedef uint64_t(* FileSystem::OperationRead) (FileSystemNode *Node, uint64_t Offset, uint64_t Size, uint8_t *Buffer)
Definition at line 22 of file filesystem.h.
OperationSync
typedef uint64_t(* FileSystem::OperationSync) (void)
Definition at line 26 of file filesystem.h.
OperationUmount
typedef uint64_t(* FileSystem::OperationUmount) (int)
Definition at line 21 of file filesystem.h.
OperationWrite
typedef uint64_t(* FileSystem::OperationWrite) (FileSystemNode *Node, uint64_t Offset, uint64_t Size, uint8_t *Buffer)
Definition at line 23 of file filesystem.h.
Enumeration Type Documentation
FILESTATUS
enum FileSystem::FILESTATUS
Enumerator
OK
NOT_FOUND
ACCESS_DENIED
INVALID_NAME
INVALID_PARAMETER
INVALID_HANDLE
INVALID_PATH
INVALID_FILE
INVALID_DEVICE
NOT_EMPTY
NOT_SUPPORTED
INVALID_DRIVE
VOLUME_IN_USE
TIMEOUT
NO_MORE_FILES
END_OF_FILE
FILE_EXISTS
PIPE_BUSY
PIPE_DISCONNECTED
MORE_DATA
NO_DATA
PIPE_NOT_CONNECTED
MORE_ENTRIES
DIRECTORY_NOT_EMPTY
NOT_A_DIRECTORY
FILE_IS_A_DIRECTORY
DIRECTORY_NOT_ROOT
DIRECTORY_NOT_EMPTY_2
END_OF_MEDIA
NO_MEDIA
UNRECOGNIZED_MEDIA
SECTOR_NOT_FOUND
Definition at line 41 of file filesystem.h.
     {
         OK = 0,
         NOT_FOUND = 1,
         ACCESS_DENIED = 2,
         INVALID_NAME = 3,
         INVALID_PARAMETER = 4,
         INVALID_HANDLE = 5,
         INVALID_PATH = 6,
         INVALID_FILE = 7,
         INVALID_DEVICE = 8,
         NOT_EMPTY = 9,
         NOT_SUPPORTED = 10,
         INVALID_DRIVE = 11,
         VOLUME_IN_USE = 12,
         TIMEOUT = 13,
         NO_MORE_FILES = 14,
         END_OF_FILE = 15,
         FILE_EXISTS = 16,
         PIPE_BUSY = 17,
         PIPE_DISCONNECTED = 18,
         MORE_DATA = 19,
         NO_DATA = 20,
         PIPE_NOT_CONNECTED = 21,
         MORE_ENTRIES = 22,
         DIRECTORY_NOT_EMPTY = 23,
         NOT_A_DIRECTORY = 24,
         FILE_IS_A_DIRECTORY = 25,
         DIRECTORY_NOT_ROOT = 26,
         DIRECTORY_NOT_EMPTY_2 = 27,
         END_OF_MEDIA = 28,
         NO_MEDIA = 29,
         UNRECOGNIZED_MEDIA = 30,
         SECTOR_NOT_FOUND = 31
     };
NodeFlags
enum FileSystem::NodeFlags
Enumerator
FS_ERROR
FS_FILE
FS_DIRECTORY
FS_CHARDEVICE
FS_BLOCKDEVICE
FS_PIPE
FS_SYMLINK
FS_MOUNTPOINT
Definition at line 77 of file filesystem.h.
     {
         FS_ERROR = 0x0,
         FS_FILE = 0x01,
         FS_DIRECTORY = 0x02,
         FS_CHARDEVICE = 0x03,
         FS_BLOCKDEVICE = 0x04,
         FS_PIPE = 0x05,
         FS_SYMLINK = 0x06,
         FS_MOUNTPOINT = 0x08
     };
Function Documentation
AddNewChild()
FileSystemNode* FileSystem::AddNewChild (FileSystemNode * Parent, string Name)
Definition at line 109 of file FileSystem.cpp.
     {
         vfsdbg("AddNewChild( Parent: \"%s\" Name: \"%s\" )", Parent->Name, Name);
         FileSystemNode *newNode = new FileSystemNode;
         newNode->Parent = Parent;
         strcpy(newNode->Name, Name);
         newNode->Operator = Parent->Operator;
         Parent->Children.push_back(newNode);
         vfsdbg("AddNewChild()->\"%s\"", newNode->Name);
         return newNode;
     }
References FileSystem::FileSystemNode::Children, FileSystem::FileSystemNode::Name, FileSystem::FileSystemNode::Operator, FileSystem::FileSystemNode::Parent, strcpy(), and vfsdbg.
Referenced by FileSystem::Virtual::Create().
GetChild()
FileSystemNode* FileSystem::GetChild (FileSystemNode * Parent, string Name)
Definition at line 121 of file FileSystem.cpp.
     {
         vfsdbg("GetChild( Parent: \"%s\" Name: \"%s\" )", Parent->Name, Name);
         foreach (auto var in Parent->Children)
             if (strcmp(var->Name, Name) == 0)
             {
                 vfsdbg("GetChild()->\"%s\"", var->Name);
                 return var;
             }
         vfsdbg("GetChild()->nullptr");
         return nullptr;
     }
References FileSystem::FileSystemNode::Name, strcmp(), and vfsdbg.
Referenced by FileSystem::Virtual::Create().
ReadFSFunction() [1/20]
FileSystem::ReadFSFunction (CPU_Hyper_Read)
Definition at line 108 of file sysinfo.cpp.
     {
         uint32_t rax, rbx, rcx, rdx;
         char vendor[12];
         cpuid(0x40000000, &rax, &rbx, &rcx, &rdx);
         memcpy(vendor + 0, &rbx, 4);
         memcpy(vendor + 4, &rcx, 4);
         memcpy(vendor + 8, &rdx, 4);
         memcpy(Buffer, vendor, strlen(vendor));
         return strlen(vendor);
     }
References cpuid(), memcpy(), and strlen().
ReadFSFunction() [2/20]
FileSystem::ReadFSFunction (CPU_Name_Read)
Definition at line 82 of file sysinfo.cpp.
     {
         uint32_t rax, rbx, rcx, rdx;
         uint32_t func;
         cpuid(0x80000000, &func, &rbx, &rcx, &rdx);
         if (func >= 0x80000004)
         {
             char name_cpuid[48];
             cpuid(0x80000002, (uint32_t *)(name_cpuid + 0), (uint32_t *)(name_cpuid + 4), (uint32_t *)(name_cpuid + 8), (uint32_t *)(name_cpuid + 12));
             cpuid(0x80000003, (uint32_t *)(name_cpuid + 16), (uint32_t *)(name_cpuid + 20), (uint32_t *)(name_cpuid + 24), (uint32_t *)(name_cpuid + 28));
             cpuid(0x80000004, (uint32_t *)(name_cpuid + 32), (uint32_t *)(name_cpuid + 36), (uint32_t *)(name_cpuid + 40), (uint32_t *)(name_cpuid + 44));
             const char *space = name_cpuid;
             while (*space == ' ')
             {
                 ++space;
             }
             memcpy(Buffer, name_cpuid, strlen(name_cpuid));
         }
         else
         {
             memcpy(Buffer, "unknown", 7);
         }
         return strlen((char *)Buffer);
     }
References cpuid(), memcpy(), and strlen().
ReadFSFunction() [3/20]
FileSystem::ReadFSFunction (CPU_Vendor_Read)
Definition at line 75 of file sysinfo.cpp.
     {
         cpuid_string(0, (int *)(Buffer));
         return 16;
     }
References cpuid_string().
ReadFSFunction() [4/20]
FileSystem::ReadFSFunction (EXT2_Read)
Definition at line 19 of file ext2.cpp.
     {
         return Size;
     }
ReadFSFunction() [5/20]
FileSystem::ReadFSFunction (FAT_Read)
Definition at line 6 of file fat.cpp.
     {
         return Size;
     }
ReadFSFunction() [6/20]
FileSystem::ReadFSFunction (FB_Address_Read)
Definition at line 35 of file sysinfo.cpp.
     {
         uint32_t ret = CurrentDisplay->GetFramebuffer()->Address;
         Buffer = (uint8_t *)((uint64_t)ret);
         return ret;
     }
References CurrentDisplay.
ReadFSFunction() [7/20]
FileSystem::ReadFSFunction (FB_Height_Read)
Definition at line 51 of file sysinfo.cpp.
     {
         uint32_t ret = CurrentDisplay->GetFramebuffer()->Height;
         Buffer = (uint8_t *)((uint64_t)ret);
         return ret;
     }
References CurrentDisplay.
ReadFSFunction() [8/20]
FileSystem::ReadFSFunction (FB_PixelsPerScanLine_Read)
Definition at line 59 of file sysinfo.cpp.
     {
         uint32_t ret = CurrentDisplay->GetFramebuffer()->PixelsPerScanLine;
         Buffer = (uint8_t *)((uint64_t)ret);
         return ret;
     }
References CurrentDisplay.
ReadFSFunction() [9/20]
FileSystem::ReadFSFunction (FB_Read)
Definition at line 15 of file fb.cpp.
     {
         uint64_t X = Offset;
         uint64_t Y = Size;
         if (X >= fbWidth || Y >= fbHeight)
             Buffer = 0;
         Buffer = (uint8_t *)((uint64_t)(((uint32_t *)fbAddress)[X + (Y * fbPixelsPerScanLine)]));
         return fbSize;
     }
References fbAddress, fbHeight, fbPixelsPerScanLine, fbSize, and fbWidth.
ReadFSFunction() [10/20]
FileSystem::ReadFSFunction (FB_Size_Read)
Definition at line 67 of file sysinfo.cpp.
     {
         uint32_t ret = CurrentDisplay->GetFramebuffer()->Size;
         Buffer = (uint8_t *)((uint64_t)ret);
         return ret;
     }
References CurrentDisplay.
ReadFSFunction() [11/20]
FileSystem::ReadFSFunction (FB_Width_Read)
Definition at line 43 of file sysinfo.cpp.
     {
         uint32_t ret = CurrentDisplay->GetFramebuffer()->Width;
         Buffer = (uint8_t *)((uint64_t)ret);
         return ret;
     }
References CurrentDisplay.
ReadFSFunction() [12/20]
FileSystem::ReadFSFunction (Initrd_Read)
Definition at line 5 of file initrd.cpp.
     {
         return 0;
     }
ReadFSFunction() [13/20]
FileSystem::ReadFSFunction (Null_Read)
Definition at line 5 of file null.cpp.
     {
         if (Size < 1)
             return 0;
         memset(Buffer, 0x0, Size);
         return Size;
     }
References memset().
ReadFSFunction() [14/20]
FileSystem::ReadFSFunction (Random_Read)
Definition at line 6 of file random.cpp.
     {
         uint64_t s = 0;
         while (s < Size)
         {
             ((uint8_t *)Buffer)[s] = (rand64()) % 0xFF;
             Offset++;
             s++;
         }
         return Size;
     }
References rand64().
ReadFSFunction() [15/20]
FileSystem::ReadFSFunction (Serial_Read1)
Definition at line 6 of file serial.cpp.
     {
         if (Size < 1)
             return 0;
         memset(Buffer, 0x00, 1);
         uint64_t received = 0;
         while (received < Size)
         {
             ((uint8_t *)Buffer)[received] = read_serial(COM1);
             received++;
         }
         return received;
     }
References COM1, memset(), and read_serial().
ReadFSFunction() [16/20]
FileSystem::ReadFSFunction (Serial_Read2)
Definition at line 31 of file serial.cpp.
     {
         if (Size < 1)
             return 0;
         memset(Buffer, 0x00, 1);
         uint64_t received = 0;
         while (received < Size)
         {
             ((uint8_t *)Buffer)[received] = read_serial(COM2);
             received++;
         }
         return received;
     }
References COM2, memset(), and read_serial().
ReadFSFunction() [17/20]
FileSystem::ReadFSFunction (Serial_Read3)
Definition at line 56 of file serial.cpp.
     {
         if (Size < 1)
             return 0;
         memset(Buffer, 0x00, 1);
         uint64_t received = 0;
         while (received < Size)
         {
             ((uint8_t *)Buffer)[received] = read_serial(COM3);
             received++;
         }
         return received;
     }
References COM3, memset(), and read_serial().
ReadFSFunction() [18/20]
FileSystem::ReadFSFunction (Serial_Read4)
Definition at line 81 of file serial.cpp.
     {
         if (Size < 1)
             return 0;
         memset(Buffer, 0x00, 1);
         uint64_t received = 0;
         while (received < Size)
         {
             ((uint8_t *)Buffer)[received] = read_serial(COM4);
             received++;
         }
         return received;
     }
References COM4, memset(), and read_serial().
ReadFSFunction() [19/20]
FileSystem::ReadFSFunction (USTAR_Read)
Definition at line 6 of file ustar.cpp.
     {
         if (!Size)
             Size = Node->Length;
         if (Offset > Node->Length)
             return 0;
         if (Offset + Size > Node->Length)
             Size = Node->Length - Offset;
         memcpy(Buffer, (uint8_t *)(Node->Address + Offset), Size);
         return Size;
     }
References memcpy().
ReadFSFunction() [20/20]
FileSystem::ReadFSFunction (Zero_Read)
Definition at line 5 of file zero.cpp.
     {
         memset(Buffer, 0, Size);
         return 0;
     }
References memset().
RemoveChild()
FILESTATUS FileSystem::RemoveChild (FileSystemNode * Parent, string Name)
Definition at line 134 of file FileSystem.cpp.
     {
         vfsdbg("RemoveChild( Parent: \"%s\" Name: \"%s\" )", Parent->Name, Name);
         for (uint64_t i = 0; i < Parent->Children.size(); i++)
             if (strcmp(Parent->Children[i]->Name, Name) == 0)
             {
                 Parent->Children.remove(i);
                 vfsdbg("RemoveChild()->OK");
                 return FILESTATUS::OK;
             }
         vfsdbg("RemoveChild()->NOT_FOUND");
         return FILESTATUS::NOT_FOUND;
     }
References FileSystem::FileSystemNode::Children, FileSystem::FileSystemNode::Name, NOT_FOUND, OK, strcmp(), and vfsdbg.
WriteFSFunction() [1/10]
FileSystem::WriteFSFunction (EXT2_Write)
Definition at line 24 of file ext2.cpp.
     {
         return Size;
     }
WriteFSFunction() [2/10]
FileSystem::WriteFSFunction (FAT_Write)
Definition at line 11 of file fat.cpp.
     {
         return Size;
     }
WriteFSFunction() [3/10]
FileSystem::WriteFSFunction (FB_Write)
Definition at line 25 of file fb.cpp.
     {
         uint64_t X = Offset;
         uint64_t Y = Size;
         if (X >= fbWidth || Y >= fbHeight)
             return 0;
         ((uint32_t *)fbAddress)[X + (Y * fbPixelsPerScanLine)] = (uint32_t)((uint64_t)Buffer);
         return fbSize;
     }
References fbAddress, fbHeight, fbPixelsPerScanLine, fbSize, and fbWidth.
WriteFSFunction() [4/10]
FileSystem::WriteFSFunction (Null_Write)
Definition at line 13 of file null.cpp.
 { return Size; }
WriteFSFunction() [5/10]
FileSystem::WriteFSFunction (Random_Write)
Definition at line 18 of file random.cpp.
 { return Size; }
WriteFSFunction() [6/10]
FileSystem::WriteFSFunction (Serial_Write1)
Definition at line 20 of file serial.cpp.
     {
         uint64_t sent = 0;
         while (sent < Size)
         {
             write_serial(COM1, ((uint8_t *)Buffer)[sent]);
             sent++;
         }
         return Size;
     }
References COM1, and write_serial().
WriteFSFunction() [7/10]
FileSystem::WriteFSFunction (Serial_Write2)
Definition at line 45 of file serial.cpp.
     {
         uint64_t sent = 0;
         while (sent < Size)
         {
             write_serial(COM2, ((uint8_t *)Buffer)[sent]);
             sent++;
         }
         return Size;
     }
References COM2, and write_serial().
WriteFSFunction() [8/10]
FileSystem::WriteFSFunction (Serial_Write3)
Definition at line 70 of file serial.cpp.
     {
         uint64_t sent = 0;
         while (sent < Size)
         {
             write_serial(COM3, ((uint8_t *)Buffer)[sent]);
             sent++;
         }
         return Size;
     }
References COM3, and write_serial().
WriteFSFunction() [9/10]
FileSystem::WriteFSFunction (Serial_Write4)
Definition at line 95 of file serial.cpp.
     {
         uint64_t sent = 0;
         while (sent < Size)
         {
             write_serial(COM4, ((uint8_t *)Buffer)[sent]);
             sent++;
         }
         return Size;
     }
References COM4, and write_serial().
WriteFSFunction() [10/10]
FileSystem::WriteFSFunction (Zero_Write)
Definition at line 11 of file zero.cpp.
 { return Size; }
Variable Documentation
DeviceNodeIndexNodeCount
uint64_t FileSystem::DeviceNodeIndexNodeCount = 0 static
Definition at line 8 of file devfs.cpp.
Referenced by FileSystem::Device::AddFileSystem().
DeviceRootNode
FileSystemNode* FileSystem::DeviceRootNode = nullptr
Definition at line 7 of file devfs.cpp.
Referenced by FileSystem::Device::AddFileSystem(), and FileSystem::Device::Device().
DriverNodeIndexNodeCount
uint64_t FileSystem::DriverNodeIndexNodeCount = 0 static
Definition at line 8 of file drvfs.cpp.
Referenced by FileSystem::Driver::AddDriver().
DriverRootNode
FileSystemNode* FileSystem::DriverRootNode = nullptr
Definition at line 7 of file drvfs.cpp.
Referenced by FileSystem::Driver::AddDriver(), and FileSystem::Driver::Driver().
ext2
FileSystemOpeations FileSystem::ext2
Initial value:
= {
        .Name = "EXT2",
        .Read = EXT2_Read,
        .Write = EXT2_Write}
Definition at line 29 of file ext2.cpp.
Referenced by FileSystem::EXT2::EXT2().
fat
FileSystemOpeations FileSystem::fat
Initial value:
= {
        .Name = "FAT",
        .Read = FAT_Read,
        .Write = FAT_Write}
Definition at line 16 of file fat.cpp.
Referenced by FileSystem::FAT::FAT().
fb
FileSystemOpeations FileSystem::fb
Initial value:
= {
        .Name = "Framebuffer",
        .Read = FB_Read,
        .Write = FB_Write}
Definition at line 35 of file fb.cpp.
Referenced by __attribute__(), FileSystem::FB::FB(), init_stivale2(), and KernelInit().
fbAddress
uint64_t FileSystem::fbAddress
Definition at line 10 of file fb.cpp.
Referenced by ReadFSFunction(), FileSystem::FB::SetFrameBufferData(), and WriteFSFunction().
fbHeight
uint32_t FileSystem::fbHeight
Definition at line 12 of file fb.cpp.
Referenced by ReadFSFunction(), FileSystem::FB::SetFrameBufferData(), and WriteFSFunction().
fbPixelsPerScanLine
uint32_t FileSystem::fbPixelsPerScanLine
Definition at line 13 of file fb.cpp.
Referenced by ReadFSFunction(), FileSystem::FB::SetFrameBufferData(), and WriteFSFunction().
fbSize
uint64_t FileSystem::fbSize
Definition at line 11 of file fb.cpp.
Referenced by init_pmm(), ReadFSFunction(), FileSystem::FB::SetFrameBufferData(), and WriteFSFunction().
fbWidth
uint32_t FileSystem::fbWidth
Definition at line 12 of file fb.cpp.
Referenced by ReadFSFunction(), FileSystem::FB::SetFrameBufferData(), and WriteFSFunction().
MountNodeIndexNodeCount
uint64_t FileSystem::MountNodeIndexNodeCount = 0 static
Definition at line 11 of file mountfs.cpp.
Referenced by FileSystem::Mount::MountFileSystem().
MountRootNode
FileSystemNode* FileSystem::MountRootNode = nullptr
Definition at line 10 of file mountfs.cpp.
Referenced by FileSystem::Mount::Mount(), and FileSystem::Mount::MountFileSystem().
NetworkNodeIndexNodeCount
uint64_t FileSystem::NetworkNodeIndexNodeCount = 0 static
Definition at line 8 of file netfs.cpp.
Referenced by FileSystem::Network::AddNetworkCard().
NetworkRootNode
FileSystemNode* FileSystem::NetworkRootNode = nullptr
Definition at line 7 of file netfs.cpp.
Referenced by FileSystem::Network::AddNetworkCard(), and FileSystem::Network::Network().
null
FileSystemOpeations FileSystem::null
Initial value:
= {
        .Name = "Null",
        .Read = Null_Read,
        .Write = Null_Write}
Definition at line 15 of file null.cpp.
ProcessRootNode
FileSystemNode* FileSystem::ProcessRootNode = nullptr
Definition at line 7 of file procfs.cpp.
Referenced by FileSystem::Process::Process().
random
FileSystemOpeations FileSystem::random
Initial value:
= {
        .Name = "Random",
        .Read = &Random_Read,
        .Write = &Random_Write}
Definition at line 20 of file random.cpp.
Referenced by FileSystem::Random::Random().
sb
EXT2::SuperBlock FileSystem::sb
Definition at line 17 of file ext2.cpp.
Referenced by FileSystem::EXT2::EXT2().
serial1
FileSystemOpeations FileSystem::serial1
Initial value:
= {
        .Name = "Serial Port 1",
        .Read = Serial_Read1,
        .Write = Serial_Write1}
Definition at line 106 of file serial.cpp.
Referenced by FileSystem::Serial::Serial().
serial2
FileSystemOpeations FileSystem::serial2
Initial value:
= {
        .Name = "Serial Port 2",
        .Read = Serial_Read2,
        .Write = Serial_Write2}
Definition at line 111 of file serial.cpp.
Referenced by FileSystem::Serial::Serial().
serial3
FileSystemOpeations FileSystem::serial3
Initial value:
= {
        .Name = "Serial Port 3",
        .Read = Serial_Read3,
        .Write = Serial_Write3}
Definition at line 116 of file serial.cpp.
Referenced by FileSystem::Serial::Serial().
serial4
FileSystemOpeations FileSystem::serial4
Initial value:
= {
        .Name = "Serial Port 4",
        .Read = Serial_Read4,
        .Write = Serial_Write4}
Definition at line 121 of file serial.cpp.
Referenced by FileSystem::Serial::Serial().
sysinfo_cpu_hyper
FileSystemOpeations FileSystem::sysinfo_cpu_hyper = {.Name = "SysInfo Data", .Read = CPU_Hyper_Read}
Definition at line 119 of file sysinfo.cpp.
sysinfo_cpu_name
FileSystemOpeations FileSystem::sysinfo_cpu_name = {.Name = "SysInfo Data", .Read = CPU_Name_Read}
Definition at line 106 of file sysinfo.cpp.
sysinfo_cpu_vendor
FileSystemOpeations FileSystem::sysinfo_cpu_vendor = {.Name = "SysInfo Data", .Read = CPU_Vendor_Read}
Definition at line 80 of file sysinfo.cpp.
sysinfo_fb_address
FileSystemOpeations FileSystem::sysinfo_fb_address = {.Name = "SysInfo Data", .Read = FB_Address_Read}
Definition at line 41 of file sysinfo.cpp.
sysinfo_fb_height
FileSystemOpeations FileSystem::sysinfo_fb_height = {.Name = "SysInfo Data", .Read = FB_Height_Read}
Definition at line 57 of file sysinfo.cpp.
sysinfo_fb_ppsl
FileSystemOpeations FileSystem::sysinfo_fb_ppsl = {.Name = "SysInfo Data", .Read = FB_PixelsPerScanLine_Read}
Definition at line 65 of file sysinfo.cpp.
sysinfo_fb_size
FileSystemOpeations FileSystem::sysinfo_fb_size = {.Name = "SysInfo Data", .Read = FB_Size_Read}
Definition at line 73 of file sysinfo.cpp.
sysinfo_fb_width
FileSystemOpeations FileSystem::sysinfo_fb_width = {.Name = "SysInfo Data", .Read = FB_Width_Read}
Definition at line 49 of file sysinfo.cpp.
SysInfoNodeIndexNodeCount
uint64_t FileSystem::SysInfoNodeIndexNodeCount = 0 static
Definition at line 12 of file sysinfo.cpp.
Referenced by FileSystem::SysInfo::AddInfo().
SysInfoRootNode
FileSystemNode* FileSystem::SysInfoRootNode = nullptr
Definition at line 11 of file sysinfo.cpp.
Referenced by FileSystem::SysInfo::AddInfo(), and FileSystem::SysInfo::SysInfo().
ustar
FileSystemOpeations FileSystem::ustar
Initial value:
= {
        .Name = "ustar",
        .Read = USTAR_Read,
    }
Definition at line 18 of file ustar.cpp.
Referenced by FileSystem::USTAR::USTAR().
zero
FileSystemOpeations FileSystem::zero
Initial value:
= {
        .Name = "Zero",
        .Read = Zero_Read,
        .Write = Zero_Write}
Definition at line 13 of file zero.cpp.
Referenced by FileSystem::Zero::Zero().