Fennix Project: kernel/interrupts/pic.h File Reference
pic.h File Reference
#include <types.h>
Macros
#define PIC1 0x20 /* IO base address for master PIC */
#define PIC2 0xA0 /* IO base address for slave PIC */
#define PIC1_COMMAND PIC1
#define PIC1_DATA (PIC1 + 1)
#define PIC2_COMMAND PIC2
#define PIC2_DATA (PIC2 + 1)
#define PIC_EOI 0x20 /* End-of-interrupt command code */
#define ICW1_ICW4 0x01 /* ICW4 (not) needed */
#define ICW1_SINGLE 0x02 /* Single (cascade) mode */
#define ICW1_INTERVAL4 0x04 /* Call address interval 4 (8) */
#define ICW1_LEVEL 0x08 /* Level triggered (edge) mode */
#define ICW1_INIT 0x10 /* Initialization - required! */
#define ICW4_8086 0x01 /* 8086/88 (MCS-80/85) mode */
#define ICW4_AUTO 0x02 /* Auto (normal) EOI */
#define ICW4_BUF_SLAVE 0x08 /* Buffered mode/slave */
#define ICW4_BUF_MASTER 0x0C /* Buffered mode/master */
#define ICW4_SFNM 0x10 /* Special fully nested (not) */
Functions
EXTERNC void PIC_disable ()
EXTERNC void PIC_sendEOI (unsigned char irq)
void PIC_remap (int offset1, int offset2)
void IRQ_set_mask (unsigned char IRQline)
void IRQ_clear_mask (unsigned char IRQline)
Macro Definition Documentation
ICW1_ICW4
#define ICW1_ICW4 0x01 /* ICW4 (not) needed */
Definition at line 11 of file pic.h.
ICW1_INIT
#define ICW1_INIT 0x10 /* Initialization - required! */
Definition at line 15 of file pic.h.
ICW1_INTERVAL4
#define ICW1_INTERVAL4 0x04 /* Call address interval 4 (8) */
Definition at line 13 of file pic.h.
ICW1_LEVEL
#define ICW1_LEVEL 0x08 /* Level triggered (edge) mode */
Definition at line 14 of file pic.h.
ICW1_SINGLE
#define ICW1_SINGLE 0x02 /* Single (cascade) mode */
Definition at line 12 of file pic.h.
ICW4_8086
#define ICW4_8086 0x01 /* 8086/88 (MCS-80/85) mode */
Definition at line 17 of file pic.h.
ICW4_AUTO
#define ICW4_AUTO 0x02 /* Auto (normal) EOI */
Definition at line 18 of file pic.h.
ICW4_BUF_MASTER
#define ICW4_BUF_MASTER 0x0C /* Buffered mode/master */
Definition at line 20 of file pic.h.
ICW4_BUF_SLAVE
#define ICW4_BUF_SLAVE 0x08 /* Buffered mode/slave */
Definition at line 19 of file pic.h.
ICW4_SFNM
#define ICW4_SFNM 0x10 /* Special fully nested (not) */
Definition at line 21 of file pic.h.
PIC1
#define PIC1 0x20 /* IO base address for master PIC */
Definition at line 3 of file pic.h.
PIC1_COMMAND
#define PIC1_COMMAND PIC1
Definition at line 5 of file pic.h.
PIC1_DATA
#define PIC1_DATA (PIC1 + 1)
Definition at line 6 of file pic.h.
PIC2
#define PIC2 0xA0 /* IO base address for slave PIC */
Definition at line 4 of file pic.h.
PIC2_COMMAND
#define PIC2_COMMAND PIC2
Definition at line 7 of file pic.h.
PIC2_DATA
#define PIC2_DATA (PIC2 + 1)
Definition at line 8 of file pic.h.
PIC_EOI
#define PIC_EOI 0x20 /* End-of-interrupt command code */
Definition at line 9 of file pic.h.
Function Documentation
IRQ_clear_mask()
void IRQ_clear_mask (unsigned char IRQline)
Definition at line 94 of file PIC.c.
 {
     uint16_t port;
     uint8_t value;
     if (IRQline < 8)
         port = PIC1_DATA;
     else
     {
         port = PIC2_DATA;
         IRQline -= 8;
     }
     value = inb(port) & ~(1 << IRQline);
     outb(port, value);
 }
References inb, outb, PIC1_DATA, and PIC2_DATA.
IRQ_set_mask()
void IRQ_set_mask (unsigned char IRQline)
Definition at line 79 of file PIC.c.
 {
     uint16_t port;
     uint8_t value;
     if (IRQline < 8)
         port = PIC1_DATA;
     else
     {
         port = PIC2_DATA;
         IRQline -= 8;
     }
     value = inb(port) | (1 << IRQline);
     outb(port, value);
 }
References inb, outb, PIC1_DATA, and PIC2_DATA.
Referenced by PIC_disable().
PIC_disable()
EXTERNC void PIC_disable ()
Definition at line 11 of file PIC.c.
 {
     debug("Disabling PIC...");
     // set PIC to one-shot mode
     outb(PIT_CMD, 0x28);
     IOWait();
     outb(PIT_COUNTER0, CMD_MODE0);
     IOWait();
     // make sure all IRQs are masked
     IRQ_set_mask(0);
     IRQ_set_mask(1);
     IRQ_set_mask(2);
     IRQ_set_mask(3);
     IRQ_set_mask(4);
     IRQ_set_mask(5);
     IRQ_set_mask(6);
     IRQ_set_mask(7);
     IRQ_set_mask(8);
     IRQ_set_mask(9);
     IRQ_set_mask(10);
     IRQ_set_mask(11);
     IRQ_set_mask(12);
     IRQ_set_mask(13);
     IRQ_set_mask(14);
     IRQ_set_mask(15);
     outb(PIC1_DATA, 0xff);
     IOWait();
     outb(PIC2_DATA, 0xff);
     IOWait();
 }
References CMD_MODE0, debug, IOWait(), IRQ_set_mask(), outb, PIC1_DATA, PIC2_DATA, PIT_CMD, and PIT_COUNTER0.
Referenced by APIC::APIC::APIC().
PIC_remap()
void PIC_remap (int offset1, int offset2)
Definition at line 49 of file PIC.c.
 {
     debug("Remmaping PIC... %#llx %#llx", offset1, offset2);
     unsigned char a1, a2;
     a1 = inb(PIC1_DATA);
     IOWait();
     a2 = inb(PIC2_DATA);
     debug("%#llx %#llx", a1, a2);
     IOWait();
     outb(PIC1_COMMAND, ICW1_INIT | ICW1_ICW4);
     IOWait();
     outb(PIC2_COMMAND, ICW1_INIT | ICW1_ICW4);
     IOWait();
     outb(PIC1_DATA, offset1);
     IOWait();
     outb(PIC2_DATA, offset2);
     IOWait();
     outb(PIC1_DATA, 4);
     IOWait();
     outb(PIC2_DATA, 2);
     IOWait();
     outb(PIC1_DATA, ICW4_8086);
     IOWait();
     outb(PIC2_DATA, ICW4_8086);
     IOWait();
     outb(PIC1_DATA, a1);
     IOWait();
     outb(PIC2_DATA, a2);
 }
References debug, ICW1_ICW4, ICW1_INIT, ICW4_8086, inb, IOWait(), outb, PIC1_COMMAND, PIC1_DATA, PIC2_COMMAND, and PIC2_DATA.
Referenced by init_idt().
PIC_sendEOI()
EXTERNC void PIC_sendEOI (unsigned char irq)
Definition at line 42 of file PIC.c.
 {
     if (irq >= 40)
         outb(PIC2_COMMAND, PIC_EOI);
     outb(PIC1_COMMAND, PIC_EOI);
 }
References outb, PIC1_COMMAND, PIC2_COMMAND, and PIC_EOI.
Referenced by EndOfInterrupt().