Fennix Project: kernel/PCI.cpp File Reference
PCI.cpp File Reference
#include "pci.h"
#include <heap.h>
#include <string.h>
#include "drivers/serial.h"
#include <debug.h>
#include <bootscreen.h>
Namespaces
PCI
Functions
void PCI::EnumerateFunction (uint64_t DeviceAddress, uint64_t Function)
void PCI::EnumerateDevice (uint64_t BusAddress, uint64_t Device)
void PCI::EnumerateBus (uint64_t BaseAddress, uint64_t Bus)
void PCI::EnumeratePCI (ACPI::ACPI::MCFGHeader *MCFG)
Vector< PCIDeviceHeader * > PCI::FindPCIDevice (uint8_t Class, uint8_t Subclass, uint8_t ProgIF)
void init_pci ()
Variables
Vector< PCI::PCIDeviceHeader * > Devices
Function Documentation
init_pci()
void init_pci ()
Definition at line 102 of file PCI.cpp.
 {
     debug("%#llx", acpi->MCFG);
     if (acpi->MCFG != NULL)
     {
         PCI::EnumeratePCI(acpi->MCFG);
     }
     else
     {
         err("No PCI support!"); // TODO: add legacy support if MCFG is not available
     }
     BS->IncreaseProgres();
 }
References acpi, BS, debug, PCI::EnumeratePCI(), err, BootScreen::Screen::IncreaseProgres(), and ACPI::ACPI::MCFG.
Referenced by KernelInit().
Variable Documentation
Devices
Vector<PCI::PCIDeviceHeader *> Devices
Definition at line 10 of file PCI.cpp.
Referenced by PCI::EnumerateFunction(), and PCI::FindPCIDevice().