Fennix Project: kernel/arch/aarch64/cpu/cpuid.h File Reference
cpuid.h File Reference
#include <types.h>
#include <cpuid.h>
Functions
EXTERNC bool cpu_feature (enum CPU_FEATURE feature)
Function Documentation
cpu_feature()
EXTERNC bool cpu_feature (enum CPU_FEATURE feature)
Definition at line 6 of file CPUID.c.
 {
     uint32_t rax, rbx, rcx, rdx;
     cpuid(0x01, &rax, &rbx, &rcx, &rdx);
     if (rdx & feature || rcx & feature)
         return true;
     return false;
 }
Referenced by apictimer_read_counter(), CheckSystemRequirements(), KernelInit(), and TSC_sleep().