Fennix Project: kernel/mem/liballoc/liballoc.h File Reference
liballoc.h File Reference
#include <types.h>
Data Structures
struct boundary_tag
Functions
void * liballoc_malloc (size_t)
void * liballoc_realloc (void *, size_t)
void * liballoc_calloc (size_t, size_t)
void liballoc_free (void *)
Variables
struct boundary_tag __attribute__
Data Structure Documentation
boundary_tag
struct boundary_tag
This is a boundary tag which is prepended to the page or section of a page which we have allocated. It is used to identify valid memory blocks that the application is trying to free.
Definition at line 15 of file liballoc.h.
Data Fields
int index
unsigned int magic
struct boundary_tag * next
struct boundary_tag * prev
unsigned int real_size
unsigned int size
struct boundary_tag * split_left
struct boundary_tag * split_right
Function Documentation
liballoc_calloc()
void* liballoc_calloc (size_t , size_t)
Definition at line 473 of file liballoc.c.
 {
     int real_size;
     void *p;
     real_size = nobj * size;
     p = liballoc_malloc(real_size);
     liballoc_memset(p, 0, real_size);
     return p;
 }
References liballoc_malloc(), liballoc_memset(), boundary_tag::real_size, and boundary_tag::size.
Referenced by HeapCalloc().
liballoc_free()
void liballoc_free (void *)
Definition at line 385 of file liballoc.c.
 {
     int index;
     struct boundary_tag *tag;
     if (ptr == NULL)
         return;
     LOCK(liballoc_lock);
     tag = (struct boundary_tag *)((unsigned int)ptr - sizeof(struct boundary_tag));
     if (tag->magic != LIBALLOC_MAGIC)
     {
         UNLOCK(liballoc_lock); // release the lock
         return;
     }
 #ifdef DEBUG
     l_inuse -= tag->size;
     printf("liballoc_free: %p, %i, %i\n", ptr, (int)l_inuse / 1024, (int)l_allocated / 1024);
 #endif
     // MELT LEFT...
     while ((tag->split_left != NULL) && (tag->split_left->index >= 0))
     {
 #ifdef DEBUG
         printf("Melting tag left into available memory. Left was %i, becomes %i (%i)\n", tag->split_left->real_size, tag->split_left->real_size + tag->real_size, tag->split_left->real_size);
 #endif
         tag = melt_left(tag);
         remove_tag(tag);
     }
     // MELT RIGHT...
     while ((tag->split_right != NULL) && (tag->split_right->index >= 0))
     {
 #ifdef DEBUG
         printf("Melting tag right into available memory. This was was %i, becomes %i (%i)\n", tag->real_size, tag->split_right->real_size + tag->real_size, tag->split_right->real_size);
 #endif
         tag = absorb_right(tag);
     }
     // Where is it going back to?
     index = getexp(tag->real_size - sizeof(struct boundary_tag));
     if (index < MINEXP)
         index = MINEXP;
     // A whole, empty block?
     if ((tag->split_left == NULL) && (tag->split_right == NULL))
     {
         if (l_completePages[index] == MAXCOMPLETE)
         {
             // Too many standing by to keep. Free this one.
             unsigned int pages = tag->real_size / l_pageSize;
             if ((tag->real_size % l_pageSize) != 0)
                 pages += 1;
             if (pages < l_pageCount)
                 pages = l_pageCount;
             FreePages(tag, pages);
 #ifdef DEBUG
             l_allocated -= pages * l_pageSize;
             printf("Resource freeing %p of %i pages\n", tag, pages);
             dump_array();
 #endif
             UNLOCK(liballoc_lock);
             return;
         }
         l_completePages[index] += 1; // Increase the count of complete pages.
     }
     // ..........
     insert_tag(tag, index);
 #ifdef DEBUG
     printf("Returning tag with %i bytes (requested %i bytes), which has exponent: %i\n", tag->real_size, tag->size, index);
     dump_array();
 #endif
     UNLOCK(liballoc_lock);
 }
References absorb_right(), FreePages(), getexp(), boundary_tag::index, insert_tag(), l_allocated, l_completePages, l_inuse, l_pageCount, l_pageSize, LIBALLOC_MAGIC, LOCK, boundary_tag::magic, MAXCOMPLETE, melt_left(), MINEXP, printf, boundary_tag::real_size, remove_tag(), boundary_tag::size, boundary_tag::split_left, boundary_tag::split_right, and UNLOCK.
Referenced by HeapFree(), and liballoc_realloc().
liballoc_malloc()
void* liballoc_malloc (size_t)
Definition at line 281 of file liballoc.c.
 {
     int index;
     void *ptr;
     struct boundary_tag *tag = NULL;
     LOCK(liballoc_lock);
     if (l_initialized == 0)
     {
 #ifdef DEBUG
         printf("%s\n", "liballoc initializing.");
 #endif
         for (index = 0; index < MAXEXP; index++)
         {
             l_freePages[index] = NULL;
             l_completePages[index] = 0;
         }
         l_initialized = 1;
     }
     index = getexp(size) + MODE;
     if (index < MINEXP)
         index = MINEXP;
     // Find one big enough.
     tag = l_freePages[index]; // Start at the front of the list.
     while (tag != NULL)
     {
         // If there's enough space in this tag.
         if ((tag->real_size - sizeof(struct boundary_tag)) >= (size + sizeof(struct boundary_tag)))
         {
 #ifdef DEBUG
             printf("Tag search found %li >= %li\n", (tag->real_size - sizeof(struct boundary_tag)), (size + sizeof(struct boundary_tag)));
 #endif
             break;
         }
         tag = tag->next;
     }
     // No page found. Make one.
     if (tag == NULL)
     {
         if ((tag = allocate_new_tag(size)) == NULL)
         {
             UNLOCK(liballoc_lock);
             return NULL;
         }
         index = getexp(tag->real_size - sizeof(struct boundary_tag));
     }
     else
     {
         remove_tag(tag);
         if ((tag->split_left == NULL) && (tag->split_right == NULL))
             l_completePages[index] -= 1;
     }
     // We have a liballoc_free page.  Remove it from the liballoc_free pages list.
     tag->size = size;
     // Removed... see if we can re-use the excess space.
 #ifdef DEBUG
     printf("Found tag with %lx bytes available (requested %li bytes, leaving %li), which has exponent: %i (%i bytes)\n", tag->real_size - sizeof(struct boundary_tag), size, tag->real_size - size - sizeof(struct boundary_tag), index, 1 << index);
 #endif
     unsigned int remainder = tag->real_size - size - sizeof(struct boundary_tag) * 2; // Support a new tag + remainder
     if (((int)(remainder) > 0) /*&& ( (tag->real_size - remainder) >= (1<<MINEXP))*/)
     {
         int childIndex = getexp(remainder);
         if (childIndex >= 0)
         {
 #ifdef DEBUG
             printf("Seems to be splittable: %i >= 2^%i .. %i\n", remainder, childIndex, (1 << childIndex));
 #endif
             struct boundary_tag *new_tag = split_tag(tag);
             new_tag = new_tag; // Get around the compiler warning about unused variables.
 #ifdef DEBUG
             printf("Old tag has become %i bytes, new tag is now %i bytes (%i exp)\n", tag->real_size, new_tag->real_size, new_tag->index);
 #endif
         }
     }
     ptr = (void *)((unsigned int)tag + sizeof(struct boundary_tag));
 #ifdef DEBUG
     l_inuse += size;
     printf("liballoc_malloc: %p,  %i, %i\n", ptr, (int)l_inuse / 1024, (int)l_allocated / 1024);
     dump_array();
 #endif
     UNLOCK(liballoc_lock);
     return ptr;
 }
References allocate_new_tag(), getexp(), boundary_tag::index, l_allocated, l_completePages, l_freePages, l_initialized, l_inuse, LOCK, MAXEXP, MINEXP, MODE, boundary_tag::next, printf, boundary_tag::real_size, remove_tag(), boundary_tag::size, boundary_tag::split_left, boundary_tag::split_right, split_tag(), and UNLOCK.
Referenced by HeapMalloc(), liballoc_calloc(), and liballoc_realloc().
liballoc_realloc()
void* liballoc_realloc (void * , size_t)
Definition at line 487 of file liballoc.c.
 {
     void *ptr;
     struct boundary_tag *tag;
     int real_size;
     if (size == 0)
     {
         liballoc_free(p);
         return NULL;
     }
     if (p == NULL)
         return liballoc_malloc(size);
     // if (liballoc_lock != NULL)
     LOCK(liballoc_lock); // lockit
     tag = (struct boundary_tag *)((unsigned int)p - sizeof(struct boundary_tag));
     real_size = tag->size;
     // if (liballoc_unlock != NULL)
     UNLOCK(liballoc_lock);
     if (real_size > size)
         real_size = size;
     ptr = liballoc_malloc(size);
     liballoc_memcpy(ptr, p, real_size);
     liballoc_free(p);
     return ptr;
 }
References liballoc_free(), liballoc_malloc(), liballoc_memcpy(), LOCK, boundary_tag::real_size, boundary_tag::size, and UNLOCK.
Referenced by HeapRealloc().
Variable Documentation
__attribute__
struct boundary_tag __attribute__