Fennix Project: libc/include/string.h File Reference
string.h File Reference
#include <stdint.h>
#include <stddef.h>
#include <cdefs.h>
Functions
E void * memcpy (void *__restrict__ dest, const void *__restrict__ src, size_t n)
E void * memset (void *dest, int data, size_t nbytes)
E void * memmove (void *dest, const void *src, size_t n)
E int memcmp (const void *vl, const void *vr, size_t n)
E int strncmp (const char *s1, const char *s2, long unsigned int n)
E long unsigned strlen (const char s[])
E char * strcat (char *destination, const char *source)
E char * strcpy (char *destination, const char *source)
E char * strncpy (char *destination, const char *source, unsigned long num)
E int strcmp (const char *l, const char *r)
E char * strstr (const char *haystack, const char *needle)
E char * strdup (const char *String)
E char * strchr (const char *String, int Char)
E char * strrchr (const char *String, int Char)
E int strncasecmp (const char *lhs, const char *rhs, long unsigned int Count)
E int strcasecmp (const char *lhs, const char *rhs)
E int isdigit (int Char)
E int isspace (int Char)
Function Documentation
isdigit()
E int isdigit (int Char)
Definition at line 139 of file String.c.
 {
     return c >= '0' && c <= '9';
 }
isspace()
E int isspace (int Char)
Definition at line 144 of file String.c.
 {
     return c == ' ' || c == '\t' || c == '\r' || c == '\n' || c == '\f' || c == '\v';
 }
Referenced by isempty().
memcmp()
E int memcmp (const void * vl, const void * vr, size_t n)
Definition at line 39 of file String.c.
 {
     const unsigned char *l = vl, *r = vr;
     for (; n && *l == *r; n--, l++, r++)
         ;
     return n ? *l - *r : 0;
 }
memcpy()
E void* memcpy (void *__restrict__ dest, const void *__restrict__ src, size_t n)
Definition at line 5 of file String.c.
 {
     unsigned char *d = (unsigned char *)dest;
     const unsigned char *c = (const unsigned char *)src;
     for (size_t i = 0; i < n; i++)
         d[i] = c[i];
     return dest;
 }
memmove()
E void* memmove (void * dest, const void * src, size_t n)
Definition at line 22 of file String.c.
 {
     unsigned char *dst = (unsigned char *)dest;
     const unsigned char *srcc = (const unsigned char *)src;
     if (dst < srcc)
     {
         for (size_t i = 0; i < n; i++)
             dst[i] = srcc[i];
     }
     else
     {
         for (size_t i = n; i != 0; i--)
             dst[i - 1] = srcc[i - 1];
     }
     return dest;
 }
memset()
E void* memset (void * dest, int data, size_t nbytes)
Definition at line 14 of file String.c.
 {
     unsigned char *buf = (unsigned char *)dest;
     for (size_t i = 0; i < nbytes; i++)
         buf[i] = (unsigned char)data;
     return dest;
 }
strcasecmp()
E int strcasecmp (const char * lhs, const char * rhs)
Definition at line 145 of file string.c.
 {
     while (*lhs && (tolower(*lhs) == tolower(*rhs)))
     {
         lhs++;
         rhs++;
     }
     int lc = tolower(*lhs);
     int rc = tolower(*rhs);
     return lc - rc;
 }
References tolower.
strcat()
E char* strcat (char * destination, const char * source)
Definition at line 68 of file String.c.
 {
     if ((destination == NULL) && (source == NULL))
         return NULL;
     char *start = destination;
     while (*start != '\0')
     {
         start++;
     }
     while (*source != '\0')
     {
         *start++ = *source++;
     }
     *start = '\0';
     return destination;
 }
strchr()
E char* strchr (const char * String, int Char)
Definition at line 105 of file string.c.
 {
     while (*String != (char)Char)
     {
         if (!*String++)
             return 0;
     }
     return (char *)String;
 }
Referenced by cag_option_find_by_letter(), and cwk_path_is_string_equal().
strcmp()
E int strcmp (const char * l, const char * r)
Definition at line 115 of file String.c.
 {
     for (; *l == *r && *l; l++, r++)
         ;
     return *(unsigned char *)l - *(unsigned char *)r;
 }
strcpy()
E char* strcpy (char * destination, const char * source)
Definition at line 85 of file String.c.
 {
     if (destination == NULL)
         return NULL;
     char *ptr = destination;
     while (*source != '\0')
     {
         *destination = *source;
         destination++;
         source++;
     }
     *destination = '\0';
     return ptr;
 }
Referenced by strdup().
strdup()
E char* strdup (const char * String)
Definition at line 98 of file string.c.
 {
     char *OutBuffer = malloc(strlen((char *)String) + 1);
     strcpy(OutBuffer, String);
     return OutBuffer;
 }
References malloc(), strcpy(), and strlen().
strlen()
E long unsigned strlen (const char s[])
Definition at line 60 of file String.c.
 {
     long unsigned i = 0;
     while (s[i] != '\0')
         ++i;
     return i;
 }
Referenced by isempty(), and strdup().
strncasecmp()
E int strncasecmp (const char * lhs, const char * rhs, long unsigned int Count)
Definition at line 126 of file string.c.
 {
     while (Count--)
     {
         if (*lhs == 0 || *rhs == 0)
         {
             return *(unsigned char *)(lhs) - *(unsigned char *)(rhs);
         }
         if (tolower(*lhs) != tolower(*rhs))
         {
             return *(unsigned char *)(lhs) - *(unsigned char *)(rhs);
         }
         lhs++;
         rhs++;
     }
     return 0;
 }
References tolower.
strncmp()
E int strncmp (const char * s1, const char * s2, long unsigned int n)
strncpy()
E char* strncpy (char * destination, const char * source, unsigned long num)
Definition at line 100 of file String.c.
 {
     if (destination == NULL)
         return NULL;
     char *ptr = destination;
     while (*source && num--)
     {
         *destination = *source;
         destination++;
         source++;
     }
     *destination = '\0';
     return ptr;
 }
strrchr()
E char* strrchr (const char * String, int Char)
Definition at line 115 of file string.c.
 {
     char *ret = 0;
     do
     {
         if (*String == (char)Char)
             ret = (char *)String;
     } while (*String++);
     return ret;
 }
strstr()
E char* strstr (const char * haystack, const char * needle)
Definition at line 122 of file String.c.
 {
     const char *a = haystack, *b = needle;
     while (1)
     {
         if (!*b)
             return (char *)haystack;
         if (!*a)
             return NULL;
         if (*a++ != *b++)
         {
             a = ++haystack;
             b = needle;
         }
     }
 }