Fennix Project: AMDPCNET::NetworkInterfaceController Class Reference
AMDPCNET::NetworkInterfaceController Class Reference
#include <AMDPCNET.hpp>
Data Structures
struct BARData
Public Member Functions
MediaAccessControl GetMAC ()
InternetProtocol4 GetIP ()
void SetIP (InternetProtocol4 IP)
NetworkInterfaceController (PCI::PCIDeviceHeader *PCIBaseAddress)
~NetworkInterfaceController ()
void Send (uint8_t *Data, uint64_t Length)
void Receive ()
void HandleInterrupt ()
Public Member Functions inherited from NetworkInterfaceManager::DeviceInterface
virtual void Send (void *Data, uint64_t Length)
Private Member Functions
void WriteRAP32 (uint32_t Value)
void WriteRAP16 (uint16_t Value)
uint32_t ReadCSR32 (uint32_t CSR)
uint16_t ReadCSR16 (uint16_t CSR)
void WriteCSR32 (uint32_t CSR, uint32_t Value)
void WriteCSR16 (uint16_t CSR, uint16_t Value)
Private Attributes
char * RXBuffer
int TXCurrent
InternetProtocol4 IP
uint32_t CurrentPacket
BARData BAR
Additional Inherited Members
Data Fields inherited from NetworkInterfaceManager::DeviceInterface
char Name [128]
Device interface name.
uint64_t ID
Device interface index.
MediaAccessControl MAC
Device interface MAC address (Big-endian)
InternetProtocol4 IP
Device interface IP address (Big-endian)
Detailed Description
Definition at line 10 of file AMDPCNET.hpp.
Data Structure Documentation
AMDPCNET::NetworkInterfaceController::BARData
struct AMDPCNET::NetworkInterfaceController::BARData
Definition at line 13 of file AMDPCNET.hpp.
Data Fields
uint16_t IOBase
uint32_t MemoryBase
uint8_t Type
Constructor & Destructor Documentation
NetworkInterfaceController()
AMDPCNET::NetworkInterfaceController::NetworkInterfaceController (PCI::PCIDeviceHeader * PCIBaseAddress)
Definition at line 58 of file AMDPCNET.cpp.
                                                                                              : DriverInterrupts::Register(((PCI::PCIHeader0 *)PCIBaseAddress)->InterruptLine + IRQ0)
     {
         if (PCIBaseAddress->VendorID != 0x1022 && PCIBaseAddress->DeviceID != 0x2000 && PCIBaseAddress->DeviceID != 0x2001)
         {
             netdbg("Not a AMD PCNET network card");
             return;
         }
         if (PCIBaseAddress->DeviceID == 0x2001)
             warn("This AMD PCNET is not supported. (Maybe it works but there is no guarantee)");
         netdbg("Found %s network card", PCI::GetDeviceName(PCIBaseAddress->VendorID, PCIBaseAddress->DeviceID));
         memcpy(this->Name, "AMD PCNET Network Driver", sizeof(this->Name));
         uint32_t PCIBAR = ((PCI::PCIHeader0 *)PCIBaseAddress)->BAR0;
         BAR.Type = PCIBAR & 1;
         BAR.IOBase = PCIBAR & (~3);
         BAR.MemoryBase = PCIBAR & (~15);
         netdbg("BAR Type: %d - BAR IOBase: %#x - BAR MemoryBase: %#x", BAR.Type, BAR.IOBase, BAR.MemoryBase);
         this->MAC = this->GetMAC();
     }
References BAR, PCI::GetDeviceName(), GetMAC(), AMDPCNET::NetworkInterfaceController::BARData::IOBase, NetworkInterfaceManager::DeviceInterface::MAC, memcpy(), AMDPCNET::NetworkInterfaceController::BARData::MemoryBase, NetworkInterfaceManager::DeviceInterface::Name, netdbg, AMDPCNET::NetworkInterfaceController::BARData::Type, and warn.
~NetworkInterfaceController()
AMDPCNET::NetworkInterfaceController::~NetworkInterfaceController ()
Definition at line 80 of file AMDPCNET.cpp.
     {
     }
Member Function Documentation
GetIP()
InternetProtocol4 AMDPCNET::NetworkInterfaceController::GetIP ()
Definition at line 48 of file AMDPCNET.cpp.
     {
         return IP;
     }
References IP.
GetMAC()
MediaAccessControl AMDPCNET::NetworkInterfaceController::GetMAC ()
Definition at line 43 of file AMDPCNET.cpp.
     {
         return MediaAccessControl();
     }
Referenced by NetworkInterfaceController().
HandleInterrupt()
void AMDPCNET::NetworkInterfaceController::HandleInterrupt ()
Definition at line 92 of file AMDPCNET.cpp.
     {
     }
ReadCSR16()
uint16_t AMDPCNET::NetworkInterfaceController::ReadCSR16 (uint16_t CSR) private
Definition at line 25 of file AMDPCNET.cpp.
     {
         WriteRAP32(CSR);
         return inportw(BAR.IOBase + 0x10);
     }
References BAR, inportw(), AMDPCNET::NetworkInterfaceController::BARData::IOBase, and WriteRAP32().
ReadCSR32()
uint32_t AMDPCNET::NetworkInterfaceController::ReadCSR32 (uint32_t CSR) private
Definition at line 19 of file AMDPCNET.cpp.
     {
         WriteRAP32(CSR);
         return inportl(BAR.IOBase + 0x10);
     }
References BAR, inportl(), AMDPCNET::NetworkInterfaceController::BARData::IOBase, and WriteRAP32().
Receive()
void AMDPCNET::NetworkInterfaceController::Receive () virtual
Reimplemented from NetworkInterfaceManager::DeviceInterface.
Definition at line 88 of file AMDPCNET.cpp.
     {
     }
Send()
void AMDPCNET::NetworkInterfaceController::Send (uint8_t * Data, uint64_t Length)
Definition at line 84 of file AMDPCNET.cpp.
     {
     }
SetIP()
void AMDPCNET::NetworkInterfaceController::SetIP (InternetProtocol4 IP)
Definition at line 53 of file AMDPCNET.cpp.
     {
         this->IP = IP;
     }
References IP.
WriteCSR16()
void AMDPCNET::NetworkInterfaceController::WriteCSR16 (uint16_t CSR, uint16_t Value) private
Definition at line 37 of file AMDPCNET.cpp.
     {
         WriteRAP16(CSR);
         outportw(BAR.IOBase + 0x10, Value);
     }
References BAR, AMDPCNET::NetworkInterfaceController::BARData::IOBase, outportw(), and WriteRAP16().
WriteCSR32()
void AMDPCNET::NetworkInterfaceController::WriteCSR32 (uint32_t CSR, uint32_t Value) private
Definition at line 31 of file AMDPCNET.cpp.
     {
         WriteRAP32(CSR);
         outportl(BAR.IOBase + 0x10, Value);
     }
References BAR, AMDPCNET::NetworkInterfaceController::BARData::IOBase, outportl(), and WriteRAP32().
WriteRAP16()
void AMDPCNET::NetworkInterfaceController::WriteRAP16 (uint16_t Value) private
Definition at line 14 of file AMDPCNET.cpp.
     {
         outportw(BAR.IOBase + 0x12, Value);
     }
References BAR, AMDPCNET::NetworkInterfaceController::BARData::IOBase, and outportw().
Referenced by WriteCSR16().
WriteRAP32()
void AMDPCNET::NetworkInterfaceController::WriteRAP32 (uint32_t Value) private
Definition at line 9 of file AMDPCNET.cpp.
     {
         outportl(BAR.IOBase + 0x14, Value);
     }
References BAR, AMDPCNET::NetworkInterfaceController::BARData::IOBase, and outportl().
Referenced by ReadCSR16(), ReadCSR32(), and WriteCSR32().
Field Documentation
BAR
BARData AMDPCNET::NetworkInterfaceController::BAR private
Definition at line 24 of file AMDPCNET.hpp.
Referenced by NetworkInterfaceController(), ReadCSR16(), ReadCSR32(), WriteCSR16(), WriteCSR32(), WriteRAP16(), and WriteRAP32().
CurrentPacket
uint32_t AMDPCNET::NetworkInterfaceController::CurrentPacket private
Definition at line 23 of file AMDPCNET.hpp.
IP
InternetProtocol4 AMDPCNET::NetworkInterfaceController::IP private
Definition at line 22 of file AMDPCNET.hpp.
Referenced by GetIP(), and SetIP().
RXBuffer
char* AMDPCNET::NetworkInterfaceController::RXBuffer private
Definition at line 20 of file AMDPCNET.hpp.
TXCurrent
int AMDPCNET::NetworkInterfaceController::TXCurrent private
Definition at line 21 of file AMDPCNET.hpp.
The documentation for this class was generated from the following files:
kernel/drivers/network/AMDPCNET/AMDPCNET.hpp
kernel/drivers/network/AMDPCNET/AMDPCNET.cpp