Fennix Project: userspace/apps/system/wm/main.cpp File Reference
main.cpp File Reference
#include <syscalls.h>
Data Structures
struct vbe
struct ms
struct scren
Macros
#define rgbWhite 0xFFFFFF
Functions
void PutRect (int X, int Y, int Width, int Height, int RGB)
void PutLine (int X1, int Y1, int X2, int Y2, int RGB)
void memcpy (uint64_t Dest, uint64_t Source, int Size)
void * alloc (uint64_t size)
void PaintDesktop ()
void PaintCursor ()
void ScreenRefreshProc ()
void PutPixel (int x, int y, int color)
void InitScreen ()
int main (int argc, char *argv[])
Variables
ms Mouse
vbe VbeModeInfoBlock
scren Screen
uint64_t ScreenZBuffer
uint64_t ScreenBufferSize
void * ScreenBackBuffer
char g_ScreenBuffer [9999]
Data Structure Documentation
vbe
struct vbe
Definition at line 13 of file main.cpp.
Data Fields
uint64_t BitsPerPixel
uint64_t BytesPerScanLine
uint64_t VideoBaseAddr
uint64_t XResolution
uint64_t YResolution
ms
struct ms
Definition at line 22 of file main.cpp.
Data Fields
int X
int Y
scren
struct scren
Definition at line 27 of file main.cpp.
Data Fields
int Height
int Width
Macro Definition Documentation
rgbWhite
#define rgbWhite 0xFFFFFF
Definition at line 11 of file main.cpp.
Function Documentation
alloc()
void* alloc (uint64_t size)
Definition at line 9 of file main.cpp.
 { return 0; }
Referenced by InitScreen().
InitScreen()
void InitScreen ()
Definition at line 107 of file main.cpp.
 {
     ScreenBufferSize = VbeModeInfoBlock.XResolution * VbeModeInfoBlock.YResolution * (VbeModeInfoBlock.BitsPerPixel / 8);
     ScreenBackBuffer = alloc(ScreenBufferSize);
     syscall_createThread((uint64_t)ScreenRefreshProc, 0, 0);
 }
References alloc(), vbe::BitsPerPixel, ScreenBackBuffer, ScreenBufferSize, ScreenRefreshProc(), VbeModeInfoBlock, vbe::XResolution, and vbe::YResolution.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 114 of file main.cpp.
 {
     PutRect(0, 0, Screen.Width, Screen.Height, 0x282828);
     /* ... show login screen and wait for user input ... */
     InitScreen();
     syscall_createProcess((char *)"/system/fesktop", 0, 0);
     while (1)
         ;
     return 0;
 }
References scren::Height, InitScreen(), PutRect(), Screen, and scren::Width.
memcpy()
void memcpy (uint64_t Dest, uint64_t Source, int Size)
Definition at line 7 of file main.cpp.
 {}
Referenced by ScreenRefreshProc().
PaintCursor()
void PaintCursor ()
Definition at line 53 of file main.cpp.
 {
     // just make a white box at the cursor position:
     PutRect(Mouse.X, Mouse.Y, 5, 5, rgbWhite);
 }
References Mouse, PutRect(), rgbWhite, ms::X, and ms::Y.
Referenced by ScreenRefreshProc().
PaintDesktop()
void PaintDesktop ()
Definition at line 42 of file main.cpp.
 {
     // fill the background of the desktop
     PutRect(0, 0, Screen.Width, Screen.Height, 0xc0c0c0c0);
     // now tell every child window to paint itself:
     // for (int i = 0; i < ChildWindows.size(); i++)
     // {
     //     ChildWindows[i].Paint();
     // }
 }
References scren::Height, PutRect(), Screen, and scren::Width.
Referenced by ScreenRefreshProc().
PutLine()
void PutLine (int X1, int Y1, int X2, int Y2, int RGB)
Definition at line 6 of file main.cpp.
 {}
PutPixel()
void PutPixel (int x, int y, int color)
Definition at line 77 of file main.cpp.
 {
     // do not write memory outside the screen buffer, check parameters against the VBE mode info
     if (x < 0 || x > VbeModeInfoBlock.XResolution || y < 0 || y > VbeModeInfoBlock.YResolution)
         return;
     if (x)
         x = (x * (VbeModeInfoBlock.BitsPerPixel >> 3));
     if (y)
         y = (y * VbeModeInfoBlock.BytesPerScanLine);
     char *cTemp;
     cTemp = &g_ScreenBuffer[x + y];
     cTemp[0] = color & 0xff;
     cTemp[1] = (color >> 8) & 0xff;
     cTemp[2] = (color >> 16) & 0xff;
 }
References vbe::BitsPerPixel, vbe::BytesPerScanLine, g_ScreenBuffer, VbeModeInfoBlock, vbe::XResolution, and vbe::YResolution.
PutRect()
void PutRect (int X, int Y, int Width, int Height, int RGB)
Definition at line 5 of file main.cpp.
 {}
Referenced by main(), PaintCursor(), and PaintDesktop().
ScreenRefreshProc()
void ScreenRefreshProc ()
Definition at line 59 of file main.cpp.
 {
     syscall_dbg(0x3F8, (char *)"WM: Screen Refresh Started\n");
     for (;;)
     {
         PaintDesktop(); // paints the desktop and all windows
         PaintCursor();  // finally paints the cursor so it's on top
 #if WAIT_FOR_VERTICAL_RETRACE
         while ((inportb(0x3DA) & 0x08))
             ;
         while (!(inportb(0x3DA) & 0x08))
             ;
 #endif
         memcpy(VbeModeInfoBlock.VideoBaseAddr, ScreenZBuffer, ScreenBufferSize);
     }
 }
References inportb(), memcpy(), PaintCursor(), PaintDesktop(), ScreenBufferSize, ScreenZBuffer, VbeModeInfoBlock, and vbe::VideoBaseAddr.
Referenced by InitScreen().
Variable Documentation
g_ScreenBuffer
char g_ScreenBuffer[9999]
Definition at line 40 of file main.cpp.
Referenced by PutPixel().
Mouse
ms Mouse
Definition at line 32 of file main.cpp.
Referenced by PaintCursor().
Screen
scren Screen
Definition at line 34 of file main.cpp.
Referenced by KernelInit(), main(), and PaintDesktop().
ScreenBackBuffer
void* ScreenBackBuffer
Definition at line 38 of file main.cpp.
Referenced by InitScreen().
ScreenBufferSize
uint64_t ScreenBufferSize
Definition at line 37 of file main.cpp.
Referenced by InitScreen(), and ScreenRefreshProc().
ScreenZBuffer
uint64_t ScreenZBuffer
Definition at line 36 of file main.cpp.
Referenced by ScreenRefreshProc().
VbeModeInfoBlock
vbe VbeModeInfoBlock
Definition at line 33 of file main.cpp.
Referenced by InitScreen(), PutPixel(), and ScreenRefreshProc().