Fennix Project: kernel/pci.h File Reference
pci.h File Reference
#include <types.h>
#include "cpu/acpi.hpp"
#include "kernel.h"
Data Structures
struct PCIDeviceHeader
struct PCIHeader0
Functions
EXTERNC void * FindTable (struct ACPIHeader *ACPIHeader, char *Signature)
EXTERNC void init_pci ()
Data Structure Documentation
PCIDeviceHeader
struct PCIDeviceHeader
Definition at line 100 of file pci.h.
Data Fields
uint8_t BIST
uint8_t CacheLineSize
uint8_t Class
uint16_t Command
uint16_t DeviceID
uint8_t HeaderType
uint8_t LatencyTimer
uint8_t ProgIF
uint8_t RevisionID
uint16_t Status
uint8_t Subclass
uint16_t VendorID
PCIHeader0
struct PCIHeader0
Definition at line 116 of file pci.h.
Data Fields
uint32_t BAR0
uint32_t BAR1
uint32_t BAR2
uint32_t BAR3
uint32_t BAR4
uint32_t BAR5
uint8_t CapabilitiesPtr
uint32_t CardbusCISPtr
uint32_t ExpansionROMBaseAddr
struct PCIDeviceHeader Header
uint8_t InterruptLine
uint8_t InterruptPin
uint8_t MaxLatency
uint8_t MinGrant
uint8_t Rsv0
uint16_t Rsv1
uint32_t Rsv2
uint16_t SubsystemID
uint16_t SubsystemVendorID
Function Documentation
FindTable()
EXTERNC void* FindTable (struct ACPIHeader * ACPIHeader, char * Signature)
init_pci()
EXTERNC void init_pci ()
Definition at line 111 of file PCI.cpp.
 {
     debug("%#llx", acpi->MCFG);
     if (acpi->MCFG != NULL)
     {
         PCI::EnumeratePCI(acpi->MCFG);
     }
     else
     {
         err("No PCI support!"); // TODO: add legacy support if MCFG is not available
     }
     BS->IncreaseProgres();
 }
References acpi, BS, debug, PCI::EnumeratePCI(), err, BootScreen::Screen::IncreaseProgres(), ACPI::ACPI::MCFG, and NULL.
Referenced by KernelInit().