Fennix Project: E1000::NetworkInterfaceController Class Reference
E1000::NetworkInterfaceController Class Reference
#include <E1000.hpp>
Data Structures
struct BARData
struct RXDescriptor
struct TXDescriptor
Public Member Functions
MediaAccessControl GetMAC ()
InternetProtocol4 GetIP ()
void SetIP (InternetProtocol4 IP)
NetworkInterfaceController (PCI::PCIDeviceHeader *PCIBaseAddress)
~NetworkInterfaceController ()
bool Start ()
void Send (void *Data, uint64_t Length)
void Receive ()
virtual void HandleInterrupt (TrapFrame *regs)
Private Types
enum REG {
CTRL = 0x0000, STATUS = 0x0008, EEPROM = 0x0014, CTRL_EXT = 0x0018,
IMASK = 0x00D0, RCTRL = 0x0100, RXDESCLO = 0x2800, RXDESCHI = 0x2804,
RXDESCLEN = 0x2808, RXDESCHEAD = 0x2810, RXDESCTAIL = 0x2818, TCTRL = 0x0400,
TXDESCLO = 0x3800, TXDESCHI = 0x3804, TXDESCLEN = 0x3808, TXDESCHEAD = 0x3810,
TXDESCTAIL = 0x3818, RDTR = 0x2820, RXDCTL = 0x3828, RADV = 0x282C,
RSRPD = 0x2C00, TIPG = 0x0410
}
enum ECTRL { SLU = 0x40 }
enum RTCL { RDMTS_HALF = (0 << 8), RDMTS_QUARTER = (1 << 8), RDMTS_EIGHTH = (2 << 8) }
enum RCTL {
EN = (1 << 1), SBP = (1 << 2), UPE = (1 << 3), MPE = (1 << 4),
LPE = (1 << 5), LBM_NONE = (0 << 6), LBM_PHY = (3 << 6), MO_36 = (0 << 12),
MO_35 = (1 << 12), MO_34 = (2 << 12), MO_32 = (3 << 12), BAM = (1 << 15),
VFE = (1 << 18), CFIEN = (1 << 19), CFI = (1 << 20), DPF = (1 << 22),
PMCF = (1 << 23), SECRC = (1 << 26), BSIZE_256 = (3 << 16), BSIZE_512 = (2 << 16),
BSIZE_1024 = (1 << 16), BSIZE_2048 = (0 << 16), BSIZE_4096 = ((3 << 16) | (1 << 25)), BSIZE_8192 = ((2 << 16) | (1 << 25)),
BSIZE_16384 = ((1 << 16) | (1 << 25))
}
enum CMD {
EOP = (1 << 0), IFCS = (1 << 1), IC = (1 << 2), RS = (1 << 3),
RPS = (1 << 4), VLE = (1 << 6), IDE = (1 << 7)
}
enum TCTL {
EN_ = (1 << 1), PSP = (1 << 3), CT_SHIFT = 4, COLD_SHIFT = 12,
SWXOFF = (1 << 22), RTLC = (1 << 24)
}
enum TSTA { DD = (1 << 0), EC = (1 << 1), LC = (1 << 2) }
enum LSTA { LSTA_TU = (1 << 3) }
Private Member Functions
struct E1000::NetworkInterfaceController::RXDescriptor __attribute__ ((packed))
struct E1000::NetworkInterfaceController::TXDescriptor __attribute__ ((packed))
void OutCMD (uint16_t Address, uint32_t Value)
uint32_t InCMD (uint16_t Address)
void StartLink ()
bool DetectEEPROM ()
uint32_t ReadEEPROM (uint8_t Address)
void rxinit ()
void txinit ()
Private Attributes
struct E1000::NetworkInterfaceController::BARData __attribute__
InternetProtocol4 IP
uint32_t CurrentPacket
BARData BAR
bool EEPROMAvailable
PCI::PCIDeviceHeader * PCIAddress
uint16_t RXCurrent
uint16_t TXCurrent
RXDescriptor * RXDescriptor [E1000_NUM_RX_DESC]
TXDescriptor * TXDescriptor [E1000_NUM_TX_DESC]
Additional Inherited Members
Data Fields inherited from NetworkInterfaceManager::DeviceInterface
char Name [128]
Device interface name.
uint64_t ID
Device interface index.
MediaAccessControl MAC
Device interface MAC address (Big-endian)
InternetProtocol4 IP
Device interface IP address (Big-endian)
Detailed Description
Definition at line 10 of file E1000.hpp.
Data Structure Documentation
E1000::NetworkInterfaceController::BARData
struct E1000::NetworkInterfaceController::BARData
Definition at line 141 of file E1000.hpp.
Data Fields
uint64_t IOBase
uint64_t MemoryBase
uint8_t Type
E1000::NetworkInterfaceController::RXDescriptor
struct E1000::NetworkInterfaceController::RXDescriptor
Definition at line 120 of file E1000.hpp.
Data Fields
volatile uint64_t Address
volatile uint16_t Checksum
volatile uint8_t Errors
volatile uint16_t Length
volatile uint16_t Special
volatile uint8_t Status
E1000::NetworkInterfaceController::TXDescriptor
struct E1000::NetworkInterfaceController::TXDescriptor
Definition at line 130 of file E1000.hpp.
Data Fields
volatile uint64_t Address
volatile uint8_t Command
volatile uint8_t cso
volatile uint8_t css
volatile uint16_t Length
volatile uint16_t Special
volatile uint8_t Status
Member Enumeration Documentation
CMD
enum E1000::NetworkInterfaceController::CMD private
Enumerator
EOP
IFCS
IC
RS
RPS
VLE
IDE
Definition at line 87 of file E1000.hpp.
         {
             EOP = (1 << 0),
             IFCS = (1 << 1),
             IC = (1 << 2),
             RS = (1 << 3),
             RPS = (1 << 4),
             VLE = (1 << 6),
             IDE = (1 << 7)
         };
ECTRL
enum E1000::NetworkInterfaceController::ECTRL private
Enumerator
SLU
Definition at line 46 of file E1000.hpp.
         {
             SLU = 0x40
         };
LSTA
enum E1000::NetworkInterfaceController::LSTA private
Enumerator
LSTA_TU
Definition at line 115 of file E1000.hpp.
         {
             LSTA_TU = (1 << 3)
         };
RCTL
enum E1000::NetworkInterfaceController::RCTL private
Enumerator
EN
SBP
UPE
MPE
LPE
LBM_NONE
LBM_PHY
MO_36
MO_35
MO_34
MO_32
BAM
VFE
CFIEN
CFI
DPF
PMCF
SECRC
BSIZE_256
BSIZE_512
BSIZE_1024
BSIZE_2048
BSIZE_4096
BSIZE_8192
BSIZE_16384
Definition at line 58 of file E1000.hpp.
         {
             EN = (1 << 1),
             SBP = (1 << 2),
             UPE = (1 << 3),
             MPE = (1 << 4),
             LPE = (1 << 5),
             LBM_NONE = (0 << 6),
             LBM_PHY = (3 << 6),
             MO_36 = (0 << 12),
             MO_35 = (1 << 12),
             MO_34 = (2 << 12),
             MO_32 = (3 << 12),
             BAM = (1 << 15),
             VFE = (1 << 18),
             CFIEN = (1 << 19),
             CFI = (1 << 20),
             DPF = (1 << 22),
             PMCF = (1 << 23),
             SECRC = (1 << 26),
             BSIZE_256 = (3 << 16),
             BSIZE_512 = (2 << 16),
             BSIZE_1024 = (1 << 16),
             BSIZE_2048 = (0 << 16),
             BSIZE_4096 = ((3 << 16) | (1 << 25)),
             BSIZE_8192 = ((2 << 16) | (1 << 25)),
             BSIZE_16384 = ((1 << 16) | (1 << 25))
         };
REG
enum E1000::NetworkInterfaceController::REG private
Enumerator
CTRL
STATUS
EEPROM
CTRL_EXT
IMASK
RCTRL
RXDESCLO
RXDESCHI
RXDESCLEN
RXDESCHEAD
RXDESCTAIL
TCTRL
TXDESCLO
TXDESCHI
TXDESCLEN
TXDESCHEAD
TXDESCTAIL
RDTR
RXDCTL
RADV
RSRPD
TIPG
Definition at line 20 of file E1000.hpp.
         {
             CTRL = 0x0000,
             STATUS = 0x0008,
             EEPROM = 0x0014,
             CTRL_EXT = 0x0018,
             IMASK = 0x00D0,
             RCTRL = 0x0100,
             RXDESCLO = 0x2800,
             RXDESCHI = 0x2804,
             RXDESCLEN = 0x2808,
             RXDESCHEAD = 0x2810,
             RXDESCTAIL = 0x2818,
             TCTRL = 0x0400,
             TXDESCLO = 0x3800,
             TXDESCHI = 0x3804,
             TXDESCLEN = 0x3808,
             TXDESCHEAD = 0x3810,
             TXDESCTAIL = 0x3818,
             RDTR = 0x2820,
             RXDCTL = 0x3828,
             RADV = 0x282C,
             RSRPD = 0x2C00,
             TIPG = 0x0410
         };
RTCL
enum E1000::NetworkInterfaceController::RTCL private
Enumerator
RDMTS_HALF
RDMTS_QUARTER
RDMTS_EIGHTH
Definition at line 51 of file E1000.hpp.
         {
             RDMTS_HALF = (0 << 8),
             RDMTS_QUARTER = (1 << 8),
             RDMTS_EIGHTH = (2 << 8)
         };
TCTL
enum E1000::NetworkInterfaceController::TCTL private
Enumerator
EN_
PSP
CT_SHIFT
COLD_SHIFT
SWXOFF
RTLC
Definition at line 98 of file E1000.hpp.
         {
             EN_ = (1 << 1),
             PSP = (1 << 3),
             CT_SHIFT = 4,
             COLD_SHIFT = 12,
             SWXOFF = (1 << 22),
             RTLC = (1 << 24)
         };
TSTA
enum E1000::NetworkInterfaceController::TSTA private
Enumerator
DD
EC
LC
Definition at line 108 of file E1000.hpp.
         {
             DD = (1 << 0),
             EC = (1 << 1),
             LC = (1 << 2)
         };
Constructor & Destructor Documentation
NetworkInterfaceController()
E1000::NetworkInterfaceController::NetworkInterfaceController (PCI::PCIDeviceHeader * PCIBaseAddress)
Definition at line 44 of file E1000.cpp.
                                                                                              : DriverInterrupts::Register(((PCI::PCIHeader0 *)PCIBaseAddress)->InterruptLine + IRQ0)
     {
         if (PCIBaseAddress->VendorID != 0x8086 && PCIBaseAddress->DeviceID != 0x100E && PCIBaseAddress->DeviceID != 0x153A && PCIBaseAddress->DeviceID != 0x10EA)
         {
             netdbg("Not a Intel-Ethernet-i217 network card");
             return;
         }
         netdbg("Found %s network card", PCI::GetDeviceName(PCIBaseAddress->VendorID, PCIBaseAddress->DeviceID));
         PCIAddress = PCIBaseAddress;
         memcpy(this->Name, "E1000 Network Driver", sizeof(this->Name));
         // Making sure that bus master is enabled
         PCIBaseAddress->Command |= PCI::PCI_COMMAND_MASTER | PCI::PCI_COMMAND_IO | PCI::PCI_COMMAND_MEMORY;
         uint32_t PCIBAR0 = ((PCI::PCIHeader0 *)PCIBaseAddress)->BAR0;
         uint32_t PCIBAR1 = ((PCI::PCIHeader0 *)PCIBaseAddress)->BAR1;
         BAR.Type = PCIBAR0 & 1;
         BAR.IOBase = PCIBAR1 & (~3);
         BAR.MemoryBase = PCIBAR0 & (~15);
         netdbg("BAR Type: %d - BAR IOBase: %#x - BAR MemoryBase: %#x", BAR.Type, BAR.IOBase, BAR.MemoryBase);
         this->EEPROMAvailable = false;
         this->Start();
     }
References BAR, EEPROMAvailable, PCI::GetDeviceName(), E1000::NetworkInterfaceController::BARData::IOBase, memcpy(), E1000::NetworkInterfaceController::BARData::MemoryBase, NetworkInterfaceManager::DeviceInterface::Name, netdbg, PCIAddress, Start(), and E1000::NetworkInterfaceController::BARData::Type.
~NetworkInterfaceController()
E1000::NetworkInterfaceController::~NetworkInterfaceController ()
Definition at line 68 of file E1000.cpp.
     {
     }
Member Function Documentation
__attribute__() [1/2]
struct E1000::NetworkInterfaceController::RXDescriptor E1000::NetworkInterfaceController::__attribute__ ((packed)) private
__attribute__() [2/2]
struct E1000::NetworkInterfaceController::TXDescriptor E1000::NetworkInterfaceController::__attribute__ ((packed)) private
DetectEEPROM()
bool E1000::NetworkInterfaceController::DetectEEPROM () private
Definition at line 94 of file E1000.cpp.
     {
         OutCMD(REG::EEPROM, 0x1);
         for (int i = 0; i < 1000 && !this->EEPROMAvailable; i++)
             if (InCMD(REG::EEPROM) & 0x10)
                 this->EEPROMAvailable = true;
             else
                 this->EEPROMAvailable = false;
         return this->EEPROMAvailable;
     }
References EEPROMAvailable, InCMD(), and OutCMD().
Referenced by Start().
GetIP()
InternetProtocol4 E1000::NetworkInterfaceController::GetIP ()
Definition at line 41 of file E1000.cpp.
 { return IP; }
GetMAC()
MediaAccessControl E1000::NetworkInterfaceController::GetMAC ()
Definition at line 9 of file E1000.cpp.
     {
         MediaAccessControl mac;
         if (this->EEPROMAvailable)
         {
             uint32_t temp;
             temp = ReadEEPROM(0);
             mac.Address[0] = temp & 0xff;
             mac.Address[1] = temp >> 8;
             temp = ReadEEPROM(1);
             mac.Address[2] = temp & 0xff;
             mac.Address[3] = temp >> 8;
             temp = ReadEEPROM(2);
             mac.Address[4] = temp & 0xff;
             mac.Address[5] = temp >> 8;
         }
         else
         {
             uint8_t *BaseMac8 = (uint8_t *)(BAR.MemoryBase + 0x5400);
             uint32_t *BaseMac32 = (uint32_t *)(BAR.MemoryBase + 0x5400);
             if (BaseMac32[0] != 0)
                 for (int i = 0; i < 6; i++)
                     mac.Address[i] = BaseMac8[i];
             else
             {
                 warn("No MAC address found.");
                 return MediaAccessControl();
             }
         }
         return mac;
     }
References MediaAccessControl::Address, BAR, EEPROMAvailable, E1000::NetworkInterfaceController::BARData::MemoryBase, ReadEEPROM(), and warn.
Referenced by Start().
HandleInterrupt()
void E1000::NetworkInterfaceController::HandleInterrupt (TrapFrame * regs) virtual
Definition at line 237 of file E1000.cpp.
     {
         OutCMD(REG::IMASK, 0x1);
         uint32_t status = InCMD(0xC0);
         char *dbgmsg = (char *)"ERROR";
         if (status & 0x01)
         {
             dbgmsg = (char *)"I=>O";
         }
         if (status & 0x04)
         {
             dbgmsg = (char *)"LINK";
             StartLink();
         }
         else if (status & 0x10)
         {
             dbgmsg = (char *)"Good Threshold"; // ?????
         }
         else if (status & 0x80)
         {
             dbgmsg = (char *)"I<=O";
             this->Receive();
         }
         else
         {
             netdbg("Unknown status: %x", status);
         }
         netdbg("IRQ%d: [%s]", regs->int_num - IRQ0, dbgmsg);
     }
References InCMD(), _TrapFrame::int_num, netdbg, OutCMD(), Receive(), and StartLink().
InCMD()
uint32_t E1000::NetworkInterfaceController::InCMD (uint16_t Address) private
Definition at line 83 of file E1000.cpp.
     {
         if (BAR.Type == 0)
             return mmioin32(BAR.MemoryBase + Address);
         else
         {
             outportl(BAR.IOBase, Address);
             return inportl(BAR.IOBase + 0x4);
         }
     }
References Address, BAR, inportl(), E1000::NetworkInterfaceController::BARData::IOBase, E1000::NetworkInterfaceController::BARData::MemoryBase, mmioin32(), outportl(), and E1000::NetworkInterfaceController::BARData::Type.
Referenced by DetectEEPROM(), HandleInterrupt(), ReadEEPROM(), Start(), and StartLink().
OutCMD()
void E1000::NetworkInterfaceController::OutCMD (uint16_t Address, uint32_t Value) private
Definition at line 72 of file E1000.cpp.
     {
         if (BAR.Type == 0)
             mmioout32(BAR.MemoryBase + Address, Value);
         else
         {
             outportl(BAR.IOBase, Address);
             outportl(BAR.IOBase + 4, Value);
         }
     }
References Address, BAR, E1000::NetworkInterfaceController::BARData::IOBase, E1000::NetworkInterfaceController::BARData::MemoryBase, mmioout32(), outportl(), and E1000::NetworkInterfaceController::BARData::Type.
Referenced by DetectEEPROM(), HandleInterrupt(), ReadEEPROM(), Receive(), rxinit(), Send(), Start(), StartLink(), and txinit().
ReadEEPROM()
uint32_t E1000::NetworkInterfaceController::ReadEEPROM (uint8_t Address) private
Definition at line 107 of file E1000.cpp.
     {
         uint16_t Data = 0;
         uint32_t temp = 0;
         if (this->EEPROMAvailable)
         {
             OutCMD(REG::EEPROM, (1) | ((uint32_t)(Address) << 8));
             while (!((temp = InCMD(REG::EEPROM)) & (1 << 4)))
                 ;
         }
         else
         {
             OutCMD(REG::EEPROM, (1) | ((uint32_t)(Address) << 2));
             while (!((temp = InCMD(REG::EEPROM)) & (1 << 1)))
                 ;
         }
         Data = (uint16_t)((temp >> 16) & 0xFFFF);
         return Data;
     }
References Address, EEPROMAvailable, InCMD(), and OutCMD().
Referenced by GetMAC().
Receive()
void E1000::NetworkInterfaceController::Receive () virtual
Reimplemented from NetworkInterfaceManager::DeviceInterface.
Definition at line 223 of file E1000.cpp.
     {
         while ((RXDescriptor[RXCurrent]->Status & 0x1))
         {
             uint8_t *Data = (uint8_t *)RXDescriptor[RXCurrent]->Address;
             uint16_t DataLength = RXDescriptor[RXCurrent]->Length;
             nimgr->Receive(this, Data, DataLength);
             RXDescriptor[RXCurrent]->Status = 0;
             uint16_t OldRXCurrent = RXCurrent;
             RXCurrent = (RXCurrent + 1) % E1000_NUM_RX_DESC;
             OutCMD(REG::RXDESCTAIL, OldRXCurrent);
         }
     }
References Address, E1000_NUM_RX_DESC, E1000::NetworkInterfaceController::RXDescriptor::Length, nimgr, OutCMD(), NetworkInterfaceManager::NetworkInterface::Receive(), RXCurrent, Status, and E1000::NetworkInterfaceController::RXDescriptor::Status.
Referenced by HandleInterrupt().
rxinit()
void E1000::NetworkInterfaceController::rxinit () private
Definition at line 127 of file E1000.cpp.
     {
         uint8_t *Ptr = (uint8_t *)KernelAllocator.RequestPages((sizeof(struct RXDescriptor) * E1000_NUM_RX_DESC + 16) / PAGE_SIZE + 1);
         struct RXDescriptor *Descriptor = (struct RXDescriptor *)Ptr;
         for (int i = 0; i < E1000_NUM_RX_DESC; i++)
         {
             RXDescriptor[i] = (struct RXDescriptor *)((uint8_t *)Descriptor + i * 16);
             RXDescriptor[i]->Address = (uint64_t)(uint8_t *)KernelAllocator.RequestPages((8192 + 16) / PAGE_SIZE + 1);
             RXDescriptor[i]->Status = 0;
         }
         OutCMD(REG::TXDESCLO, (uint32_t)((uint64_t)Ptr >> 32));
         OutCMD(REG::TXDESCHI, (uint32_t)((uint64_t)Ptr & 0xFFFFFFFF));
         OutCMD(REG::RXDESCLO, (uint64_t)Ptr);
         OutCMD(REG::RXDESCHI, 0);
         OutCMD(REG::RXDESCLEN, E1000_NUM_RX_DESC * 16);
         OutCMD(REG::RXDESCHEAD, 0);
         OutCMD(REG::RXDESCTAIL, E1000_NUM_RX_DESC - 1);
         RXCurrent = 0;
         OutCMD(REG::RCTRL, RCTL::EN | RCTL::SBP | RCTL::UPE | RCTL::MPE | RCTL::LBM_NONE | RTCL::RDMTS_HALF | RCTL::BAM | RCTL::SECRC | RCTL::BSIZE_8192);
     }
References E1000::NetworkInterfaceController::RXDescriptor::Address, E1000_NUM_RX_DESC, KernelAllocator, OutCMD(), PAGE_SIZE, RXCurrent, and E1000::NetworkInterfaceController::RXDescriptor::Status.
Referenced by Start().
Send()
void E1000::NetworkInterfaceController::Send (void * Data, uint64_t Length) virtual
Reimplemented from NetworkInterfaceManager::DeviceInterface.
Definition at line 210 of file E1000.cpp.
     {
         TXDescriptor[TXCurrent]->Address = (uint64_t)Data;
         TXDescriptor[TXCurrent]->Length = Length;
         TXDescriptor[TXCurrent]->Command = CMD::EOP | CMD::IFCS | CMD::RS;
         TXDescriptor[TXCurrent]->Status = 0;
         uint8_t OldTXCurrent = TXCurrent;
         TXCurrent = (TXCurrent + 1) % E1000_NUM_TX_DESC;
         OutCMD(REG::TXDESCTAIL, TXCurrent);
         while (!(TXDescriptor[OldTXCurrent]->Status & 0xff))
             ;
     }
References E1000::NetworkInterfaceController::TXDescriptor::Address, E1000::NetworkInterfaceController::TXDescriptor::Command, E1000_NUM_TX_DESC, E1000::NetworkInterfaceController::TXDescriptor::Length, Length, OutCMD(), Status, E1000::NetworkInterfaceController::TXDescriptor::Status, and TXCurrent.
SetIP()
void E1000::NetworkInterfaceController::SetIP (InternetProtocol4 IP)
Definition at line 42 of file E1000.cpp.
 { this->IP = IP; }
Start()
bool E1000::NetworkInterfaceController::Start ()
Definition at line 189 of file E1000.cpp.
     {
         DetectEEPROM();
         if (!this->GetMAC().Valid())
             return false;
         this->MAC = this->GetMAC();
         StartLink();
         for (int i = 0; i < 0x80; i++)
             OutCMD(0x5200 + i * 4, 0);
         OutCMD(REG::IMASK, 0x1F6DC);
         OutCMD(REG::IMASK, 0xff & ~4);
         InCMD(0xc0);
         rxinit();
         txinit();
         netdbg("E1000 Started");
         return true;
     }
References DetectEEPROM(), GetMAC(), InCMD(), NetworkInterfaceManager::DeviceInterface::MAC, netdbg, OutCMD(), rxinit(), StartLink(), and txinit().
Referenced by NetworkInterfaceController().
StartLink()
void E1000::NetworkInterfaceController::StartLink () private
Definition at line 183 of file E1000.cpp.
     {
         uint32_t ret = InCMD(REG::CTRL);
         OutCMD(REG::CTRL, ret | ECTRL::SLU);
     }
References InCMD(), and OutCMD().
Referenced by HandleInterrupt(), and Start().
txinit()
void E1000::NetworkInterfaceController::txinit () private
Definition at line 153 of file E1000.cpp.
     {
         uint8_t *Ptr = (uint8_t *)KernelAllocator.RequestPages((sizeof(struct TXDescriptor) * E1000_NUM_RX_DESC + 16) / PAGE_SIZE + 1);
         struct TXDescriptor *Descriptor = (struct TXDescriptor *)Ptr;
         for (int i = 0; i < E1000_NUM_TX_DESC; i++)
         {
             TXDescriptor[i] = (struct TXDescriptor *)((uint8_t *)Descriptor + i * 16);
             TXDescriptor[i]->Address = 0;
             TXDescriptor[i]->Command = 0;
             TXDescriptor[i]->Status = TSTA::DD;
         }
         OutCMD(REG::TXDESCHI, (uint32_t)((uint64_t)Ptr >> 32));
         OutCMD(REG::TXDESCLO, (uint32_t)((uint64_t)Ptr & 0xFFFFFFFF));
         OutCMD(REG::TXDESCLEN, E1000_NUM_TX_DESC * 16);
         OutCMD(REG::TXDESCHEAD, 0);
         OutCMD(REG::TXDESCTAIL, 0);
         TXCurrent = 0;
         OutCMD(REG::TCTRL, TCTL::EN_ | TCTL::PSP | (15 << TCTL::CT_SHIFT) | (64 << TCTL::COLD_SHIFT) | TCTL::RTLC);
         // This line of code overrides the one before it but I left both to highlight that the previous one works with e1000 cards, but for the e1000e cards
         // you should set the TCTRL register as follows. For detailed description of each bit, please refer to the Intel Manual.
         // In the case of I217 and 82577LM packets will not be sent if the TCTRL is not configured using the following bits.
         OutCMD(REG::TCTRL, 0b0110000000000111111000011111010);
         OutCMD(REG::TIPG, 0x0060200A);
     }
References E1000::NetworkInterfaceController::TXDescriptor::Address, E1000::NetworkInterfaceController::TXDescriptor::Command, E1000_NUM_RX_DESC, E1000_NUM_TX_DESC, KernelAllocator, OutCMD(), PAGE_SIZE, E1000::NetworkInterfaceController::TXDescriptor::Status, and TXCurrent.
Referenced by Start().
Field Documentation
__attribute__
struct E1000::NetworkInterfaceController::BARData E1000::NetworkInterfaceController::__attribute__ private
BAR
BARData E1000::NetworkInterfaceController::BAR private
Definition at line 150 of file E1000.hpp.
Referenced by GetMAC(), InCMD(), NetworkInterfaceController(), and OutCMD().
CurrentPacket
uint32_t E1000::NetworkInterfaceController::CurrentPacket private
Definition at line 149 of file E1000.hpp.
EEPROMAvailable
bool E1000::NetworkInterfaceController::EEPROMAvailable private
Definition at line 151 of file E1000.hpp.
Referenced by DetectEEPROM(), GetMAC(), NetworkInterfaceController(), and ReadEEPROM().
IP
InternetProtocol4 E1000::NetworkInterfaceController::IP private
Definition at line 148 of file E1000.hpp.
PCIAddress
PCI::PCIDeviceHeader* E1000::NetworkInterfaceController::PCIAddress private
Definition at line 152 of file E1000.hpp.
Referenced by NetworkInterfaceController().
RXCurrent
uint16_t E1000::NetworkInterfaceController::RXCurrent private
Definition at line 154 of file E1000.hpp.
Referenced by Receive(), and rxinit().
RXDescriptor
RXDescriptor* E1000::NetworkInterfaceController::RXDescriptor[E1000_NUM_RX_DESC] private
Definition at line 156 of file E1000.hpp.
TXCurrent
uint16_t E1000::NetworkInterfaceController::TXCurrent private
Definition at line 155 of file E1000.hpp.
Referenced by Send(), and txinit().
TXDescriptor
TXDescriptor* E1000::NetworkInterfaceController::TXDescriptor[E1000_NUM_TX_DESC] private
Definition at line 157 of file E1000.hpp.
The documentation for this class was generated from the following files:
kernel/drivers/network/E1000/E1000.hpp
kernel/drivers/network/E1000/E1000.cpp