Fennix Project: libc/include/file.h File Reference
file.h File Reference
#include <cdefs.h>
#include <stddef.h>
Data Structures
struct _FILE
Typedefs
typedef struct _FILE FILE
Enumerations
enum Seek { SEEK_BEGIN, SEEK_CURRENT, SEEK_END }
Functions
E FILE * FileOpen (const char *Filename, const char *Mode)
Open a file specified by filename and mode.
E size_t FileRead (void *Buffer, size_t Size, size_t Count, FILE *Stream)
Read data from the given stream into the array pointed to, by Buffer.
E size_t FileWrite (const void *Buffer, size_t Size, size_t Count, FILE *Stream)
Write data from the array pointed to by Buffer to the given stream.
E int FileSeek (FILE *Stream, long int Offset, enum Seek Whence)
E long int FileTell (FILE *Stream)
E int MakeDirectory (const char *Path, int Mode)
E int RenameFile (const char *OldFileName, const char *NewFileName)
E int RemoveFile (const char *FileName)
E int FileClose (FILE *Stream)
Close the given stream.
Data Structure Documentation
_FILE
struct _FILE
Definition at line 7 of file file.h.
Data Fields
void * Khnd Kernel internal file handle. Trying to access it will cause a page fault.
char PrintBuffer[2048]
Typedef Documentation
FILE
typedef struct _FILE FILE
Enumeration Type Documentation
Seek
enum Seek
Enumerator
SEEK_BEGIN
SEEK_CURRENT
SEEK_END
Definition at line 14 of file file.h.
 {
     SEEK_BEGIN,
     SEEK_CURRENT,
     SEEK_END
 };
Function Documentation
FileClose()
E int FileClose (FILE * Stream)
Close the given stream.
Parameters
stream The stream to close.
Returns
0 on success.
Definition at line 58 of file file.c.
 {
     syscall_FileClose(Stream->Khnd);
     free(Stream);
     return 0;
 }
References free(), and _FILE::Khnd.
FileOpen()
E FILE* FileOpen (const char * Filename, const char * Mode)
Open a file specified by filename and mode.
Parameters
Filename The filename to open.
Mode The mode to open the file in.
Returns
The file pointer to the opened file.
Definition at line 8 of file file.c.
 {
     void *ret = (void *)syscall_FileOpen((char *)Filename /*, Mode*/);
     if (ret == NULL)
         return NULL;
     FILE *file = (FILE *)malloc(sizeof(FILE));
     file->Khnd = ret;
     return file;
 }
References _FILE::Khnd, and malloc().
FileRead()
E size_t FileRead (void * Buffer, size_t Size, size_t Count, FILE * Stream)
Read data from the given stream into the array pointed to, by Buffer.
Parameters
Buffer The array to read data into with a minimum size of Size * Count.
Size The size of each element to read.
Count The number of elements to read (each element is Size bytes long).
Stream The stream to read from (obtained from FileOpen).
Returns
The number of bytes read into the array.
Definition at line 18 of file file.c.
 {
     return syscall_FileRead(Stream->Khnd, 0 /*offset*/, Buffer, Size);
 }
References _FILE::Khnd.
FileSeek()
E int FileSeek (FILE * Stream, long int Offset, enum Seek Whence)
Definition at line 28 of file file.c.
 {
     WriteSysDebugger("FileSeek( %p %ld %d ) stub\n", Stream, Offset, Whence);
     return 0;
 }
References WriteSysDebugger().
FileTell()
E long int FileTell (FILE * Stream)
Definition at line 34 of file file.c.
 {
     WriteSysDebugger("FileTell( %p ) stub\n", Stream);
     return 0;
 }
References WriteSysDebugger().
FileWrite()
E size_t FileWrite (const void * Buffer, size_t Size, size_t Count, FILE * Stream)
Write data from the array pointed to by Buffer to the given stream.
Parameters
Buffer The array to write data from.
Size The size of each element to write.
Count The number of elements to write (each element is Size bytes long).
Stream The stream to write to (obtained from FileOpen).
Returns
The number of bytes written to the stream.
Definition at line 23 of file file.c.
 {
     return syscall_FileWrite(Stream->Khnd, 0 /*offset*/, (void *)Buffer, Size);
 }
References _FILE::Khnd.
MakeDirectory()
E int MakeDirectory (const char * Path, int Mode)
Definition at line 40 of file file.c.
 {
     WriteSysDebugger("MakeDirectory( %s %d ) stub\n", Path, Mode);
     return 0;
 }
References WriteSysDebugger().
RemoveFile()
E int RemoveFile (const char * FileName)
Definition at line 52 of file file.c.
 {
     WriteSysDebugger("RemoveFile( %s ) stub\n", FileName);
     return 0;
 }
References WriteSysDebugger().
RenameFile()
E int RenameFile (const char * OldFileName, const char * NewFileName)
Definition at line 46 of file file.c.
 {
     WriteSysDebugger("RenameFile( %s %s ) stub\n", OldFileName, NewFileName);
     return 0;
 }
References WriteSysDebugger().