Fennix Project: kernel/security/security.hpp File Reference
security.hpp File Reference
#include "../syscalls/syscalls.hpp"
Functions
uint64_t CreateToken ()
void TrustToken (uint64_t Token, bool Process, uint64_t ID, int TrustLevel)
bool CanSyscall (SyscallsRegs *regs)
Function Documentation
CanSyscall()
bool CanSyscall (SyscallsRegs * regs)
Definition at line 40 of file Security.cpp.
 {
     // fixme("CanSyscall( %p %ld )", regs, TmpToken);
     return true;
     uint64_t TmpToken = SysGetCurrentThread()->Security.Token;
     foreach (auto var in Tokens)
     {
         if (var.Token == TmpToken)
         {
             if (var.TrustLevel == TokenTrustLevel::UnknownTrustLevel)
             {
                 return false;
             }
             else if (var.TrustLevel == TokenTrustLevel::TrustedByKernel)
             {
                 return true;
             }
             else if (var.TrustLevel == TokenTrustLevel::Trusted)
             {
                 return true;
             }
             else if (var.TrustLevel == TokenTrustLevel::Untrusted)
             {
                 return true;
             }
             else
             {
                 return false;
             }
         }
     }
     return true;
 }
References TCB::Security, SysGetCurrentThread(), GeneralSecurityInfo::Token, Tokens, Trusted, TrustedByKernel, UnknownTrustLevel, and Untrusted.
Referenced by internal_beep(), internal_cli(), internal_createprocess(), internal_createtask(), internal_createthread(), internal_dbg(), internal_fadebootlogo(), internal_fbaddress(), internal_fbheight(), internal_fbppsl(), internal_fbsize(), internal_fbwidth(), internal_filechildrensize(), internal_fileClose(), internal_filefullpath(), internal_filegetchildren(), internal_fileOpen(), internal_fileOpenWithParent(), internal_fileRead(), internal_filesize(), internal_fileWrite(), internal_freepage(), internal_freepages(), internal_getargc(), internal_getargv(), internal_getcurrentprocess(), internal_getcurrentprocessid(), internal_getcurrentthread(), internal_getcurrentthreadid(), internal_getenvp(), internal_poptask(), internal_pushtask(), internal_reboot(), internal_requestpage(), internal_requestpages(), internal_shutdown(), internal_sti(), and internal_usleep().
CreateToken()
uint64_t CreateToken ()
Definition at line 17 of file Security.cpp.
 {
     uint64_t ret = rand64();
     Tokens.push_back({ret, UnknownTrustLevel, 0, false});
     return ret;
 }
References rand64(), Tokens, and UnknownTrustLevel.
TrustToken()
void TrustToken (uint64_t Token, bool Process, uint64_t ID, int TrustLevel)
Definition at line 24 of file Security.cpp.
 {
     enum TokenTrustLevel Level = static_cast<enum TokenTrustLevel>(TrustLevel);
     foreach (auto var in Tokens)
     {
         if (var.Token == Token)
         {
             var.TrustLevel = Level;
             var.OwnerID = ID;
             var.Process = Process;
             return;
         }
     }
 }
References ID, and Tokens.