Fennix Project: FileSystem::Driver Class Reference
FileSystem::Driver Class Reference
#include <filesystem.h>
Public Member Functions
FileSystemNode * AddDriver (struct FileSystemOpeations *Operator, uint64_t Mode, string Name, int Flags)
Driver ()
~Driver ()
Detailed Description
Definition at line 187 of file filesystem.h.
Constructor & Destructor Documentation
Driver()
FileSystem::Driver::Driver ()
Definition at line 19 of file drvfs.cpp.
     {
         trace("Initializing driver file system...");
         DriverRootNode = vfs->Create(nullptr, "/system/drv");
         DriverRootNode->Flags = NodeFlags::FS_MOUNTPOINT;
         DriverRootNode->Mode = 0755;
         BS->IncreaseProgres();
     }
References BS, FileSystem::Virtual::Create(), FileSystem::DriverRootNode, FileSystem::FileSystemNode::Flags, FS_MOUNTPOINT, BootScreen::Screen::IncreaseProgres(), FileSystem::FileSystemNode::Mode, trace, and vfs.
~Driver()
FileSystem::Driver::~Driver ()
Definition at line 28 of file drvfs.cpp.
     {
     }
Member Function Documentation
AddDriver()
FileSystemNode * FileSystem::Driver::AddDriver (struct FileSystemOpeations * Operator, uint64_t Mode, string Name, int Flags)
Definition at line 9 of file drvfs.cpp.
     {
         trace("Adding %s to file system", Name);
         FileSystemNode *newNode = vfs->Create(DriverRootNode, Name);
         newNode->Mode = Mode;
         newNode->Operator = Operator;
         newNode->Flags = Flags;
         return newNode;
     }
References FileSystem::Virtual::Create(), FileSystem::DriverRootNode, FileSystem::FileSystemNode::Flags, Flags, FileSystem::FileSystemNode::Mode, Mode, FileSystem::FileSystemNode::Operator, trace, and vfs.
Referenced by Driver::KernelDriver::KernelDriver().
The documentation for this class was generated from the following files:
kernel/include/filesystem.h
kernel/filesystem/mountpoints/drvfs.cpp