Fennix Project: userspace/apps/system/monoton/monoton.hpp File Reference
monoton.hpp File Reference
#include "../../../libs/monoton/monotonlib.h"
#include "../../../libs/scparse/scparse.h"
#include <string.h>
#include <syscalls.h>
Functions
static void backspace (char s[])
static void append (char s[], char n)
static int isempty_1 (char *str)
char * usr ()
char * pwd ()
void InitLogin ()
Variables
MonotonLib::mtl * mono
Function Documentation
append()
static void append (char s[], char n) inline static
Definition at line 13 of file monoton.hpp.
 {
     int len = strlen(s);
     s[len] = n;
     s[len + 1] = '\0';
 }
References len, and strlen().
Referenced by InitLogin(), and loop().
backspace()
static void backspace (char s[]) inline static
Definition at line 7 of file monoton.hpp.
 {
     int len = strlen(s);
     s[len - 1] = '\0';
 }
References len, and strlen().
Referenced by InitLogin(), and loop().
InitLogin()
void InitLogin ()
Definition at line 91 of file login.cpp.
 {
     int backspacelimit = 0;
 RetryLoginName:
     mono->print("Login as: ");
     while (1)
     {
         int key = GetLetterFromScanCode((uint8_t)syscall_getLastKeyboardScanCode());
         if (key != KEY_INVALID)
         {
             if (key == KEY_D_BACKSPACE)
             {
                 if (backspacelimit > 0)
                 {
                     mono->RemoveChar();
                     backspace(usrbuf);
                     backspacelimit--;
                 }
             }
             else if (key == '\n')
             {
                 break;
             }
             else
             {
                 append(usrbuf, key);
                 mono->printchar(key);
                 backspacelimit++;
             }
         }
     }
     backspacelimit = 0;
     if (isempty_1(usrbuf))
     {
         mono->print("\nThe username cannot be empty.\n");
         clearbuffer();
         goto RetryLoginName;
     }
     int illegal = HasIllegalCharacter(usrbuf);
     if (illegal != 0)
     {
         mono->print("\nThe username cannot contain \"");
         mono->printchar(illegal);
         mono->print("\" characters.\n");
         clearbuffer();
         goto RetryLoginName;
     }
     mono->print("\nPassword for ");
     mono->print(usrbuf);
     mono->print(": ");
     while (1)
     {
         int key = GetLetterFromScanCode((uint8_t)syscall_getLastKeyboardScanCode());
         if (key != KEY_INVALID)
         {
             if (key == KEY_D_BACKSPACE)
             {
                 if (backspacelimit > 0)
                 {
                     mono->RemoveChar();
                     backspace(pwdbuf);
                     backspacelimit--;
                 }
             }
             else if (key == '\n')
             {
                 break;
             }
             else
             {
                 append(pwdbuf, key);
                 mono->printchar('*');
                 backspacelimit++;
             }
         }
     }
 }
References append(), backspace(), clearbuffer(), GetLetterFromScanCode(), HasIllegalCharacter(), isempty_1(), KEY_D_BACKSPACE, KEY_INVALID, mono, MonotonLib::mtl::print(), MonotonLib::mtl::printchar(), pwdbuf, MonotonLib::mtl::RemoveChar(), and usrbuf.
Referenced by main().
isempty_1()
static int isempty_1 (char * str) inline static
Definition at line 20 of file monoton.hpp.
 {
     long unsigned i = 0;
     while (str[i] != '\0')
         ++i;
     if (i == 0)
         return 1;
     while (*str != '\0')
     {
         if (!isspace(*str))
             return 0;
         str++;
     }
     return 1;
 }
References isspace().
Referenced by InitLogin(), and ParseBuffer().
pwd()
char* pwd ()
Definition at line 7 of file login.cpp.
 { return pwdbuf; }
References pwdbuf.
usr()
char* usr ()
Definition at line 6 of file login.cpp.
 { return usrbuf; }
References usrbuf.
Referenced by ParseBuffer(), and PrintShellPrefix().
Variable Documentation
mono
MonotonLib::mtl* mono
Definition at line 12 of file monoton.cpp.
Referenced by InitLogin(), loop(), main(), ParseBuffer(), and PrintShellPrefix().