Fennix Project: RTL8139::NetworkInterfaceController Class Reference
RTL8139::NetworkInterfaceController Class Reference
#include <RTL8139.hpp>
Data Structures
struct BARData
Public Member Functions
MediaAccessControl GetMAC ()
InternetProtocol4 GetIP ()
void SetIP (InternetProtocol4 IP)
NetworkInterfaceController (PCI::PCIDeviceHeader *PCIBaseAddress)
~NetworkInterfaceController ()
void Send (void *Data, uint64_t Length)
void Receive ()
virtual void HandleInterrupt (TrapFrame *regs)
Private Member Functions
void RTLOB (uint16_t Address, uint8_t Value)
void RTLOW (uint16_t Address, uint16_t Value)
void RTLOL (uint16_t Address, uint32_t Value)
uint8_t RTLIB (uint16_t Address)
uint16_t RTLIW (uint16_t Address)
uint32_t RTLIL (uint16_t Address)
Private Attributes
uint8_t * RXBuffer
int TXCurrent
InternetProtocol4 IP
uint32_t CurrentPacket
BARData BAR
Additional Inherited Members
Data Fields inherited from NetworkInterfaceManager::DeviceInterface
char Name [128]
Device interface name.
uint64_t ID
Device interface index.
MediaAccessControl MAC
Device interface MAC address (Big-endian)
InternetProtocol4 IP
Device interface IP address (Big-endian)
Detailed Description
Definition at line 11 of file RTL8139.hpp.
Data Structure Documentation
RTL8139::NetworkInterfaceController::BARData
struct RTL8139::NetworkInterfaceController::BARData
Definition at line 14 of file RTL8139.hpp.
Data Fields
uint16_t IOBase
uint32_t MemoryBase
uint8_t Type
Constructor & Destructor Documentation
NetworkInterfaceController()
RTL8139::NetworkInterfaceController::NetworkInterfaceController (PCI::PCIDeviceHeader * PCIBaseAddress)
Definition at line 34 of file RTL8139.cpp.
                                                                                              : DriverInterrupts::Register(((PCI::PCIHeader0 *)PCIBaseAddress)->InterruptLine + IRQ0)
     {
         if (PCIBaseAddress->VendorID != 0x10EC && PCIBaseAddress->DeviceID != 0x8139)
         {
             netdbg("Not a RTL-8139 network card");
             return;
         }
         netdbg("Found %s network card", PCI::GetDeviceName(PCIBaseAddress->VendorID, PCIBaseAddress->DeviceID));
         // Making sure that bus master is enabled
         PCIBaseAddress->Command |= PCI::PCI_COMMAND_MASTER | PCI::PCI_COMMAND_IO | PCI::PCI_COMMAND_MEMORY;
         uint32_t PCIBAR0 = ((PCI::PCIHeader0 *)PCIBaseAddress)->BAR0;
         uint32_t PCIBAR1 = ((PCI::PCIHeader0 *)PCIBaseAddress)->BAR1;
         BAR.Type = PCIBAR1 & 1;
         BAR.IOBase = PCIBAR0 & (~3);
         BAR.MemoryBase = PCIBAR1 & (~15);
         netdbg("BAR Type: %d - BAR IOBase: %#x - BAR MemoryBase: %#x", BAR.Type, BAR.IOBase, BAR.MemoryBase);
         memcpy(this->Name, "RTL-8139 Network Driver", sizeof(this->Name));
         RXBuffer = (uint8_t *)KernelAllocator.RequestPages(2);
         RTLOB(0x52, 0x0);
         RTLOB(0x37, (1 << 4));
         while ((RTLIB(0x37) & (1 << 4)))
             ;
         RTLOL(0x30, static_cast<uint32_t>(reinterpret_cast<uint64_t>(RXBuffer)));
         RTLOW(0x3C, ((1 << 0) | (1 << 1) | (1 << 2) | (1 << 3) |
                      (1 << 4) | (1 << 5) | (1 << 6) | (1 << 13) |
                      (1 << 14) | (1 << 15)));
         RTLOL(0x44, ((1 << 0) | (1 << 1) | (1 << 2) | (1 << 3) | (1 << 7)));
         RTLOB(0x37, 0x0C);
         this->MAC = this->GetMAC();
     }
References BAR, PCI::GetDeviceName(), GetMAC(), RTL8139::NetworkInterfaceController::BARData::IOBase, KernelAllocator, NetworkInterfaceManager::DeviceInterface::MAC, memcpy(), RTL8139::NetworkInterfaceController::BARData::MemoryBase, NetworkInterfaceManager::DeviceInterface::Name, netdbg, RTLIB(), RTLOB(), RTLOL(), RTLOW(), RXBuffer, and RTL8139::NetworkInterfaceController::BARData::Type.
~NetworkInterfaceController()
RTL8139::NetworkInterfaceController::~NetworkInterfaceController ()
Definition at line 67 of file RTL8139.cpp.
 { KernelAllocator.FreePages(RXBuffer, 2); }
References KernelAllocator, and RXBuffer.
Member Function Documentation
GetIP()
InternetProtocol4 RTL8139::NetworkInterfaceController::GetIP ()
Definition at line 27 of file RTL8139.cpp.
 { return IP; }
References IP.
GetMAC()
MediaAccessControl RTL8139::NetworkInterfaceController::GetMAC ()
Definition at line 13 of file RTL8139.cpp.
     {
         uint32_t MAC1 = RTLIL(0x0);
         uint16_t MAC2 = RTLIW(0x04);
         MediaAccessControl mac = {
             mac.Address[0] = MAC1,
             mac.Address[1] = (MAC1 >> 8),
             mac.Address[2] = (MAC1 >> 16),
             mac.Address[3] = (MAC1 >> 24),
             mac.Address[4] = MAC2,
             mac.Address[5] = (MAC2 >> 8)};
         return mac;
     }
References MediaAccessControl::Address, RTLIL(), and RTLIW().
Referenced by NetworkInterfaceController().
HandleInterrupt()
void RTL8139::NetworkInterfaceController::HandleInterrupt (TrapFrame * regs) virtual
Definition at line 89 of file RTL8139.cpp.
     {
         uint16_t status = RTLIW(0x3e);
         char *dbgmsg = (char *)"ERROR";
         if (status & (1 << 2)) // TOK
             dbgmsg = (char *)"I=>O";
         else if (status & (1 << 0)) // ROK
         {
             dbgmsg = (char *)"I<=O";
             this->Receive();
         }
         else
         {
             netdbg("Unknown status %#lx", status);
         }
         netdbg("IRQ%d: [%s]", regs->int_num - IRQ0, dbgmsg);
         RTLOW(0x3E, (1 << 0) | (1 << 2));
     }
References _TrapFrame::int_num, netdbg, Receive(), RTLIW(), and RTLOW().
Receive()
void RTL8139::NetworkInterfaceController::Receive () virtual
Reimplemented from NetworkInterfaceManager::DeviceInterface.
Definition at line 77 of file RTL8139.cpp.
     {
         uint16_t *Data = (uint16_t *)(RXBuffer + CurrentPacket);
         uint16_t DataLength = *(Data + 1);
         Data = Data + 2;
         nimgr->Receive(this, (uint8_t *)Data, DataLength);
         CurrentPacket = (CurrentPacket + DataLength + 4 + 3) & (~3);
         if (CurrentPacket > 8192)
             CurrentPacket -= 8192;
         RTLOW(0x38, CurrentPacket - 0x10);
     }
References CurrentPacket, nimgr, NetworkInterfaceManager::NetworkInterface::Receive(), RTLOW(), and RXBuffer.
Referenced by HandleInterrupt().
RTLIB()
uint8_t RTL8139::NetworkInterfaceController::RTLIB (uint16_t Address) inline private
Definition at line 51 of file RTL8139.hpp.
         {
             if (this->BAR.Type == 0)
                 return mminb(reinterpret_cast<void *>(this->BAR.MemoryBase + Address));
             else
                 return inportb(this->BAR.IOBase + Address);
         }
References Address, inportb(), RTL8139::NetworkInterfaceController::BARData::IOBase, RTL8139::NetworkInterfaceController::BARData::MemoryBase, mminb(), and RTL8139::NetworkInterfaceController::BARData::Type.
Referenced by NetworkInterfaceController().
RTLIL()
uint32_t RTL8139::NetworkInterfaceController::RTLIL (uint16_t Address) inline private
Definition at line 67 of file RTL8139.hpp.
         {
             if (this->BAR.Type == 0)
                 return mminl(reinterpret_cast<void *>(this->BAR.MemoryBase + Address));
             else
                 return inportl(this->BAR.IOBase + Address);
         }
References Address, inportl(), RTL8139::NetworkInterfaceController::BARData::IOBase, RTL8139::NetworkInterfaceController::BARData::MemoryBase, mminl(), and RTL8139::NetworkInterfaceController::BARData::Type.
Referenced by GetMAC().
RTLIW()
uint16_t RTL8139::NetworkInterfaceController::RTLIW (uint16_t Address) inline private
Definition at line 59 of file RTL8139.hpp.
         {
             if (this->BAR.Type == 0)
                 return mminw(reinterpret_cast<void *>(this->BAR.MemoryBase + Address));
             else
                 return inportw(this->BAR.IOBase + Address);
         }
References Address, inportw(), RTL8139::NetworkInterfaceController::BARData::IOBase, RTL8139::NetworkInterfaceController::BARData::MemoryBase, mminw(), and RTL8139::NetworkInterfaceController::BARData::Type.
Referenced by GetMAC(), and HandleInterrupt().
RTLOB()
void RTL8139::NetworkInterfaceController::RTLOB (uint16_t Address, uint8_t Value) inline private
Definition at line 27 of file RTL8139.hpp.
         {
             if (this->BAR.Type == 0)
                 mmoutb(reinterpret_cast<void *>(this->BAR.MemoryBase + Address), Value);
             else
                 outportb(this->BAR.IOBase + Address, Value);
         }
References Address, RTL8139::NetworkInterfaceController::BARData::IOBase, RTL8139::NetworkInterfaceController::BARData::MemoryBase, mmoutb(), outportb(), and RTL8139::NetworkInterfaceController::BARData::Type.
Referenced by NetworkInterfaceController().
RTLOL()
void RTL8139::NetworkInterfaceController::RTLOL (uint16_t Address, uint32_t Value) inline private
Definition at line 43 of file RTL8139.hpp.
         {
             if (this->BAR.Type == 0)
                 mmoutl(reinterpret_cast<void *>(this->BAR.MemoryBase + Address), Value);
             else
                 outportl(this->BAR.IOBase + Address, Value);
         }
References Address, RTL8139::NetworkInterfaceController::BARData::IOBase, RTL8139::NetworkInterfaceController::BARData::MemoryBase, mmoutl(), outportl(), and RTL8139::NetworkInterfaceController::BARData::Type.
Referenced by NetworkInterfaceController(), and Send().
RTLOW()
void RTL8139::NetworkInterfaceController::RTLOW (uint16_t Address, uint16_t Value) inline private
Definition at line 35 of file RTL8139.hpp.
         {
             if (this->BAR.Type == 0)
                 mmoutw(reinterpret_cast<void *>(this->BAR.MemoryBase + Address), Value);
             else
                 outportw(this->BAR.IOBase + Address, Value);
         }
References Address, RTL8139::NetworkInterfaceController::BARData::IOBase, RTL8139::NetworkInterfaceController::BARData::MemoryBase, mmoutw(), outportw(), and RTL8139::NetworkInterfaceController::BARData::Type.
Referenced by HandleInterrupt(), NetworkInterfaceController(), and Receive().
Send()
void RTL8139::NetworkInterfaceController::Send (void * Data, uint64_t Length) virtual
Reimplemented from NetworkInterfaceManager::DeviceInterface.
Definition at line 69 of file RTL8139.cpp.
     {
         RTLOL(TSAD[TXCurrent], static_cast<uint32_t>(reinterpret_cast<uint64_t>(Data)));
         RTLOL(TSD[TXCurrent++], Length);
         if (TXCurrent > 3)
             TXCurrent = 0;
     }
References Length, RTLOL(), RTL8139::TSAD, RTL8139::TSD, and TXCurrent.
SetIP()
void RTL8139::NetworkInterfaceController::SetIP (InternetProtocol4 IP)
Definition at line 29 of file RTL8139.cpp.
     {
         fixme("NetworkInterfaceController::SetIP( %d.%d.%d.%d )", IP.Address[0], IP.Address[1], IP.Address[2], IP.Address[3]);
     }
References InternetProtocol4::Address, fixme(), and IP.
Field Documentation
BAR
BARData RTL8139::NetworkInterfaceController::BAR private
Definition at line 25 of file RTL8139.hpp.
Referenced by NetworkInterfaceController().
CurrentPacket
uint32_t RTL8139::NetworkInterfaceController::CurrentPacket private
Definition at line 24 of file RTL8139.hpp.
Referenced by Receive().
IP
InternetProtocol4 RTL8139::NetworkInterfaceController::IP private
Definition at line 23 of file RTL8139.hpp.
Referenced by GetIP(), and SetIP().
RXBuffer
uint8_t* RTL8139::NetworkInterfaceController::RXBuffer private
Definition at line 21 of file RTL8139.hpp.
Referenced by NetworkInterfaceController(), Receive(), and ~NetworkInterfaceController().
TXCurrent
int RTL8139::NetworkInterfaceController::TXCurrent private
Definition at line 22 of file RTL8139.hpp.
Referenced by Send().
The documentation for this class was generated from the following files:
kernel/drivers/network/RTL8139/RTL8139.hpp
kernel/drivers/network/RTL8139/RTL8139.cpp