Fennix Project: libc/include/system.h File Reference
system.h File Reference
#include <cdefs.h>
Functions
E void WriteSysDebugger (const char *Format,...)
Write to the system debugger.
E void usleep (unsigned long Microseconds)
Sleep for a given number of microseconds.
E int system (const char *Command)
Execute a command in the system shell.
E void Exit (int Status) NO_THROW NO_RETURN
Exit the program with a status code.
Function Documentation
Exit()
E void Exit (int Status)
Exit the program with a status code.
Parameters
Status
Returns
void
Definition at line 54 of file system.c.
 {
     syscall_exit(Status);
     while (1)
         ;
 }
References Status.
system()
E int system (const char * Command)
Execute a command in the system shell.
Parameters
Command
Returns
int
Definition at line 45 of file system.c.
 {
     // mono 1 - multi 2
     if (syscall_getScheduleMode() == 2)
         return syscall_createProcess((char *)Command, 0, 0);
     else if (syscall_getScheduleMode() == 1)
         return -1;
 }
References Command.
usleep()
E void usleep (unsigned long Microseconds)
Sleep for a given number of microseconds.
Parameters
Microseconds
Returns
void
Definition at line 40 of file system.c.
 {
     syscall_usleep(Microseconds);
 }
WriteSysDebugger()
E void WriteSysDebugger (const char * Format, ...)
Write to the system debugger.
Parameters
Format
...
Returns
void
Definition at line 25 of file system.c.
 {
     // mono 1 - multi 2
     if (syscall_getScheduleMode() == 2)
     {
         // write info about the current thread
     }
     syswritedbgbuf[0] = '\0';
     va_list args;
     va_start(args, Format);
     vfctprintf(syswritedbgprint_wrapper, NULL, Format, args);
     va_end(args);
     syscall_dbg(0x3F8, (char *)syswritedbgbuf);
 }
References syswritedbgbuf, syswritedbgprint_wrapper(), va_end, va_start, and vfctprintf().
Referenced by Cat(), fflush(), FileSeek(), FileTell(), fprintf(), loop(), main(), MakeDirectory(), ParseBuffer(), RemoveFile(), RenameFile(), and sprintf().