Fennix Project: kernel/mem/defaultalloc/defaultalloc.hpp File Reference
defaultalloc.hpp File Reference
#include <types.h>
Data Structures
struct Heap::HeapSegHdr
Namespaces
Heap
Macros
#define defPREFIX(func) defk##func
Functions
struct Heap::HeapSegHdr Heap::__attribute__ ((aligned(16)))
void CombineForward ()
void CombineBackward ()
HeapSegHdr * Split (uint64_t SplitLength)
void InitHeap (void *HeapAddress, uint64_t PageCount)
void defPREFIX() free (void *Address)
void *defPREFIX() malloc (uint64_t Size)
void *defPREFIX() calloc (uint64_t n, uint64_t Size)
void *defPREFIX() realloc (void *Address, uint64_t Size)
Variables
uint64_t Length
HeapSegHdr * Next
HeapSegHdr * Last
bool IsFree
Macro Definition Documentation
defPREFIX
#define defPREFIX (func) defk##func
Definition at line 18 of file defaultalloc.hpp.
Function Documentation
calloc()
void* defPREFIX() calloc (uint64_t n, uint64_t Size)
Definition at line 170 of file defaultalloc.cpp.
 {
     if (HeapStart == nullptr)
     {
         err("Memory allocation not initialized yet!");
         return 0;
     }
     if (Size < 0x10)
     {
         // warn("Allocation size is too small, using 0x10 instead!");
         Size = 0x10;
     }
     void *Block = defPREFIX(malloc)(n * Size);
     if (Block)
         memset(Block, 0, n * Size);
     return Block;
 }
References defPREFIX, err, HeapStart, malloc(), and memset().
Referenced by Cat(), HeapCalloc(), and realloc().
CombineBackward()
void __attribute__::CombineBackward ()
CombineForward()
void __attribute__::CombineForward ()
free()
void defPREFIX() free (void * Address)
Definition at line 99 of file defaultalloc.cpp.
 {
     if (HeapStart == nullptr)
     {
         err("Memory allocation not initialized yet!");
         return;
     }
     HeapSegHdr *Segment = (HeapSegHdr *)Address - 1;
     Segment->IsFree = true;
     Segment->CombineForward();
     Segment->CombineBackward();
 }
InitHeap()
void InitHeap (void * HeapAddress, uint64_t PageCount)
Definition at line 11 of file defaultalloc.cpp.
 {
     trace("heap initialization %016p, %d", HeapAddress, PageCount);
     void *Position = HeapAddress;
     for (uint64_t i = 0; i < PageCount; i++)
     {
         void *Page = KernelAllocator.RequestPage();
         KernelPageTableManager.MapMemory(Position, Page, RW);
         trace("Preallocate Heap Memory (%#llx-%#llx [%#llx])...", Position, (uint64_t)Position + PAGE_SIZE, Page);
         Position = (void *)((uint64_t)Position + PAGE_SIZE);
     }
     uint64_t HeapLength = PageCount * PAGE_SIZE;
     HeapStart = HeapAddress;
     HeapEnd = (void *)((uint64_t)HeapStart + HeapLength);
     HeapSegHdr *StartSegment = (HeapSegHdr *)HeapAddress;
     StartSegment->Length = HeapLength - sizeof(HeapSegHdr);
     StartSegment->Next = nullptr;
     StartSegment->Last = nullptr;
     StartSegment->IsFree = true;
     LastHdr = StartSegment;
 }
References HeapEnd, HeapStart, Heap::HeapSegHdr::IsFree, KernelAllocator, KernelPageTableManager, Heap::HeapSegHdr::Last, LastHdr, Heap::HeapSegHdr::Length, Heap::HeapSegHdr::Next, PAGE_SIZE, RW, and trace.
Referenced by init_heap().
malloc()
void* defPREFIX() malloc (uint64_t Size)
Definition at line 112 of file defaultalloc.cpp.
 {
     if (HeapStart == nullptr)
     {
         err("Memory allocation not initialized yet!");
         return 0;
     }
     if (Size < 0x10)
     {
         // warn("Allocation size is too small, using 0x10 instead!");
         Size = 0x10;
     }
     // #ifdef DEBUG
     //     if (Size < 1024)
     //         debug("Allocating %dB", Size);
     //     else if (TO_KB(Size) < 1024)
     //         debug("Allocating %dKB", TO_KB(Size));
     //     else if (TO_MB(Size) < 1024)
     //         debug("Allocating %dMB", TO_MB(Size));
     //     else if (TO_GB(Size) < 1024)
     //         debug("Allocating %dGB", TO_GB(Size));
     // #endif
     if (Size % 0x10 > 0)
     { // it is not a multiple of 0x10
         Size -= (Size % 0x10);
         Size += 0x10;
     }
     if (Size == 0)
         return nullptr;
     HeapSegHdr *CurrentSegment = (HeapSegHdr *)HeapStart;
     while (true)
     {
         if (CurrentSegment->IsFree)
         {
             if (CurrentSegment->Length > Size)
             {
                 CurrentSegment->Split(Size);
                 CurrentSegment->IsFree = false;
                 return (void *)((uint64_t)CurrentSegment + sizeof(HeapSegHdr));
             }
             if (CurrentSegment->Length == Size)
             {
                 CurrentSegment->IsFree = false;
                 return (void *)((uint64_t)CurrentSegment + sizeof(HeapSegHdr));
             }
         }
         if (CurrentSegment->Next == nullptr)
             break;
         CurrentSegment = CurrentSegment->Next;
     }
     ExpandHeap(Size);
     return defPREFIX(malloc)(Size);
 }
References defPREFIX, err, ExpandHeap(), HeapStart, Heap::HeapSegHdr::IsFree, Heap::HeapSegHdr::Length, malloc(), Heap::HeapSegHdr::Next, and Heap::HeapSegHdr::Split().
Referenced by calloc(), Cat(), FileOpen(), HeapMalloc(), malloc(), MonotonLib::mtl::mtl(), ParseBuffer(), and strdup().
realloc()
void* defPREFIX() realloc (void * Address, uint64_t Size)
Definition at line 190 of file defaultalloc.cpp.
 {
     if (HeapStart == nullptr)
     {
         err("Memory allocation not initialized yet!");
         return 0;
     }
     if (!Address && Size == 0)
     {
         defPREFIX(free)(Address);
         return nullptr;
     }
     else if (!Address)
     {
         return defPREFIX(calloc)(Size, sizeof(char));
     }
     if (Size < 0x10)
     {
         // warn("Allocation size is too small, using 0x10 instead!");
         Size = 0x10;
     }
     void *newAddress = defPREFIX(calloc)(Size, sizeof(char));
     memcpy(newAddress, Address, Size);
     return newAddress;
 }
References Address, calloc(), defPREFIX, err, free(), HeapStart, and memcpy().
Referenced by HeapRealloc().
Split()
HeapSegHdr* __attribute__::Split (uint64_t SplitLength)
Variable Documentation
IsFree
bool IsFree
Definition at line 29 of file defaultalloc.hpp.
Last
HeapSegHdr* Last
Definition at line 28 of file defaultalloc.hpp.
Length
uint64_t Length
Definition at line 26 of file defaultalloc.hpp.
Next
HeapSegHdr* Next
Definition at line 27 of file defaultalloc.hpp.