Fennix Project: NetworkDHCP::DHCP Class Reference
NetworkDHCP::DHCP Class Reference
#include <NetworkController.hpp>
Public Member Functions
DHCP (NetworkUDP::Socket *Socket, NetworkInterfaceManager::DeviceInterface *Interface)
~DHCP ()
void Request ()
void Request (InternetProtocol4 IP)
virtual void OnUDPPacketReceived (NetworkUDP::Socket *Socket, uint8_t *Data, uint64_t Length)
Data Fields
InternetProtocol4 IP = {.Address = {0x0, 0x0, 0x0, 0x0}}
IP address (Little-endian)
InternetProtocol4 Gateway = {.Address = {0x0, 0x0, 0x0, 0x0}}
Gateway address (Little-endian)
InternetProtocol4 SubnetworkMask = {.Address = {0x0, 0x0, 0x0, 0x0}}
Subnet mask (Little-endian)
InternetProtocol4 DomainNameSystem = {.Address = {0x0, 0x0, 0x0, 0x0}}
DNS server address (Little-endian)
Private Member Functions
void CreatePacket (DHCPHeader *Packet, uint8_t MessageType, uint32_t RequestIP)
void * GetOption (DHCPHeader *Packet, uint8_t Type)
Private Attributes
NetworkUDP::Socket * UDPSocket
NetworkInterfaceManager::DeviceInterface * Interface
bool Received = false
Additional Inherited Members
Protected Member Functions inherited from NetworkUDP::UDPEvents
UDPEvents ()
~UDPEvents ()
Detailed Description
Definition at line 792 of file NetworkController.hpp.
Constructor & Destructor Documentation
DHCP()
NetworkDHCP::DHCP::DHCP (NetworkUDP::Socket * Socket, NetworkInterfaceManager::DeviceInterface * Interface)
Definition at line 7 of file DynamicHostConfigurationProtocol.cpp.
     {
         netdbg("DHCP: Initializing.");
         this->UDPSocket = Socket;
         this->Interface = Interface;
         Socket->LocalPort = b16(68);
     }
References b16, Interface, NetworkUDP::Socket::LocalPort, netdbg, and UDPSocket.
~DHCP()
NetworkDHCP::DHCP::~DHCP ()
Definition at line 15 of file DynamicHostConfigurationProtocol.cpp.
     {
     }
Member Function Documentation
CreatePacket()
void NetworkDHCP::DHCP::CreatePacket (DHCPHeader * Packet, uint8_t MessageType, uint32_t RequestIP) private
Definition at line 19 of file DynamicHostConfigurationProtocol.cpp.
     {
         Packet->Opcode = b8(DHCP_OP_BOOTREQUEST);
         Packet->HardwareType = b8(1);
         Packet->HardwareAddressLength = b8(6);
         Packet->Hops = b8(0);
         Packet->TransactionID = b32(DHCP_TRANSACTION_ID);
         Packet->Flags = b16(0x40);
         uint48_t InterfaceMAC = b48(Interface->MAC.ToHex());
         memcpy(Packet->ClientHardwareAddress, &InterfaceMAC, sizeof(InterfaceMAC));
         uint8_t *Ptr = Packet->Options;
         *((uint32_t *)(Ptr)) = b32(0x63825363); // magic cookie
         Ptr += 4;
         *(Ptr++) = DHCP_OPTION_MESSAGE_TYPE;
         *(Ptr++) = DHCP_MESSAGE_TYPE_DISCOVER;
         *(Ptr++) = MessageType;
         *(Ptr++) = DHCP_OPTION_CLIENT_IDENTIFIER;
         *(Ptr++) = 0x07;
         *(Ptr++) = 0x01;
         memcpy(Ptr, &InterfaceMAC, sizeof(InterfaceMAC));
         Ptr += 6;
         *(Ptr++) = DHCP_OPTION_REQUESTED_IP;
         *(Ptr++) = 0x04;
         *((uint32_t *)(Ptr)) = b32(0x0a00020e);
         memcpy((uint32_t *)(Ptr), &RequestIP, 4);
         Ptr += 4;
         *(Ptr++) = DHCP_OPTION_HOST_NAME;
         char *HostName = (char *)KERNEL_NAME;
         *(Ptr++) = 1 + strlen(HostName);
         memcpy(Ptr, HostName, strlen(HostName));
         Ptr += strlen(HostName);
         *(Ptr++) = DHCP_OPTION_PAD;
         *(Ptr++) = DHCP_OPTION_PARAMETER_REQUEST_LIST;
         *(Ptr++) = DHCP_OPTION_COOKIE_SERVER;
         *(Ptr++) = DHCP_OPTION_SUBNETMASK;
         *(Ptr++) = DHCP_OPTION_ROUTER;
         *(Ptr++) = DHCP_OPTION_DOMAIN_NAME_SERVER;
         *(Ptr++) = DHCP_OPTION_DOMAIN_NAME;
         *(Ptr++) = DHCP_OPTION_NETBIOS_NAME_SERVERS;
         *(Ptr++) = DHCP_OPTION_NETBIOS_NODE_TYPE;
         *(Ptr++) = DHCP_OPTION_NETBIOS_SCOPE;
         *(Ptr++) = DHCP_OPTION_MAX_MESSAGE_SIZE;
         *(Ptr++) = DHCP_OPTION_END;
     }
References b16, b32, b48, b8, NetworkDHCP::DHCP_MESSAGE_TYPE_DISCOVER, NetworkDHCP::DHCP_OP_BOOTREQUEST, NetworkDHCP::DHCP_OPTION_CLIENT_IDENTIFIER, NetworkDHCP::DHCP_OPTION_COOKIE_SERVER, NetworkDHCP::DHCP_OPTION_DOMAIN_NAME, NetworkDHCP::DHCP_OPTION_DOMAIN_NAME_SERVER, NetworkDHCP::DHCP_OPTION_END, NetworkDHCP::DHCP_OPTION_HOST_NAME, NetworkDHCP::DHCP_OPTION_MAX_MESSAGE_SIZE, NetworkDHCP::DHCP_OPTION_MESSAGE_TYPE, NetworkDHCP::DHCP_OPTION_NETBIOS_NAME_SERVERS, NetworkDHCP::DHCP_OPTION_NETBIOS_NODE_TYPE, NetworkDHCP::DHCP_OPTION_NETBIOS_SCOPE, NetworkDHCP::DHCP_OPTION_PAD, NetworkDHCP::DHCP_OPTION_PARAMETER_REQUEST_LIST, NetworkDHCP::DHCP_OPTION_REQUESTED_IP, NetworkDHCP::DHCP_OPTION_ROUTER, NetworkDHCP::DHCP_OPTION_SUBNETMASK, DHCP_TRANSACTION_ID, Interface, NetworkInterfaceManager::DeviceInterface::MAC, memcpy(), PS2Mouse::Packet, strlen(), and MediaAccessControl::ToHex().
Referenced by Request().
GetOption()
void * NetworkDHCP::DHCP::GetOption (DHCPHeader * Packet, uint8_t Type) private
Definition at line 103 of file DynamicHostConfigurationProtocol.cpp.
     {
         uint8_t *Option = Packet->Options + 4;
         uint8_t Current = *Option;
         while (Current != 0xff)
         {
             uint8_t OptionLength = *(Option + 1);
             if (Current == Type)
                 return Option + 2;
             Option += (2 + OptionLength);
             Current = *Option;
         }
         warn("DHCP: Option %#x not found", Type);
         return nullptr;
     }
References PS2Mouse::Packet, Type, and warn.
Referenced by OnUDPPacketReceived().
OnUDPPacketReceived()
void NetworkDHCP::DHCP::OnUDPPacketReceived (NetworkUDP::Socket * Socket, uint8_t * Data, uint64_t Length) virtual
Reimplemented from NetworkUDP::UDPEvents.
Definition at line 119 of file DynamicHostConfigurationProtocol.cpp.
     {
         DHCPHeader *Packet = (DHCPHeader *)Data;
         uint8_t *MessageType = (uint8_t *)GetOption(Packet, DHCP_OPTION_MESSAGE_TYPE);
         switch (*MessageType)
         {
         case DHCP_OPTION_TIME_OFFSET:
             this->Request(InternetProtocol4().FromHex(Packet->YourIP));
             break;
         case DHCP_OPTION_NAME_SERVER:
             this->IP.FromHex(Packet->YourIP);
             this->Gateway.FromHex(*(uint32_t *)GetOption(Packet, DHCP_OPTION_ROUTER));
             this->DomainNameSystem.FromHex(*(uint32_t *)GetOption(Packet, DHCP_OPTION_DOMAIN_NAME_SERVER));
             this->SubnetworkMask.FromHex((*(uint32_t *)GetOption(Packet, DHCP_OPTION_SUBNETMASK)));
             this->Received = true;
             break;
         default:
             netdbg("DHCP: Received unknown message type %#x", *MessageType);
             break;
         }
     }
References NetworkDHCP::DHCP_OPTION_DOMAIN_NAME_SERVER, NetworkDHCP::DHCP_OPTION_MESSAGE_TYPE, NetworkDHCP::DHCP_OPTION_NAME_SERVER, NetworkDHCP::DHCP_OPTION_ROUTER, NetworkDHCP::DHCP_OPTION_SUBNETMASK, NetworkDHCP::DHCP_OPTION_TIME_OFFSET, DomainNameSystem, InternetProtocol4::FromHex(), Gateway, GetOption(), IP, netdbg, PS2Mouse::Packet, Received, Request(), SubnetworkMask, and NetworkDHCP::DHCPHeader::YourIP.
Request() [1/2]
void NetworkDHCP::DHCP::Request ()
Definition at line 72 of file DynamicHostConfigurationProtocol.cpp.
     {
         netdbg("DHCP: Requesting IP address");
         DHCPHeader packet;
         memset(&packet, 0, sizeof(DHCPHeader));
         CreatePacket(&packet, DHCP_MESSAGE_TYPE_DISCOVER, 0x00000000);
         this->UDPSocket->SocketUDP->Send(this->UDPSocket, (uint8_t *)&packet, sizeof(DHCPHeader));
         int RequestTimeout = 10;
         while (!Received)
         {
             if (--RequestTimeout == 0)
             {
                 warn("DHCP: Request timeout.");
                 break;
             }
             sleep(5);
         }
     }
References CreatePacket(), NetworkDHCP::DHCP_MESSAGE_TYPE_DISCOVER, memset(), netdbg, Received, NetworkUDP::UDP::Send(), sleep(), NetworkUDP::Socket::SocketUDP, UDPSocket, and warn.
Referenced by OnUDPPacketReceived(), and NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
Request() [2/2]
void NetworkDHCP::DHCP::Request (InternetProtocol4 IP)
Definition at line 93 of file DynamicHostConfigurationProtocol.cpp.
     {
         netdbg("DHCP: Requesting IP address %d.%d.%d.%d", IP.Address[0], IP.Address[1], IP.Address[2], IP.Address[3]);
         DHCPHeader packet;
         memset(&packet, 0, sizeof(DHCPHeader));
         CreatePacket(&packet, DHCP_MESSAGE_TYPE_REQUEST, IP.ToHex());
         UDPSocket->SocketUDP->Send(UDPSocket, (uint8_t *)&packet, sizeof(DHCPHeader));
     }
References InternetProtocol4::Address, CreatePacket(), NetworkDHCP::DHCP_MESSAGE_TYPE_REQUEST, IP, memset(), netdbg, NetworkUDP::UDP::Send(), NetworkUDP::Socket::SocketUDP, InternetProtocol4::ToHex(), and UDPSocket.
Field Documentation
DomainNameSystem
InternetProtocol4 NetworkDHCP::DHCP::DomainNameSystem = {.Address = {0x0, 0x0, 0x0, 0x0}}
DNS server address (Little-endian)
Definition at line 810 of file NetworkController.hpp.
Referenced by OnUDPPacketReceived(), and NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
Gateway
InternetProtocol4 NetworkDHCP::DHCP::Gateway = {.Address = {0x0, 0x0, 0x0, 0x0}}
Gateway address (Little-endian)
Definition at line 806 of file NetworkController.hpp.
Referenced by OnUDPPacketReceived(), and NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
Interface
NetworkInterfaceManager::DeviceInterface* NetworkDHCP::DHCP::Interface private
Definition at line 796 of file NetworkController.hpp.
Referenced by CreatePacket(), and DHCP().
IP
InternetProtocol4 NetworkDHCP::DHCP::IP = {.Address = {0x0, 0x0, 0x0, 0x0}}
IP address (Little-endian)
Definition at line 804 of file NetworkController.hpp.
Referenced by OnUDPPacketReceived(), Request(), and NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
Received
bool NetworkDHCP::DHCP::Received = false private
Definition at line 797 of file NetworkController.hpp.
Referenced by OnUDPPacketReceived(), and Request().
SubnetworkMask
InternetProtocol4 NetworkDHCP::DHCP::SubnetworkMask = {.Address = {0x0, 0x0, 0x0, 0x0}}
Subnet mask (Little-endian)
Definition at line 808 of file NetworkController.hpp.
Referenced by OnUDPPacketReceived(), and NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
UDPSocket
NetworkUDP::Socket* NetworkDHCP::DHCP::UDPSocket private
Definition at line 795 of file NetworkController.hpp.
Referenced by DHCP(), and Request().
The documentation for this class was generated from the following files:
kernel/network/NetworkController.hpp
kernel/network/DynamicHostConfigurationProtocol.cpp