Fennix Project: Tasking::Multitasking Class Reference
Tasking::Multitasking Class Reference
#include <internal_task.h>
Public Member Functions
PCB * CreateProcess (PCB *Parent, char *Name, ELEVATION Elevation, int Priority=1)
TCB * CreateThread (PCB *Parent, uint64_t InstructionPointer, uint64_t Arg0, uint64_t Arg1, int Priority=1, enum Architecture Architecture=Architecture::x64, enum Platform Platform=Platform::Native)
Multitasking ()
~Multitasking ()
Data Fields
Vector< PCB * > ListProcess
uint64_t NextPID = 0
uint64_t NextTID = 0
PCB * IdleProcess = nullptr
TCB * IdleThread = nullptr
Detailed Description
Definition at line 96 of file internal_task.h.
Constructor & Destructor Documentation
Multitasking()
Tasking::Multitasking::Multitasking ()
Definition at line 767 of file Multitasking.cpp.
     {
         CurrentTaskingMode = TaskingMode::Multi;
         CriticalSectionData = new Critical::CriticalSectionData;
         apic->RedirectIRQ(CurrentCPU->ID, SchedulerInterrupt - IRQ0, 1);
         TriggerOneShot(SchedulerInterrupt, 100);
     }
References apic, Tasking::CriticalSectionData, CurrentCPU, CurrentTaskingMode, Multi, APIC::APIC::RedirectIRQ(), SchedulerInterrupt, and Tasking::TriggerOneShot().
~Multitasking()
Tasking::Multitasking::~Multitasking ()
Definition at line 775 of file Multitasking.cpp.
     {
         debug("Multitasking destructor called.");
         CurrentTaskingMode = TaskingMode::None;
         MultitaskingSchedulerEnabled = false;
         delete CriticalSectionData;
         foreach (PCB *pcb in mt->ListProcess)
         {
             if (InvalidPCB(pcb))
                 continue;
             pcb->Status = STATUS::Terminated;
             debug("Process %s terminated.", pcb->Name);
             RemoveProcess(pcb);
         }
     }
References Tasking::CriticalSectionData, CurrentTaskingMode, debug, Tasking::InvalidPCB(), ListProcess, Tasking::mt, Tasking::MultitaskingSchedulerEnabled, None, and Tasking::RemoveProcess().
Member Function Documentation
CreateProcess()
PCB * Tasking::Multitasking::CreateProcess (PCB * Parent, char * Name, ELEVATION Elevation, int Priority = 1)
Definition at line 224 of file Multitasking.cpp.
     {
         EnterCriticalSection;
         PCB *process = new PCB;
         process->Checksum = Checksum::PROCESS_CHECKSUM;
         SetInfo(&process->Info);
         process->Info.Priority = Priority;
         process->Info.Architecture = Architecture::UnknownArchitecture;
         process->Info.Platform = Platform::UnknownPlatform;
         process->ID = this->NextPID++;
         process->Offset = 0;
         process->Security.Token = CreateToken();
         trace("New security token created %p", process->Security.Token);
         if (Elevation == ELEVATION::Idle || Elevation == ELEVATION::Kernel || Elevation == ELEVATION::System)
             TrustToken(process->Security.Token, true, process->ID, TokenTrustLevel::TrustedByKernel);
         process->Elevation = Elevation;
         process->Status = STATUS::Ready;
         memcpy(process->Name, Name, sizeof(process->Name));
         if (Parent)
         {
             process->Parent = Parent;
             process->Parent->Children.push_back(process);
         }
         CR3 cr3;
         if (Elevation == ELEVATION::User)
             cr3.raw = KernelPageTableAllocator->CreatePageTable(true).raw;
         else
             cr3.raw = KernelPageTableAllocator->CreatePageTable(false).raw;
         process->PageTable = cr3;
         schedbg("Address space for %s has been created at %#llx", Name, process->PageTable.raw);
         ListProcess.push_back(process);
         trace("New process %s (%d) created.", process->Name, process->ID);
         LeaveCriticalSection;
         return process;
     }
References CreateToken(), EnterCriticalSection, KernelPageTableAllocator, LeaveCriticalSection, ListProcess, memcpy(), NextPID, schedbg, Tasking::SetInfo(), trace, and TrustToken().
Referenced by Tasking::MultiTaskingSchedulerHandler(), StartTasking(), and SysCreateProcess().
CreateThread()
TCB * Tasking::Multitasking::CreateThread (PCB * Parent, uint64_t InstructionPointer, uint64_t Arg0, uint64_t Arg1, int Priority = 1, enum Architecture Architecture = Architecture::x64, enum Platform Platform = Platform::Native)
Definition at line 261 of file Multitasking.cpp.
     {
         EnterCriticalSection;
         if (Parent == nullptr || Parent->Checksum != Checksum::PROCESS_CHECKSUM)
         {
             err("Null parent process not allowed.");
             LeaveCriticalSection;
             return nullptr;
         }
         TCB *thread = new TCB;
         thread->Checksum = Checksum::THREAD_CHECKSUM;
         thread->ID = this->NextTID++;
         thread->Status = STATUS::Ready;
         thread->Security.Token = CreateToken();
         thread->Parent = Parent;
         memcpy(thread->Name, Parent->Name, sizeof(Parent->Name));
         memset(&thread->Registers, 0, sizeof(TrapFrame));
         schedbg("Parent elevation is %d", Parent->Elevation);
         switch (Parent->Elevation)
         {
         case ELEVATION::System:
             err("Elevation not supported. Using kernel elevation.");
             [[fallthrough]];
         case ELEVATION::Idle:
         case ELEVATION::Kernel:
             TrustToken(thread->Security.Token, false, thread->ID, TokenTrustLevel::TrustedByKernel);
             thread->gs = (uint64_t)thread;
             thread->fs = rdmsr(MSR_FS_BASE);
             thread->Registers.cs = GDT_KERNEL_CODE;
             thread->Registers.ss = GDT_KERNEL_DATA;
             thread->Registers.rflags.always_one = 1;
             thread->Registers.rflags.IF = 1;
             thread->Registers.rflags.ID = 1;
             thread->Stack = KernelStackAllocator->AllocateStack();
             thread->Registers.STACK = (uint64_t)thread->Stack;
             POKE(uint64_t, thread->Registers.rsp) = (uint64_t)ThreadDoExit;
             break;
         case ELEVATION::User:
             TrustToken(thread->Security.Token, false, thread->ID, TokenTrustLevel::Untrusted);
             thread->gs = 0;
             thread->fs = rdmsr(MSR_FS_BASE);
             thread->Registers.cs = GDT_USER_CODE;
             thread->Registers.ss = GDT_USER_DATA;
             thread->Registers.rflags.always_one = 1;
             thread->Registers.rflags.IF = 1;
             thread->Registers.rflags.ID = 1;
             thread->Stack = KernelStackAllocator->AllocateStack(true);
             thread->Registers.STACK = (uint64_t)thread->Stack;
             /*
                 We can't add ThreadDoExit at the end of the stack because it will
                 trigger a page fault or invalid general protection fault exception (because
                 it will execute kernel code ofc).
                 We need to leave the libc's crt to make a syscall when the thread is exited.
             */
             break;
         default:
             err("Unknown elevation.");
             delete thread;
             LeaveCriticalSection;
             return nullptr;
         }
         thread->Registers.FUNCTION = (InstructionPointer + Parent->Offset);
         thread->Registers.ARG0 = Arg0; // args0
         thread->Registers.ARG1 = Arg1; // args1
         SetInfo(&thread->Info);
         thread->Info.Architecture = Architecture;
         thread->Info.Platform = Platform;
         thread->Info.Priority = Priority;
         Parent->Threads.push_back(thread);
         trace("New thread %d created (%s).", thread->ID, thread->Name);
         LeaveCriticalSection;
         return thread;
     }
References CreateToken(), EnterCriticalSection, err, GDT_KERNEL_CODE, GDT_KERNEL_DATA, GDT_USER_CODE, GDT_USER_DATA, KernelStackAllocator, LeaveCriticalSection, memcpy(), memset(), MSR_FS_BASE, NextTID, POKE, rdmsr(), schedbg, Tasking::SetInfo(), Tasking::ThreadDoExit(), trace, and TrustToken().
Referenced by Tasking::MultiTaskingSchedulerHandler(), StartTasking(), and SysCreateThread().
Field Documentation
IdleProcess
PCB* Tasking::Multitasking::IdleProcess = nullptr
Definition at line 103 of file internal_task.h.
Referenced by Tasking::MultiTaskingSchedulerHandler().
IdleThread
TCB* Tasking::Multitasking::IdleThread = nullptr
Definition at line 104 of file internal_task.h.
Referenced by Tasking::MultiTaskingSchedulerHandler().
ListProcess
Vector<PCB *> Tasking::Multitasking::ListProcess
Definition at line 100 of file internal_task.h.
Referenced by CreateProcess(), Tasking::MultiTaskingSchedulerHandler(), Tasking::RemoveProcess(), SysGetProcessByPID(), SysGetThreadByTID(), and ~Multitasking().
NextPID
uint64_t Tasking::Multitasking::NextPID = 0
Definition at line 101 of file internal_task.h.
Referenced by CreateProcess().
NextTID
uint64_t Tasking::Multitasking::NextTID = 0
Definition at line 101 of file internal_task.h.
Referenced by CreateThread().
The documentation for this class was generated from the following files:
kernel/include/internal_task.h
kernel/proc/Multitasking.cpp