Fennix Project: NetworkARP::ARP Class Reference
NetworkARP::ARP Class Reference
#include <NetworkController.hpp>
Public Member Functions
ARP (NetworkEthernet::Ethernet *Ethernet)
~ARP ()
uint48_t Resolve (InternetProtocol4 IP)
Resolve an IP address to a MAC address.
void Broadcast (InternetProtocol4 IP)
Broadcast an ARP packet.
Public Member Functions inherited from NetworkEthernet::EthernetEvents
FrameType GetFrameType ()
virtual void OnEthernetPacketSent (EthernetPacket *Packet)
Private Types
enum DAType { DA_ADD = 1, DA_DEL = 2, DA_SEARCH = 3, DA_UPDATE = 4 }
Private Member Functions
DiscoveredAddress * ManageDA (DAType Type, InternetProtocol4 IP, MediaAccessControl MAC)
DiscoveredAddress * Search (InternetProtocol4 TargetIP)
DiscoveredAddress * Update (InternetProtocol4 TargetIP, MediaAccessControl TargetMAC)
bool OnEthernetPacketReceived (uint8_t *Data, uint64_t Length)
Private Attributes
NetworkEthernet::Ethernet * Ethernet
Vector< NetworkARP::DiscoveredAddress * > DiscoveredAddresses
Additional Inherited Members
Protected Member Functions inherited from NetworkEthernet::EthernetEvents
EthernetEvents (FrameType Type)
~EthernetEvents ()
Detailed Description
Definition at line 346 of file NetworkController.hpp.
Member Enumeration Documentation
DAType
enum NetworkARP::ARP::DAType private
Enumerator
DA_ADD
DA_DEL
DA_SEARCH
DA_UPDATE
Definition at line 351 of file NetworkController.hpp.
         {
             DA_ADD = 1,
             DA_DEL = 2,
             DA_SEARCH = 3,
             DA_UPDATE = 4
         };
Constructor & Destructor Documentation
ARP()
NetworkARP::ARP::ARP (NetworkEthernet::Ethernet * Ethernet)
Definition at line 52 of file AddressResolutionProtocol.cpp.
                                               : NetworkEthernet::EthernetEvents(NetworkEthernet::TYPE_ARP)
     {
         netdbg("ARP: Initializing.");
         this->Ethernet = Ethernet;
     }
References Ethernet, and netdbg.
~ARP()
NetworkARP::ARP::~ARP ()
Definition at line 58 of file AddressResolutionProtocol.cpp.
     {
     }
Member Function Documentation
Broadcast()
void NetworkARP::ARP::Broadcast (InternetProtocol4 IP)
Broadcast an ARP packet.
Parameters
IP The IP address to broadcast.
Definition at line 125 of file AddressResolutionProtocol.cpp.
     {
         netdbg("ARP: Sending broadcast");
         uint64_t ResolvedMAC = this->Resolve(IP);
         ARPHeader *Header = new ARPHeader;
         Header->HardwareType = b16(ARPHardwareType::HTYPE_ETHERNET);
         Header->ProtocolType = b16(NetworkEthernet::FrameType::TYPE_IPV4);
         Header->HardwareSize = b8(0x6);
         Header->ProtocolSize = b8(0x4);
         Header->Operation = b16(ARPOperation::REQUEST);
         Header->SenderMAC = b48(Ethernet->GetInterface()->MAC.ToHex());
         Header->SenderIP = b32(Ethernet->GetInterface()->IP.ToHex());
         Header->TargetMAC = ResolvedMAC;
         Header->TargetIP = IP.ToHex();
         Ethernet->Send(MediaAccessControl().FromHex(ResolvedMAC), NetworkEthernet::FrameType::TYPE_ARP, (uint8_t *)Header, sizeof(ARPHeader));
         delete Header;
     }
References b16, b32, b48, b8, Ethernet, NetworkEthernet::Ethernet::GetInterface(), Header, NetworkARP::HTYPE_ETHERNET, NetworkInterfaceManager::DeviceInterface::IP, NetworkInterfaceManager::DeviceInterface::MAC, netdbg, NetworkARP::REQUEST, Resolve(), NetworkEthernet::Ethernet::Send(), MediaAccessControl::ToHex(), InternetProtocol4::ToHex(), NetworkEthernet::TYPE_ARP, and NetworkEthernet::TYPE_IPV4.
Referenced by NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
ManageDA()
DiscoveredAddress * NetworkARP::ARP::ManageDA (DAType Type, InternetProtocol4 IP, MediaAccessControl MAC) private
Definition at line 9 of file AddressResolutionProtocol.cpp.
     {
         // TODO: Compare IPv6 too.
         DiscoveredAddress *tmp = new DiscoveredAddress;
         switch (Type)
         {
         case DA_ADD:
             tmp->IP = IP;
             tmp->MAC = MAC;
             DiscoveredAddresses.push_back(tmp);
             return tmp;
         case DA_DEL:
             for (uint64_t i = 0; i < DiscoveredAddresses.size(); i++)
                 if (DiscoveredAddresses[i]->IP == IP)
                 {
                     DiscoveredAddress *tmp = DiscoveredAddresses[i];
                     DiscoveredAddresses.remove(i);
                     return tmp;
                 }
             delete tmp;
             return nullptr;
         case DA_SEARCH:
             delete tmp;
             for (uint64_t i = 0; i < DiscoveredAddresses.size(); i++)
                 if (DiscoveredAddresses[i]->IP == IP)
                 {
                     return DiscoveredAddresses[i];
                 }
             return nullptr;
         case DA_UPDATE:
             delete tmp;
             for (uint64_t i = 0; i < DiscoveredAddresses.size(); i++)
                 if (DiscoveredAddresses[i]->IP == IP)
                 {
                     DiscoveredAddresses[i]->MAC = MAC;
                     return DiscoveredAddresses[i];
                 }
             return nullptr;
         }
         delete tmp;
         return nullptr;
     }
References DA_ADD, DA_DEL, DA_SEARCH, DA_UPDATE, DiscoveredAddresses, NetworkARP::DiscoveredAddress::IP, NetworkARP::DiscoveredAddress::MAC, and Type.
Referenced by OnEthernetPacketReceived(), Search(), and Update().
OnEthernetPacketReceived()
bool NetworkARP::ARP::OnEthernetPacketReceived (uint8_t * Data, uint64_t Length) private virtual
Reimplemented from NetworkEthernet::EthernetEvents.
Definition at line 143 of file AddressResolutionProtocol.cpp.
     {
         netdbg("ARP: Received packet");
         ARPHeader *Header = (ARPHeader *)Data;
         InternetProtocol4 SenderIPv4;
         SenderIPv4.FromHex(b32(Header->SenderIP));
         if (b16(Header->HardwareType) != ARPHardwareType::HTYPE_ETHERNET || b16(Header->ProtocolType) != NetworkEthernet::FrameType::TYPE_IPV4)
         {
             warn("ARP: [DA] Invalid hardware/protocol type (%d/%d)", Header->HardwareType, Header->ProtocolType);
             return false;
         }
         if (ManageDA(DA_SEARCH, InternetProtocol4().FromHex(Header->SenderIP), MediaAccessControl().FromHex(Header->SenderMAC)) == nullptr)
         {
             netdbg("ARP: [DA] Discovered new address %d.%d.%d.%d", SenderIPv4.Address[3], SenderIPv4.Address[2], SenderIPv4.Address[1], SenderIPv4.Address[0]);
             ManageDA(DA_ADD, InternetProtocol4().FromHex(Header->SenderIP), MediaAccessControl().FromHex(Header->SenderMAC));
         }
         else
         {
             netdbg("ARP: [DA] Updated address %d.%d.%d.%d", SenderIPv4.Address[3], SenderIPv4.Address[2], SenderIPv4.Address[1], SenderIPv4.Address[0]);
             ManageDA(DA_UPDATE, InternetProtocol4().FromHex(Header->SenderIP), MediaAccessControl().FromHex(Header->SenderMAC));
         }
         switch (b16(Header->Operation))
         {
         case ARPOperation::REQUEST:
             netdbg("ARP: Received request from %d.%d.%d.%d", SenderIPv4.Address[3], SenderIPv4.Address[2], SenderIPv4.Address[1], SenderIPv4.Address[0]);
             Header->TargetMAC = Header->SenderMAC;
             Header->TargetIP = Header->SenderIP;
             Header->SenderMAC = b48(Ethernet->GetInterface()->MAC.ToHex());
             Header->SenderIP = b32(Ethernet->GetInterface()->IP.ToHex());
             Header->Operation = b16(ARPOperation::REPLY);
             Ethernet->Send(MediaAccessControl().FromHex(Header->TargetMAC), NetworkEthernet::FrameType::TYPE_ARP, (uint8_t *)Header, sizeof(ARPHeader));
             netdbg("ARP: Sent request for %d.%d.%d.%d", SenderIPv4.Address[0], SenderIPv4.Address[1], SenderIPv4.Address[2], SenderIPv4.Address[3]);
             break;
         case ARPOperation::REPLY:
             fixme("ARP: Received reply from %d.%d.%d.%d", SenderIPv4.Address[0], SenderIPv4.Address[1], SenderIPv4.Address[2], SenderIPv4.Address[3]);
             break;
         default:
             warn("ARP: Invalid operation (%d)", Header->Operation);
             break;
         }
         return false;
     }
References InternetProtocol4::Address, b16, b32, b48, DA_ADD, DA_SEARCH, DA_UPDATE, Ethernet, fixme(), InternetProtocol4::FromHex(), NetworkEthernet::Ethernet::GetInterface(), Header, NetworkARP::HTYPE_ETHERNET, NetworkInterfaceManager::DeviceInterface::IP, NetworkInterfaceManager::DeviceInterface::MAC, ManageDA(), netdbg, NetworkARP::REPLY, NetworkARP::REQUEST, NetworkEthernet::Ethernet::Send(), MediaAccessControl::ToHex(), InternetProtocol4::ToHex(), NetworkEthernet::TYPE_ARP, NetworkEthernet::TYPE_IPV4, and warn.
Resolve()
uint48_t NetworkARP::ARP::Resolve (InternetProtocol4 IP)
Resolve an IP address to a MAC address.
Parameters
IP The IP address to resolve. (Little-endian)
Returns
uint48_t The MAC address of the IP address.
Definition at line 84 of file AddressResolutionProtocol.cpp.
     {
         netdbg("ARP: Resolving %d.%d.%d.%d", IP.Address[3], IP.Address[2], IP.Address[1], IP.Address[0]);
         if (IP == 0xFFFFFFFF)
             return 0xFFFFFFFFFFFF;
         uint48_t ret = this->Search(IP)->MAC.ToHex();
         netdbg("ARP: Resolved %d.%d.%d.%d to %x", IP.Address[3], IP.Address[2], IP.Address[1], IP.Address[0], ret);
         if (ret == 0xFFFFFFFFFFFF)
         {
             ARPHeader *Header = new ARPHeader;
             Header->HardwareType = ARPHardwareType::HTYPE_ETHERNET;
             Header->ProtocolType = NetworkEthernet::FrameType::TYPE_IPV4;
             Header->HardwareSize = 6;
             Header->ProtocolSize = 4;
             Header->Operation = ARPOperation::REQUEST;
             Header->SenderMAC = Ethernet->GetInterface()->MAC.ToHex();
             Header->SenderIP = Ethernet->GetInterface()->IP.ToHex();
             Header->TargetMAC = 0xFFFFFFFFFFFF;
             Header->TargetIP = IP.ToHex();
             Ethernet->Send({.Address = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}}, NetworkEthernet::FrameType::TYPE_ARP, (uint8_t *)Header, sizeof(ARPHeader));
             delete Header;
             netdbg("ARP: Sent request");
         }
         int RequestTimeout = 10;
         while (ret == 0xFFFFFFFFFFFF)
         {
             ret = this->Search(IP)->MAC.ToHex();
             if (--RequestTimeout == 0)
             {
                 warn("ARP: Request timeout.");
                 return 0;
             }
             sleep(5);
         }
         return ret;
     }
References InternetProtocol4::Address, Ethernet, NetworkEthernet::Ethernet::GetInterface(), Header, NetworkARP::HTYPE_ETHERNET, NetworkInterfaceManager::DeviceInterface::IP, NetworkInterfaceManager::DeviceInterface::MAC, NetworkARP::DiscoveredAddress::MAC, netdbg, NetworkARP::REQUEST, Search(), NetworkEthernet::Ethernet::Send(), sleep(), MediaAccessControl::ToHex(), InternetProtocol4::ToHex(), NetworkEthernet::TYPE_ARP, NetworkEthernet::TYPE_IPV4, and warn.
Referenced by Broadcast(), and NetworkIPv4::IPv4::Send().
Search()
DiscoveredAddress * NetworkARP::ARP::Search (InternetProtocol4 TargetIP) private
Definition at line 66 of file AddressResolutionProtocol.cpp.
     {
         DiscoveredAddress *ret = ManageDA(DA_SEARCH, TargetIP, MediaAccessControl());
         if (ret)
             return ret;
         netdbg("ARP: [DA] No address found for %d.%d.%d.%d", TargetIP.Address[0], TargetIP.Address[1], TargetIP.Address[2], TargetIP.Address[3]);
         return &InvalidRet;
     }
References DA_SEARCH, NetworkARP::InvalidRet, ManageDA(), netdbg, and TargetIP.
Referenced by Resolve().
Update()
DiscoveredAddress * NetworkARP::ARP::Update (InternetProtocol4 TargetIP, MediaAccessControl TargetMAC) private
Definition at line 75 of file AddressResolutionProtocol.cpp.
     {
         DiscoveredAddress *ret = ManageDA(DA_UPDATE, TargetIP, TargetMAC);
         if (ret)
             return ret;
         warn("ARP: [DA] No address found for %d.%d.%d.%d", TargetIP.Address[0], TargetIP.Address[1], TargetIP.Address[2], TargetIP.Address[3]);
         return &InvalidRet;
     }
References DA_UPDATE, NetworkARP::InvalidRet, ManageDA(), TargetIP, TargetMAC, and warn.
Field Documentation
DiscoveredAddresses
Vector<NetworkARP::DiscoveredAddress *> NetworkARP::ARP::DiscoveredAddresses private
Definition at line 359 of file NetworkController.hpp.
Referenced by ManageDA().
Ethernet
NetworkEthernet::Ethernet* NetworkARP::ARP::Ethernet private
Definition at line 349 of file NetworkController.hpp.
Referenced by ARP(), Broadcast(), OnEthernetPacketReceived(), and Resolve().
The documentation for this class was generated from the following files:
kernel/network/NetworkController.hpp
kernel/network/AddressResolutionProtocol.cpp