Fennix Project: kernel/drivers/serial.c File Reference
serial.c File Reference
#include "serial.h"
#include <lock.h>
#include <io.h>
Functions
NEWLOCK (serial_lock)
int init_serial (int serial_port)
Initialize the serial port.
int is_transmit_empty (int serial_port)
int serial_received (int serial_port)
char read_serial (int serial_port)
void write_serial (int serial_port, char a)
void serial_write_text (int serial_port, char *text)
Sends a text to the serial port (Used by the debug system, don't use this!!)
Function Documentation
init_serial()
int init_serial (int serial_port)
Initialize the serial port.
Parameters
serial_port
Returns
0 or -1 if the serial port is faulty.
Definition at line 9 of file serial.c.
 {
     LOCK(serial_lock);
     outb(serial_port + 7, 0x55);
     if (inb(serial_port + 7) != 0x55)
     {
         UNLOCK(serial_lock);
         return -1;
     }
     outb(serial_port + 1, 0x00);
     outb(serial_port + 3, SERIAL_ENABLE_DLAB);
     outb(serial_port + 0, 0x01);
     outb(serial_port + 1, SERIAL_RATE_38400_HI);
     outb(serial_port + 3, 0x03);
     outb(serial_port + 2, 0xC7);
     outb(serial_port + 4, 0x0B);
     if (inb(serial_port + 0) != 0xAE)
     {
         UNLOCK(serial_lock);
         return -1;
     }
     outb(serial_port + 4, 0x0F);
     UNLOCK(serial_lock);
     return 0;
 }
References inb, LOCK, outb, SERIAL_ENABLE_DLAB, SERIAL_RATE_38400_HI, and UNLOCK.
Referenced by init_limine().
is_transmit_empty()
int is_transmit_empty (int serial_port)
Definition at line 38 of file serial.c.
 { return inb(serial_port + 5) & SERIAL_BUFFER_EMPTY; }
References inb, and SERIAL_BUFFER_EMPTY.
Referenced by write_serial().
NEWLOCK()
NEWLOCK (serial_lock)
read_serial()
char read_serial (int serial_port)
Definition at line 42 of file serial.c.
 {
     while (serial_received(serial_port) == 0)
         ;
     return inb(serial_port);
 }
References inb, and serial_received().
Referenced by FileSystem::ReadFSFunction().
serial_received()
int serial_received (int serial_port)
Definition at line 40 of file serial.c.
 { return inb(serial_port + 5) & 1; }
References inb.
Referenced by read_serial().
serial_write_text()
void serial_write_text (int serial_port, char * text)
Sends a text to the serial port (Used by the debug system, don't use this!!)
Parameters
serial_port
text
Definition at line 56 of file serial.c.
 {
     // LOCK(serial_lock);
     for (long unsigned i = 0; i < (strlen(text)); i++)
         write_serial(serial_port, text[i]);
     // UNLOCK(serial_lock);
 }
References strlen(), and write_serial().
Referenced by deadlock_handler(), debug_printf(), and init_limine().
write_serial()
void write_serial (int serial_port, char a)
Definition at line 49 of file serial.c.
 {
     while (is_transmit_empty(serial_port) == 0)
         ;
     outb(serial_port, a);
 }
References is_transmit_empty(), and outb.
Referenced by deadlock_handler(), serial_write_text(), serialwrite_wrapper(), and FileSystem::WriteFSFunction().