Fennix Project: kernel/cpu/DSDT.cpp File Reference
DSDT.cpp File Reference
#include "acpi.hpp"
#include <io.h>
#include "../timer.h"
#include "apic.hpp"
#include "smp.hpp"
#include <int.h>
Namespaces
ACPI
Macros
#define ACPI_TIMER 0x0001
#define ACPI_BUSMASTER 0x0010
#define ACPI_GLOBAL 0x0020
#define ACPI_POWER_BUTTON 0x0100
#define ACPI_SLEEP_BUTTON 0x0200
#define ACPI_RTC_ALARM 0x0400
#define ACPI_PCIE_WAKE 0x4000
#define ACPI_WAKE 0x8000
#define ACPI_ENABLED 0x0001
#define ACPI_SLEEP 0x2000
#define ACPI_GAS_MMIO 0
#define ACPI_GAS_IO 1
#define ACPI_GAS_PCI 2
Functions
void SCIHandler (TrapFrame *regs)
ACPI::__attribute__ ((always_inline)) inline bool IsCanonical(uint64_t Address)
Variables
ACPI::DSDT * dsdt = nullptr
Macro Definition Documentation
ACPI_BUSMASTER
#define ACPI_BUSMASTER 0x0010
Definition at line 14 of file DSDT.cpp.
ACPI_ENABLED
#define ACPI_ENABLED 0x0001
Definition at line 53 of file DSDT.cpp.
ACPI_GAS_IO
#define ACPI_GAS_IO 1
Definition at line 57 of file DSDT.cpp.
ACPI_GAS_MMIO
#define ACPI_GAS_MMIO 0
Definition at line 56 of file DSDT.cpp.
ACPI_GAS_PCI
#define ACPI_GAS_PCI 2
Definition at line 58 of file DSDT.cpp.
ACPI_GLOBAL
#define ACPI_GLOBAL 0x0020
Definition at line 15 of file DSDT.cpp.
ACPI_PCIE_WAKE
#define ACPI_PCIE_WAKE 0x4000
Definition at line 19 of file DSDT.cpp.
ACPI_POWER_BUTTON
#define ACPI_POWER_BUTTON 0x0100
Definition at line 16 of file DSDT.cpp.
ACPI_RTC_ALARM
#define ACPI_RTC_ALARM 0x0400
Definition at line 18 of file DSDT.cpp.
ACPI_SLEEP
#define ACPI_SLEEP 0x2000
Definition at line 54 of file DSDT.cpp.
ACPI_SLEEP_BUTTON
#define ACPI_SLEEP_BUTTON 0x0200
Definition at line 17 of file DSDT.cpp.
ACPI_TIMER
#define ACPI_TIMER 0x0001
Definition at line 13 of file DSDT.cpp.
ACPI_WAKE
#define ACPI_WAKE 0x8000
Definition at line 20 of file DSDT.cpp.
Function Documentation
SCIHandler()
void SCIHandler (TrapFrame * regs)
Definition at line 22 of file DSDT.cpp.
 {
     debug("SCI Handle Triggered");
     uint16_t event = dsdt->GetSCIevent();
     debug("SCI Event: %#llx", event);
     if (event & ACPI_TIMER)
         event &= ~ACPI_TIMER; // remove the ACPI timer flag
     switch (event)
     {
     case ACPI_POWER_BUTTON:
         dsdt->shutdown();
         msleep(50);
         outw(0xB004, 0x2000);
         outw(0x604, 0x2000);
         outw(0x4004, 0x3400);
         CPU_STOP;
         break;
     default:
         warn("unknown event 0x%04p", event);
         return;
     }
     UNUSED(regs);
 }
References ACPI_POWER_BUTTON, ACPI_TIMER, CPU_STOP, debug, dsdt, ACPI::DSDT::GetSCIevent(), msleep(), outw, ACPI::DSDT::shutdown(), UNUSED, and warn.
Referenced by ACPI::DSDT::InitSCI().
Variable Documentation
dsdt
ACPI::DSDT* dsdt = nullptr
Definition at line 11 of file DSDT.cpp.
Referenced by internal_reboot(), internal_shutdown(), KernelInit(), SystemRecovery::Recovery::Recovery(), and SCIHandler().