Fennix Project: kernel/timer/HPETTimer.cpp File Reference
HPETTimer.cpp File Reference
#include "hpet.h"
#include <io.h>
#include "../cpu/acpi.hpp"
#include <heap.h>
Functions
uint32_t get_clk ()
uint64_t hpet_read_counter ()
void hpet_uwait (uint64_t Microseconds)
void hpet_mwait (uint64_t Miliseconds)
void hpet_wait (uint64_t Seconds)
void init_HPET ()
void HPET_oneshot (uint32_t Vector, uint64_t Miliseconds)
void disable_HPET ()
Variables
bool HPET_initialized = false
struct HPET * hpet
static uint32_t clk = 0
Function Documentation
disable_HPET()
void disable_HPET ()
Definition at line 60 of file HPETTimer.cpp.
 {
     HPET_initialized = false;
 }
References HPET_initialized.
get_clk()
uint32_t get_clk ()
Definition at line 10 of file HPETTimer.cpp.
 {
     return clk;
 }
References clk.
Referenced by get_timer_clock().
hpet_mwait()
void hpet_mwait (uint64_t Miliseconds)
Definition at line 27 of file HPETTimer.cpp.
 {
     hpet_uwait(Miliseconds * 10000);
 }
References hpet_uwait().
Referenced by msleep().
HPET_oneshot()
void HPET_oneshot (uint32_t Vector, uint64_t Miliseconds)
Definition at line 55 of file HPETTimer.cpp.
 {
     err("HPET One-Shot is not implemented!");
 }
References err.
Referenced by TimerOneShot().
hpet_read_counter()
uint64_t hpet_read_counter ()
Definition at line 15 of file HPETTimer.cpp.
 {
     return mminq(&hpet->main_counter_value);
 }
References hpet, HPET::main_counter_value, and mminq().
Referenced by counter(), and hpet_uwait().
hpet_uwait()
void hpet_uwait (uint64_t Microseconds)
Definition at line 20 of file HPETTimer.cpp.
 {
     uint64_t target = hpet_read_counter() + (Microseconds * 1000000000) / clk;
     while (hpet_read_counter() < target)
         ;
 }
References clk, and hpet_read_counter().
Referenced by hpet_mwait(), hpet_wait(), nsleep(), and usleep().
hpet_wait()
void hpet_wait (uint64_t Seconds)
Definition at line 32 of file HPETTimer.cpp.
 {
     hpet_uwait(Seconds * 1000000);
 }
References hpet_uwait(), and Seconds.
Referenced by sleep().
init_HPET()
void init_HPET ()
Definition at line 37 of file HPETTimer.cpp.
 {
     trace("Initializing HPET timer");
     if (!acpi->HPET)
     {
         warn("HPET timer is not supported");
         return;
     }
     MapMemory(NULL, (void *)acpi->HPET->address.Address, (void *)acpi->HPET->address.Address, RW | PCD);
     hpet = (HPET *)(acpi->HPET->address.Address);
     debug("%s timer is at address %016p", acpi->HPET->header.OEMID, (void *)acpi->HPET->address.Address);
     clk = hpet->general_capabilities >> 32;
     mmoutq(&hpet->general_configuration, 0);
     mmoutq(&hpet->main_counter_value, 0);
     mmoutq(&hpet->general_configuration, 1);
     HPET_initialized = true;
 }
References acpi, ACPI::ACPI::GenericAddressStructure::Address, ACPI::ACPI::HPETHeader::address, clk, debug, HPET::general_capabilities, HPET::general_configuration, ACPI::ACPI::HPETHeader::header, hpet, ACPI::ACPI::HPET, HPET_initialized, HPET::main_counter_value, MapMemory(), mmoutq(), NULL, ACPI::ACPI::ACPIHeader::OEMID, PCD, RW, trace, and warn.
Referenced by init_timer().
Variable Documentation
clk
uint32_t clk = 0 static
Definition at line 8 of file HPETTimer.cpp.
Referenced by get_clk(), hpet_uwait(), and init_HPET().
hpet
struct HPET* hpet
Definition at line 7 of file HPETTimer.cpp.
Referenced by hpet_read_counter(), and init_HPET().
HPET_initialized
bool HPET_initialized = false
Definition at line 6 of file HPETTimer.cpp.
Referenced by counter(), disable_HPET(), get_timer_clock(), init_HPET(), init_timer(), msleep(), nsleep(), sleep(), TimerOneShot(), and usleep().