Fennix Project: kernel/syscalls/SystemCalls.cpp File Reference
SystemCalls.cpp File Reference
#include "syscalls.hpp"
#include "../cpu/gdt.h"
#include "../cpu/idt.h"
#include <internal_task.h>
#include <critical.hpp>
#include <stdarg.h>
#include <task.h>
#include <asm.h>
Functions
uint64_t syscall_handler (SyscallsRegs *regs)
void syscall_handle ()
void init_syscalls ()
Function Documentation
init_syscalls()
void init_syscalls ()
Definition at line 53 of file SystemCalls.cpp.
 {
     // TODO: not tested enough
     // EFER efer;
     // efer.raw = rdmsr(MSR_EFER);
     // efer.SCE = 1;
     // wrmsr(MSR_EFER, efer.raw);
     wrmsr(MSR_EFER, rdmsr(MSR_EFER) | 1);
     wrmsr(MSR_STAR, ((uint64_t)(GDT_KERNEL_CODE) << 32) | ((uint64_t)(GDT_KERNEL_DATA | 3) << 48));
     wrmsr(MSR_LSTAR, (uint64_t)syscall_handle);
     wrmsr(MSR_SYSCALL_MASK, 0);
     // debug("Syscalls has been initialized");
 }
References GDT_KERNEL_CODE, GDT_KERNEL_DATA, MSR_EFER, MSR_LSTAR, MSR_STAR, MSR_SYSCALL_MASK, rdmsr(), syscall_handle(), and wrmsr().
Referenced by StartCPU(), and StartTasking().
syscall_handle()
void syscall_handle ()
Referenced by init_syscalls().
syscall_handler()
uint64_t syscall_handler (SyscallsRegs * regs)
Definition at line 22 of file SystemCalls.cpp.
 {
     switch (SysGetCurrentThread()->Info.Platform)
     {
     case Platform::UnknownPlatform:
         static int once = 0;
         if (!once++)
             err("No platform is specified by the process? Guessing Native...");
         [[fallthrough]];
     case Platform::Native:
     {
         return HandleFennixSyscalls(regs);
     }
     case Platform::POSIX: // TODO: add support for POSIX
     case Platform::Linux:
     {
         return HandleLinuxSyscalls(regs);
     }
     case Platform::Windows:
     {
         err("Platform Windows is not supported yet.");
         return -1;
     }
     default:
         return -1;
     }
     return -1;
 }
References err, HandleFennixSyscalls(), HandleLinuxSyscalls(), and SysGetCurrentThread().