Fennix Project: FileSystem::SysInfo Class Reference
FileSystem::SysInfo Class Reference
#include <filesystem.h>
Public Member Functions
FileSystemNode * AddInfo (FileSystemOpeations *Operator, string Name)
SysInfo ()
~SysInfo ()
Detailed Description
Definition at line 209 of file filesystem.h.
Constructor & Destructor Documentation
SysInfo()
FileSystem::SysInfo::SysInfo ()
Definition at line 171 of file sysinfo.cpp.
     {
         trace("Initializing device file system...");
         SysInfoRootNode = vfs->Create(nullptr, "/system/sys");
         SysInfoRootNode->Flags = NodeFlags::FS_DIRECTORY;
         SysInfoRootNode->Mode = 0755;
         this->AddInfo(&sysinfo_fb_address, "fb0address");
         this->AddInfo(&sysinfo_fb_width, "fb0width");
         this->AddInfo(&sysinfo_fb_height, "fb0height");
         this->AddInfo(&sysinfo_fb_ppsl, "fb0ppsl");
         this->AddInfo(&sysinfo_fb_size, "fb0size");
         this->AddInfo(&sysinfo_cpu_vendor, "cpu_vendor");
         this->AddInfo(&sysinfo_cpu_name, "cpu_name");
         this->AddInfo(&sysinfo_cpu_hypervisor, "cpu_hypervisor");
         this->AddInfo(&sysinfo_mem_used, "mem_used");
         this->AddInfo(&sysinfo_mem_free, "mem_free");
         this->AddInfo(&sysinfo_mem_total, "mem_total");
         this->AddInfo(&sysinfo_mem_reserved, "mem_reserved");
         this->AddInfo(&sysinfo_kernel_version, "kernel_version");
         this->AddInfo(&sysinfo_kernel_name, "kernel_name");
         this->AddInfo(&sysinfo_kernel_build_date, "kernel_build_date");
         BS->IncreaseProgres();
     }
References AddInfo(), BS, FileSystem::Virtual::Create(), FileSystem::FileSystemNode::Flags, FS_DIRECTORY, BootScreen::Screen::IncreaseProgres(), FileSystem::FileSystemNode::Mode, FileSystem::SysInfoRootNode, trace, and vfs.
~SysInfo()
FileSystem::SysInfo::~SysInfo ()
Definition at line 199 of file sysinfo.cpp.
     {
     }
Member Function Documentation
AddInfo()
FileSystemNode * FileSystem::SysInfo::AddInfo (FileSystemOpeations * Operator, string Name)
Definition at line 15 of file sysinfo.cpp.
     {
         trace("Adding %s to device file system", Name);
         // char *FullPath = new char[256];
         // strcpy(FullPath, "/system/dev/");
         // strcat(FullPath, Name);
         // FileSystemNode *newNode = vfs->Create(nullptr, FullPath);
         // delete[] FullPath;
         // FileSystemNode *newNode = vfs->Create(DeviceRootNode, Name);
         FileSystemNode *newNode = new FileSystemNode;
         strcpy(newNode->Name, Name);
         newNode->IndexNode = SysInfoNodeIndexNodeCount++;
         newNode->Mode = 0444;
         newNode->Operator = Operator;
         newNode->Flags = NodeFlags::FS_FILE;
         SysInfoRootNode->Children.push_back(newNode);
         return newNode;
     }
References FileSystem::FileSystemNode::Children, FileSystem::FileSystemNode::Flags, FS_FILE, FileSystem::FileSystemNode::IndexNode, FileSystem::FileSystemNode::Mode, FileSystem::FileSystemNode::Name, FileSystem::FileSystemNode::Operator, strcpy(), FileSystem::SysInfoNodeIndexNodeCount, FileSystem::SysInfoRootNode, and trace.
Referenced by SysInfo().
The documentation for this class was generated from the following files:
kernel/include/filesystem.h
kernel/filesystem/mountpoints/sysinfo.cpp