Fennix Project: FileSystem::Device Class Reference
FileSystem::Device Class Reference
#include <filesystem.h>
Public Member Functions
FileSystemNode * AddFileSystem (FileSystemOpeations *Operator, uint64_t Mode, string Name, int Flags)
Device ()
~Device ()
Detailed Description
Definition at line 164 of file filesystem.h.
Constructor & Destructor Documentation
Device()
FileSystem::Device::Device ()
Definition at line 31 of file devfs.cpp.
     {
         trace("Initializing device file system...");
         DeviceRootNode = vfs->Create(nullptr, "/system/dev");
         DeviceRootNode->Flags = NodeFlags::FS_DIRECTORY;
         DeviceRootNode->Mode = 0755;
         BS->IncreaseProgres();
     }
References BS, FileSystem::Virtual::Create(), FileSystem::DeviceRootNode, FileSystem::FileSystemNode::Flags, FS_DIRECTORY, BootScreen::Screen::IncreaseProgres(), FileSystem::FileSystemNode::Mode, trace, and vfs.
~Device()
FileSystem::Device::~Device ()
Definition at line 40 of file devfs.cpp.
     {
     }
Member Function Documentation
AddFileSystem()
FileSystemNode * FileSystem::Device::AddFileSystem (FileSystemOpeations * Operator, uint64_t Mode, string Name, int Flags)
Definition at line 10 of file devfs.cpp.
     {
         trace("Adding %s to device file system", Name);
         // char *FullPath = new char[256];
         // strcpy(FullPath, "/system/dev/");
         // strcat(FullPath, Name);
         // FileSystemNode *newNode = vfs->Create(nullptr, FullPath);
         // delete[] FullPath;
         // FileSystemNode *newNode = vfs->Create(DeviceRootNode, Name);
         FileSystemNode *newNode = new FileSystemNode;
         strcpy(newNode->Name, Name);
         newNode->IndexNode = DeviceNodeIndexNodeCount++;
         newNode->Mode = Mode;
         newNode->Operator = Operator;
         newNode->Flags = Flags;
         DeviceRootNode->Children.push_back(newNode);
         return newNode;
     }
References FileSystem::FileSystemNode::Children, FileSystem::DeviceNodeIndexNodeCount, FileSystem::DeviceRootNode, Flags, FileSystem::FileSystemNode::Flags, FileSystem::FileSystemNode::IndexNode, FileSystem::FileSystemNode::Mode, Mode, FileSystem::FileSystemNode::Name, FileSystem::FileSystemNode::Operator, strcpy(), and trace.
Referenced by DiskManager::Partition::AddPartition(), FileSystem::FB::FB(), FileSystem::Null::Null(), PS2Mouse::PS2MouseDriver::PS2MouseDriver(), FileSystem::Random::Random(), FileSystem::Serial::Serial(), and FileSystem::Zero::Zero().
The documentation for this class was generated from the following files:
kernel/include/filesystem.h
kernel/filesystem/mountpoints/devfs.cpp