Fennix Project: kernel/interrupts/PIC.c File Reference
PIC.c File Reference
#include <interrupts.h>
#include "pic.h"
#include "../timer/pit.h"
#include <int.h>
#include <asm.h>
#include <io.h>
Functions
void IRQ_set_mask (unsigned char IRQline)
void IRQ_clear_mask (unsigned char IRQline)
void PIC_disable ()
void PIC_sendEOI (unsigned char irq)
void PIC_remap (int offset1, int offset2)
Function Documentation
IRQ_clear_mask()
void IRQ_clear_mask (unsigned char IRQline)
Definition at line 94 of file PIC.c.
 {
     uint16_t port;
     uint8_t value;
     if (IRQline < 8)
         port = PIC1_DATA;
     else
     {
         port = PIC2_DATA;
         IRQline -= 8;
     }
     value = inb(port) & ~(1 << IRQline);
     outb(port, value);
 }
References inb, outb, PIC1_DATA, and PIC2_DATA.
IRQ_set_mask()
void IRQ_set_mask (unsigned char IRQline)
Definition at line 79 of file PIC.c.
 {
     uint16_t port;
     uint8_t value;
     if (IRQline < 8)
         port = PIC1_DATA;
     else
     {
         port = PIC2_DATA;
         IRQline -= 8;
     }
     value = inb(port) | (1 << IRQline);
     outb(port, value);
 }
References inb, outb, PIC1_DATA, and PIC2_DATA.
Referenced by PIC_disable().
PIC_disable()
void PIC_disable ()
Definition at line 11 of file PIC.c.
 {
     debug("Disabling PIC...");
     // set PIC to one-shot mode
     outb(PIT_CMD, 0x28);
     IOWait();
     outb(PIT_COUNTER0, CMD_MODE0);
     IOWait();
     // make sure all IRQs are masked
     IRQ_set_mask(0);
     IRQ_set_mask(1);
     IRQ_set_mask(2);
     IRQ_set_mask(3);
     IRQ_set_mask(4);
     IRQ_set_mask(5);
     IRQ_set_mask(6);
     IRQ_set_mask(7);
     IRQ_set_mask(8);
     IRQ_set_mask(9);
     IRQ_set_mask(10);
     IRQ_set_mask(11);
     IRQ_set_mask(12);
     IRQ_set_mask(13);
     IRQ_set_mask(14);
     IRQ_set_mask(15);
     outb(PIC1_DATA, 0xff);
     IOWait();
     outb(PIC2_DATA, 0xff);
     IOWait();
 }
References CMD_MODE0, debug, IOWait(), IRQ_set_mask(), outb, PIC1_DATA, PIC2_DATA, PIT_CMD, and PIT_COUNTER0.
Referenced by APIC::APIC::APIC().
PIC_remap()
void PIC_remap (int offset1, int offset2)
Definition at line 49 of file PIC.c.
 {
     debug("Remmaping PIC... %#llx %#llx", offset1, offset2);
     unsigned char a1, a2;
     a1 = inb(PIC1_DATA);
     IOWait();
     a2 = inb(PIC2_DATA);
     debug("%#llx %#llx", a1, a2);
     IOWait();
     outb(PIC1_COMMAND, ICW1_INIT | ICW1_ICW4);
     IOWait();
     outb(PIC2_COMMAND, ICW1_INIT | ICW1_ICW4);
     IOWait();
     outb(PIC1_DATA, offset1);
     IOWait();
     outb(PIC2_DATA, offset2);
     IOWait();
     outb(PIC1_DATA, 4);
     IOWait();
     outb(PIC2_DATA, 2);
     IOWait();
     outb(PIC1_DATA, ICW4_8086);
     IOWait();
     outb(PIC2_DATA, ICW4_8086);
     IOWait();
     outb(PIC1_DATA, a1);
     IOWait();
     outb(PIC2_DATA, a2);
 }
References debug, ICW1_ICW4, ICW1_INIT, ICW4_8086, inb, IOWait(), outb, PIC1_COMMAND, PIC1_DATA, PIC2_COMMAND, and PIC2_DATA.
Referenced by init_idt().
PIC_sendEOI()
void PIC_sendEOI (unsigned char irq)
Definition at line 42 of file PIC.c.
 {
     if (irq >= 40)
         outb(PIC2_COMMAND, PIC_EOI);
     outb(PIC1_COMMAND, PIC_EOI);
 }
References outb, PIC1_COMMAND, PIC2_COMMAND, and PIC_EOI.
Referenced by EndOfInterrupt().