Fennix Project: kernel/include/internal_task.h File Reference
internal_task.h File Reference
#include <interrupts.h>
#include <types.h>
#include <heap.h>
#include <task.h>
Enumerations
enum TaskingMode { None, Mono, Multi }
Functions
START_EXTERNC PCB * SysGetProcessByPID (uint64_t ID)
Get a running process by PID.
TCB * SysGetThreadByTID (uint64_t ID)
Get a running thread by PID.
PCB * SysGetCurrentProcess ()
Get current process.
TCB * SysGetCurrentThread ()
Get current thread.
void SysSetProcessPriority (int Priority)
Set current process priority.
int SysGetProcessPriority ()
Get current process priority.
void SysSetThreadPriority (int Priority)
Get current thread priority.
int SysGetThreadPriority ()
Get current thread priority.
PCB * SysCreateProcessFromFile (const char *File, uint64_t arg0, uint64_t arg1, ELEVATION Elevation)
Create a new process from a file.
PCB * SysCreateProcess (const char *Name, ELEVATION Elevation)
Create a new simple process with custom name and address space.
TCB * SysCreateThread (PCB *Parent, uint64_t InstructionPointer, uint64_t arg0, uint64_t arg1)
Create a new thread.
void StartTasking (uint64_t Address, enum TaskingMode Mode)
void init_syscalls ()
Variables
int CurrentTaskingMode
Enumeration Type Documentation
TaskingMode
enum TaskingMode
Enumerator
None
Mono
Multi
Definition at line 7 of file internal_task.h.
 {
     None,
     Mono,
     Multi
 };
Function Documentation
init_syscalls()
void init_syscalls ()
Definition at line 53 of file SystemCalls.cpp.
 {
     // TODO: not tested enough
     // EFER efer;
     // efer.raw = rdmsr(MSR_EFER);
     // efer.SCE = 1;
     // wrmsr(MSR_EFER, efer.raw);
     wrmsr(MSR_EFER, rdmsr(MSR_EFER) | 1);
     wrmsr(MSR_STAR, ((uint64_t)(GDT_KERNEL_CODE) << 32) | ((uint64_t)(GDT_KERNEL_DATA | 3) << 48));
     wrmsr(MSR_LSTAR, (uint64_t)syscall_handle);
     wrmsr(MSR_SYSCALL_MASK, 0);
     // debug("Syscalls has been initialized");
 }
References GDT_KERNEL_CODE, GDT_KERNEL_DATA, MSR_EFER, MSR_LSTAR, MSR_STAR, MSR_SYSCALL_MASK, rdmsr(), syscall_handle(), and wrmsr().
Referenced by StartCPU(), and StartTasking().
StartTasking()
void StartTasking (uint64_t Address, enum TaskingMode Mode)
Definition at line 11 of file Task.cpp.
 {
     CLI;
     trace("Initializing Syscalls...");
     init_syscalls();
     BS->IncreaseProgres();
     trace("Starting tasking mode %d", Mode);
     switch (Mode)
     {
     case TaskingMode::Mono:
     {
         monot = new Monotasking(Address);
         BS->IncreaseProgres();
         break;
     }
     case TaskingMode::Multi:
     {
         mt = new Multitasking;
         mt->CreateThread(mt->CreateProcess(nullptr, (char *)"kernel", ELEVATION::Kernel), Address, 0, 0);
         MultitaskingSchedulerEnabled = true;
         BS->IncreaseProgres();
         break;
     }
     default:
     {
         STI;
         throw;
         break;
     }
     }
     STI;
 }
References Address, BS, CLI, BootScreen::Screen::IncreaseProgres(), init_syscalls(), Mode, Mono, Tasking::monot, Tasking::mt, Multi, Tasking::MultitaskingSchedulerEnabled, STI, and trace.
Referenced by do_tasking_test(), and KernelInit().
SysCreateProcess()
PCB* SysCreateProcess (const char * Name, ELEVATION Elevation)
Create a new simple process with custom name and address space.
Parameters
Name
PageTable
Returns
PCB*
Definition at line 258 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         static int once = 0;
         if (!once++)
             err("The current tasking mode does not support the request.");
         static PCB pcb = {
             .ID = 0,
             .Name = {'\0'},
             .Status = STATUS::UnknownStatus,
             .Elevation = ELEVATION::UnknownElevation,
             .ExitCode = 0,
             .Offset = 0,
             .Parent = nullptr,
             .PageTable = {},
             .Info = {},
             .Security = {},
             .Threads = {},
             .Children = {},
             .Checksum = PROCESS_CHECKSUM};
         memcpy(pcb.Name, "Unknown Task", sizeof(pcb.Name));
         return &pcb;
     }
     case TaskingMode::Multi:
         return mt->CreateProcess(SysGetCurrentProcess(), (char *)Name, Elevation);
     default:
         return nullptr;
     }
 }
References CurrentTaskingMode, err, memcpy(), Mono, Tasking::mt, Multi, and SysGetCurrentProcess().
Referenced by Driver::KernelDriver::KernelDriver(), NetworkInterfaceManager::NetworkInterface::StartService(), and SysCreateProcessFromFile().
SysCreateProcessFromFile()
PCB* SysCreateProcessFromFile (const char * File, uint64_t arg0, uint64_t arg1, ELEVATION Elevation)
Create a new process from a file.
Parameters
File TODO: more
Returns
PCB
Definition at line 329 of file ProcessAPI.cpp.
 {
     /* ... Open file ... Parse file ... map elf file ... get rip etc ... */
     EnterCriticalSection;
     FILE *file = vfs->Open(File);
     if (file->Status != FILESTATUS::OK)
     {
         err("File status error %d for file %s", file->Status, File);
         goto error_exit;
     }
     if (file->Node->Flags == NodeFlags::FS_FILE)
     {
         void *FileBuffer = KernelAllocator.RequestPages(file->Node->Length / 0x1000 + 1);
         vfs->Read(file, 0, (uint8_t *)FileBuffer, file->Node->Length);
         Elf64_Ehdr *ELFHeader = (Elf64_Ehdr *)FileBuffer;
         if (ELFHeader->e_ident[EI_MAG0] == ELFMAG0 &&
             ELFHeader->e_ident[EI_MAG1] == ELFMAG1 &&
             ELFHeader->e_ident[EI_MAG2] == ELFMAG2 &&
             ELFHeader->e_ident[EI_MAG3] == ELFMAG3)
         {
             if (ELFHeader->e_ident[EI_CLASS] == ELFCLASS32)
             {
                 err("32 bit ELF file not supported for now.");
                 KernelAllocator.FreePages(FileBuffer, file->Node->Length / 0x1000 + 1);
                 goto error_exit;
             }
             if (ELFHeader->e_ident[EI_CLASS] == ELFCLASS64)
             {
                 if (ELFHeader->e_type == ET_EXEC)
                 {
                     debug("64 bit ELF file found.");
                     if (ELFHeader->e_ident[EI_OSABI] == ELFOSABI_NONE)
                     {
                         if (Elevation == ELEVATION::User)
{
                             uint64_t MappedAddrs = (uint64_t)FileBuffer;
                             for (uint64_t i = 0; i < file->Node->Length / 0x1000 + 1; i++)
{
                                 KernelPageTableManager.MapMemory((void *)MappedAddrs, (void *)MappedAddrs, PTFlag::RW | PTFlag::US);
                                 MappedAddrs += PAGE_SIZE;
                             }
                         }
                         else if (Elevation == ELEVATION::Kernel)
{
                             uint64_t MappedAddrs = (uint64_t)FileBuffer;
                             for (uint64_t i = 0; i < file->Node->Length / 0x1000 + 1; i++)
{
                                 KernelPageTableManager.MapMemory((void *)MappedAddrs, (void *)MappedAddrs, PTFlag::RW);
                                 MappedAddrs += PAGE_SIZE;
                             }
                         }
                         Elf64_Phdr *pheader = (Elf64_Phdr *)(((char *)FileBuffer) + ELFHeader->e_phoff);
                         void *addr;
                         for (int i = 0; i < ELFHeader->e_phnum; i++, pheader++)
{
                             if (pheader->p_type != PT_LOAD)
                                 continue;
                             addr = (void *)((uint64_t)pheader->p_vaddr + pheader->p_memsz);
                         }
                         void *offset = KernelAllocator.RequestPages((uint64_t)addr / 0x1000 + 1);
                         if (Elevation == ELEVATION::User)
{
                             uint64_t MappedAddrs = (uint64_t)offset;
                             for (uint64_t i = 0; i < (uint64_t)addr / 0x1000 + 1; i++)
{
                                 KernelPageTableManager.MapMemory((void *)MappedAddrs, (void *)MappedAddrs, PTFlag::RW | PTFlag::US);
                                 MappedAddrs += PAGE_SIZE;
                             }
                         }
                         else if (Elevation == ELEVATION::Kernel)
{
                             uint64_t MappedAddrs = (uint64_t)offset;
                             for (uint64_t i = 0; i < (uint64_t)addr / 0x1000 + 1; i++)
{
                                 KernelPageTableManager.MapMemory((void *)MappedAddrs, (void *)MappedAddrs, PTFlag::RW);
                                 MappedAddrs += PAGE_SIZE;
                             }
                         }
                         pheader = (Elf64_Phdr *)(((char *)FileBuffer) + ELFHeader->e_phoff);
                         for (int i = 0; i < ELFHeader->e_phnum; i++, pheader++)
{
                             if (pheader->p_type != PT_LOAD)
                                 continue;
                             void *dst = (void *)((uint64_t)pheader->p_vaddr + (uint64_t)offset);
                             memset(dst, 0, pheader->p_memsz);
                             memcpy(dst, ((char *)FileBuffer) + pheader->p_offset, pheader->p_filesz);
                         }
                         // process pages -> addr / 0x1000 + 1;
                         // KernelAllocator.FreePages(FileBuffer, file->Node->Length / 0x1000 + 1);
                         debug("%s Entry Point: %#lx [%#lx + %#lx]",
                               File,
                               (uint64_t)(ELFHeader->e_entry + (uint64_t)offset),
                               ELFHeader->e_entry, offset);
                         vfs->Close(file);
                         LeaveCriticalSection;
                         if (CurrentTaskingMode == TaskingMode::Mono)
{
                             bool user = false;
                             if (Elevation == ELEVATION::User)
                                 user = true;
                             return (/* data will be invalid but not null */ PCB *)monot->CreateTask(ELFHeader->e_entry + (uint64_t)offset, arg0, arg1, (char *)file->Name, user);
                         }
                         else
{
                             PCB *pcb = SysCreateProcess(file->Name, Elevation);
                             pcb->Offset = (uint64_t)offset;
                             return SysCreateThread(pcb, (uint64_t)ELFHeader->e_entry, arg0, arg1)->Parent;
                         }
                     }
                     else
                     {
                         fixme("File loading from other operating systems is not supported! (%d)", ELFHeader->e_ident[EI_OSABI]);
                         KernelAllocator.FreePages(FileBuffer, file->Node->Length / 0x1000 + 1);
                         goto error_exit;
                     }
                 }
                 else if (ELFHeader->e_type == ET_DYN)
                 {
                     err("Dynamic ELF file not supported for now.");
                     KernelAllocator.FreePages(FileBuffer, file->Node->Length / 0x1000 + 1);
                     goto error_exit;
                 }
                 else
                 {
                     err("Unknown ELF file type.");
                     KernelAllocator.FreePages(FileBuffer, file->Node->Length / 0x1000 + 1);
                     goto error_exit;
                 }
             }
         }
         else
         {
             trace("File %s is not an elf file", File);
             IMAGE_DOS_HEADER *MZHeader = (IMAGE_DOS_HEADER *)FileBuffer;
             if (MZHeader->e_magic == IMAGE_DOS_SIGNATURE)
             {
                 trace("File %s is a MZ file", File);
                 IMAGE_NT_HEADERS *PEHeader = (IMAGE_NT_HEADERS *)(((char *)FileBuffer) + MZHeader->e_lfanew);
                 IMAGE_OS2_HEADER *NEHeader = (IMAGE_OS2_HEADER *)(((char *)FileBuffer) + MZHeader->e_lfanew);
                 if (NEHeader->ne_magic == IMAGE_OS2_SIGNATURE)
                 {
                     trace("File %s is a NE file", File);
                     goto error_exit;
                 }
                 else if (PEHeader->Signature == IMAGE_NT_SIGNATURE)
                 {
                     trace("File %s is a PE file", File);
                     if (PEHeader->FileHeader.Machine == IMAGE_FILE_MACHINE_I386)
                     {
                         err("32 bit PE file not supported for now.");
                         KernelAllocator.FreePages(FileBuffer, file->Node->Length / 0x1000 + 1);
                         goto error_exit;
                     }
                     else if (PEHeader->FileHeader.Machine == IMAGE_FILE_MACHINE_AMD64)
                     {
                         debug("64 bit PE file found.");
                         if (Elevation == ELEVATION::User)
{
                             uint64_t MappedAddrs = (uint64_t)FileBuffer;
                             for (uint64_t i = 0; i < file->Node->Length / 0x1000 + 1; i++)
{
                                 KernelPageTableManager.MapMemory((void *)MappedAddrs, (void *)MappedAddrs, PTFlag::RW | PTFlag::US);
                                 MappedAddrs += PAGE_SIZE;
                             }
                         }
                         else if (Elevation == ELEVATION::Kernel)
{
                             uint64_t MappedAddrs = (uint64_t)FileBuffer;
                             for (uint64_t i = 0; i < file->Node->Length / 0x1000 + 1; i++)
{
                                 KernelPageTableManager.MapMemory((void *)MappedAddrs, (void *)MappedAddrs, PTFlag::RW);
                                 MappedAddrs += PAGE_SIZE;
                             }
                         }
                         IMAGE_SECTION_HEADER *section = (IMAGE_SECTION_HEADER *)(((char *)PEHeader) + sizeof(IMAGE_NT_HEADERS));
                         for (int i = 0; i < PEHeader->FileHeader.NumberOfSections; i++, section++)
{
                             fixme("NumOfSections: %ld | SizeOfRawData: %ld",
                                   PEHeader->FileHeader.NumberOfSections, section->SizeOfRawData);
                             if (section->SizeOfRawData == 0)
                                 continue;
                             void *addr = (void *)((uint64_t)section->VirtualAddress + (uint64_t)FileBuffer);
                             void *offset = KernelAllocator.RequestPages((uint64_t)addr / 0x1000 + 1);
                             if (Elevation == ELEVATION::User)
{
                                 uint64_t MappedAddrs = (uint64_t)offset;
                                 for (uint64_t i = 0; i < (uint64_t)addr / 0x1000 + 1; i++)
{
                                     KernelPageTableManager.MapMemory((void *)MappedAddrs, (void *)MappedAddrs, PTFlag::RW | PTFlag::US);
                                     MappedAddrs += PAGE_SIZE;
                                 }
                             }
                             else if (Elevation == ELEVATION::Kernel)
{
                                 uint64_t MappedAddrs = (uint64_t)offset;
                                 for (uint64_t i = 0; i < (uint64_t)addr / 0x1000 + 1; i++)
{
                                     KernelPageTableManager.MapMemory((void *)MappedAddrs, (void *)MappedAddrs, PTFlag::RW);
                                     MappedAddrs += PAGE_SIZE;
                                 }
                             }
                             memcpy(addr, ((char *)FileBuffer) + section->PointerToRawData, section->SizeOfRawData);
                         }
                         debug("%s Entry Point: %#llx", File, (uint64_t)(PEHeader->OptionalHeader.AddressOfEntryPoint + (uint64_t)FileBuffer));
                     }
                     else
                     {
                         err("Unknown Machine: %#lx", PEHeader->FileHeader.Machine);
                         KernelAllocator.FreePages(FileBuffer, file->Node->Length / 0x1000 + 1);
                         goto error_exit;
                     }
                 }
                 else
                 {
                     err("Unknown file type.");
                     KernelAllocator.FreePages(FileBuffer, file->Node->Length / 0x1000 + 1);
                     goto error_exit;
                 }
             }
         }
     }
 error_exit:
     vfs->Close(file);
     LeaveCriticalSection;
     return nullptr;
 }
References addr, _IMAGE_OPTIONAL_HEADER::AddressOfEntryPoint, FileSystem::Virtual::Close(), CurrentTaskingMode, debug, elf64_hdr::e_entry, elf64_hdr::e_ident, _IMAGE_DOS_HEADER::e_lfanew, _IMAGE_DOS_HEADER::e_magic, elf64_hdr::e_phnum, elf64_hdr::e_phoff, elf64_hdr::e_type, EI_CLASS, EI_MAG0, EI_MAG1, EI_MAG2, EI_MAG3, EI_OSABI, ELFCLASS32, ELFCLASS64, ELFMAG0, ELFMAG1, ELFMAG2, ELFMAG3, ELFOSABI_NONE, EnterCriticalSection, err, ET_DYN, ET_EXEC, _IMAGE_NT_HEADERS::FileHeader, fixme(), FileSystem::FileSystemNode::Flags, FS_FILE, IMAGE_DOS_SIGNATURE, IMAGE_FILE_MACHINE_AMD64, IMAGE_FILE_MACHINE_I386, IMAGE_NT_SIGNATURE, IMAGE_OS2_SIGNATURE, KernelAllocator, KernelPageTableManager, LeaveCriticalSection, FileSystem::FileSystemNode::Length, _IMAGE_FILE_HEADER::Machine, memcpy(), memset(), Mono, Tasking::monot, FileSystem::FILE::Name, _IMAGE_OS2_HEADER::ne_magic, FileSystem::FILE::Node, _IMAGE_FILE_HEADER::NumberOfSections, OK, FileSystem::Virtual::Open(), _IMAGE_NT_HEADERS::OptionalHeader, Elf64_Phdr::p_filesz, Elf64_Phdr::p_memsz, Elf64_Phdr::p_offset, Elf64_Phdr::p_type, Elf64_Phdr::p_vaddr, PAGE_SIZE, _IMAGE_SECTION_HEADER::PointerToRawData, PT_LOAD, FileSystem::Virtual::Read(), RW, _IMAGE_NT_HEADERS::Signature, _IMAGE_SECTION_HEADER::SizeOfRawData, FileSystem::FILE::Status, SysCreateProcess(), SysCreateThread(), trace, US, vfs, and _IMAGE_SECTION_HEADER::VirtualAddress.
Referenced by internal_createprocess(), and KernelTask().
SysCreateThread()
TCB* SysCreateThread (PCB * Parent, uint64_t InstructionPointer, uint64_t arg0, uint64_t arg1)
Create a new thread.
Parameters
Parent if null is using the current running
InstructionPointer
Returns
TCB*
Definition at line 291 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         static int once = 0;
         if (!once++)
             err("The current tasking mode does not support the request.");
         static TCB tcb = {
             .ID = 0,
             .Name = {'\0'},
             .Status = STATUS::UnknownStatus,
             .ExitCode = 0,
             .Parent = nullptr,
             .Stack = 0x0,
             .FXRegion = 0,
             .Registers = {},
             .fs = 0,
             .gs = 0,
             .cs = 0,
             .ss = 0,
             .ds = 0,
             .es = 0,
             .Info = {},
             .Security = {},
             .Checksum = THREAD_CHECKSUM};
         memcpy(tcb.Name, "Unknown Task", sizeof(tcb.Name));
         return &tcb;
     }
     case TaskingMode::Multi:
         return mt->CreateThread(Parent, InstructionPointer, arg0, arg1);
     default:
         return nullptr;
     }
 }
References CurrentTaskingMode, err, memcpy(), Mono, Tasking::mt, and Multi.
Referenced by internal_createthread(), Driver::KernelDriver::KernelDriver(), NetworkInterfaceManager::NetworkInterface::StartService(), and SysCreateProcessFromFile().
SysGetCurrentProcess()
PCB* SysGetCurrentProcess ()
Get current process.
Returns
PCB
Definition at line 166 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
         return ConvertTaskCBToPCB(monot->GetCurrentTask());
     case TaskingMode::Multi:
         return CurrentCPU->CurrentProcess;
     default:
         return nullptr;
     }
 }
References ConvertTaskCBToPCB(), CurrentCPU, CurrentTaskingMode, Mono, Tasking::monot, and Multi.
Referenced by internal_createthread(), internal_getcurrentprocess(), internal_getcurrentprocessid(), and SysCreateProcess().
SysGetCurrentThread()
TCB* SysGetCurrentThread ()
Get current thread.
Returns
TCB
Definition at line 179 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
         return ConvertTaskCBToTCB(monot->GetCurrentTask());
     case TaskingMode::Multi:
         return CurrentCPU->CurrentThread;
     default:
         return nullptr;
     }
 }
References ConvertTaskCBToTCB(), CurrentCPU, CurrentTaskingMode, Mono, Tasking::monot, and Multi.
Referenced by CanSyscall(), internal_exit(), internal_getargc(), internal_getargv(), internal_getcurrentthread(), internal_getcurrentthreadid(), internal_getenvp(), syscall_handler(), and TriggerUserModeCrash().
SysGetProcessByPID()
START_EXTERNC PCB* SysGetProcessByPID (uint64_t ID)
Get a running process by PID.
Parameters
pid Process identifier
Returns
PCB
Definition at line 64 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         static int once = 0;
         if (!once++)
             err("The current tasking mode does not support the request.");
         static PCB pcb = {
             .ID = 0,
             .Name = {'\0'},
             .Status = STATUS::UnknownStatus,
             .Elevation = ELEVATION::UnknownElevation,
             .ExitCode = 0,
             .Offset = 0,
             .Parent = nullptr,
             .PageTable = {},
             .Info = {},
             .Security = {},
             .Threads = {},
             .Children = {},
             .Checksum = PROCESS_CHECKSUM};
         memcpy(pcb.Name, "Unknown Task", sizeof(pcb.Name));
         return &pcb;
     }
     case TaskingMode::Multi:
     {
         EnterCriticalSection;
         foreach (PCB *pcb in mt->ListProcess)
         {
             if (pcb == nullptr || pcb->Checksum != Checksum::PROCESS_CHECKSUM || pcb->Elevation == ELEVATION::Idle)
                 continue;
             if (pcb->ID == ID)
             {
                 LeaveCriticalSection;
                 return pcb;
             }
         }
         LeaveCriticalSection;
         return nullptr;
     }
     default:
         return nullptr;
     }
 }
References CurrentTaskingMode, EnterCriticalSection, err, ID, LeaveCriticalSection, memcpy(), Mono, Tasking::mt, and Multi.
SysGetProcessPriority()
int SysGetProcessPriority ()
Get current process priority.
Returns
int
Definition at line 209 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         trace("Priority get not supported in current tasking mode. Ignoring...");
         return 0;
     }
     case TaskingMode::Multi:
         return CurrentCPU->CurrentProcess->Info.Priority;
     default:
         return 0;
     }
 }
References CurrentCPU, CurrentTaskingMode, Mono, Multi, and trace.
SysGetThreadByTID()
TCB* SysGetThreadByTID (uint64_t ID)
Get a running thread by PID.
Parameters
pid Thread identifier
Returns
TCB
Definition at line 111 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         static int once = 0;
         if (!once++)
             err("The current tasking mode does not support the request.");
         static TCB tcb = {
             .ID = 0,
             .Name = {'\0'},
             .Status = STATUS::UnknownStatus,
             .ExitCode = 0,
             .Parent = nullptr,
             .Stack = 0x0,
             .FXRegion = 0,
             .Registers = {},
             .fs = 0,
             .gs = 0,
             .cs = 0,
             .ss = 0,
             .ds = 0,
             .es = 0,
             .Info = {},
             .Security = {},
             .Checksum = THREAD_CHECKSUM};
         memcpy(tcb.Name, "Unknown Task", sizeof(tcb.Name));
         return &tcb;
     }
     case TaskingMode::Multi:
     {
         EnterCriticalSection;
         foreach (PCB *pcb in mt->ListProcess)
         {
             if (pcb == nullptr || pcb->Checksum != Checksum::PROCESS_CHECKSUM || pcb->Elevation == ELEVATION::Idle)
                 continue;
             foreach (TCB *tcb in pcb->Threads)
             {
                 if (tcb->ID == ID)
                 {
                     LeaveCriticalSection;
                     return tcb;
                 }
             }
         }
         LeaveCriticalSection;
         return nullptr;
     }
     default:
         return nullptr;
     }
 }
References CurrentTaskingMode, EnterCriticalSection, err, ID, LeaveCriticalSection, memcpy(), Mono, Tasking::mt, and Multi.
SysGetThreadPriority()
int SysGetThreadPriority ()
Get current thread priority.
Returns
int
Definition at line 242 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         trace("Priority get not supported in current tasking mode. Ignoring...");
         return 0;
     }
     case TaskingMode::Multi:
         return CurrentCPU->CurrentThread->Info.Priority;
     default:
         return 0;
     }
 }
References CurrentCPU, CurrentTaskingMode, Mono, Multi, and trace.
SysSetProcessPriority()
void SysSetProcessPriority (int Priority)
Set current process priority.
Parameters
Priority
Definition at line 192 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         trace("Priority change not supported in current tasking mode. Ignoring...");
         return;
     }
     case TaskingMode::Multi:
         CurrentCPU->CurrentProcess->Info.Priority = Priority;
         return;
     default:
         return;
     }
 }
References CurrentCPU, CurrentTaskingMode, Mono, Multi, and trace.
SysSetThreadPriority()
void SysSetThreadPriority (int Priority)
Get current thread priority.
Parameters
Priority
Definition at line 225 of file ProcessAPI.cpp.
 {
     switch (CurrentTaskingMode)
     {
     case TaskingMode::Mono:
     {
         trace("Priority change not supported in current tasking mode. Ignoring...");
         return;
     }
     case TaskingMode::Multi:
         CurrentCPU->CurrentThread->Info.Priority = Priority;
         return;
     default:
         return;
     }
 }
References CurrentCPU, CurrentTaskingMode, Mono, Multi, and trace.
Referenced by Driver::DriverManagerMainLoop(), KernelTask(), and NetworkInterfaceManager::NetworkInterface::StartNetworkStack().
Variable Documentation
CurrentTaskingMode
int CurrentTaskingMode
Definition at line 15 of file ProcessAPI.cpp.
Referenced by internal_exit(), internal_fadebootlogo(), internal_getschedulemode(), internal_usleep(), KernelTask(), SysCreateProcess(), SysCreateProcessFromFile(), SysCreateThread(), SysGetCurrentProcess(), SysGetCurrentThread(), SysGetProcessByPID(), SysGetProcessPriority(), SysGetThreadByTID(), SysGetThreadPriority(), SysSetProcessPriority(), SysSetThreadPriority(), and TriggerUserModeCrash().