Fennix Project: FileSystem::Network Class Reference
FileSystem::Network Class Reference
#include <filesystem.h>
Public Member Functions
FileSystemNode * AddNetworkCard (struct FileSystemOpeations *Operator, uint64_t Mode, string Name, int Flags)
Network ()
~Network ()
Detailed Description
Definition at line 200 of file filesystem.h.
Constructor & Destructor Documentation
Network()
FileSystem::Network::Network ()
Definition at line 25 of file netfs.cpp.
     {
         trace("Initializing network file system...");
         NetworkRootNode = vfs->Create(nullptr, "/system/net");
         NetworkRootNode->Flags = NodeFlags::FS_DIRECTORY;
         NetworkRootNode->Mode = 0755;
         BS->IncreaseProgres();
     }
References BS, FileSystem::Virtual::Create(), FileSystem::FileSystemNode::Flags, FS_DIRECTORY, BootScreen::Screen::IncreaseProgres(), FileSystem::FileSystemNode::Mode, FileSystem::NetworkRootNode, trace, and vfs.
~Network()
FileSystem::Network::~Network ()
Definition at line 34 of file netfs.cpp.
     {
     }
Member Function Documentation
AddNetworkCard()
FileSystemNode * FileSystem::Network::AddNetworkCard (struct FileSystemOpeations * Operator, uint64_t Mode, string Name, int Flags)
Definition at line 10 of file netfs.cpp.
     {
         trace("Adding %s to file system", Name);
         // FileSystemNode *newNode = vfs->Create(NetworkRootNode, Name);
         FileSystemNode *newNode = new FileSystemNode;
         strcpy(newNode->Name, Name);
         newNode->IndexNode = NetworkNodeIndexNodeCount++;
         newNode->Mode = Mode;
         newNode->Operator = Operator;
         newNode->Flags = Flags;
         NetworkRootNode->Children.push_back(newNode);
         return newNode;
     }
References FileSystem::FileSystemNode::Children, FileSystem::FileSystemNode::Flags, Flags, FileSystem::FileSystemNode::IndexNode, FileSystem::FileSystemNode::Mode, Mode, FileSystem::FileSystemNode::Name, FileSystem::NetworkNodeIndexNodeCount, FileSystem::NetworkRootNode, FileSystem::FileSystemNode::Operator, strcpy(), and trace.
Referenced by NetworkInterfaceManager::NetworkInterface::StartService().
The documentation for this class was generated from the following files:
kernel/include/filesystem.h
kernel/filesystem/mountpoints/netfs.cpp