name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Update System
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install xorriso mtools genisoimage ovmf nasm doxygen -y

    - name: Install binutils & GCC dependencies
      run: sudo apt-get install build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo -y

    - name: Downloading fonts & compiling initrd
      run: make tools_workflow0

    - name: Get the latest version of Limine
      run: make tools_workflow1

    - name: Clone and compile binutils
      run: make tools_workflow2

    - name: Clone and compile GCC
      run: make tools_workflow3

    - name: Build Image
      run: make build
