Fennix Project: FileSystem::EXT2 Class Reference
FileSystem::EXT2 Class Reference
#include <filesystem.h>
Data Structures
struct SuperBlock
Public Member Functions
EXT2 (void *partition)
~EXT2 ()
Detailed Description
Definition at line 284 of file filesystem.h.
Data Structure Documentation
FileSystem::EXT2::SuperBlock
struct FileSystem::EXT2::SuperBlock
Definition at line 287 of file filesystem.h.
Data Fields
uint32_t BitmapAlogrithm
uint16_t BlockGroups
uint32_t Blocks
uint32_t BlocksPerGroup
uint32_t CheckInternval
uint32_t DefaultMountOptions
uint8_t DefHashVersion
uint16_t Errors
uint32_t FeatureCompatibility
uint32_t FeatureIncompatibility
uint32_t FeatureRoCompatibility
uint32_t FirstDataBlock
uint32_t FirstInode
uint32_t FirstMetaBg
uint32_t FragsPerGroup
uint32_t FreeBlock
uint32_t FreeInodes
uint32_t HashSeed[4]
uint32_t Inodes
uint16_t InodeSize
uint32_t InodesPerGroup
uint32_t JournalDev
uint32_t JournalInum
uint8_t JournalUUID[16]
uint32_t LastCheck
char LastMounted[64]
uint32_t LastMountTime
uint32_t LastOrphan
uint32_t LastWrittenTime
uint32_t LogBlockSize
uint32_t LogFragSize
uint16_t Magic
uint16_t MaximumMountedTimes
uint16_t MinorRevLevel
uint16_t MountedTimes
uint16_t Padding
uint8_t PreallocatedBlocks
uint8_t PreallocatedDirectoryBlocks
uint32_t Reserved[190]
uint32_t ReservedBlocks
uint16_t ReservedBlocksGroupID
uint16_t ReservedBlocksUserID
uint8_t ReservedCharPad
uint16_t ReservedWordPad
uint32_t RevLevel
uint16_t State
uint32_t SystemID
uint8_t UUID[16]
char VolumeName[16]
Constructor & Destructor Documentation
EXT2()
FileSystem::EXT2::EXT2 (void * partition)
Definition at line 25 of file ext2.cpp.
     {
         DiskManager::Partition::Part *Partition = (DiskManager::Partition::Part *)partition;
         // Partition->Read(1024, 2, (unsigned char *)&sb);
         void *buffer = RequestPage();
         Partition->Read(2, 2, buffer);
         memcpy(&sb, buffer, sizeof(SuperBlock));
         FreePage(buffer);
         if (sb.Magic == EXT2_MAGIC) // FIXME: ext4 is detected as ext2!
         {
             debug("EXT2 Name: \"%s\" Last Mounted In: \"%s\"", sb.VolumeName, sb.LastMounted);
             // TODO: Implement reading and writing files
             char CleandVolumeName[16] = {'\0'};
             for (size_t i = 0; i < strlen(sb.VolumeName); i++)
                 if (sb.VolumeName[i] == '/')
                     CleandVolumeName[i] = '_';
                 else
                     CleandVolumeName[i] = sb.VolumeName[i];
             mountfs->MountFileSystem(&ext2, 0666, CleandVolumeName);
         }
     }
References debug, FileSystem::ext2, EXT2_MAGIC, FreePage(), FileSystem::EXT2::SuperBlock::LastMounted, FileSystem::EXT2::SuperBlock::Magic, memcpy(), FileSystem::Mount::MountFileSystem(), mountfs, DiskManager::Partition::Part::Read(), RequestPage(), FileSystem::sb, strlen(), and FileSystem::EXT2::SuperBlock::VolumeName.
~EXT2()
FileSystem::EXT2::~EXT2 ()
Definition at line 52 of file ext2.cpp.
 { warn("Destroyed"); }
References warn.
The documentation for this class was generated from the following files:
kernel/include/filesystem.h
kernel/fs/ext2.cpp